import { LearningModule } from '@/types/content';
import { FUNDAMENTALS_LESSONS } from '@/content/git/fundamentalsLessons';
import { WORKFLOW_LESSONS } from '@/content/git/workflowLessons';
import { INTERNALS_MENTAL_MODEL_LESSONS } from '@/content/git/internalsMentalModel';
import { INTERNALS_OBJECTS_LESSONS } from '@/content/git/internalsObjects';
import { INTERNALS_REFERENCES_LESSONS } from '@/content/git/internalsReferences';
import { INTERNALS_HISTORY_LESSONS } from '@/content/git/internalsHistory';
import { INTERNALS_STORAGE_LESSONS } from '@/content/git/internalsStorage';

/**
 * Git Learning Modules Hierarchy
 *
 * Defines the core modules (8 original + 5 Git Internals) and structured lesson metadata.
 * Every lesson references a globally unique contentId for robust progress tracking.
 */
export const GIT_MODULES: LearningModule[] = [
  {
    id: 'git-fundamentals',
    subjectId: 'git',
    slug: 'fundamentals',
    title: 'Git Fundamentals',
    titleBn: 'গিট ফান্ডামেন্টালস',
    description: 'Core concepts, snapshots vs deltas, working directory, staging area, and first commits.',
    descriptionBn: 'গিটের মূল ধারণা, স্ন্যাপশট বনাম ডেল্টা, ওয়ার্কিং ট্রি, স্টেজিং এরিয়া এবং প্রথম কমিট।',
    icon: 'FolderGit2',
    difficulty: 'beginner',
    order: 1,
    lessons: FUNDAMENTALS_LESSONS,
  },
  {
    id: 'git-workflow',
    subjectId: 'git',
    slug: 'everyday-workflow',
    title: 'Everyday Workflow & Inspection',
    titleBn: 'দৈনন্দিন ওয়ার্কফ্লো ও নিরীক্ষণ',
    description: 'Inspecting changes with diff, examining logs, and ignoring files cleanly.',
    descriptionBn: 'diff দিয়ে পরিবর্তন পরীক্ষা, লগ পর্যালোচনা ও .gitignore পরিচালনা।',
    icon: 'Terminal',
    difficulty: 'beginner',
    order: 2,
    lessons: WORKFLOW_LESSONS,
  },
  {
    id: 'git-branching',
    subjectId: 'git',
    slug: 'branching',
    title: 'Branching Mechanics & Pointers',
    titleBn: 'ব্রাঞ্চিং মেকানিক্স ও পয়েন্টার',
    description: 'How branches work as 41-byte pointer files, switching branches, and branch management.',
    descriptionBn: 'ব্রাঞ্চ কীভাবে পয়েন্টার হিসেবে কাজ করে, ব্রাঞ্চ পরিবর্তন ও পরিচালনা।',
    icon: 'GitBranch',
    difficulty: 'intermediate',
    order: 3,
    lessons: [
      {
        id: 'git.branching.what-are-branches',
        moduleId: 'git-branching',
        slug: 'what-are-branches',
        title: 'Understanding Branch Pointers',
        titleBn: 'ব্রাঞ্চ পয়েন্টারের ধারণা',
        summary: 'Why Git branches are instantaneous and lightweight (just a commit hash in a file).',
        summaryBn: 'গিট ব্রাঞ্চ কেন অত্যন্ত দ্রুত ও হালকা।',
        order: 1,
        durationMinutes: 10,
        difficulty: 'intermediate',
        keyTakeaways: ['Branches are references in .git/refs/heads/', 'HEAD points to the active branch'],
      },
      {
        id: 'git.branching.creating-switching',
        moduleId: 'git-branching',
        slug: 'creating-branches',
        title: 'Creating & Switching (git switch vs checkout)',
        titleBn: 'ব্রাঞ্চ তৈরি ও পরিবর্তন (git switch)',
        summary: 'Master modern branch commands (git switch -c) over overloaded legacy checkout.',
        summaryBn: 'আধুনিক গিট সুইচ কমান্ড দিয়ে ব্রাঞ্চ পরিচালনা।',
        order: 2,
        durationMinutes: 12,
        difficulty: 'intermediate',
        keyTakeaways: ['git switch -c <name>', 'Why switch is safer than checkout'],
      },
    ],
  },
  {
    id: 'git-merging',
    subjectId: 'git',
    slug: 'merging',
    title: 'Merging & Conflict Resolution',
    titleBn: 'মার্জিং ও কনফ্লিক্ট সমাধান',
    description: 'Fast-forward merges, three-way recursive merges, and resolving merge conflicts confidently.',
    descriptionBn: 'ফাস্ট-ফরোয়ার্ড ও থ্রি-ওয়ে মার্জ এবং নির্ভুলভাবে কনফ্লিক্ট সমাধান।',
    icon: 'GitMerge',
    difficulty: 'intermediate',
    order: 4,
    lessons: [
      {
        id: 'git.merging.types',
        moduleId: 'git-merging',
        slug: 'merge-types',
        title: 'Fast-Forward vs 3-Way Merge',
        titleBn: 'ফাস্ট-ফরোয়ার্ড বনাম ৩-ওয়ে মার্জ',
        summary: 'Understand common ancestor commits and why merge commits are created.',
        summaryBn: 'কমন অ্যানসেস্টর কমিট ও মার্জ কমিটের গঠন।',
        order: 1,
        durationMinutes: 12,
        difficulty: 'intermediate',
        keyTakeaways: ['Fast-forward moves pointer', '3-way merge creates a merge commit with 2 parents'],
      },
      {
        id: 'git.merging.conflicts',
        moduleId: 'git-merging',
        slug: 'resolving-conflicts',
        title: 'Diagnosing & Resolving Merge Conflicts',
        titleBn: 'মার্জ কনফ্লিক্ট নির্ণয় ও সমাধান',
        summary: 'Read conflict markers (<<<<<<<, =======, >>>>>>>) and complete merges cleanly.',
        summaryBn: 'কনফ্লিক্ট মার্কার বোঝা ও সঠিক সমাধান স্টেজ করা।',
        order: 2,
        durationMinutes: 15,
        difficulty: 'intermediate',
        keyTakeaways: ['Conflict marker syntax', 'Abort with git merge --abort'],
      },
    ],
  },
  {
    id: 'git-rebasing',
    subjectId: 'git',
    slug: 'rebasing',
    title: 'Rebasing & History Rewriting',
    titleBn: 'রিবেসিং ও হিস্টোরি রিরাইটিং',
    description: 'Linear history, rebase mechanics, interactive rebase squashing, and the golden rule.',
    descriptionBn: 'লিনিয়ার হিস্টোরি, রিবেস মেকানিক্স, কমিট স্কোয়াশ এবং রিবেসের গোল্ডেন রুল।',
    icon: 'GitPullRequest',
    difficulty: 'intermediate',
    order: 5,
    lessons: [
      {
        id: 'git.rebasing.basics',
        moduleId: 'git-rebasing',
        slug: 'rebase-fundamentals',
        title: 'Rebase vs Merge',
        titleBn: 'রিবেস বনাম মার্জ',
        summary: 'How rebase replays commit patches atop a new base commit.',
        summaryBn: 'রিবেস কীভাবে নতুন বেসের উপর কমিট পুনরায় তৈরি করে।',
        order: 1,
        durationMinutes: 15,
        difficulty: 'intermediate',
        keyTakeaways: ['Linear commit history', 'The Golden Rule: Never rebase public shared branches'],
      },
      {
        id: 'git.rebasing.interactive',
        moduleId: 'git-rebasing',
        slug: 'interactive-rebase',
        title: 'Interactive Rebase (git rebase -i)',
        titleBn: 'ইন্টারেক্টিভ রিবেস (git rebase -i)',
        summary: 'Squash messy commits, edit messages, reorder commits, and drop dead code.',
        summaryBn: 'একাধিক কমিট একত্র (Squash) করা ও হিস্টোরি পরিচ্ছন্ন রাখা।',
        order: 2,
        durationMinutes: 20,
        difficulty: 'intermediate',
        keyTakeaways: ['squash and fixup verbs', 'Rebase conflict handling'],
      },
    ],
  },
  {
    id: 'git-remote',
    subjectId: 'git',
    slug: 'remote-and-github',
    title: 'Remote Repositories & GitHub',
    titleBn: 'রিমোট রিপোজিটরি ও গিটহাব',
    description: 'Cloning, push, fetch vs pull, upstream tracking, PR reviews, and team collaboration.',
    descriptionBn: 'ক্লোন, পুশ, পুল, রিমোট ট্র্যাকিং, পিআর ও টিম কলাবোরেশন।',
    icon: 'CloudUpload',
    difficulty: 'intermediate',
    order: 6,
    lessons: [
      {
        id: 'git.remote.fetch-vs-pull',
        moduleId: 'git-remote',
        slug: 'fetch-vs-pull',
        title: 'Fetch vs. Pull: How They Work',
        titleBn: 'Fetch বনাম Pull সহজ ব্যাখ্যা',
        summary: 'Why git fetch is non-destructive while git pull executes a merge/rebase automatically.',
        summaryBn: 'git fetch কেন নিরাপদ এবং pull কীভাবে কাজ করে।',
        order: 1,
        durationMinutes: 12,
        difficulty: 'intermediate',
        keyTakeaways: ['git pull = git fetch + git merge', 'Remote tracking branches (origin/main)'],
      },
      {
        id: 'git.remote.github-prs',
        moduleId: 'git-remote',
        slug: 'pull-requests',
        title: 'Pull Requests & Collaboration',
        titleBn: 'পুল রিকোয়েস্ট ও টিম কলাবোরেশন',
        summary: 'Creating clear PR descriptions, requesting reviews, and syncing forks.',
        summaryBn: 'সঠিক পিআর ডেসক্রিপশন, কোড রিভিউ এবং ফর্ক সিঙ্ক।',
        order: 2,
        durationMinutes: 15,
        difficulty: 'intermediate',
        keyTakeaways: ['Draft PRs vs Ready for Review', 'Resolving PR review comments cleanly'],
      },
    ],
  },
  {
    id: 'git-recovery',
    subjectId: 'git',
    slug: 'undo-and-recovery',
    title: 'Undo, Recovery & Diagnostics',
    titleBn: 'আনডু, রিকভারি ও ডায়াগনস্টিকস',
    description: 'git restore, reset (--soft/--mixed/--hard), revert, stash, and git reflog.',
    descriptionBn: 'রিস্টোর, রিসেট, রিভার্ট, স্ট্যাশ এবং git reflog দিয়ে হারানো কমিট উদ্ধার।',
    icon: 'RotateCcw',
    difficulty: 'advanced',
    order: 7,
    lessons: [
      {
        id: 'git.recovery.restore-and-revert',
        moduleId: 'git-recovery',
        slug: 'restore-and-revert',
        title: 'Safe Undos: git restore & git revert',
        titleBn: 'নিরাপদ আনডু: git restore ও git revert',
        summary: 'Discard unstaged changes safely and invert public commits without rewriting history.',
        summaryBn: 'আনস্টেজড পরিবর্তন বাতিল ও নিরাপদ রিভার্ট কমিট তৈরি।',
        order: 1,
        durationMinutes: 12,
        difficulty: 'intermediate',
        keyTakeaways: ['git restore <file> vs git restore --staged <file>', 'git revert creates new inverse commit'],
      },
      {
        id: 'git.recovery.reset-matrix',
        moduleId: 'git-recovery',
        slug: 'git-reset-explained',
        title: 'The Three Trees of git reset',
        titleBn: 'git reset-এর ৩টি স্তর (Soft, Mixed, Hard)',
        summary: 'Master the differences between --soft, --mixed, and --hard reset.',
        summaryBn: '--soft, --mixed ও --hard রিসেটের সুস্পষ্ট পার্থক্য।',
        order: 2,
        durationMinutes: 18,
        difficulty: 'advanced',
        keyTakeaways: ['Soft touches HEAD only', 'Mixed touches index', 'Hard overwrites working tree'],
      },
      {
        id: 'git.recovery.reflog-lifesaver',
        moduleId: 'git-recovery',
        slug: 'reflog-recovery',
        title: 'Emergency Recovery with git reflog',
        titleBn: 'git reflog দিয়ে হারানো কমিট পুনরুদ্ধার',
        summary: 'How to recover accidentally deleted branches, lost commits, and botched hard resets.',
        summaryBn: 'ডিলিট হওয়া ব্রাঞ্চ বা ভুল রিসেট থেকে সবকিছু ফিরিয়ে আনা।',
        order: 3,
        durationMinutes: 20,
        difficulty: 'advanced',
        keyTakeaways: ['Reflog records every HEAD movement', 'Recover with git reset --hard HEAD@{n}'],
      },
    ],
  },
  {
    id: 'git-advanced',
    subjectId: 'git',
    slug: 'advanced-internals',
    title: 'Advanced Git & Plumbing Internals',
    titleBn: 'অ্যাডভান্সড গিট ও প্লাম্বিং ইন্টারনালস',
    description: 'The .git object database, blobs, trees, commits, tags, and custom Git aliases.',
    descriptionBn: '.git অবজেক্ট ডাটাবেস, ব্লব, ট্রি, কমিট ও কাস্টম গিট এলিয়াস।',
    icon: 'Layers',
    difficulty: 'advanced',
    order: 8,
    lessons: [
      {
        id: 'git.advanced.object-database',
        moduleId: 'git-advanced',
        slug: 'object-database',
        title: 'The .git Directory & Object Store',
        titleBn: '.git ডিরেক্টরি ও অবজেক্ট স্টোর',
        summary: 'Understand content-addressable storage, zlib compression, and SHA hashes.',
        summaryBn: 'কন্টেন্ট-অ্যাড্রেসেবল স্টোরেজ ও হ্যাশ কী কীভাবে কাজ করে।',
        order: 1,
        durationMinutes: 20,
        difficulty: 'advanced',
        keyTakeaways: ['4 Object types: blob, tree, commit, tag', 'git cat-file -p inspection'],
      },
      {
        id: 'git.advanced.bisect-and-aliases',
        moduleId: 'git-advanced',
        slug: 'bisect-and-aliases',
        title: 'Binary Bug Hunting (git bisect) & Aliases',
        titleBn: 'বাগ অনুসন্ধান (git bisect) ও কাস্টম এলিয়াস',
        summary: 'Find the exact commit that introduced a bug using binary search.',
        summaryBn: 'বাইনারি সার্চ দিয়ে ঠিক কোন কমিটে বাগ ঢুকেছে তা বের করা।',
        order: 2,
        durationMinutes: 15,
        difficulty: 'advanced',
        keyTakeaways: ['git bisect start / bad / good', 'Productivity git aliases'],
      },
    ],
  },
  {
    id: 'git-internals-mental-model',
    subjectId: 'git',
    slug: 'mental-model',
    title: "Git's Mental Model",
    titleBn: 'গিটের মেন্টাল মডেল',
    description: 'Object database plus references: working tree, index, snapshots, branches, and HEAD.',
    descriptionBn: 'অবজেক্ট ডাটাবেস সাথে রেফারেন্স: ওয়ার্কিং ট্রি, ইনডেক্স, স্ন্যাপশট, ব্রাঞ্চ ও HEAD।',
    icon: 'Brain',
    difficulty: 'advanced',
    order: 9,
    lessons: INTERNALS_MENTAL_MODEL_LESSONS,
  },
  {
    id: 'git-internals-objects',
    subjectId: 'git',
    slug: 'git-objects',
    title: 'Git Objects',
    titleBn: 'গিট অবজেক্ট',
    description: 'Blobs, trees, commits, tags, and content addressing — what Git actually stores.',
    descriptionBn: 'ব্লব, ট্রি, কমিট, ট্যাগ ও কন্টেন্ট অ্যাড্রেসিং — গিট আসলে কী সংরক্ষণ করে।',
    icon: 'Boxes',
    difficulty: 'advanced',
    order: 10,
    lessons: INTERNALS_OBJECTS_LESSONS,
  },
  {
    id: 'git-internals-references',
    subjectId: 'git',
    slug: 'references',
    title: 'References',
    titleBn: 'রেফারেন্স',
    description: 'Branches, HEAD, remote-tracking refs, tags, and the reflog safety net.',
    descriptionBn: 'ব্রাঞ্চ, HEAD, রিমোট-ট্র্যাকিং রেফ, ট্যাগ ও রিফ্লগ নিরাপত্তা জাল।',
    icon: 'Signpost',
    difficulty: 'advanced',
    order: 11,
    lessons: INTERNALS_REFERENCES_LESSONS,
  },
  {
    id: 'git-internals-history',
    subjectId: 'git',
    slug: 'commit-history',
    title: 'History as a Graph',
    titleBn: 'গ্রাফ হিসেবে ইতিহাস',
    description: 'Commit graphs, parents, reachability, DAG structure, cheap branches, and rebase identity.',
    descriptionBn: 'কমিট গ্রাফ, প্যারেন্ট, রিচেবিলিটি, DAG কাঠামো, সস্তা ব্রাঞ্চ ও রিবেস পরিচয়।',
    icon: 'Workflow',
    difficulty: 'advanced',
    order: 12,
    lessons: INTERNALS_HISTORY_LESSONS,
  },
  {
    id: 'git-internals-storage',
    subjectId: 'git',
    slug: 'storage-maintenance',
    title: 'Storage & Maintenance',
    titleBn: 'স্টোরেজ ও রক্ষণাবেক্ষণ',
    description: 'Object database layout, loose objects, packfiles, garbage collection, and honest expiry.',
    descriptionBn: 'অবজেক্ট ডাটাবেস বিন্যাস, লুজ অবজেক্ট, প্যাকফাইল, গারবেজ কালেকশন ও সৎ মেয়াদ।',
    icon: 'Database',
    difficulty: 'advanced',
    order: 13,
    lessons: INTERNALS_STORAGE_LESSONS,
  },
];
