import { CurriculumLesson } from '@/types/content';

/**
 * Module 5 — Collaboration (subject: github)
 * Permissions, forks, fork vs clone, configuring upstream,
 * open-source contribution, keeping forks updated.
 */
export const GITHUB_COLLABORATION_LESSONS: CurriculumLesson[] = [
  {
    id: 'github.collaboration.permissions',
    moduleId: 'github-collaboration',
    slug: 'collaborator-permissions',
    order: 1,
    durationMinutes: 6,
    difficulty: 'beginner',
    title: 'Collaborator Permissions',
    titleBn: 'সহকর্মী অনুমতি',
    summary: 'Who can do what: read, triage, write, maintain, and admin roles — and why least privilege keeps teams safe.',
    summaryBn: 'কে কী করতে পারে: read, triage, write, maintain ও admin ভূমিকা — এবং কেন সর্বনিম্ন সুযোগ টিম নিরাপদ রাখে।',
    learningObjectives: [
      'Describe the five collaborator permission levels',
      'Explain least privilege for team safety',
      'Choose the right role when inviting someone',
    ],
    learningObjectivesBn: [
      'পাঁচটি সহকর্মী অনুমতি স্তর বর্ণনা করা',
      'টিম নিরাপত্তায় সর্বনিম্ন সুযোগ ব্যাখ্যা করা',
      'কাউকে আমন্ত্রণে সঠিক ভূমিকা বেছে নেওয়া',
    ],
    keyTakeaways: [
      'Read < Triage < Write < Maintain < Admin in capability.',
      'Most contributors need Write; few need Admin.',
      'Permissions gate pushing and settings — pull requests stay open to process.',
    ],
    sections: [
      {
        id: 'sec-roles',
        title: 'Five Levels of Trust',
        titleBn: 'বিশ্বাসের পাঁচ স্তর',
        blocks: [
          {
            type: 'list',
            items: [
              'Read: view, clone, and open issues and PRs.',
              'Triage: also manage issues and PRs without code write access.',
              'Write: push branches and open PRs — the standard contributor role.',
              'Maintain: also manage settings like branch protection (without admin).',
              'Admin: full control, including danger-zone settings and access.',
            ],
            itemsBn: [
              'Read: দেখা, ক্লোন, ইস্যু ও PR খোলা।',
              'Triage: কোড লেখার অ্যাক্সেস ছাড়া ইস্যু ও PR ব্যবস্থাপনা।',
              'Write: ব্রাঞ্চ পুশ ও PR খোলা — মানক অবদানকারী ভূমিকা।',
              'Maintain: ব্রাঞ্চ সুরক্ষার মতো সেটিংস ব্যবস্থাপনা (admin ছাড়া)।',
              'Admin: অ্যাক্সেসসহ পূর্ণ নিয়ন্ত্রণ।',
            ],
          },
        ],
      },
    ],
    relatedLessons: ['github.basics.public-vs-private'],
  },
  {
    id: 'github.collaboration.forks',
    moduleId: 'github-collaboration',
    slug: 'forks',
    order: 2,
    durationMinutes: 7,
    difficulty: 'beginner',
    title: 'Forks',
    titleBn: 'ফোর্ক',
    summary: 'A fork is your personal GitHub-side copy of someone else’s repository — the starting point of open-source contribution.',
    summaryBn: 'ফোর্ক হলো অন্যের রিপোজিটরির আপনার ব্যক্তিগত গিটহাব-পার্শ্ব কপি — ওপেন-সোর্স অবদানের সূচনা।',
    learningObjectives: [
      'Explain what forking creates and where it lives',
      'Describe how forks relate to the original repository',
      'Know when to fork instead of branching directly',
    ],
    learningObjectivesBn: [
      'ব্যাখ্যা করা ফোর্ক কী তৈরি করে ও কোথায় থাকে',
      'ফোর্ক মূল রিপোজিটরির সাথে কীভাবে সম্পর্কিত তা বর্ণনা করা',
      'সরাসরি ব্রাঞ্চের বদলে কখন ফোর্ক করবেন তা জানা',
    ],
    keyTakeaways: [
      'Forking copies a repository into your GitHub account in one click.',
      'Your fork is independent — the original is unaffected by your experiments.',
      'Fork when you lack write access to the original repository.',
    ],
    sections: [
      {
        id: 'sec-fork',
        title: 'Your Copy on GitHub’s Side',
        titleBn: 'গিটহাব পার্শ্বে আপনার কপি',
        blocks: [
          {
            type: 'paragraph',
            text: 'Clicking Fork duplicates the repository — code, branches, and history — under your username. The original project never notices your copy until you open a pull request back to it. That separation is the whole point: strangers can experiment safely, and maintainers review only finished proposals.',
            textBn: 'Fork ক্লিকে রিপোজিটরি — কোড, ব্রাঞ্চ ও হিস্ট্রি — আপনার ইউজারনেমে ডুপ্লিকেট হয়। আপনি পুল রিকোয়েস্ট না খোলা পর্যন্ত মূল প্রজেক্ট কপি টের পায় না। এই বিচ্ছেদই আসল কথা: অপরিচিতরা নিরাপদে পরীক্ষা করে, রক্ষণাবেক্ষণকারীরা শুধু সমাপ্ত প্রস্তাব রিভিউ করেন।',
          },
        ],
      },
    ],
    relatedLessons: ['github.collaboration.fork-vs-clone', 'github.basics.origin-and-upstream'],
  },
  {
    id: 'github.collaboration.fork-vs-clone',
    moduleId: 'github-collaboration',
    slug: 'fork-vs-clone',
    order: 3,
    durationMinutes: 7,
    difficulty: 'beginner',
    title: 'Fork vs Clone',
    titleBn: 'ফোর্ক বনাম ক্লোন',
    summary: 'Fork copies a repository between GitHub accounts; clone copies it to your machine. Contributors do both, in order.',
    summaryBn: 'ফোর্ক গিটহাব অ্যাকাউন্টের মধ্যে রিপোজিটরি কপি করে; ক্লোন মেশিনে কপি করে। অবদানকারীরা ক্রমে দুটোই করেন।',
    learningObjectives: [
      'State exactly what fork and clone each copy, and where',
      'Sequence fork → clone for outside contributors',
      'Avoid the classic "cloned but cannot push" confusion',
    ],
    learningObjectivesBn: [
      'নির্ভুল বলা ফোর্ক ও ক্লোন প্রতিটি কী, কোথায় কপি করে',
      'বাইরের অবদানকারীর fork → clone ক্রম সাজানো',
      'ক্লাসিক "ক্লোন করেছি কিন্তু পুশ হয় না" বিভ্রান্তি এড়ানো',
    ],
    keyTakeaways: [
      'Fork: GitHub-level copy under another account or namespace.',
      'Clone: local Git copy of a repository onto your machine.',
      'Outside contributors fork on GitHub, then clone their fork locally.',
    ],
    sections: [
      {
        id: 'sec-compare',
        title: 'Two Copies, Two Places',
        titleBn: 'দুটি কপি, দুটি জায়গা',
        blocks: [
          {
            type: 'code',
            code: 'Original Repository (GitHub)\n        │  Fork (GitHub button)\n        ↓\nYour Fork (GitHub)\n        │  Clone (git clone)\n        ↓\nYour Machine (local)',
            language: 'text',
          },
          {
            type: 'paragraph',
            text: 'The classic confusion: cloning the original repository gives you code but no permission to push — hence "permission denied" surprises. Fork first (permission on your copy), then clone your fork (push works). Remember it as: fork on GitHub, clone locally.',
            textBn: 'ক্লাসিক বিভ্রান্তি: মূল রিপোজিটরি ক্লোনে কোড পান কিন্তু পুশ অনুমতি নয় — তাই "permission denied" চমক। আগে ফোর্ক করুন (নিজ কপিতে অনুমতি), তারপর ফোর্ক ক্লোন করুন (পুশ চলে)। মনে রাখুন: ফোর্ক গিটহাবে, ক্লোন লোকালি।',
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-github-fork-clone',
      subjectId: 'github',
      difficulty: 'beginner',
      question: 'An outside contributor wants to propose a change. What is the correct sequence?',
      questionBn: 'বাইরের অবদানকারী পরিবর্তন প্রস্তাব করতে চান। সঠিক ক্রম কী?',
      options: [
        { id: 'opt-a', text: 'Clone the original, push directly to it', textBn: 'মূল ক্লোন করে সরাসরি পুশ', isCorrect: false },
        { id: 'opt-b', text: 'Fork on GitHub, then clone the fork locally', textBn: 'গিটহাবে ফোর্ক, তারপর ফোর্ক লোকালি ক্লোন', isCorrect: true },
        { id: 'opt-c', text: 'Clone locally, then fork from the terminal', textBn: 'লোকালি ক্লোন, তারপর টার্মিনাল থেকে ফোর্ক', isCorrect: false },
        { id: 'opt-d', text: 'Open a pull request without any local copy', textBn: 'লোকাল কপি ছাড়া পুল রিকোয়েস্ট খোলা', isCorrect: false },
      ],
      explanation: 'Fork creates your pushable GitHub copy; cloning it gives you a local workspace wired to that copy.',
      explanationBn: 'ফোর্ক পুশযোগ্য গিটহাব কপি বানায়; ক্লোন সেই কপির সাথে যুক্ত লোকাল কর্মক্ষেত্র দেয়।',
    },
    relatedLessons: ['github.collaboration.forks', 'github.collaboration.configuring-upstream'],
  },
  {
    id: 'github.collaboration.configuring-upstream',
    moduleId: 'github-collaboration',
    slug: 'configuring-upstream',
    order: 4,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'Configuring upstream',
    titleBn: 'upstream কনফিগার করা',
    summary: 'After cloning your fork, register the original project as upstream so you can fetch official updates any time.',
    summaryBn: 'ফোর্ক ক্লোনের পর মূল প্রজেক্ট upstream হিসেবে নিবন্ধন করুন যাতে যেকোনো সময় অফিসিয়াল আপডেট আনতে পারেন।',
    learningObjectives: [
      'Add the original repository as an upstream remote',
      'Verify the origin/upstream wiring',
      'Fetch official updates without disturbing your work',
    ],
    learningObjectivesBn: [
      'মূল রিপোজিটরি আপস্ট্রিম রিমোট হিসেবে যোগ করা',
      'origin/upstream সংযোগ যাচাই করা',
      'কাজ না নাড়িয়ে অফিসিয়াল আপডেট আনা',
    ],
    keyTakeaways: [
      'origin → your fork (where you push); upstream → original (where updates come from).',
      'git remote add upstream <url> is a one-time setup per clone.',
      'Fetching upstream never touches your branches — integration stays your decision.',
    ],
    sections: [
      {
        id: 'sec-upstream',
        title: 'One-Time Wiring',
        titleBn: 'একবারের সংযোগ',
        blocks: [
          {
            type: 'command',
            command: 'git remote add upstream https://github.com/original/project.git',
            description: 'Register the original project alongside your fork.',
            descriptionBn: 'ফোর্কের পাশে মূল প্রজেক্ট নিবন্ধন করুন।',
          },
          {
            type: 'command',
            command: 'git remote -v',
            description: 'Confirm origin points to your fork and upstream to the original.',
            descriptionBn: 'নিশ্চিত করুন origin ফোর্ক ও upstream মূলকে নির্দেশ করে।',
          },
          {
            type: 'command',
            command: 'git fetch upstream',
            description: 'Download official updates into upstream/* refs.',
            descriptionBn: 'অফিসিয়াল আপডেট upstream/* রেফে ডাউনলোড করুন।',
          },
        ],
      },
    ],
    relatedCommands: ['git.remote', 'git.fetch'],
    relatedLessons: ['github.basics.origin-and-upstream', 'github.collaboration.keep-fork-updated'],
  },
  {
    id: 'github.collaboration.contributing-open-source',
    moduleId: 'github-collaboration',
    slug: 'contributing-open-source',
    order: 5,
    durationMinutes: 10,
    difficulty: 'intermediate',
    title: 'Contributing to Open Source',
    titleBn: 'ওপেন সোর্সে অবদান রাখা',
    summary: 'The full contributor loop: fork, clone, branch, change, push to fork, pull request, review, merge — with etiquette that gets PRs accepted.',
    summaryBn: 'সম্পূর্ণ অবদান চক্র: ফোর্ক, ক্লোন, ব্রাঞ্চ, পরিবর্তন, ফোর্কে পুশ, পুল রিকোয়েস্ট, রিভিউ, মার্জ — PR গৃহীত হওয়ার শিষ্টাচারসহ।',
    learningObjectives: [
      'Execute the end-to-end open-source contribution flow',
      'Follow contributor etiquette that maintainers appreciate',
      'Respond constructively to review feedback',
    ],
    learningObjectivesBn: [
      'শেষ-থেকে-শেষ ওপেন-সোর্স অবদান প্রবাহ সম্পন্ন করা',
      'রক্ষণাবেক্ষণকারীদের পছন্দের শিষ্টাচার অনুসরণ করা',
      'রিভিউ মতামতে গঠনমূলক সাড়া দেওয়া',
    ],
    keyTakeaways: [
      'The loop: fork → clone → branch → change → push to fork → PR → review → merge.',
      'Read CONTRIBUTING.md first — every project’s rules differ.',
      'Small, focused PRs with tests get merged; giant surprises get closed.',
    ],
    sections: [
      {
        id: 'sec-loop',
        title: 'The Contributor Loop',
        titleBn: 'অবদানকারী চক্র',
        blocks: [
          {
            type: 'list',
            ordered: true,
            items: [
              'Fork the original repository on GitHub.',
              'Clone your fork locally.',
              'Create a focused branch for one change.',
              'Make changes, commit, and push to your fork (origin).',
              'Open a pull request against the original repository.',
              'Respond to review, push fixes, and celebrate the merge.',
            ],
            itemsBn: [
              'গিটহাবে মূল রিপোজিটরি ফোর্ক করুন।',
              'ফোর্ক লোকালি ক্লোন করুন।',
              'একটি পরিবর্তনে ফোকাসড ব্রাঞ্চ তৈরি করুন।',
              'পরিবর্তন, কমিট ও ফোর্কে (origin) পুশ করুন।',
              'মূল রিপোজিটরির বিরুদ্ধে পুল রিকোয়েস্ট খুলুন।',
              'রিভিউয়ে সাড়া দিন, ফিক্স পুশ করুন, মার্জ উদযাপন করুন।',
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            title: 'Etiquette that gets merged',
            titleBn: 'মার্জ পাওয়া শিষ্টাচার',
            text: 'Start with documentation or good-first-issues, keep PRs small, describe the why, run the test suite before pushing, and thank reviewers — even when they request changes.',
            textBn: 'ডকুমেন্টেশন বা good-first-issue দিয়ে শুরু করুন, PR ছোট রাখুন, কেন বর্ণনা করুন, পুশের আগে টেস্ট স্যুট চালান, রিভিউয়ারদের ধন্যবাদ দিন — পরিবর্তন চাইলেও।',
          },
        ],
      },
    ],
    relatedCommands: ['git.clone', 'git.push', 'git.fetch'],
    relatedLessons: ['github.collaboration.fork-vs-clone', 'github.pr.create-pull-request'],
  },
  {
    id: 'github.collaboration.keep-fork-updated',
    moduleId: 'github-collaboration',
    slug: 'keep-fork-updated',
    order: 6,
    durationMinutes: 8,
    difficulty: 'intermediate',
    title: 'Keeping a Fork Updated',
    titleBn: 'ফোর্ক হালনাগাদ রাখা',
    summary: 'Fetch upstream, then integrate deliberately — merge for honesty or rebase for linearity, matching the project’s workflow.',
    summaryBn: 'upstream fetch করুন, তারপর সচেতনভাবে একীভূত করুন — সততায় মার্জ বা রৈখিকতায় রিবেস, প্রজেক্ট ওয়ার্কফ্লো মিলিয়ে।',
    learningObjectives: [
      'Fetch upstream changes into tracking refs',
      'Integrate with merge or rebase deliberately',
      'Push the updated fork so PRs stay mergeable',
    ],
    learningObjectivesBn: [
      'আপস্ট্রিম পরিবর্তন ট্র্যাকিং রেফে আনা',
      'সচেতনভাবে মার্জ বা রিবেসে একীভূত করা',
      'আপডেটেড ফোর্ক পুশ করে PR মার্জযোগ্য রাখা',
    ],
    keyTakeaways: [
      'git fetch upstream refreshes your picture without touching work.',
      'Merge preserves both histories; rebase replays yours on top.',
      'Push the result to your fork so open PRs stay conflict-free.',
    ],
    sections: [
      {
        id: 'sec-sync-fork',
        title: 'Sync Deliberately',
        titleBn: 'সচেতনভাবে সিঙ্ক করুন',
        blocks: [
          {
            type: 'command',
            command: 'git fetch upstream',
            description: 'Download the project’s latest into upstream/* refs.',
            descriptionBn: 'প্রজেক্টের সর্বশেষ upstream/* রেফে ডাউনলোড করুন।',
          },
          {
            type: 'command',
            command: 'git switch main && git merge upstream/main',
            description: 'Join official updates into your fork’s main.',
            descriptionBn: 'অফিসিয়াল আপডেট ফোর্কের main-এ যুক্ত করুন।',
          },
          {
            type: 'paragraph',
            text: 'Prefer rebase instead if the project keeps linear history — git rebase upstream/main replays your local commits on top. Either way, the rule is the same: fetch first, read the new commits, then choose your integration consciously rather than blindly.',
            textBn: 'প্রজেক্ট লিনিয়ার হিস্ট্রি রাখলে বরং রিবেস করুন — git rebase upstream/main লোকাল কমিট ওপরে রিপ্লে করে। যেভাবেই, নিয়ম এক: আগে fetch, নতুন কমিট পড়ুন, তারপর অন্ধভাবে নয় সচেতনভাবে একীভূত বেছে নিন।',
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-github-keep-fork-updated',
      subjectId: 'github',
      difficulty: 'intermediate',
      question: 'What is the safe sequence for updating your fork?',
      questionBn: 'ফোর্ক আপডেটের নিরাপদ ক্রম কী?',
      options: [
        { id: 'opt-a', text: 'Push first, then fetch upstream', textBn: 'আগে পুশ, তারপর upstream fetch', isCorrect: false },
        { id: 'opt-b', text: 'Fetch upstream, review, integrate deliberately, then push to origin', textBn: 'upstream fetch, পর্যালোচনা, সচেতন একীভূত, তারপর origin-এ পুশ', isCorrect: true },
        { id: 'opt-c', text: 'Delete the fork and fork again', textBn: 'ফোর্ক মুছে আবার ফোর্ক', isCorrect: false },
        { id: 'opt-d', text: 'Force-push upstream/main into origin', textBn: 'upstream/main ফোর্স-পুশ করে origin-এ', isCorrect: false },
      ],
      explanation: 'Fetch to see, review the new commits, integrate with merge or rebase, then push the result to your fork.',
      explanationBn: 'দেখতে fetch, নতুন কমিট পর্যালোচনা, মার্জ বা রিবেসে একীভূত, তারপর ফল ফোর্কে পুশ।',
    },
    relatedCommands: ['git.fetch', 'git.merge', 'git.rebase', 'git.push'],
    relatedLessons: ['github.collaboration.configuring-upstream'],
  },
];
