import { CurriculumLesson } from '@/types/content';

/**
 * Module 1 — GitHub Fundamentals (subject: github)
 * What GitHub is, how it differs from Git, remotes, origin/upstream,
 * repository anatomy, and public vs private.
 */
export const GITHUB_FUNDAMENTALS_LESSONS: CurriculumLesson[] = [
  {
    id: 'github.basics.what-is-github',
    moduleId: 'github-fundamentals',
    slug: 'what-is-github',
    order: 1,
    durationMinutes: 7,
    difficulty: 'beginner',
    title: 'What is GitHub?',
    titleBn: 'গিটহাব কী?',
    summary: 'GitHub is a hosted platform built around Git repositories — issue tracking, pull requests, code review, and automation on top of the Git you already know.',
    summaryBn: 'গিটহাব হলো গিট রিপোজিটরিকে কেন্দ্র করে গড়া একটি হোস্টেড প্ল্যাটফর্ম — আপনার চেনা গিটের ওপরে ইস্যু ট্র্যাকিং, পুল রিকোয়েস্ট, কোড রিভিউ ও অটোমেশন।',
    learningObjectives: [
      'Describe what GitHub adds on top of plain Git',
      'Name the core collaboration features of a GitHub repository',
      'Explain why teams keep their shared history on GitHub',
    ],
    learningObjectivesBn: [
      'সাধারণ গিটের ওপরে গিটহাব কী যোগ করে তা বর্ণনা করা',
      'গিটহাব রিপোজিটরির মূল সহযোগিতা ফিচারগুলোর নাম বলা',
      'টিম কেন শেয়ার্ড হিস্ট্রি গিটহাবে রাখে তা ব্যাখ্যা করা',
    ],
    keyTakeaways: [
      'GitHub hosts Git repositories and adds collaboration tooling around them.',
      'Issues, pull requests, reviews, and checks live on GitHub — not inside Git itself.',
      'The shared remote on GitHub is the team’s source of truth.',
    ],
    sections: [
      {
        id: 'sec-platform',
        title: 'A Platform Around Repositories',
        titleBn: 'রিপোজিটরিকে ঘিরে একটি প্ল্যাটফর্ম',
        blocks: [
          {
            type: 'paragraph',
            text: 'Git tracks history on your machine. GitHub gives that history a shared home on the internet, plus the tools teams need to discuss, review, and ship changes together: issues for planning, pull requests for proposing changes, reviews for quality, and checks for automation.',
            textBn: 'গিট আপনার মেশিনে হিস্ট্রি ট্র্যাক করে। গিটহাব সেই হিস্ট্রিকে ইন্টারনেটে একটি শেয়ার্ড ঠিকানা দেয়, সাথে টিমের একসাথে আলোচনা, রিভিউ ও রিলিজের টুল: পরিকল্পনায় ইস্যু, পরিবর্তন প্রস্তাবে পুল রিকোয়েস্ট, মান যাচাইয়ে রিভিউ, অটোমেশনে চেক।',
          },
          {
            type: 'keyConcept',
            title: 'GitHub does not replace Git',
            titleBn: 'গিটহাব গিটের বিকল্প নয়',
            conceptKey: 'GITHUB_PLATFORM',
            text: 'Every GitHub workflow bottoms out in ordinary Git operations — clone, fetch, push, merge. GitHub is the meeting place; Git is still the version control engine doing the work.',
            textBn: 'প্রতিটি গিটহাব ওয়ার্কফ্লোর তলায় সাধারণ গিট অপারেশন — clone, fetch, push, merge। গিটহাব মিলনস্থল; কাজ করা ভার্সন কন্ট্রোল ইঞ্জিন এখনো গিট।',
          },
          {
            type: 'list',
            items: ['Repositories with a web interface', 'Issues and project planning', 'Pull requests and code review', 'Automated checks and releases'],
            itemsBn: ['ওয়েব ইন্টারফেসসহ রিপোজিটরি', 'ইস্যু ও প্রজেক্ট পরিকল্পনা', 'পুল রিকোয়েস্ট ও কোড রিভিউ', 'স্বয়ংক্রিয় চেক ও রিলিজ'],
          },
        ],
      },
    ],
    relatedCommands: ['git.clone', 'git.push', 'git.fetch'],
    relatedLessons: ['git.fundamentals.what-is-git', 'git.fundamentals.git-vs-github'],
  },
  {
    id: 'github.basics.git-vs-github',
    moduleId: 'github-fundamentals',
    slug: 'git-vs-github',
    order: 2,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'Git vs GitHub',
    titleBn: 'গিট বনাম গিটহাব',
    summary: 'Git is a distributed version control system that runs anywhere — including remotes. GitHub is one hosting service for Git repositories. The distinction matters.',
    summaryBn: 'গিট একটি ডিস্ট্রিবিউটেড ভার্সন কন্ট্রোল সিস্টেম যা যেকোনো জায়গায় চলে — রিমোটসহ। গিটহাব গিট রিপোজিটরির একটি হোস্টিং সেবা। পার্থক্যটি গুরুত্বপূর্ণ।',
    learningObjectives: [
      'State precisely what Git is and what GitHub is',
      'Explain why "Git is local, GitHub is remote" is incomplete',
      'Give examples of Git remotes that are not GitHub',
    ],
    learningObjectivesBn: [
      'গিট কী ও গিটহাব কী তা নির্ভুলভাবে বলা',
      '"গিট লোকাল, গিটহাব রিমোট" কেন অসম্পূর্ণ তা ব্যাখ্যা করা',
      'গিটহাব নয় এমন গিট রিমোটের উদাহরণ দেওয়া',
    ],
    keyTakeaways: [
      'Git is the version control system; GitHub is a service that hosts Git repositories.',
      'Git natively supports remotes — GitHub is one popular remote, not the concept itself.',
      'You can use Git fully offline; you need GitHub only for collaboration features.',
    ],
    sections: [
      {
        id: 'sec-distinction',
        title: 'Two Different Things',
        titleBn: 'দুটি ভিন্ন জিনিস',
        blocks: [
          {
            type: 'paragraph',
            text: 'Git is a distributed version control system: a program on your computer that records snapshots, branches, and merges. It works fully offline and it natively understands remote repositories — any other copy of the history, anywhere.',
            textBn: 'গিট একটি ডিস্ট্রিবিউটেড ভার্সন কন্ট্রোল সিস্টেম: আপনার কম্পিউটারের একটি প্রোগ্রাম যা স্ন্যাপশট, ব্রাঞ্চ ও মার্জ রেকর্ড করে। এটি সম্পূর্ণ অফলাইনে কাজ করে এবং রিমোট রিপোজিটরি সহজাতভাবে বোঝে — ইতিহাসের অন্য যেকোনো কপি, যেকোনো জায়গায়।',
          },
          {
            type: 'paragraph',
            text: 'GitHub is a company and a hosted platform built around Git repositories. Saying "Git is local and GitHub is remote" is incomplete because Git itself supports remotes — a teammate’s laptop, a company server, GitLab, or Bitbucket can all be Git remotes. GitHub is simply the most popular place to put one.',
            textBn: 'গিটহাব একটি কোম্পানি ও গিট রিপোজিটরিকে ঘিরে গড়া হোস্টেড প্ল্যাটফর্ম। "গিট লোকাল আর গিটহাব রিমোট" বলা অসম্পূর্ণ, কারণ গিট নিজেই রিমোট সমর্থন করে — সহকর্মীর ল্যাপটপ, কোম্পানির সার্ভার, GitLab বা Bitbucket সবই গিট রিমোট হতে পারে। গিটহাব শুধু সবচেয়ে জনপ্রিয় ঠিকানা।',
          },
          {
            type: 'callout',
            variant: 'tip',
            title: 'The incomplete sentence',
            titleBn: 'অসম্পূর্ণ বাক্য',
            text: 'Replace "Git is local, GitHub is remote" with "Git is the version control tool; GitHub is a service that hosts Git repositories and adds collaboration features." Interviewers notice the difference.',
            textBn: '"গিট লোকাল, গিটহাব রিমোট"-এর বদলে বলুন "গিট ভার্সন কন্ট্রোল টুল; গিটহাব গিট রিপোজিটরি হোস্ট করা ও সহযোগিতা ফিচার যোগ করা সেবা।" ইন্টারভিউয়াররা পার্থক্য লক্ষ্য করেন।',
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-github-git-vs-github',
      subjectId: 'github',
      difficulty: 'beginner',
      question: 'Which statement about Git and GitHub is most accurate?',
      questionBn: 'গিট ও গিটহাব সম্পর্কে কোন বক্তব্যটি সবচেয়ে নির্ভুল?',
      options: [
        { id: 'opt-a', text: 'Git is the offline part and GitHub is the online part of the same program', textBn: 'গিট অফলাইন অংশ আর গিটহাব একই প্রোগ্রামের অনলাইন অংশ', isCorrect: false },
        { id: 'opt-b', text: 'Git is the version control system; GitHub is a hosting service for Git repositories', textBn: 'গিট ভার্সন কন্ট্রোল সিস্টেম; গিটহাব গিট রিপোজিটরির হোস্টিং সেবা', isCorrect: true },
        { id: 'opt-c', text: 'GitHub invented Git and controls how it works', textBn: 'গিটহাব গিট আবিষ্কার করেছে ও এটি কীভাবে কাজ করে নিয়ন্ত্রণ করে', isCorrect: false },
        { id: 'opt-d', text: 'You cannot use Git without a GitHub account', textBn: 'গিটহাব অ্যাকাউন্ট ছাড়া গিট ব্যবহার করা যায় না', isCorrect: false },
      ],
      explanation: 'Git works fully on its own, including with non-GitHub remotes. GitHub hosts repositories and adds collaboration tooling.',
      explanationBn: 'গিট নিজে সম্পূর্ণ কাজ করে, গিটহাব-বহির্ভূত রিমোটসহ। গিটহাব রিপোজিটরি হোস্ট করে ও সহযোগিতা টুল যোগ করে।',
    },
    relatedCommands: ['git.clone', 'git.remote'],
    relatedLessons: ['git.fundamentals.what-is-git', 'git.fundamentals.git-vs-github', 'github.basics.what-is-github'],
  },
  {
    id: 'github.basics.remote-repositories',
    moduleId: 'github-fundamentals',
    slug: 'remote-repositories',
    order: 3,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'Remote Repositories',
    titleBn: 'রিমোট রিপোজিটরি',
    summary: 'A remote is simply another copy of your history with a nickname. Learn how locals and remotes relate, and what tracking really means.',
    summaryBn: 'রিমোট হলো ডাকনামসহ আপনার হিস্ট্রির আরেকটি কপি। লোকাল ও রিমোটের সম্পর্ক এবং ট্র্যাকিংয়ের আসল মানে শিখুন।',
    learningObjectives: [
      'Define a Git remote in one sentence',
      'Explain remote-tracking branches like origin/main',
      'Describe what fetch, push, and pull move between copies',
    ],
    learningObjectivesBn: [
      'এক বাক্যে গিট রিমোটের সংজ্ঞা দেওয়া',
      'origin/main-এর মতো রিমোট-ট্র্যাকিং ব্রাঞ্চ ব্যাখ্যা করা',
      'fetch, push ও pull কপিগুলোর মধ্যে কী সরায় তা বর্ণনা করা',
    ],
    keyTakeaways: [
      'A remote is a named reference to another copy of the repository.',
      'origin/main is your local photo of the remote — updated only by fetch, pull, or push.',
      'fetch downloads, push uploads, pull fetches and then integrates.',
    ],
    sections: [
      {
        id: 'sec-remotes',
        title: 'Copies With Nicknames',
        titleBn: 'ডাকনামসহ কপি',
        blocks: [
          {
            type: 'paragraph',
            text: 'Every clone is a full repository. A "remote" is just a nickname your local repository keeps for another copy — usually the shared one on GitHub. Your repository also keeps remote-tracking branches such as origin/main: a local photograph of where the remote was the last time you fetched, pulled, or pushed.',
            textBn: 'প্রতিটি ক্লোন একটি পূর্ণ রিপোজিটরি। "রিমোট" হলো আপনার লোকাল রিপোজিটরির রাখা আরেকটি কপির ডাকনাম — সাধারণত গিটহাবের শেয়ার্ড কপি। রিপোজিটরি রিমোট-ট্র্যাকিং ব্রাঞ্চও রাখে, যেমন origin/main: শেষ fetch, pull বা push-এর সময় রিমোট কোথায় ছিল তার লোকাল ছবি।',
          },
          {
            type: 'command',
            command: 'git remote -v',
            description: 'List the nicknames and the URLs they point to.',
            descriptionBn: 'ডাকনাম ও সেগুলোর URL তালিকা দেখুন।',
          },
          {
            type: 'keyConcept',
            title: 'Tracking is a photo, not a live feed',
            titleBn: 'ট্র্যাকিং ছবি, লাইভ ফিড নয়',
            conceptKey: 'REMOTE_TRACKING',
            text: 'origin/main only changes when your Git talks to the remote. Teammates can push all day — your photo stays stale until you fetch.',
            textBn: 'origin/main বদলায় শুধু যখন আপনার গিট রিমোটের সাথে কথা বলে। সহকর্মীরা সারাদিন পুশ করুক — fetch না করা পর্যন্ত ছবি পুরনোই থাকে।',
          },
        ],
      },
    ],
    relatedCommands: ['git.remote', 'git.fetch', 'git.push', 'git.pull'],
    relatedLessons: ['git.fundamentals.remote-repository', 'github.basics.origin-and-upstream'],
  },
  {
    id: 'github.basics.origin-and-upstream',
    moduleId: 'github-fundamentals',
    slug: 'origin-and-upstream',
    order: 4,
    durationMinutes: 9,
    difficulty: 'beginner',
    title: 'origin and upstream',
    titleBn: 'origin ও upstream',
    summary: 'origin and upstream are conventional nicknames — not Git keywords. Learn what each points to in fork workflows and multi-remote setups.',
    summaryBn: 'origin ও upstream প্রচলিত ডাকনাম — গিট কি-ওয়ার্ড নয়। ফোর্ক ওয়ার্কফ্লো ও মাল্টি-রিমোট সেটআপে প্রতিটি কী নির্দেশ করে শিখুন।',
    learningObjectives: [
      'Explain that origin/upstream are conventions, not keywords',
      'Map origin and upstream in the personal fork workflow',
      'Describe a repository with several arbitrarily named remotes',
    ],
    learningObjectivesBn: [
      'ব্যাখ্যা করা origin/upstream প্রচলন, কি-ওয়ার্ড নয়',
      'ব্যক্তিগত ফোর্ক ওয়ার্কফ্লোতে origin ও upstream ম্যাপ করা',
      'ইচ্ছামতো নামের একাধিক রিমোটসহ রিপোজিটরি বর্ণনা করা',
    ],
    keyTakeaways: [
      'origin conventionally means "where I push my work" — often your fork.',
      'upstream conventionally means "the original project I follow".',
      'Any remote can have any name; teams choose names that communicate intent.',
    ],
    sections: [
      {
        id: 'sec-contexts',
        title: 'Two Common Contexts',
        titleBn: 'দুটি সাধারণ প্রেক্ষাপট',
        blocks: [
          {
            type: 'heading',
            level: 3,
            text: 'Personal fork workflow',
            textBn: 'ব্যক্তিগত ফোর্ক ওয়ার্কফ্লো',
          },
          {
            type: 'paragraph',
            text: 'When you fork a project, you get your own copy on GitHub. You clone your fork, so origin points to your fork — the place you push to. You then add the original repository as a second remote conventionally named upstream, so you can fetch official updates.',
            textBn: 'প্রজেক্ট ফোর্ক করলে গিটহাবে নিজের কপি পান। ফোর্ক ক্লোন করেন, তাই origin আপনার ফোর্ককে নির্দেশ করে — যেখানে পুশ করেন। তারপর মূল রিপোজিটরি দ্বিতীয় রিমোট হিসেবে যোগ করেন, প্রচলিত নাম upstream, যাতে অফিসিয়াল আপডেট fetch করতে পারেন।',
          },
          {
            type: 'code',
            code: 'Original Repository\n        ↑\n    upstream\n        |\n      Local\n        |\n     origin\n        ↓\n   Personal Fork',
            language: 'text',
          },
          {
            type: 'heading',
            level: 3,
            text: 'Multiple remote workflow',
            textBn: 'মাল্টিপল রিমোট ওয়ার্কফ্লো',
          },
          {
            type: 'paragraph',
            text: 'A repository can track any number of remotes with arbitrary names — production, staging, teammate, backup. origin is simply the default nickname clone assigns to the source; upstream is a human convention for "the project I follow". Neither name has special powers inside Git.',
            textBn: 'রিপোজিটরি ইচ্ছামতো নামে যেকোনো সংখ্যক রিমোট ট্র্যাক করতে পারে — production, staging, teammate, backup। origin হলো clone-এর দেওয়া ডিফল্ট ডাকনাম; upstream হলো "যে প্রজেক্ট অনুসরণ করি" বোঝানো মানবিক প্রচলন। গিটের ভেতরে কোনো নামের বিশেষ ক্ষমতা নেই।',
          },
          {
            type: 'callout',
            variant: 'warning',
            title: 'Conventions, not keywords',
            titleBn: 'প্রচলন, কি-ওয়ার্ড নয়',
            text: 'Renaming origin to anything else changes nothing about how Git works — scripts and habits just expect the convention. That is exactly why the distinction matters.',
            textBn: 'origin-এর নাম বদলে অন্য কিছু রাখলে গিটের কাজে কিছু বদলায় না — স্ক্রিপ্ট ও অভ্যাস শুধু প্রচলন আশা করে। পার্থক্য গুরুত্বপূর্ণ ঠিক এই কারণে।',
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-github-origin-upstream',
      subjectId: 'github',
      difficulty: 'beginner',
      question: 'In a personal fork workflow, what do origin and upstream conventionally point to?',
      questionBn: 'ব্যক্তিগত ফোর্ক ওয়ার্কফ্লোতে origin ও upstream প্রচলিতভাবে কী নির্দেশ করে?',
      options: [
        { id: 'opt-a', text: 'origin → original repo, upstream → your fork', textBn: 'origin → মূল রেপো, upstream → আপনার ফোর্ক', isCorrect: false },
        { id: 'opt-b', text: 'origin → your fork, upstream → original repo', textBn: 'origin → আপনার ফোর্ক, upstream → মূল রেপো', isCorrect: true },
        { id: 'opt-c', text: 'origin and upstream are reserved Git keywords for push and pull', textBn: 'origin ও upstream পুশ ও পুলের সংরক্ষিত গিট কি-ওয়ার্ড', isCorrect: false },
        { id: 'opt-d', text: 'Both always point to the same URL', textBn: 'দুটো সবসময় একই URL নির্দেশ করে', isCorrect: false },
      ],
      explanation: 'origin is where you push (your fork); upstream is the original project you fetch updates from. Both are mere naming conventions.',
      explanationBn: 'origin যেখানে পুশ করেন (আপনার ফোর্ক); upstream মূল প্রজেক্ট যেখান থেকে আপডেট আনেন। দুটোই শুধু নামকরণ প্রচলন।',
    },
    relatedCommands: ['git.remote', 'git.fetch', 'git.clone'],
    relatedLessons: ['git.fundamentals.remote-repository', 'github.collaboration.configuring-upstream'],
  },
  {
    id: 'github.basics.repository-structure',
    moduleId: 'github-fundamentals',
    slug: 'repository-structure',
    order: 5,
    durationMinutes: 7,
    difficulty: 'beginner',
    title: 'GitHub Repository Structure',
    titleBn: 'গিটহাব রিপোজিটরি কাঠামো',
    summary: 'Code, branches, README, issues, pull requests, actions, and settings — what lives where on a GitHub repository page.',
    summaryBn: 'কোড, ব্রাঞ্চ, README, ইস্যু, পুল রিকোয়েস্ট, অ্যাকশন ও সেটিংস — গিটহাব রিপোজিটরি পেজে কী কোথায় থাকে।',
    learningObjectives: [
      'Navigate the main areas of a repository page',
      'Explain what the default branch, README, and insights tabs are for',
      'Find issues, pull requests, and actions from the repo header',
    ],
    learningObjectivesBn: [
      'রিপোজিটরি পেজের প্রধান এলাকায় চলাচল করা',
      'ডিফল্ট ব্রাঞ্চ, README ও ইনসাইট ট্যাবের কাজ ব্যাখ্যা করা',
      'রেপো হেডার থেকে ইস্যু, পুল রিকোয়েস্ট ও অ্যাকশন খোঁজা',
    ],
    keyTakeaways: [
      'The Code tab shows files, branches, and the README of the default branch.',
      'Issues track work, Pull requests propose changes, Actions run automation.',
      'Settings controls collaborators, branches rules, and repository visibility.',
    ],
    sections: [
      {
        id: 'sec-anatomy',
        title: 'Anatomy of a Repository Page',
        titleBn: 'রিপোজিটরি পেজের অঙ্গসংস্থান',
        blocks: [
          {
            type: 'list',
            items: [
              'Code: file browser, branch switcher, README preview, clone options',
              'Issues: discussions, bug reports, and task tracking',
              'Pull requests: proposed changes awaiting review and merge',
              'Actions: automated test, build, and release pipelines',
              'Insights: contributors, traffic, and commit activity graphs',
              'Settings: collaborators, branch protection, secrets, visibility',
            ],
            itemsBn: [
              'Code: ফাইল ব্রাউজার, ব্রাঞ্চ সুইচার, README প্রিভিউ, ক্লোন অপশন',
              'Issues: আলোচনা, বাগ রিপোর্ট ও টাস্ক ট্র্যাকিং',
              'Pull requests: রিভিউ ও মার্জের অপেক্ষায় প্রস্তাবিত পরিবর্তন',
              'Actions: স্বয়ংক্রিয় টেস্ট, বিল্ড ও রিলিজ পাইপলাইন',
              'Insights: কন্ট্রিবিউটর, ট্রাফিক ও কমিট অ্যাক্টিভিটি গ্রাফ',
              'Settings: সহকর্মী, ব্রাঞ্চ সুরক্ষা, সিক্রেট, দৃশ্যমানতা',
            ],
          },
          {
            type: 'paragraph',
            text: 'The README on the front page is the project’s handshake: what it does, how to install it, and how to contribute. Teams judge repositories partly by how well this page answers a newcomer’s first three questions.',
            textBn: 'সামনের পেজের README প্রজেক্টের করমর্দন: এটি কী করে, কীভাবে ইনস্টল করবেন, কীভাবে অবদান রাখবেন। নতুনদের প্রথম তিন প্রশ্নের উত্তর কত ভালো দেয় তা দিয়ে টিম আংশিক রিপোজিটরি বিচার করে।',
          },
        ],
      },
    ],
    relatedLessons: ['github.basics.what-is-github'],
  },
  {
    id: 'github.basics.public-vs-private',
    moduleId: 'github-fundamentals',
    slug: 'public-vs-private',
    order: 6,
    durationMinutes: 6,
    difficulty: 'beginner',
    title: 'Public vs Private Repositories',
    titleBn: 'পাবলিক বনাম প্রাইভেট রিপোজিটরি',
    summary: 'Visibility controls who can see and copy your code — and what "public" really implies for secrets and licensing.',
    summaryBn: 'দৃশ্যমানতা নিয়ন্ত্রণ করে কে কোড দেখতে ও কপি করতে পারে — এবং সিক্রেট ও লাইসেন্সিংয়ে "পাবলিক"-এর আসল মানে।',
    learningObjectives: [
      'Compare public and private repository visibility',
      'Explain why secrets must never enter any repository',
      'Choose the right visibility for personal, team, and open-source work',
    ],
    learningObjectivesBn: [
      'পাবলিক ও প্রাইভেট রিপোজিটরি দৃশ্যমানতা তুলনা করা',
      'কেন সিক্রেট কোনো রিপোজিটরিতে যাওয়া উচিত নয় তা ব্যাখ্যা করা',
      'ব্যক্তিগত, টিম ও ওপেন-সোর্স কাজে সঠিক দৃশ্যমানতা বেছে নেওয়া',
    ],
    keyTakeaways: [
      'Public means anyone can read and fork; private restricts access to collaborators.',
      'Visibility can change later, but history pushed publicly cannot be unseen.',
      'Secrets belong in environment variables and secret stores — never in Git history.',
    ],
    sections: [
      {
        id: 'sec-visibility',
        title: 'Choosing Visibility',
        titleBn: 'দৃশ্যমানতা বেছে নেওয়া',
        blocks: [
          {
            type: 'paragraph',
            text: 'Public repositories are readable — and forkable — by the whole internet, which is exactly what open source wants. Private repositories are visible only to people you invite, which is what most company work needs. You can flip visibility later, but anything pushed while public may already be copied elsewhere.',
            textBn: 'পাবলিক রিপোজিটরি পুরো ইন্টারনেট পড়তে — ও ফোর্ক করতে — পারে, ওপেন সোর্স ঠিক এটাই চায়। প্রাইভেট রিপোজিটরি শুধু আমন্ত্রিতরা দেখে, বেশিরভাগ কোম্পানির কাজে এটাই দরকার। দৃশ্যমানতা পরে বদলানো যায়, কিন্তু পাবলিক থাকতে পুশ করা কিছু ইতিমধ্যে অন্যত্র কপি হয়ে থাকতে পারে।',
          },
          {
            type: 'callout',
            variant: 'danger',
            title: 'History remembers',
            titleBn: 'হিস্ট্রি মনে রাখে',
            text: 'Switching a repository from public to private does not erase copies others already made — and deleting a secret in a later commit does not remove it from history. Rotate exposed credentials immediately.',
            textBn: 'রিপোজিটরি পাবলিক থেকে প্রাইভেট করলে অন্যের করা কপি মোছে না — আর পরের কমিটে সিক্রেট মুছলেও হিস্ট্রি থেকে যায় না। প্রকাশিত ক্রেডেনশিয়াল সাথে সাথে রোটেট করুন।',
          },
        ],
      },
    ],
    relatedLessons: ['github.basics.what-is-github'],
  },
];
