import { Workflow } from '@/types/content';

/**
 * GitHub collaboration workflows (subject: github).
 * Reuses the existing Workflow / WorkflowStep contracts — rendered by the
 * GitHub PR page's workflow guides section, searched via lesson search.
 */
export const GITHUB_WORKFLOWS: Workflow[] = [
  {
    id: 'github.workflow.create-repository',
    subjectId: 'github',
    title: 'Create a Repository',
    titleBn: 'রিপোজিটরি তৈরি',
    category: 'Setup',
    difficulty: 'beginner',
    scenario: 'Start a brand-new project on GitHub with a README, .gitignore, license, and the right visibility.',
    scenarioBn: 'README, .gitignore, লাইসেন্স ও সঠিক দৃশ্যমানতাসহ গিটহাবে নতুন প্রজেক্ট শুরু করুন।',
    tags: ['github', 'setup', 'repository', 'beginner'],
    steps: [
      { stepNumber: 1, title: 'Name and describe the repository', titleBn: 'রিপোজিটরির নাম ও বর্ণনা', description: 'Short lowercase hyphenated name plus one honest sentence of description.', descriptionBn: 'সংক্ষিপ্ত ছোট-হাতের হাইফেনযুক্ত নাম ও এক বাক্যের সৎ বর্ণনা।' },
      { stepNumber: 2, title: 'Initialize with README, .gitignore, license', titleBn: 'README, .gitignore, লাইসেন্সে শুরু', description: 'Never leave the first page empty; protect secrets and declare usage rights from day one.', descriptionBn: 'প্রথম পেজ কখনো খালি রাখবেন না; শুরু থেকে সিক্রেট রক্ষা ও ব্যবহার অধিকার ঘোষণা করুন।' },
      { stepNumber: 3, title: 'Choose visibility deliberately', titleBn: 'সচেতনভাবে দৃশ্যমানতা বেছে নিন', description: 'Public for open source, private for company and personal work.', descriptionBn: 'ওপেন সোর্সে পাবলিক, কোম্পানি ও ব্যক্তিগত কাজে প্রাইভেট।' },
      { stepNumber: 4, title: 'Clone and verify', titleBn: 'ক্লোন ও যাচাই', command: 'git clone <url>', description: 'Clone to your machine and confirm the README and default branch.', descriptionBn: 'মেশিনে ক্লোন করে README ও ডিফল্ট ব্রাঞ্চ নিশ্চিত করুন।' },
    ],
  },
  {
    id: 'github.workflow.clone-repository',
    subjectId: 'github',
    title: 'Clone a Repository',
    titleBn: 'রিপোজিটরি ক্লোন',
    category: 'Setup',
    difficulty: 'beginner',
    scenario: 'Join an existing GitHub project with full history and a pre-configured origin remote.',
    scenarioBn: 'সম্পূর্ণ হিস্ট্রি ও প্রি-কনফিগারড origin রিমোটসহ বিদ্যমান গিটহাব প্রজেক্টে যোগ দিন।',
    tags: ['github', 'clone', 'setup'],
    steps: [
      { stepNumber: 1, title: 'Copy the clone URL', titleBn: 'ক্লোন URL কপি করুন', description: 'Use the green Code button; prefer SSH after one-time key setup, else HTTPS.', descriptionBn: 'সবুজ Code বোতাম ব্যবহার করুন; একবার কী সেটআপের পর SSH, নইলে HTTPS।' },
      { stepNumber: 2, title: 'Clone locally', titleBn: 'লোকালি ক্লোন করুন', command: 'git clone <url>', description: 'Full history, origin remote, and tracked default branch arrive together.', descriptionBn: 'সম্পূর্ণ হিস্ট্রি, origin রিমোট ও ট্র্যাকড ডিফল্ট ব্রাঞ্চ একসাথে আসে।' },
      { stepNumber: 3, title: 'Verify remotes', titleBn: 'রিমোট যাচাই করুন', command: 'git remote -v', description: 'Confirm origin points where you expect before pushing anything.', descriptionBn: 'কিছু পুশের আগে origin প্রত্যাশিত জায়গা নির্দেশ করছে নিশ্চিত করুন।' },
    ],
  },
  {
    id: 'github.workflow.feature-branch',
    subjectId: 'github',
    title: 'Feature Branch Workflow',
    titleBn: 'ফিচার ব্রাঞ্চ ওয়ার্কফ্লো',
    category: 'Branching',
    difficulty: 'beginner',
    scenario: 'Isolate one unit of work from fresh main through push, ready for pull-request review.',
    scenarioBn: 'নতুন main থেকে পুশ পর্যন্ত একটি কাজ আলাদা করুন, পুল-রিকোয়েস্ট রিভিউয়ের জন্য প্রস্তুত।',
    tags: ['github', 'branch', 'feature', 'workflow'],
    steps: [
      { stepNumber: 1, title: 'Sync main', titleBn: 'main সিঙ্ক করুন', command: 'git switch main && git pull', description: 'Start from the team’s latest truth, never from a stale copy.', descriptionBn: 'পুরনো কপি নয়, টিমের সর্বশেষ সত্য থেকে শুরু করুন।' },
      { stepNumber: 2, title: 'Create the feature branch', titleBn: 'ফিচার ব্রাঞ্চ তৈরি করুন', command: 'git switch -c feature/<name>', description: 'One branch, one reviewable unit of work.', descriptionBn: 'এক ব্রাঞ্চ, একটি রিভিউযোগ্য কাজ।' },
      { stepNumber: 3, title: 'Commit in small steps', titleBn: 'ছোট ধাপে কমিট করুন', command: 'git add -p && git commit -m "..."', description: 'Logical commits make review fast and reverts safe.', descriptionBn: 'যৌক্তিক কমিট রিভিউ দ্রুত ও রিভার্ট নিরাপদ করে।' },
      { stepNumber: 4, title: 'Push early with tracking', titleBn: 'ট্র্যাকিংসহ তাড়াতাড়ি পুশ করুন', command: 'git push -u origin feature/<name>', description: 'Backup plus visibility; pushing is sharing, not merging.', descriptionBn: 'ব্যাকআপ ও দৃশ্যমানতা; পুশ শেয়ার করা, মার্জ নয়।' },
      { stepNumber: 5, title: 'Keep it updated', titleBn: 'হালনাগাদ রাখুন', command: 'git fetch origin && git merge origin/main', description: 'Fold main in regularly so the final review stays small.', descriptionBn: 'নিয়মিত main ভাঁজুন যাতে চূড়ান্ত রিভিউ ছোট থাকে।' },
    ],
  },
  {
    id: 'github.workflow.pull-request',
    subjectId: 'github',
    title: 'Pull Request Lifecycle',
    titleBn: 'পুল রিকোয়েস্ট জীবনচক্র',
    category: 'Pull Requests',
    difficulty: 'beginner',
    scenario: 'From pushed branch to merged main: open, describe, review, check, approve, merge.',
    scenarioBn: 'পুশড ব্রাঞ্চ থেকে মার্জড main: খুলুন, বর্ণনা, রিভিউ, চেক, অনুমোদন, মার্জ।',
    tags: ['github', 'pull-request', 'review', 'merge'],
    steps: [
      { stepNumber: 1, title: 'Open against the right base', titleBn: 'সঠিক বেসে খুলুন', description: 'Confirm base: main and compare: your branch before writing anything.', descriptionBn: 'কিছু লেখার আগে base: main ও compare: ব্রাঞ্চ নিশ্চিত করুন।' },
      { stepNumber: 2, title: 'Describe what, why, and testing', titleBn: 'কী, কেন ও টেস্টিং বর্ণনা করুন', description: 'Reviewers act on evidence: link issues and state how it was tested.', descriptionBn: 'রিভিউয়াররা প্রমাণে কাজ করেন: ইস্যু লিঙ্ক ও কীভাবে পরীক্ষিত তা বলুন।' },
      { stepNumber: 3, title: 'Collect review and checks', titleBn: 'রিভিউ ও চেক সংগ্রহ করুন', description: 'Human approval plus green automated checks gate the merge.', descriptionBn: 'মানব অনুমোদন ও সবুজ স্বয়ংক্রিয় চেক মার্জ আটকায়।' },
      { stepNumber: 4, title: 'Address feedback, push fixes', titleBn: 'মতামত সামলান, ফিক্স পুশ করুন', description: 'Every thread gets fixed, answered, or a reasoned deferral; the PR updates itself.', descriptionBn: 'প্রতিটি থ্রেড ফিক্স, উত্তর বা যুক্তিসহ স্থগিত পায়; PR নিজে আপডেট হয়।' },
      { stepNumber: 5, title: 'Merge and delete the branch', titleBn: 'মার্জ করে ব্রাঞ্চ মুছুন', description: 'Merge per repo strategy, then delete the branch everywhere.', descriptionBn: 'রেপো কৌশলে মার্জ করে সর্বত্র ব্রাঞ্চ মুছুন।' },
    ],
  },
  {
    id: 'github.workflow.code-review',
    subjectId: 'github',
    title: 'Code Review Pass',
    titleBn: 'কোড রিভিউ ধাপ',
    category: 'Review',
    difficulty: 'intermediate',
    scenario: 'Review a teammate’s diff for intent, bugs, and maintainability — then leave comments that teach.',
    scenarioBn: 'উদ্দেশ্য, বাগ ও রক্ষণাবেক্ষণে সহকর্মীর diff রিভিউ করুন — তারপর শেখায় এমন মন্তব্য রাখুন।',
    tags: ['github', 'review', 'collaboration'],
    steps: [
      { stepNumber: 1, title: 'Read the description first', titleBn: 'আগে বর্ণনা পড়ুন', description: 'Intent frames everything; review the goal before the code.', descriptionBn: 'উদ্দেশ্য সব ফ্রেম করে; কোডের আগে লক্ষ্য রিভিউ করুন।' },
      { stepNumber: 2, title: 'Walk the diff file by file', titleBn: 'ফাইল ধরে diff হাঁটুন', description: 'Ask: does it do what it claims, could it break, will we understand it later?', descriptionBn: 'জিজ্ঞেস করুন: দাবি মতো করে কি, ভাঙতে পারে কি, পরে বুঝব কি?' },
      { stepNumber: 3, title: 'Comment with specifics and why', titleBn: 'নির্দিষ্ট ও কেনসহ মন্তব্য করুন', description: 'Point at code, explain the concern, suggest a path. Separate blockers from suggestions.', descriptionBn: 'কোডে আঙুল দিন, উদ্বেগ ব্যাখ্যা করুন, পথ প্রস্তাব করুন। ব্লকার পরামর্শ থেকে আলাদা করুন।' },
      { stepNumber: 4, title: 'Approve, comment, or request changes', titleBn: 'অনুমোদন, মন্তব্য বা পরিবর্তন চান', description: 'Reserve change requests for genuine merge-blockers.', descriptionBn: 'আসল মার্জ-ব্লকারে পরিবর্তন অনুরোধ সংরক্ষণ করুন।' },
    ],
  },
  {
    id: 'github.workflow.merge-pull-request',
    subjectId: 'github',
    title: 'Merge a Pull Request',
    titleBn: 'পুল রিকোয়েস্ট মার্জ',
    category: 'Pull Requests',
    difficulty: 'intermediate',
    scenario: 'Land an approved, green pull request using the repository’s chosen strategy — then clean up.',
    scenarioBn: 'রিপোজিটরির বেছে নেওয়া কৌশলে অনুমোদিত, সবুজ পুল রিকোয়েস্ট অবতরণ করান — তারপর পরিষ্কার করুন।',
    tags: ['github', 'merge', 'squash', 'rebase'],
    steps: [
      { stepNumber: 1, title: 'Confirm approval and green checks', titleBn: 'অনুমোদন ও সবুজ চেক নিশ্চিত করুন', description: 'Never merge past red checks or missing required reviews.', descriptionBn: 'লাল চেক বা অনুপস্থিত বাধ্যতামূলক রিভিউ পেরিয়ে কখনো মার্জ নয়।' },
      { stepNumber: 2, title: 'Pick the configured strategy', titleBn: 'কনফিগারড কৌশল বেছে নিন', description: 'Merge commit, squash, or rebase — follow the repo default.', descriptionBn: 'মার্জ কমিট, স্কোয়াশ বা রিবেস — রেপো ডিফল্ট অনুসরণ করুন।' },
      { stepNumber: 3, title: 'Merge and verify main', titleBn: 'মার্জ করে main যাচাই করুন', description: 'Confirm the change landed and checks still pass on base.', descriptionBn: 'পরিবর্তন এসেছে ও বেসে চেক পাস নিশ্চিত করুন।' },
      { stepNumber: 4, title: 'Delete the branch', titleBn: 'ব্রাঞ্চ মুছুন', description: 'Remove the GitHub branch so the list stays honest.', descriptionBn: 'গিটহাব ব্রাঞ্চ সরিয়ে তালিকা সৎ রাখুন।' },
    ],
  },
  {
    id: 'github.workflow.sync-branch',
    subjectId: 'github',
    title: 'Sync a Branch with Base',
    titleBn: 'বেসের সাথে ব্রাঞ্চ সিঙ্ক',
    category: 'Sync',
    difficulty: 'beginner',
    scenario: 'Your branch fell behind main. Fetch, read the gap, and integrate deliberately before review.',
    scenarioBn: 'ব্রাঞ্চ main থেকে পিছিয়েছে। fetch করুন, ব্যবধান পড়ুন, রিভিউয়ের আগে সচেতনভাবে একীভূত করুন।',
    tags: ['github', 'sync', 'fetch', 'merge'],
    steps: [
      { stepNumber: 1, title: 'Fetch the latest', titleBn: 'সর্বশেষ আনুন', command: 'git fetch origin', description: 'Refresh your picture without touching any work.', descriptionBn: 'কাজ না ছুঁয়ে ছবি রিফ্রেশ করুন।' },
      { stepNumber: 2, title: 'Read the gap', titleBn: 'ব্যবধান পড়ুন', command: 'git log HEAD..origin/main --oneline', description: 'Know exactly what you are about to integrate.', descriptionBn: 'ঠিক কী একীভূত করতে যাচ্ছেন জানুন।' },
      { stepNumber: 3, title: 'Integrate and push', titleBn: 'একীভূত করে পুশ করুন', command: 'git merge origin/main && git push', description: 'Join histories (or rebase per convention), then publish the update.', descriptionBn: 'হিস্ট্রি যুক্ত করুন (বা প্রচলনে রিবেস), তারপর আপডেট প্রকাশ করুন।' },
    ],
  },
  {
    id: 'github.workflow.resolve-pr-conflict',
    subjectId: 'github',
    title: 'Resolve a PR Conflict',
    titleBn: 'PR কনফ্লিক্ট সমাধান',
    category: 'Conflicts',
    difficulty: 'intermediate',
    scenario: 'GitHub flags your pull request as conflicted. Resolve locally with the standard technique and push the resolution.',
    scenarioBn: 'গিটহাব পুল রিকোয়েস্ট কনফ্লিক্টেড চিহ্নিত করে। মানক কৌশলে লোকালি সমাধান করে রেজোলিউশন পুশ করুন।',
    tags: ['github', 'conflict', 'merge', 'pull-request'],
    steps: [
      { stepNumber: 1, title: 'Update against base', titleBn: 'বেসের বিপরীতে আপডেট করুন', command: 'git fetch origin && git merge origin/main', description: 'Surface the overlapping edits on your machine.', descriptionBn: 'মেশিনে ওভারল্যাপিং এডিট সামনে আনুন।' },
      { stepNumber: 2, title: 'Resolve markers and finish', titleBn: 'মার্কার সমাধান করে শেষ করুন', command: 'git add <files> && git commit', description: 'Edit to the correct final code, stage, and complete the merge.', descriptionBn: 'সঠিক চূড়ান্ত কোডে এডিট করে স্টেজ ও মার্জ সম্পন্ন করুন।' },
      { stepNumber: 3, title: 'Push and verify checks', titleBn: 'পুশ করে চেক যাচাই করুন', command: 'git push', description: 'The PR refreshes and checks re-run automatically.', descriptionBn: 'PR রিফ্রেশ হয় ও চেক স্বয়ংক্রিয় পুনরায় চলে।' },
    ],
  },
];
