import { CurriculumLesson } from '@/types/content';

/**
 * Module 4 — Pull Requests (subject: github)
 * The heart of GitHub collaboration: what PRs are, creating them well,
 * drafts, review dynamics, approval, merge, and closing.
 */
export const GITHUB_PR_LESSONS: CurriculumLesson[] = [
  {
    id: 'github.pr.what-is-a-pull-request',
    moduleId: 'github-pull-requests',
    slug: 'what-is-a-pull-request',
    order: 1,
    durationMinutes: 9,
    difficulty: 'beginner',
    title: 'What is a Pull Request?',
    titleBn: 'পুল রিকোয়েস্ট কী?',
    summary: 'A Pull Request is a proposal to merge one branch into another — plus the entire conversation, review, and automation around that proposal.',
    summaryBn: 'পুল রিকোয়েস্ট হলো একটি ব্রাঞ্চ আরেকটিতে মার্জের প্রস্তাব — সাথে প্রস্তাব ঘিরে পুরো আলোচনা, রিভিউ ও অটোমেশন।',
    learningObjectives: [
      'Define a pull request as proposal + process',
      'Explain that a PR is not a Git command',
      'Trace the ten conceptual steps from push to merge',
    ],
    learningObjectivesBn: [
      'পুল রিকোয়েস্টকে প্রস্তাব + প্রক্রিয়া হিসেবে সংজ্ঞায়িত করা',
      'ব্যাখ্যা করা PR গিট কমান্ড নয়',
      'পুশ থেকে মার্জ পর্যন্ত দশটি ধারণাগত ধাপ অনুসরণ করা',
    ],
    keyTakeaways: [
      'A PR proposes integrating feature/login into main; humans and checks decide.',
      'PRs are a GitHub concept — Git itself has branches and merges, not pull requests.',
      'Pushing more commits to the branch automatically updates the open PR.',
    ],
    sections: [
      {
        id: 'sec-proposal',
        title: 'A Proposal, Not a Command',
        titleBn: 'প্রস্তাব, কমান্ড নয়',
        blocks: [
          {
            type: 'paragraph',
            text: 'A Pull Request is a proposal to integrate changes from one branch into another — for example feature/login into main. Crucially, a PR is not itself a Git command: no git pull-request exists. It is a GitHub object that wraps a branch comparison in discussion, review, automated checks, and finally a merge operation.',
            textBn: 'পুল রিকোয়েস্ট হলো একটি ব্রাঞ্চের পরিবর্তন আরেকটিতে একীভূতের প্রস্তাব — যেমন feature/login থেকে main-এ। গুরুত্বপূর্ণ: PR নিজে গিট কমান্ড নয়: git pull-request বলে কিছু নেই। এটি গিটহাব অবজেক্ট যা ব্রাঞ্চ তুলনাকে আলোচনা, রিভিউ, স্বয়ংক্রিয় চেক ও শেষে মার্জ অপারেশনে মোড়ায়।',
          },
          {
            type: 'code',
            code: 'feature/login\n      ↓\nPull Request\n      ↓\nmain',
            language: 'text',
          },
          {
            type: 'heading',
            level: 3,
            text: 'What happens conceptually',
            textBn: 'ধারণাগতভাবে কী ঘটে',
          },
          {
            type: 'list',
            ordered: true,
            items: [
              'Developer pushes the branch to GitHub.',
              'GitHub receives the branch commits.',
              'Developer opens the pull request.',
              'Reviewers inspect the changes.',
              'Review comments may be added.',
              'Developer pushes additional commits; the PR updates.',
              'Automated checks run against the branch.',
              'The PR is approved.',
              'The PR is merged into the base branch.',
            ],
            itemsBn: [
              'ডেভেলপার ব্রাঞ্চ গিটহাবে পুশ করেন।',
              'গিটহাব ব্রাঞ্চ কমিট গ্রহণ করে।',
              'ডেভেলপার পুল রিকোয়েস্ট খোলেন।',
              'রিভিউয়াররা পরিবর্তন পরিদর্শন করেন।',
              'রিভিউ মন্তব্য যোগ হতে পারে।',
              'ডেভেলপার অতিরিক্ত কমিট পুশ করেন; PR আপডেট হয়।',
              'ব্রাঞ্চের বিরুদ্ধে স্বয়ংক্রিয় চেক চলে।',
              'PR অনুমোদিত হয়।',
              'PR বেস ব্রাঞ্চে মার্জ হয়।',
            ],
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-github-what-is-pr',
      subjectId: 'github',
      difficulty: 'beginner',
      question: 'What is a GitHub Pull Request?',
      questionBn: 'গিটহাব পুল রিকোয়েস্ট কী?',
      options: [
        { id: 'opt-a', text: 'A Git command that downloads pull changes faster', textBn: 'পুল পরিবর্তন দ্রুত ডাউনলোড করা গিট কমান্ড', isCorrect: false },
        { id: 'opt-b', text: 'A proposal to merge one branch into another, with review and checks', textBn: 'এক ব্রাঞ্চ আরেকটিতে মার্জের প্রস্তাব, রিভিউ ও চেকসহ', isCorrect: true },
        { id: 'opt-c', text: 'A backup copy of a repository on GitHub servers', textBn: 'গিটহাব সার্ভারে রিপোজিটরির ব্যাকআপ কপি', isCorrect: false },
        { id: 'opt-d', text: 'A chat room for developers on a team', textBn: 'টিম ডেভেলপারদের চ্যাট রুম', isCorrect: false },
      ],
      explanation: 'A PR wraps a branch comparison in proposal, discussion, review, checks, and merge — it is a GitHub concept, not a Git command.',
      explanationBn: 'PR ব্রাঞ্চ তুলনাকে প্রস্তাব, আলোচনা, রিভিউ, চেক ও মার্জে মোড়ায় — এটি গিটহাব ধারণা, গিট কমান্ড নয়।',
    },
    relatedCommands: ['git.push', 'git.branch'],
    relatedLessons: ['github.branching.feature-branches', 'git.fundamentals.branch'],
  },
  {
    id: 'github.pr.create-pull-request',
    moduleId: 'github-pull-requests',
    slug: 'create-pull-request',
    order: 2,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'Creating a Pull Request',
    titleBn: 'পুল রিকোয়েস্ট তৈরি করা',
    summary: 'Push your branch, pick the right base and compare branches, verify the diff, then open the PR with a description reviewers can act on.',
    summaryBn: 'ব্রাঞ্চ পুশ করুন, সঠিক বেস ও তুলনা ব্রাঞ্চ বেছে নিন, diff যাচাই করুন, তারপর রিভিউয়াররা কাজ করতে পারে এমন বর্ণনাসহ PR খুলুন।',
    learningObjectives: [
      'Open a PR with the correct base and compare branches',
      'Verify the diff before requesting review',
      'Choose reviewers deliberately',
    ],
    learningObjectivesBn: [
      'সঠিক বেস ও তুলনা ব্রাঞ্চে PR খোলা',
      'রিভিউ চাওয়ার আগে diff যাচাই করা',
      'সচেতনভাবে রিভিউয়ার বেছে নেওয়া',
    ],
    keyTakeaways: [
      'Base is where changes go; compare is where they come from — double-check both.',
      'The diff preview is your last self-review before humans arrive.',
      'Request reviewers who own the touched code, not random teammates.',
    ],
    sections: [
      {
        id: 'sec-open',
        title: 'From Push to Proposal',
        titleBn: 'পুশ থেকে প্রস্তাব',
        blocks: [
          {
            type: 'list',
            ordered: true,
            items: [
              'Push the branch: git push -u origin feature/login.',
              'On GitHub, open Compare & pull request from the branch banner.',
              'Confirm base: main and compare: feature/login.',
              'Scan the diff — files, additions, deletions — for surprises.',
              'Write the title and description, then create the pull request.',
            ],
            itemsBn: [
              'ব্রাঞ্চ পুশ করুন: git push -u origin feature/login।',
              'গিটহাবে ব্রাঞ্চ ব্যানার থেকে Compare & pull request খুলুন।',
              'নিশ্চিত করুন base: main ও compare: feature/login।',
              'diff স্ক্যান করুন — ফাইল, সংযোজন, বিয়োজন — চমকের জন্য।',
              'শিরোনাম ও বর্ণনা লিখে পুল রিকোয়েস্ট তৈরি করুন।',
            ],
          },
          {
            type: 'callout',
            variant: 'warning',
            title: 'Base mistakes are expensive',
            titleBn: 'বেস ভুল ব্যয়বহুল',
            text: 'Opening a PR against the wrong base branch proposes merging into the wrong timeline. Always glance at the base/compare header before writing a single word.',
            textBn: 'ভুল বেস ব্রাঞ্চে PR খুললে ভুল টাইমলাইনে মার্জ প্রস্তাব হয়। একটি শব্দ লেখার আগে বেস/compare হেডারে চোখ বুলান।',
          },
        ],
      },
    ],
    relatedCommands: ['git.push', 'git.branch'],
    relatedLessons: ['github.pr.pr-title-description', 'github.pr.what-is-a-pull-request'],
  },
  {
    id: 'github.pr.pr-title-description',
    moduleId: 'github-pull-requests',
    slug: 'pr-title-description',
    order: 3,
    durationMinutes: 7,
    difficulty: 'beginner',
    title: 'PR Title and Description',
    titleBn: 'PR শিরোনাম ও বর্ণনা',
    summary: 'Reviewers decide how carefully to read from your title and description. What changed, why, how tested, and what to watch.',
    summaryBn: 'রিভিউয়াররা শিরোনাম ও বর্ণনা দেখে কত যত্নে পড়বেন ঠিক করেন। কী বদলেছে, কেন, কীভাবে পরীক্ষিত, কী দেখবেন।',
    learningObjectives: [
      'Write a scannable PR title',
      'Cover what, why, testing, and reviewer notes',
      'Link related issues for context',
    ],
    learningObjectivesBn: [
      'স্ক্যানযোগ্য PR শিরোনাম লেখা',
      'কী, কেন, টেস্টিং ও রিভিউয়ার নোট কভার করা',
      'প্রেক্ষাপটে সম্পর্কিত ইস্যু লিঙ্ক করা',
    ],
    keyTakeaways: [
      'Title states the change; description justifies and evidences it.',
      'Always say how it was tested — reviewers trust evidence, not claims.',
      'Link issues (Fixes #123) so merging can close the loop automatically.',
    ],
    sections: [
      {
        id: 'sec-template',
        title: 'A Template That Earns Reviews',
        titleBn: 'রিভিউ অর্জনকারী টেমপ্লেট',
        blocks: [
          {
            type: 'code',
            code: '## What changed\nAdded password reset flow.\n\n## Why\nUsers currently cannot recover access.\n\n## Testing\nTested successful reset and invalid token cases.\n\nReviewers: please check the token expiry logic.',
            language: 'markdown',
          },
          {
            type: 'paragraph',
            text: 'Treat the template as guidance, not bureaucracy: tiny PRs need tiny descriptions, but they always need the why. A reviewer who understands the reason reviews the right thing.',
            textBn: 'টেমপ্লেটকে নির্দেশনা ধরুন, আমলাতন্ত্র নয়: ছোট PR-এ ছোট বর্ণনা, কিন্তু কেন সবসময় দরকার। কারণ বোঝা রিভিউয়ার সঠিক জিনিস রিভিউ করেন।',
          },
        ],
      },
    ],
    relatedLessons: ['github.pr.create-pull-request'],
  },
  {
    id: 'github.pr.draft-pull-requests',
    moduleId: 'github-pull-requests',
    slug: 'draft-pull-requests',
    order: 4,
    durationMinutes: 6,
    difficulty: 'beginner',
    title: 'Draft Pull Requests',
    titleBn: 'ড্রাফট পুল রিকোয়েস্ট',
    summary: 'Draft PRs invite early feedback on unfinished work. They communicate clearly: this is not ready to merge yet.',
    summaryBn: 'ড্রাফট PR অসমাপ্ত কাজে আগাম মতামত আনে। স্পষ্ট জানায়: এটি এখনো মার্জের জন্য প্রস্তুত নয়।',
    learningObjectives: [
      'Explain when a draft beats a finished PR',
      'Describe what draft status signals to reviewers',
      'Convert a draft to ready when work completes',
    ],
    learningObjectivesBn: [
      'ব্যাখ্যা করা কখন ড্রাফট সম্পূর্ণ PR-কে হারায়',
      'ড্রাফট অবস্থা রিভিউয়ারদের কী সংকেত দেয় তা বর্ণনা করা',
      'কাজ শেষে ড্রাফট প্রস্তুত করা',
    ],
    keyTakeaways: [
      'Drafts are for direction feedback: architecture, approach, early API shape.',
      'Draft status blocks merging — the platform enforces the message.',
      'Mark ready for review only when checks pass and the diff is complete.',
    ],
    sections: [
      {
        id: 'sec-draft',
        title: 'Not Ready — On Purpose',
        titleBn: 'প্রস্তুত নয় — উদ্দেশ্যমূলকভাবে',
        blocks: [
          {
            type: 'list',
            items: [
              'Early feedback on an uncertain implementation direction.',
              'Architectural discussion before the code hardens.',
              'Work in progress you want visible and backed up.',
              'Signalling teammates that review can wait.',
            ],
            itemsBn: [
              'অনিশ্চিত বাস্তবায়ন দিকে আগাম মতামত।',
              'কোড শক্ত হওয়ার আগে আর্কিটেকচার আলোচনা।',
              'দৃশ্যমান ও ব্যাকআপ চাওয়া চলমান কাজ।',
              'সহকর্মীদের জানানো রিভিউ অপেক্ষা করতে পারে।',
            ],
          },
          {
            type: 'paragraph',
            text: 'A Draft PR says "this is not ready to merge yet" in a way no comment can match — GitHub itself refuses the merge button. Use drafts to think out loud; convert to ready when the thinking is done.',
            textBn: 'ড্রাফট PR "এটি এখনো মার্জের জন্য প্রস্তুত নয়" এমনভাবে বলে যা কোনো মন্তব্য পারে না — গিটহাব নিজেই মার্জ বোতাম প্রত্যাখ্যান করে। জোরে ভাবতে ড্রাফট ব্যবহার করুন; ভাবনা শেষে প্রস্তুত করুন।',
          },
        ],
      },
    ],
    relatedLessons: ['github.pr.create-pull-request'],
  },
  {
    id: 'github.pr.reviewing-changes',
    moduleId: 'github-pull-requests',
    slug: 'reviewing-changes',
    order: 5,
    durationMinutes: 10,
    difficulty: 'intermediate',
    title: 'Reviewing Changes',
    titleBn: 'পরিবর্তন রিভিউ করা',
    summary: 'Review the diff with intent: understand the goal, hunt bugs and maintainability risks, and leave comments that teach rather than wound.',
    summaryBn: 'উদ্দেশ্য নিয়ে diff রিভিউ করুন: লক্ষ্য বুঝুন, বাগ ও রক্ষণাবেক্ষণ ঝুঁকি খুঁজুন, আঘাত নয় শেখায় এমন মন্তব্য রাখুন।',
    learningObjectives: [
      'Review a diff for intent, bugs, and maintainability',
      'Separate blocking issues from suggestions',
      'Write constructive review comments with examples',
    ],
    learningObjectivesBn: [
      'উদ্দেশ্য, বাগ ও রক্ষণাবেক্ষণে diff রিভিউ করা',
      'ব্লকিং সমস্যা ও পরামর্শ আলাদা করা',
      'উদাহরণসহ গঠনমূলক রিভিউ মন্তব্য লেখা',
    ],
    keyTakeaways: [
      'Reviewers inspect the difference between base and proposed branches.',
      'Good comments point at code, explain why, and suggest a path.',
      'Blocking issues stop the merge; suggestions respect author judgment.',
    ],
    sections: [
      {
        id: 'sec-review',
        title: 'How to Read a Diff',
        titleBn: 'Diff কীভাবে পড়বেন',
        blocks: [
          {
            type: 'paragraph',
            text: 'Reviewers inspect the difference between the base branch and the proposed branch — nothing else. Start with the PR description for intent, read the diff file by file, and ask three questions: does it do what it claims, could it break anything, and will future us understand it?',
            textBn: 'রিভিউয়াররা বেস ও প্রস্তাবিত ব্রাঞ্চের পার্থক্য পরিদর্শন করেন — আর কিছু নয়। উদ্দেশ্যে PR বর্ণনা দিয়ে শুরু, ফাইল ধরে diff পড়ুন, তিন প্রশ্ন করুন: দাবি মতো কাজ করে কি, কিছু ভাঙতে পারে কি, ভবিষ্যৎ আমরা বুঝবে কি?',
          },
          {
            type: 'code',
            code: '- const oldValue = readCache(key);\n+ const newValue = readCache(key, { ttl: 60 });',
            language: 'diff',
          },
          {
            type: 'heading',
            level: 3,
            text: 'Good vs poor comments',
            textBn: 'ভালো বনাম খারাপ মন্তব্য',
          },
          {
            type: 'list',
            items: [
              'Good: "Could we extract this validation into a helper? It is duplicated in these two paths."',
              'Poor: "This is bad."',
              'Good: "Blocking: this deletes rows without a backup — can we confirm the migration first?"',
              'Poor: "Why did you do it like this???"',
            ],
            itemsBn: [
              'ভালো: "এই ভ্যালিডেশন হেলপারে তোলা যায় কি? দুটি পথে ডুপ্লিকেট আছে।"',
              'খারাপ: "এটা খারাপ।"',
              'ভালো: "ব্লকিং: ব্যাকআপ ছাড়া রো মুছছে — আগে মাইগ্রেশন নিশ্চিত করি?"',
              'খারাপ: "এভাবে কেন করলে???"',
            ],
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-github-code-review',
      subjectId: 'github',
      category: 'Collaboration',
      difficulty: 'intermediate',
      question: 'What do you look for when reviewing a pull request?',
      questionBn: 'পুল রিকোয়েস্ট রিভিউয়ে কী দেখেন?',
      answer: 'Intent first (does it match the description?), then correctness (bugs, edge cases, security), then maintainability (naming, duplication, tests). I separate blocking issues from suggestions and always explain the why behind a requested change.',
      answerBn: 'আগে উদ্দেশ্য (বর্ণনার সাথে মেলে?), তারপর সঠিকতা (বাগ, এজ কেস, নিরাপত্তা), তারপর রক্ষণাবেক্ষণ (নামকরণ, ডুপ্লিকেশন, টেস্ট)। ব্লকিং সমস্যা পরামর্শ থেকে আলাদা করি ও অনুরোধের পেছনের কেন সবসময় ব্যাখ্যা করি।',
      keyPoints: ['Intent, correctness, maintainability — in that order', 'Blocking vs suggestion', 'Explain the why'],
      keyPointsBn: ['উদ্দেশ্য, সঠিকতা, রক্ষণাবেক্ষণ — এই ক্রমে', 'ব্লকিং বনাম পরামর্শ', 'কেন ব্যাখ্যা করুন'],
    },
    quiz: {
      id: 'quiz-github-review-comments',
      subjectId: 'github',
      difficulty: 'intermediate',
      question: 'Which review comment is constructive?',
      questionBn: 'কোন রিভিউ মন্তব্য গঠনমূলক?',
      options: [
        { id: 'opt-a', text: '"This is bad."', textBn: '"এটা খারাপ।"', isCorrect: false },
        { id: 'opt-b', text: '"Could we extract this validation into a helper? It is duplicated in these two paths."', textBn: '"ভ্যালিডেশন হেলপারে তোলা যায় কি? দুটি পথে ডুপ্লিকেট।"', isCorrect: true },
        { id: 'opt-c', text: '"Why did you do it like this???"', textBn: '"এভাবে কেন করলে???"', isCorrect: false },
        { id: 'opt-d', text: '"Just rewrite the whole file."', textBn: '"পুরো ফাইল আবার লেখো।"', isCorrect: false },
      ],
      explanation: 'Constructive comments point at specific code, explain the concern, and suggest a concrete path forward.',
      explanationBn: 'গঠনমূলক মন্তব্য নির্দিষ্ট কোডে আঙুল দেয়, উদ্বেগ ব্যাখ্যা করে ও সুনির্দিষ্ট পথ প্রস্তাব করে।',
    },
    relatedLessons: ['github.pr.requesting-changes', 'github.pr.pr-title-description'],
  },
  {
    id: 'github.pr.requesting-changes',
    moduleId: 'github-pull-requests',
    slug: 'requesting-changes',
    order: 6,
    durationMinutes: 7,
    difficulty: 'intermediate',
    title: 'Requesting Changes',
    titleBn: 'পরিবর্তনের অনুরোধ',
    summary: 'Requesting changes blocks the merge until issues are resolved. Use it precisely, explain thoroughly, and re-review promptly.',
    summaryBn: 'পরিবর্তনের অনুরোধ সমস্যা সমাধান না হওয়া পর্যন্ত মার্জ আটকায়। নির্ভুল ব্যবহার করুন, পুঙ্খানুপুঙ্খ ব্যাখ্যা দিন, দ্রুত পুনরায় রিভিউ করুন।',
    learningObjectives: [
      'Explain what a change request does to PR state',
      'Decide when to request changes vs comment',
      'Follow up with timely re-reviews',
    ],
    learningObjectivesBn: [
      'ব্যাখ্যা করা পরিবর্তন অনুরোধ PR অবস্থার কী করে',
      'কখন পরিবর্তন চাইবেন বনাম মন্তব্য করবেন তা ঠিক করা',
      'সময়মতো পুনরায় রিভিউয়ে ফলোআপ করা',
    ],
    keyTakeaways: [
      'Request changes only for issues that must block merging.',
      'Every requested change needs a clear reason and a path to resolve it.',
      'Re-review quickly after fixes — requested changes create a debt of attention.',
    ],
    sections: [
      {
        id: 'sec-request',
        title: 'A Brake, Not a Weapon',
        titleBn: 'ব্রেক, অস্ত্র নয়',
        blocks: [
          {
            type: 'paragraph',
            text: 'Requesting changes moves the PR into Changes Requested state: the merge is blocked until the author addresses each thread and you re-review. Reserve it for genuine blockers — bugs, security holes, broken tests. For taste and polish, use comments that the author may resolve freely.',
            textBn: 'পরিবর্তনের অনুরোধ PR-কে Changes Requested অবস্থায় নেয়: প্রতিটি থ্রেড সমাধান ও আপনার পুনরায় রিভিউ না হওয়া পর্যন্ত মার্জ আটকে থাকে। আসল ব্লকারে সংরক্ষণ করুন — বাগ, নিরাপত্তা ছিদ্র, ভাঙা টেস্ট। রুচি ও পরিমার্জনে মন্তব্য ব্যবহার করুন যা লেখক স্বাধীনভাবে সমাধান করতে পারেন।',
          },
        ],
      },
    ],
    relatedLessons: ['github.pr.reviewing-changes', 'github.team.handling-review-changes'],
  },
  {
    id: 'github.pr.approving-pr',
    moduleId: 'github-pull-requests',
    slug: 'approving-pr',
    order: 7,
    durationMinutes: 6,
    difficulty: 'beginner',
    title: 'Approving a Pull Request',
    titleBn: 'পুল রিকোয়েস্ট অনুমোদন',
    summary: 'Approval means you reviewed the diff and accept responsibility for it entering the codebase. Approve deliberately, not socially.',
    summaryBn: 'অনুমোদন মানে diff রিভিউ করেছেন ও কোডবেসে ঢোকার দায় নিচ্ছেন। সামাজিকভাবে নয়, সচেতনভাবে অনুমোদন করুন।',
    learningObjectives: [
      'Explain what an approval signifies',
      'Distinguish approval from merging',
      'Know when to withhold approval',
    ],
    learningObjectivesBn: [
      'ব্যাখ্যা করা অনুমোদন কী বোঝায়',
      'অনুমোদন ও মার্জের পার্থক্য করা',
      'কখন অনুমোদন আটকে রাখবেন তা জানা',
    ],
    keyTakeaways: [
      'Approve means "I reviewed this and it is good to merge".',
      'Approval does not merge — it unlocks merging per branch rules.',
      'Withhold approval for unresolved blockers, even under time pressure.',
    ],
    sections: [
      {
        id: 'sec-approve',
        title: 'A Signature of Responsibility',
        titleBn: 'দায়িত্বের স্বাক্ষর',
        blocks: [
          {
            type: 'paragraph',
            text: 'Clicking Approve attaches your name to the change. In repositories with branch protection, the required number of approvals is what actually permits the merge button. Approve when you would be comfortable debugging this code at midnight — otherwise, comment or request changes.',
            textBn: 'Approve ক্লিকে নাম পরিবর্তনে যুক্ত হয়। ব্রাঞ্চ সুরক্ষিত রিপোজিটরিতে প্রয়োজনীয় সংখ্যক অনুমোদনই মার্জ বোতামের অনুমতি দেয়। মধ্যরাতে এই কোড ডিবাগ করতে স্বচ্ছন্দ হলে অনুমোদন করুন — নইলে মন্তব্য বা পরিবর্তন চান।',
          },
        ],
      },
    ],
    relatedLessons: ['github.pr.reviewing-changes', 'github.pr.merging-pr'],
  },
  {
    id: 'github.pr.merging-pr',
    moduleId: 'github-pull-requests',
    slug: 'merging-pr',
    order: 8,
    durationMinutes: 10,
    difficulty: 'intermediate',
    title: 'Merging a Pull Request',
    titleBn: 'পুল রিকোয়েস্ট মার্জ করা',
    summary: 'Merge commit, squash, or rebase — three strategies with different histories. Understand each, then follow your team’s choice.',
    summaryBn: 'মার্জ কমিট, স্কোয়াশ বা রিবেস — ভিন্ন হিস্ট্রির তিন কৌশল। প্রতিটি বুঝুন, তারপর টিমের পছন্দ অনুসরণ করুন।',
    learningObjectives: [
      'Compare merge commit, squash, and rebase strategies',
      'Explain what each produces on the base branch',
      'Follow the repository’s configured strategy',
    ],
    learningObjectivesBn: [
      'মার্জ কমিট, স্কোয়াশ ও রিবেস কৌশল তুলনা করা',
      'ব্যাখ্যা করা প্রতিটি বেস ব্রাঞ্চে কী তৈরি করে',
      'রিপোজিটরির কনফিগারড কৌশল অনুসরণ করা',
    ],
    keyTakeaways: [
      'Merge commit preserves topology with a join commit.',
      'Squash condenses the PR into one commit on base.',
      'Rebase replays PR commits linearly onto base.',
      'No strategy is universally best — teams choose deliberately.',
    ],
    sections: [
      {
        id: 'sec-strategies',
        title: 'Three Ways to Land',
        titleBn: 'অবতরণের তিন পথ',
        blocks: [
          {
            type: 'heading',
            level: 3,
            text: '1. Merge commit',
            textBn: '১. মার্জ কমিট',
          },
          {
            type: 'paragraph',
            text: 'Preserves the branch topology exactly and records a merge commit with two parents. History is honest and complete — and branchy. Best when the journey (individual commits, discussion context) matters.',
            textBn: 'ব্রাঞ্চ টপোলজি হুবহু সংরক্ষণ করে দুই প্যারেন্টের মার্জ কমিট রেকর্ড করে। হিস্ট্রি সৎ ও সম্পূর্ণ — এবং শাখাময়। যাত্রা (আলাদা কমিট, আলোচনা প্রেক্ষাপট) গুরুত্বপূর্ণ হলে সেরা।',
          },
          {
            type: 'heading',
            level: 3,
            text: '2. Squash and merge',
            textBn: '২. স্কোয়াশ ও মার্জ',
          },
          {
            type: 'paragraph',
            text: 'Combines every PR commit into a single commit on the target branch. Base history stays a clean list of features, while the messy middle (typo fixes, experiments) disappears. Best for small PRs where only the outcome matters.',
            textBn: 'প্রতিটি PR কমিট টার্গেট ব্রাঞ্চে এক কমিটে একত্র করে। বেস হিস্ট্রি ফিচারের পরিষ্কার তালিকা থাকে, অগোছালো মাঝ (বানান ঠিক, পরীক্ষা) উধাও হয়। ছোট PR-এ সেরা যেখানে শুধু ফলাফল গুরুত্বপূর্ণ।',
          },
          {
            type: 'heading',
            level: 3,
            text: '3. Rebase and merge',
            textBn: '৩. রিবেস ও মার্জ',
          },
          {
            type: 'paragraph',
            text: 'Places each PR commit linearly onto the tip of the base branch with no merge commit. History reads like a story — but every commit is rewritten, so it suits teams comfortable with rebasing conventions.',
            textBn: 'প্রতিটি PR কমিট মার্জ কমিট ছাড়া বেস ব্রাঞ্চের শীর্ষে রৈখিক বসায়। হিস্ট্রি গল্পের মতো পড়া যায় — তবে প্রতিটি কমিট পুনর্লিখিত হয়, তাই রিবেস প্রচলনে স্বচ্ছন্দ টিমে মানায়।',
          },
          {
            type: 'callout',
            variant: 'note',
            title: 'Team choice, not dogma',
            titleBn: 'টিম পছন্দ, মতবাদ নয়',
            text: 'Repositories configure which strategies are allowed. Learn all three, respect the configured default, and never declare one universally superior.',
            textBn: 'রিপোজিটরি কনফিগার করে কোন কৌশল অনুমোদিত। তিনটি শিখুন, কনফিগারড ডিফল্ট সম্মান করুন, কোনোটিকে সার্বজনীন শ্রেষ্ঠ ঘোষণা করবেন না।',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-github-merge-strategies',
      subjectId: 'github',
      category: 'Collaboration',
      difficulty: 'intermediate',
      question: 'Compare GitHub’s merge commit, squash, and rebase strategies.',
      questionBn: 'গিটহাবের মার্জ কমিট, স্কোয়াশ ও রিবেস কৌশল তুলনা করুন।',
      answer: 'Merge commit preserves full topology with a join commit. Squash condenses the PR to one commit for a clean feature list. Rebase replays commits linearly with no merge commit. The right choice depends on whether the team values complete history, clean logs, or linear stories.',
      answerBn: 'মার্জ কমিট জয়েন কমিটে পূর্ণ টপোলজি সংরক্ষণ করে। স্কোয়াশ PR-কে পরিষ্কার ফিচার তালিকায় এক কমিটে ঘনীভূত করে। রিবেস মার্জ কমিট ছাড়া রৈখিক রিপ্লে করে। সঠিক পছন্দ নির্ভর করে টিম সম্পূর্ণ হিস্ট্রি, পরিষ্কার লগ না রৈখিক গল্প চায়।',
      keyPoints: ['Topology vs cleanliness vs linearity', 'Rebase rewrites identities', 'Follow repo configuration'],
      keyPointsBn: ['টপোলজি বনাম পরিষ্কারতা বনাম রৈখিকতা', 'রিবেস পরিচয় পুনর্লিখন করে', 'রেপো কনফিগারেশন অনুসরণ করুন'],
    },
    relatedCommands: ['git.merge', 'git.rebase', 'git.log'],
    relatedLessons: ['github.branching.merging-branches', 'git.fundamentals.branch', 'git.internals.rebase-rewrites-history', 'git.internals.dag-structure'],
  },
  {
    id: 'github.pr.closing-pr',
    moduleId: 'github-pull-requests',
    slug: 'closing-pr',
    order: 9,
    durationMinutes: 5,
    difficulty: 'beginner',
    title: 'Closing a Pull Request',
    titleBn: 'পুল রিকোয়েস্ট বন্ধ করা',
    summary: 'Not every PR should merge. Close superseded or abandoned proposals kindly, with a reason future readers understand.',
    summaryBn: 'প্রতিটি PR মার্জ হওয়া উচিত নয়। অপ্রচলিত বা পরিত্যক্ত প্রস্তাব সদয়ভাবে বন্ধ করুন, ভবিষ্যৎ পাঠক বোঝে এমন কারণসহ।',
    learningObjectives: [
      'Distinguish closing from merging',
      'Close a PR with a helpful final comment',
      'Reopen or reference closed PRs when plans change',
    ],
    learningObjectivesBn: [
      'বন্ধ করা ও মার্জের পার্থক্য করা',
      'সহায়ক শেষ মন্তব্যে PR বন্ধ করা',
      'পরিকল্পনা বদলে বন্ধ PR পুনরায় খোলা বা রেফারেন্স করা',
    ],
    keyTakeaways: [
      'Closing ends the proposal without changing the base branch.',
      'Always leave a closing reason — silence reads as rejection.',
      'Closed PRs remain searchable history; link them when superseded.',
    ],
    sections: [
      {
        id: 'sec-close',
        title: 'End Proposals Gracefully',
        titleBn: 'মর্যাদায় প্রস্তাব শেষ করুন',
        blocks: [
          {
            type: 'paragraph',
            text: 'Ideas expire: a better approach landed first, priorities shifted, or the author moved on. Closing without merging is a normal, healthy outcome — write one sentence explaining why, so nobody reopens the same debate in six months.',
            textBn: 'ধারণার মেয়াদ শেষ হয়: ভালো পদ্ধতি আগে এসেছে, অগ্রাধিকার বদলেছে, বা লেখক সরে গেছেন। মার্জ না করে বন্ধ করা স্বাভাবিক, সুস্থ ফল — কেন এক বাক্যে লিখুন, যাতে ছয় মাস পর কেউ একই বিতর্ক না খোলে।',
          },
        ],
      },
    ],
    relatedLessons: ['github.pr.what-is-a-pull-request'],
  },
];
