/**
 * Interview questions — commands (15).
 * Data only. Stable ids (`git.interview.<slug>`), bilingual copy.
 */
import { InterviewQuestion } from '@/types/interview';

export const COMMAND_QUESTIONS: InterviewQuestion[] = [
  {
    id: 'git.interview.cmd-status',
    category: 'commands',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'You return to a project after a week. What is the first command you run, and why?',
      bn: 'এক সপ্তাহ পর প্রজেক্টে ফিরলেন। প্রথমে কোন কমান্ড চালাবেন, কেন?',
    },
    shortAnswer: {
      en: 'git status — it shows the branch, staged/unstaged changes, and sync state before you touch anything.',
      bn: 'git status — কিছু ধরার আগে ব্রাঞ্চ, স্টেজড/আনস্টেজড পরিবর্তন ও সিঙ্ক অবস্থা দেখায়।',
    },
    explanation: {
      en: 'Status is the only command that is always safe and always informative: current branch, what changed, what is staged, and whether you are ahead or behind the remote. Professionals run it reflexively before and after every operation.',
      bn: 'Status একমাত্র কমান্ড যা সবসময় নিরাপদ ও তথ্যবহুল: বর্তমান ব্রাঞ্চ, কী বদলেছে, কী স্টেজড, রিমোট থেকে এগিয়ে না পিছিয়ে। পেশাদাররা প্রতিটি অপারেশনের আগে-পরে প্রতিবর্তে চালান।',
    },
    interviewTip: {
      en: '"Status first, always" is a one-line culture signal — it tells interviewers you work carefully.',
      bn: '"আগে status, সবসময়" এক লাইনের সংস্কৃতি সংকেত — ইন্টারভিউয়ারদের বলে যত্নে কাজ করেন।',
    },
    commonMistake: {
      en: 'Diving straight into edits or merges on an unknown tree state — the root cause of most "Git ate my work" stories.',
      bn: 'অজানা ট্রি অবস্থায় সরাসরি এডিট বা মার্জে ঝাঁপ — বেশিরভাগ "গিট কাজ খেয়েছে" গল্পের মূল।',
    },
    options: [
      { id: 'a', label: 'git status', correct: true },
      { id: 'b', label: 'git commit', correct: false },
      { id: 'c', label: 'git push', correct: false },
      { id: 'd', label: 'git rebase', correct: false },
    ],
    relatedCommands: ['git.status'],
    relatedLessons: ['git.fundamentals.working-directory'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-inspect-status'],
    relatedInternals: [],
    tags: ['status', 'workflow', 'safety'],
    order: 16,
  },
  {
    id: 'git.interview.cmd-add',
    category: 'commands',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'You edited two files but want to commit only one. Which command stages just that file?',
      bn: 'দুটি ফাইল এডিট করেছেন কিন্তু একটিই কমিট করতে চান। কোন কমান্ড শুধু সেটি স্টেজ করে?',
    },
    shortAnswer: {
      en: 'git add with the file path — for example git add app.js — stages exactly that file and nothing else.',
      bn: 'ফাইল পাথসহ git add — যেমন git add app.js — ঠিক সেই ফাইল স্টেজ করে, আর কিছু নয়।',
    },
    explanation: {
      en: 'git add accepts pathspecs, so you curate per file. git add . would sweep in both files (plus accidents like .env), which is precisely what selective staging avoids.',
      bn: 'git add পাথস্পেক নেয়, তাই ফাইল ধরে সাজান। git add . উভয় ফাইল (সাথে .env-এর মতো দুর্ঘটনা) টেনে নিত — নির্বাচনী স্টেজিং ঠিক এটাই এড়ায়।',
    },
    interviewTip: {
      en: 'Mention checking git status first — selective staging starts with knowing what changed.',
      bn: 'আগে git status দেখার কথা বলুন — নির্বাচনী স্টেজিং কী বদলেছে জানা দিয়ে শুরু।',
    },
    commonMistake: {
      en: 'Always using git add . out of habit, then committing secrets or debug files by accident.',
      bn: 'অভ্যাসে সবসময় git add . চালিয়ে দুর্ঘটনায় সিক্রেট বা ডিবাগ ফাইল কমিট করা।',
    },
    options: [
      { id: 'a', label: 'git add app.js', correct: true },
      { id: 'b', label: 'git add .', correct: false },
      { id: 'c', label: 'git commit app.js', correct: false },
      { id: 'd', label: 'git stage --all', correct: false },
    ],
    relatedCommands: ['git.add', 'git.status'],
    relatedLessons: ['git.fundamentals.staging-area'],
    relatedTroubleshooting: ['git.troubleshooting.staged-file'],
    relatedPractice: ['git.practice.command-stage-first-change'],
    relatedInternals: [],
    tags: ['add', 'staging', 'selective'],
    order: 17,
  },
  {
    id: 'git.interview.cmd-commit',
    category: 'commands',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'Your changes are staged. Which command records them permanently with a message, without involving any remote?',
      bn: 'পরিবর্তন স্টেজড। কোন কমান্ড রিমোট ছাড়াই বার্তাসহ স্থায়ী রেকর্ড করে?',
    },
    shortAnswer: {
      en: 'git commit -m with an imperative message — it freezes the staged snapshot locally; remotes hear nothing until push.',
      bn: 'আদেশসূচক বার্তাসহ git commit -m — স্টেজড স্ন্যাপশট লোকালি হিমায়িত করে; পুশ না হওয়া পর্যন্ত রিমোট কিছু শোনে না।',
    },
    explanation: {
      en: 'Commit takes the index and mints a commit object: tree pointer, parent, author, timestamp, message. It is 100% local — git status afterwards shows you ahead of the remote, which is the receipt proving nothing was uploaded.',
      bn: 'কমিট ইনডেক্স নিয়ে কমিট অবজেক্ট তৈরি করে: ট্রি পয়েন্টার, প্যারেন্ট, লেখক, সময়, বার্তা। এটি ১০০% লোকাল — পরে git status রিমোট থেকে এগিয়ে দেখায়, যা প্রমাণ কিছু আপলোড হয়নি।',
    },
    interviewTip: {
      en: 'Stress "local until push" — confusing commit with publish is the classic junior tell.',
      bn: '"পুশ পর্যন্ত লোকাল" জোর দিন — কমিটকে প্রকাশ ভাবা ক্লাসিক জুনিয়র লক্ষণ।',
    },
    commonMistake: {
      en: 'Believing teammates can see unpushed commits, or that amending them affects anyone else.',
      bn: 'সহকর্মীরা আনপুশড কমিট দেখতে পায় বিশ্বাস, বা amend করলে অন্যের কিছু যায় আসে ভাবা।',
    },
    options: [
      { id: 'a', label: 'git commit -m "Add login validation"', correct: true },
      { id: 'b', label: 'git push -m "Add login validation"', correct: false },
      { id: 'c', label: 'git save "Add login validation"', correct: false },
      { id: 'd', label: 'git stage --commit', correct: false },
    ],
    relatedCommands: ['git.commit'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.basic-commit'],
    relatedInternals: ['git.internals.commit-objects'],
    tags: ['commit', 'local', 'snapshot'],
    order: 18,
  },
  {
    id: 'git.interview.cmd-log',
    category: 'commands',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'You need a compact, readable history with branch structure. Which command gives it?',
      bn: 'ব্রাঞ্চ কাঠামোসহ সংক্ষিপ্ত, পাঠযোগ্য হিস্ট্রি দরকার। কোন কমান্ড দেয়?',
    },
    shortAnswer: {
      en: 'git log --oneline --graph --all (often aliased) — one line per commit with ASCII branch lines.',
      bn: 'git log --oneline --graph --all (প্রায়ই এলিয়াস করা) — প্রতি কমিটে এক লাইন সাথে ASCII ব্রাঞ্চ রেখা।',
    },
    explanation: {
      en: 'Plain git log is verbose; --oneline compresses to hash plus subject, --graph draws the parent/merge topology, and --all includes every reference instead of just HEAD. Together they turn archaeology into reading.',
      bn: 'সাধারণ git log ভার্বোস; --oneline হ্যাশ ও বিষয়ে সংকুচিত করে, --graph প্যারেন্ট/মার্জ টপোলজি আঁকে, --all শুধু HEAD নয় প্রতিটি রেফারেন্স আনে। একসাথে প্রত্নতত্ত্ব পড়ায় বদলায়।',
    },
    interviewTip: {
      en: 'Mention having this aliased (e.g. git lg) — small workflow details signal daily fluency.',
      bn: 'এলিয়াস করা আছে উল্লেখ করুন (যেমন git lg) — ছোট ওয়ার্কফ্লো বিবরণ দৈনন্দিন দক্ষতার সংকেত।',
    },
    commonMistake: {
      en: 'Reading raw git log output for structure — without --graph, merges and forks are invisible.',
      bn: 'কাঠামোতে কাঁচা git log পড়া — --graph ছাড়া মার্জ ও ফোর্ক অদৃশ্য।',
    },
    options: [
      { id: 'a', label: 'git log --oneline --graph --all', correct: true },
      { id: 'b', label: 'git status -v', correct: false },
      { id: 'c', label: 'git show --all', correct: false },
      { id: 'd', label: 'git branch --history', correct: false },
    ],
    relatedCommands: ['git.log'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-inspect-history'],
    relatedInternals: ['git.internals.commit-graphs'],
    tags: ['log', 'history', 'graph'],
    order: 19,
  },
  {
    id: 'git.interview.cmd-diff',
    category: 'commands',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'Before staging, you want to review exactly what you changed. Which command, and what does it compare?',
      bn: 'স্টেজের আগে ঠিক কী বদলেছেন পর্যালোচনা চান। কোন কমান্ড, আর কী তুলনা করে?',
    },
    shortAnswer: {
      en: 'git diff — it compares the working tree against the staging area, showing only unstaged changes.',
      bn: 'git diff — ওয়ার্কিং ট্রির সাথে স্টেজিং এরিয়ার তুলনা করে, শুধু আনস্টেজড পরিবর্তন দেখায়।',
    },
    explanation: {
      en: 'Diff answers "what would staging capture right now?" Staged content is deliberately hidden here — git diff --staged shows that instead. Reviewing the diff is where stray console.logs and debug tokens get caught.',
      bn: 'Diff উত্তর দেয় "এখন স্টেজ করলে কী ধরা পড়বে?" স্টেজড কন্টেন্ট এখানে ইচ্ছাকৃত লুকানো — বদলে git diff --staged দেখায়। diff পর্যালোচনায় ভুল console.log ও ডিবাগ টোকেন ধরা পড়ে।',
    },
    interviewTip: {
      en: 'Add that you never stage what you have not read — process answers beat flag trivia.',
      bn: 'যোগ করুন না পড়ে কখনো স্টেজ করেন না — প্রক্রিয়ার উত্তর ফ্ল্যাগ মুখস্থকে হারায়।',
    },
    commonMistake: {
      en: 'Expecting staged changes in git diff output, then assuming "no output" means "no changes".',
      bn: 'git diff আউটপুটে স্টেজড পরিবর্তন আশা, তারপর "আউটপুট নেই" মানে "পরিবর্তন নেই" ভাবা।',
    },
    options: [
      { id: 'a', label: 'git diff (working tree vs staging)', correct: true },
      { id: 'b', label: 'git diff --staged', correct: false },
      { id: 'c', label: 'git log -p', correct: false },
      { id: 'd', label: 'git show', correct: false },
    ],
    relatedCommands: ['git.diff', 'git.status'],
    relatedLessons: ['git.fundamentals.staging-area'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-inspect-before-commit'],
    relatedInternals: [],
    tags: ['diff', 'review', 'staging'],
    order: 20,
  },
  {
    id: 'git.interview.cmd-branch',
    category: 'commands',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'How do you list branches and create a new one called feature/login?',
      bn: 'ব্রাঞ্চ তালিকা ও feature/login নামে নতুন কীভাবে তৈরি করবেন?',
    },
    shortAnswer: {
      en: 'git branch lists; git branch feature/login creates (without switching); git switch -c feature/login creates and switches in one move.',
      bn: 'git branch তালিকা করে; git branch feature/login তৈরি করে (সুইচ ছাড়া); git switch -c feature/login এক চালে তৈরি ও সুইচ করে।',
    },
    explanation: {
      en: 'Listing shows local branches with * marking HEAD. Creating only writes the 41-byte pointer — you stay where you are until you switch. Modern Git prefers git switch -c over git checkout -b because switching and file-restoring are no longer one overloaded command.',
      bn: 'তালিকায় * দিয়ে HEADসহ লোকাল ব্রাঞ্চ দেখায়। তৈরি শুধু ৪১-বাইট পয়েন্টার লেখে — সুইচ না করা পর্যন্ত যেখানে আছেন সেখানেই। আধুনিক গিট git checkout -b-এর বদলে git switch -c পছন্দ করে কারণ সুইচিং ও ফাইল-পুনরুদ্ধার আর এক ওভারলোডেড কমান্ড নয়।',
    },
    interviewTip: {
      en: 'Drop "switch -c creates and moves in one step" — it shows you use modern Git, not tutorials from 2015.',
      bn: '"switch -c এক ধাপে তৈরি ও সরায়" বলুন — এতে বোঝায় ২০১৫-র টিউটোরিয়াল নয়, আধুনিক গিট ব্যবহার করেন।',
    },
    commonMistake: {
      en: 'Creating a branch and assuming you moved to it — then committing onto the wrong branch.',
      bn: 'ব্রাঞ্চ তৈরি করে সেখানে গেছেন ভাবা — তারপর ভুল ব্রাঞ্চে কমিট।',
    },
    options: [
      { id: 'a', label: 'git branch, then git switch -c feature/login', correct: true },
      { id: 'b', label: 'git checkout -- feature/login', correct: false },
      { id: 'c', label: 'git init feature/login', correct: false },
      { id: 'd', label: 'git push feature/login', correct: false },
    ],
    relatedCommands: ['git.branch', 'git.switch'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: ['git.troubleshooting.wrong-branch'],
    relatedPractice: ['git.practice.create-feature-branch'],
    relatedInternals: ['git.internals.branch-references'],
    tags: ['branch', 'switch', 'workflow'],
    order: 21,
  },
  {
    id: 'git.interview.cmd-switch',
    category: 'commands',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'You need to move from main to an existing feature/login branch. Which command, and what must be true first?',
      bn: 'main থেকে বিদ্যমান feature/login ব্রাঞ্চে যেতে হবে। কোন কমান্ড, আর আগে কী সত্য হতে হবে?',
    },
    shortAnswer: {
      en: 'git switch feature/login — and the working tree should be clean, or Git may refuse to rewrite your uncommitted files.',
      bn: 'git switch feature/login — এবং ওয়ার্কিং ট্রি পরিষ্কার থাকা উচিত, নইলে আনকমিটেড ফাইল পুনর্লিখনে গিট প্রত্যাখ্যান করতে পারে।',
    },
    explanation: {
      en: 'Switching rewrites working-tree files to match the target tip and moves HEAD. Git blocks the switch when it would overwrite uncommitted changes — commit, stash, or discard first, then move.',
      bn: 'সুইচ টার্গেট টিপে মেলাতে ওয়ার্কিং-ট্রি ফাইল পুনর্লিখন করে ও HEAD সরায়। আনকমিটেড পরিবর্তন ওভাররাইট হলে গিট সুইচ আটকায় — আগে কমিট, স্ট্যাশ বা বাতিল, তারপর সরুন।',
    },
    interviewTip: {
      en: 'Mention the dirty-tree guard unprompted — protecting uncommitted work is exactly what interviewers test here.',
      bn: 'না জিজ্ঞেসেই নোংরা-ট্রি পাহারা উল্লেখ করুন — আনকমিটেড কাজ রক্ষাই এখানে ইন্টারভিউয়াররা পরীক্ষা করেন।',
    },
    commonMistake: {
      en: 'Using git checkout for everything out of habit, including file restores that can silently discard work.',
      bn: 'অভ্যাসে সবকিছুতে git checkout, ফাইল পুনরুদ্ধারসহ যা নীরবে কাজ মুছে দিতে পারে।',
    },
    options: [
      { id: 'a', label: 'git switch feature/login (clean tree first)', correct: true },
      { id: 'b', label: 'git switch --force feature/login', correct: false },
      { id: 'c', label: 'git merge feature/login', correct: false },
      { id: 'd', label: 'git branch feature/login', correct: false },
    ],
    relatedCommands: ['git.switch', 'git.status'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.switch-branches'],
    relatedInternals: [],
    tags: ['switch', 'branches', 'safety'],
    order: 22,
  },
  {
    id: 'git.interview.cmd-merge',
    category: 'commands',
    difficulty: 'intermediate',
    type: 'choice',
    question: {
      en: 'feature/login is tested and ready. Which command joins it into your current branch, and what gets recorded?',
      bn: 'feature/login পরীক্ষিত ও প্রস্তুত। কোন কমান্ড বর্তমান ব্রাঞ্চে যুক্ত করে, আর কী রেকর্ড হয়?',
    },
    shortAnswer: {
      en: 'git merge feature/login — Git records either a fast-forward pointer move or, when histories diverged, a merge commit with two parents.',
      bn: 'git merge feature/login — গিট ফাস্ট-ফরোয়ার্ড পয়েন্টার সরণ বা, হিস্ট্রি ডাইভার্জ হলে, দুই প্যারেন্টের মার্জ কমিট রেকর্ড করে।',
    },
    explanation: {
      en: 'Merge always targets the checked-out branch: it folds the named branch in. Linear case? The pointer just slides forward. Diverged case? A merge commit joins both lines honestly, preserving each side for later blame and revert.',
      bn: 'মার্জ সবসময় চেক-আউট ব্রাঞ্চ লক্ষ্য করে: নাম দেওয়া ব্রাঞ্চ ভাঁজ করে। রৈখিক ক্ষেত্রে? পয়েন্টার এগিয়ে যায়। ডাইভার্জ ক্ষেত্রে? মার্জ কমিট উভয় লাইন সৎভাবে যুক্ত করে, পরের blame ও revert-এ প্রতিটি পক্ষ সংরক্ষণ করে।',
    },
    interviewTip: {
      en: 'Say both outcomes (fast-forward vs true merge) before being asked — it preempts the classic follow-up.',
      bn: 'জিজ্ঞেসের আগেই উভয় ফল (ফাস্ট-ফরোয়ার্ড বনাম সত্য মার্জ) বলুন — ক্লাসিক ফলো-আপ আগেই শেষ।',
    },
    commonMistake: {
      en: 'Merging the wrong direction (merging main into feature when you meant the reverse) — always confirm the checked-out branch first.',
      bn: 'ভুল দিকে মার্জ (বিপরীত চাইতে main-কে feature-এ) — আগে চেক-আউট ব্রাঞ্চ নিশ্চিত করুন।',
    },
    options: [
      { id: 'a', label: 'git merge feature/login', correct: true },
      { id: 'b', label: 'git merge main feature/login', correct: false },
      { id: 'c', label: 'git push feature/login', correct: false },
      { id: 'd', label: 'git rebase feature/login', correct: false },
    ],
    relatedCommands: ['git.merge', 'git.log'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: ['git.troubleshooting.merge-conflict'],
    relatedPractice: ['git.practice.merge-feature'],
    relatedInternals: ['git.internals.commit-objects'],
    tags: ['merge', 'join', 'workflow'],
    order: 23,
  },
  {
    id: 'git.interview.cmd-rebase',
    category: 'commands',
    difficulty: 'intermediate',
    type: 'choice',
    question: {
      en: 'Your private feature branch fell behind main. Which command replays it onto the latest main?',
      bn: 'ব্যক্তিগত ফিচার ব্রাঞ্চ main থেকে পিছিয়েছে। কোন কমান্ড সর্বশেষ main-এর ওপর রিপ্লে করে?',
    },
    shortAnswer: {
      en: 'git rebase main (run while on the feature branch) — it replays your commits onto main’s tip for linear history.',
      bn: 'git rebase main (ফিচার ব্রাঞ্চে থেকে চালিয়ে) — main-এর টিপে কমিট রিপ্লে করে লিনিয়ার হিস্ট্রি দেয়।',
    },
    explanation: {
      en: 'Rebase finds your branch’s unique commits, resets the branch to main’s tip, and re-applies each change as a brand-new commit. History reads cleanly — but every hash changes, which is why this is only safe for unshared branches.',
      bn: 'রিবেস ব্রাঞ্চের অনন্য কমিট খুঁজে, main-এর টিপে ব্রাঞ্চ রিসেট করে, প্রতিটি পরিবর্তন একদম নতুন কমিটে পুনঃপ্রয়োগ করে। হিস্ট্রি পরিষ্কার পড়া যায় — কিন্তু প্রতিটি হ্যাশ বদলায়, তাই শুধু আনশেয়ার্ড ব্রাঞ্চে নিরাপদ।',
    },
    interviewTip: {
      en: 'Immediately add "only because this branch is private" — interviewers listen for the golden rule without prompting.',
      bn: 'সাথে সাথে "শুধু ব্রাঞ্চ ব্যক্তিগত বলে" যোগ করুন — ইন্টারভিউয়াররা না জিজ্ঞেসেই গোল্ডেন রুল শোনেন।',
    },
    commonMistake: {
      en: 'Rebasing a branch teammates already pulled — rewriting history others stand on.',
      bn: 'সহকর্মীরা ইতিমধ্যে পুল করা ব্রাঞ্চ রিবেস — অন্যরা দাঁড়ানো হিস্ট্রি পুনর্লিখন।',
    },
    options: [
      { id: 'a', label: 'git rebase main', correct: true },
      { id: 'b', label: 'git merge main --rebase', correct: false },
      { id: 'c', label: 'git pull --no-rebase', correct: false },
      { id: 'd', label: 'git reset main', correct: false },
    ],
    relatedCommands: ['git.rebase', 'git.log'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: ['git.troubleshooting.rebase-conflict'],
    relatedPractice: ['git.practice.rebase-feature'],
    relatedInternals: ['git.internals.rebase-rewrites-history'],
    tags: ['rebase', 'linear', 'private-branches'],
    order: 24,
  },
  {
    id: 'git.interview.cmd-fetch',
    category: 'commands',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'You want to see teammates’ new commits without touching your own work. Which command?',
      bn: 'নিজের কাজ না ছুঁয়ে সহকর্মীদের নতুন কমিট দেখতে চান। কোন কমান্ড?',
    },
    shortAnswer: {
      en: 'git fetch — it downloads everything new and updates remote-tracking refs while your branches and files stay frozen.',
      bn: 'git fetch — সব নতুন ডাউনলোড করে রিমোট-ট্র্যাকিং ref আপডেট করে আর ব্রাঞ্চ ও ফাইল হিমায়িত থাকে।',
    },
    explanation: {
      en: 'Fetch is the safe half of syncing: objects arrive, origin/main advances, and absolutely nothing of yours moves. You then inspect with git log origin/main and decide — merge, rebase, or wait.',
      bn: 'Fetch সিঙ্কের নিরাপদ অর্ধেক: অবজেক্ট আসে, origin/main এগোয়, আপনার কিছু নড়ে না। তারপর git log origin/main দিয়ে পরিদর্শন করে সিদ্ধান্ত নিন — মার্জ, রিবেস, না অপেক্ষা।',
    },
    interviewTip: {
      en: '"Fetch never merges" said confidently is worth more than any flag trivia in this topic.',
      bn: 'আত্মবিশ্বাসে "fetch কখনো মার্জ করে না" বলা এই বিষয়ে যেকোনো ফ্ল্যাগ মুখস্থের চেয়ে মূল্যবান।',
    },
    commonMistake: {
      en: 'Fetching then assuming you are updated — until you integrate (merge/rebase/pull), your branches are exactly where they were.',
      bn: 'fetch করে আপডেটেড ভাবা — একীভূত (মার্জ/রিবেস/পুল) না করা পর্যন্ত ব্রাঞ্চ ঠিক যেখানে ছিল।',
    },
    options: [
      { id: 'a', label: 'git fetch', correct: true },
      { id: 'b', label: 'git pull', correct: false },
      { id: 'c', label: 'git push', correct: false },
      { id: 'd', label: 'git clone', correct: false },
    ],
    relatedCommands: ['git.fetch', 'git.log'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: ['git.troubleshooting.behind-remote'],
    relatedPractice: ['git.practice.fetch-changes'],
    relatedInternals: ['git.internals.remote-tracking-references'],
    tags: ['fetch', 'safe', 'remote'],
    order: 25,
  },
  {
    id: 'git.interview.cmd-pull',
    category: 'commands',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'What does git pull actually do under the hood?',
      bn: 'git pull পর্দার আড়ালে আসলে কী করে?',
    },
    shortAnswer: {
      en: 'Fetch followed immediately by integration — by default a merge of the tracked branch, or a rebase with --rebase.',
      bn: 'সাথে সাথে একীভূতসহ fetch — ডিফল্টে ট্র্যাকড ব্রাঞ্চের মার্জ, বা --rebase-এ রিবেস।',
    },
    explanation: {
      en: 'Pull is fetch plus a second step you do not get to preview: merge (default) or rebase (--rebase). That is why veterans often fetch first, read the incoming commits, and only then choose how to integrate.',
      bn: 'পুল হলো fetch সাথে দ্বিতীয় ধাপ যা আগাম দেখা যায় না: মার্জ (ডিফল্ট) বা রিবেস (--rebase)। তাই অভিজ্ঞরা প্রায়ই আগে fetch করে, আগত কমিট পড়ে, তারপর কীভাবে একীভূত করবেন বেছে নেন।',
    },
    interviewTip: {
      en: 'Decompose it live: "pull equals fetch plus merge" — then mention --rebase as the common variant.',
      bn: 'সরাসরি ভাঙুন: "pull সমান fetch যোগ মার্জ" — তারপর সাধারণ রূপ হিসেবে --rebase উল্লেখ করুন।',
    },
    commonMistake: {
      en: 'Pulling with uncommitted changes and being surprised by the merge it triggers — fetch first when unsure.',
      bn: 'আনকমিটেড পরিবর্তনে পুল করে ট্রিগার হওয়া মার্জে অবাক — অনিশ্চিত হলে আগে fetch।',
    },
    options: [
      { id: 'a', label: 'Fetch, then merge (or rebase with --rebase)', correct: true },
      { id: 'b', label: 'Fetch only, changing nothing locally', correct: false },
      { id: 'c', label: 'Push, then fetch the result', correct: false },
      { id: 'd', label: 'Clone the remote again', correct: false },
    ],
    relatedCommands: ['git.pull', 'git.fetch', 'git.merge'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: ['git.troubleshooting.pull-conflict'],
    relatedPractice: ['git.practice.command-fetch-vs-pull'],
    relatedInternals: [],
    tags: ['pull', 'fetch', 'merge'],
    order: 26,
  },
  {
    id: 'git.interview.cmd-push',
    category: 'commands',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'Your commits are ready to share. Which command publishes the current branch, and when does it fail?',
      bn: 'কমিট শেয়ারে প্রস্তুত। কোন কমান্ড বর্তমান ব্রাঞ্চ প্রকাশ করে, আর কখন ব্যর্থ হয়?',
    },
    shortAnswer: {
      en: 'git push (first time: git push -u origin <branch>). It fails when the remote moved first — a non-fast-forward rejection protecting teammates’ work.',
      bn: 'git push (প্রথমবার: git push -u origin <branch>)। রিমোট আগে সরলে ব্যর্থ হয় — সহকর্মীদের কাজ রক্ষায় নন-ফাস্ট-ফরোয়ার্ড প্রত্যাখ্যান।',
    },
    explanation: {
      en: 'Push uploads commits the remote lacks and fast-forwards the remote branch — nothing more. Rejection means someone else’s work arrived first; the fix is fetch, integrate, and push again, never a blind force-push on shared branches.',
      bn: 'পুশ রিমোটে নেই এমন কমিট আপলোড করে রিমোট ব্রাঞ্চ ফাস্ট-ফরোয়ার্ড করে — এর বেশি কিছু নয়। প্রত্যাখ্যান মানে অন্য কারো কাজ আগে পৌঁছেছে; সমাধান fetch, একীভূত, আবার পুশ — শেয়ার্ড ব্রাঞ্চে অন্ধ ফোর্স-পুশ কখনো নয়।',
    },
    interviewTip: {
      en: 'Explain rejection correctly and you answer two questions at once — push mechanics and teamwork judgment.',
      bn: 'প্রত্যাখ্যান সঠিক ব্যাখ্যা করলে একসাথে দুই প্রশ্নের উত্তর — পুশ মেকানিক্স ও টিমওয়ার্ক বিচার।',
    },
    commonMistake: {
      en: '"Fixing" a rejection with --force on a shared branch, erasing teammates’ commits from the remote.',
      bn: 'শেয়ার্ড ব্রাঞ্চে --force দিয়ে প্রত্যাখ্যান "ঠিক" করা, রিমোট থেকে সহকর্মীদের কমিট মোছা।',
    },
    options: [
      { id: 'a', label: 'git push (or git push -u origin <branch> first time)', correct: true },
      { id: 'b', label: 'git commit --publish', correct: false },
      { id: 'c', label: 'git upload --all', correct: false },
      { id: 'd', label: 'git sync', correct: false },
    ],
    relatedCommands: ['git.push', 'git.fetch'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: ['git.troubleshooting.push-rejected'],
    relatedPractice: ['git.practice.push-feature'],
    relatedInternals: [],
    tags: ['push', 'remote', 'share'],
    order: 27,
  },
  {
    id: 'git.interview.cmd-restore',
    category: 'commands',
    difficulty: 'intermediate',
    type: 'choice',
    question: {
      en: 'You want to discard unstaged changes in a tracked file. Which command is appropriate?',
      bn: 'ট্র্যাকড ফাইলে আনস্টেজড পরিবর্তন ফেলে দিতে চান। কোন কমান্ড উপযুক্ত?',
    },
    shortAnswer: {
      en: 'git restore <file> — it overwrites the working-tree file with the staged (or HEAD) version. Destructive and final.',
      bn: 'git restore <file> — ওয়ার্কিং-ট্রি ফাইল স্টেজড (বা HEAD) সংস্করণে ওভাররাইট করে। ধ্বংসাত্মক ও চূড়ান্ত।',
    },
    explanation: {
      en: 'Restore copies content downward: from index (default) or from a commit with --source. Unlike reset, it never moves branch pointers; unlike revert, it creates no commit. And because the discarded edits were never snapshotted, they are unrecoverable.',
      bn: 'Restore কন্টেন্ট নিচে কপি করে: ইনডেক্স (ডিফল্ট) বা --source-এ কমিট থেকে। রিসেটের বিপরীতে ব্রাঞ্চ পয়েন্টার সরায় না; revert-এর বিপরীতে কমিট বানায় না। আর বাতিল এডিট কখনো স্ন্যাপশট হয়নি বলে পুনরুদ্ধার অযোগ্য।',
    },
    interviewTip: {
      en: 'Name the direction of copying (downward, into the working tree) — direction language proves the mental model.',
      bn: 'কপির দিক নাম বলুন (নিচে, ওয়ার্কিং ট্রিতে) — দিকের ভাষা মেন্টাল মডেল প্রমাণ করে।',
    },
    commonMistake: {
      en: 'Reaching for git reset --hard to discard file edits — a sledgehammer that also moves branch pointers.',
      bn: 'ফাইল এডিট বাতিলে git reset --hard ধরা — হাতুড়ি যা ব্রাঞ্চ পয়েন্টারও সরায়।',
    },
    options: [
      { id: 'a', label: 'git restore <file>', correct: true },
      { id: 'b', label: 'git reset', correct: false },
      { id: 'c', label: 'git revert', correct: false },
      { id: 'd', label: 'git clean', correct: false },
    ],
    relatedCommands: ['git.restore', 'git.status'],
    relatedLessons: ['git.fundamentals.working-directory'],
    relatedTroubleshooting: ['git.troubleshooting.deleted-changes'],
    relatedPractice: [],
    relatedInternals: ['git.internals.working-tree-index-repository'],
    tags: ['restore', 'discard', 'working-tree'],
    order: 28,
  },
  {
    id: 'git.interview.cmd-reset',
    category: 'commands',
    difficulty: 'intermediate',
    type: 'choice',
    question: {
      en: 'You want to undo the last commit but keep its changes staged. Which exact command?',
      bn: 'শেষ কমিট বাতিল কিন্তু পরিবর্তন স্টেজড রাখতে চান। ঠিক কোন কমান্ড?',
    },
    shortAnswer: {
      en: 'git reset --soft HEAD~1 — the branch pointer steps back one commit while index and working tree stay frozen.',
      bn: 'git reset --soft HEAD~1 — ব্রাঞ্চ পয়েন্টার এক কমিট পেছনে যায় আর ইনডেক্স ও ওয়ার্কিং ট্রি হিমায়িত থাকে।',
    },
    explanation: {
      en: 'The three modes differ only in blast radius: --soft moves HEAD alone, --mixed (default) also resets the index, --hard additionally overwrites working-tree files. For "uncommit but keep everything", --soft is the scalpel.',
      bn: 'তিন মোডে শুধু বিস্ফোরণ ব্যাসার্ধে তফাত: --soft শুধু HEAD সরায়, --mixed (ডিফল্ট) ইনডেক্সও রিসেট করে, --hard ওয়ার্কিং-ট্রি ফাইলও ওভাররাইট করে। "আনকমিট কিন্তু সব রাখুন"-এ --soft স্ক্যালপেল।',
    },
    interviewTip: {
      en: 'Recite all three modes even when asked for one — interviewers almost always follow up with the comparison.',
      bn: 'একটি জিজ্ঞেস করলেও তিন মোড বলুন — ইন্টারভিউয়াররা প্রায় সবসময় তুলনায় ফলো-আপ করেন।',
    },
    commonMistake: {
      en: 'Defaulting to --hard out of habit and vaporizing uncommitted work that no command can bring back.',
      bn: 'অভ্যাসে --hard ডিফল্ট করে আনকমিটেড কাজ উড়িয়ে দেওয়া যা কোনো কমান্ড ফেরাতে পারে না।',
    },
    options: [
      { id: 'a', label: 'git reset --soft HEAD~1', correct: true },
      { id: 'b', label: 'git reset --mixed HEAD~1', correct: false },
      { id: 'c', label: 'git reset --hard HEAD~1', correct: false },
      { id: 'd', label: 'git revert HEAD~1', correct: false },
    ],
    relatedCommands: ['git.reset'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: ['git.troubleshooting.undo-last-commit', 'git.troubleshooting.reset-hard'],
    relatedPractice: ['git.practice.command-undo-unwanted-change'],
    relatedInternals: ['git.internals.what-is-a-reference'],
    tags: ['reset', 'soft', 'undo'],
    order: 29,
  },
  {
    id: 'git.interview.cmd-revert',
    category: 'commands',
    difficulty: 'intermediate',
    type: 'choice',
    question: {
      en: 'A bad commit is already pushed and shared. How do you undo it without rewriting history?',
      bn: 'খারাপ কমিট ইতিমধ্যে পুশ ও শেয়ার্ড। হিস্ট্রি পুনর্লিখন ছাড়া কীভাবে বাতিল করবেন?',
    },
    shortAnswer: {
      en: 'git revert <commit> — it records a brand-new commit that undoes the change, so shared history only ever moves forward.',
      bn: 'git revert <commit> — পরিবর্তন বাতিল করা একদম নতুন কমিট রেকর্ড করে, তাই শেয়ার্ড হিস্ট্রি শুধু এগোয়।',
    },
    explanation: {
      en: 'Reset rewrites the past, which strands everyone who already pulled it. Revert adds to the future instead: the bad commit stays visible (honest history), the fix is reviewable, and pushing needs no force. Public mistakes get reverts; private ones may get resets.',
      bn: 'রিসেট অতীত পুনর্লেখে, যা ইতিমধ্যে পুল করেছে সবাইকে আটকায়। Revert বদলে ভবিষ্যতে যোগ করে: খারাপ কমিট দৃশ্যমান থাকে (সৎ হিস্ট্রি), ফিক্স পর্যালোচনাযোগ্য, পুশে ফোর্স লাগে না। পাবলিক ভুলে revert; ব্যক্তিগতে রিসেট চলতে পারে।',
    },
    interviewTip: {
      en: '"Revert adds, reset rewrites" — six words that answer the whole reset-vs-revert family of questions.',
      bn: '"Revert যোগ করে, reset পুনর্লেখে" — ছয় শব্দে পুরো reset-বনাম-revert প্রশ্ন পরিবারের উত্তর।',
    },
    commonMistake: {
      en: 'Resetting a pushed commit then force-pushing to "clean it up" — rewriting history your teammates stand on.',
      bn: 'পুশড কমিট রিসেট করে "পরিষ্কারে" ফোর্স-পুশ — সহকর্মীরা দাঁড়ানো হিস্ট্রি পুনর্লেখন।',
    },
    options: [
      { id: 'a', label: 'git revert <commit>, then push normally', correct: true },
      { id: 'b', label: 'git reset --hard, then force-push', correct: false },
      { id: 'c', label: 'git restore <commit>', correct: false },
      { id: 'd', label: 'Delete the branch and recreate it', correct: false },
    ],
    relatedCommands: ['git.reset'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: ['git.troubleshooting.undo-last-commit'],
    relatedPractice: [],
    relatedInternals: [],
    tags: ['revert', 'shared-history', 'safe-undo'],
    order: 30,
  },
];
