/**
 * Interview questions — troubleshooting (10) + internals (10) + scenarios (5).
 * Data only. Stable ids (`git.interview.<slug>`), bilingual copy.
 */
import { InterviewQuestion } from '@/types/interview';

export const RECOVERY_QUESTIONS: InterviewQuestion[] = [
  /* ---------------- Troubleshooting (10) ---------------- */
  {
    id: 'git.interview.wrong-branch-fix',
    category: 'troubleshooting',
    difficulty: 'intermediate',
    type: 'scenario',
    question: {
      en: 'You just committed to main instead of your feature branch, and have not pushed. How do you move the work safely?',
      bn: 'ফিচার ব্রাঞ্চের বদলে main-এ কমিট করে ফেলেছেন, পুশ করেননি। নিরাপদে কাজ সরাবেন কীভাবে?',
    },
    shortAnswer: {
      en: 'Create the feature branch where you stand, switch back to main, then reset main back one commit — the work now lives on the right pointer.',
      bn: 'যেখানে দাঁড়িয়ে সেখানে ফিচার ব্রাঞ্চ তৈরি করুন, main-এ ফিরে এক কমিট পেছনে রিসেট করুন — কাজ এখন সঠিক পয়েন্টারে।',
    },
    explanation: {
      en: 'The commit object is fine; only its address is wrong. Branching at HEAD gives it a home first, so the subsequent reset --hard of main destroys nothing. If it were already pushed, you would instead cherry-pick plus revert to protect teammates.',
      bn: 'কমিট অবজেক্ট ঠিক আছে; শুধু ঠিকানা ভুল। HEAD-এ ব্রাঞ্চ করলে আগে ঠিকানা পায়, তাই পরে main-এর reset --hard কিছু ধ্বংস করে না। পুশ হয়ে গেলে বদলে cherry-pick ও revert করতেন সহকর্মী রক্ষায়।',
    },
    exampleCommand: 'git switch -c feature/login && git switch main && git reset --hard HEAD~1',
    interviewTip: {
      en: 'Always ask "pushed yet?" first in your answer — interviewers test whether you condition the fix on shared state.',
      bn: 'উত্তরে আগে "পুশ হয়েছে?" জিজ্ঞেস করুন — শেয়ার্ড অবস্থায় ফিক্স শর্ত করেন কিনা ইন্টারভিউয়াররা পরীক্ষা করেন।',
    },
    commonMistake: {
      en: 'Resetting main first and orphaning the commit, then hunting through reflog unnecessarily.',
      bn: 'আগে main রিসেট করে কমিট এতিম করা, তারপর অযথা রিফ্লগে খোঁজা।',
    },
    relatedCommands: ['git.switch', 'git.reset', 'git.branch'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: ['git.troubleshooting.wrong-branch'],
    relatedPractice: [],
    relatedInternals: ['git.internals.branch-references'],
    tags: ['wrong-branch', 'reset', 'recovery'],
    order: 56,
  },
  {
    id: 'git.interview.merge-conflict-steps',
    category: 'troubleshooting',
    difficulty: 'intermediate',
    type: 'scenario',
    question: {
      en: 'A merge stopped with conflict markers in app.js. Walk through exactly what you do next.',
      bn: 'app.js-এ কনফ্লিক্ট মার্কারে মার্জ থেমেছে। পরে ঠিক কী করবেন বলুন।',
    },
    shortAnswer: {
      en: 'Read both sides in the markers, edit the true outcome, remove markers, stage with git add, and commit to finish the merge.',
      bn: 'মার্কারে উভয় পক্ষ পড়ুন, সত্য ফল এডিট করুন, মার্কার সরান, git add-এ স্টেজ করে কমিটে মার্জ শেষ করুন।',
    },
    explanation: {
      en: 'Markers delimit HEAD’s version, a divider, and the incoming version. Your job is editorial: understand both intents, write the correct merged code, delete every marker line, then git add tells Git the file is resolved. The final commit has two parents preserving both histories.',
      bn: 'মার্কার HEAD সংস্করণ, বিভাজক ও আগত সংস্করণ সীমাবদ্ধ করে। কাজ সম্পাদকীয়: উভয় উদ্দেশ্য বুঝুন, সঠিক মার্জড কোড লিখুন, প্রতিটি মার্কার লাইন মুছুন, git add গিটকে বলে ফাইল সমাধান। চূড়ান্ত কমিটে দুই প্যারেন্ট উভয় হিস্ট্রি সংরক্ষণ করে।',
    },
    interviewTip: {
      en: 'Narrate it as a calm checklist — interviewers hire people who de-escalate conflicts, literal and otherwise.',
      bn: 'শান্ত চেকলিস্টে বলুন — ইন্টারভিউয়াররা এমন মানুষ নিয়োগ করে যারা কনফ্লিক্ট প্রশমিত করে, আক্ষরিক ও অন্যথায়।',
    },
    commonMistake: {
      en: 'Committing with markers still in the file, or deleting one side wholesale without reading it.',
      bn: 'ফাইলে মার্কারসহ কমিট করা, বা না পড়ে এক পক্ষ পুরো মুছে দেওয়া।',
    },
    relatedCommands: ['git.merge', 'git.status', 'git.add'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: ['git.troubleshooting.merge-conflict'],
    relatedPractice: ['git.practice.merge-conflict-flow'],
    relatedInternals: [],
    tags: ['conflict', 'merge', 'markers'],
    order: 57,
  },
  {
    id: 'git.interview.rebase-conflict-steps',
    category: 'troubleshooting',
    difficulty: 'advanced',
    type: 'scenario',
    question: {
      en: 'During git rebase, Git stops on a conflict. How is resolving it different from a merge conflict?',
      bn: 'git rebase চলাকালে কনফ্লিক্টে গিট থামে। মার্জ কনফ্লিক্ট থেকে সমাধান কীভাবে আলাদা?',
    },
    shortAnswer: {
      en: 'You resolve markers the same way, but then run git rebase --continue instead of committing — the replay, not you, owns the commit.',
      bn: 'একইভাবে মার্কার সমাধান করেন, কিন্তু কমিটের বদলে git rebase --continue চালান — রিপ্লে কমিটের মালিক, আপনি নন।',
    },
    explanation: {
      en: 'A rebase conflict pauses mid-replay of one commit. After fixing markers and staging, --continue resumes the replay onto the next commit. Committing manually here creates a stray duplicate commit — the classic rebase-conflict mistake. And git rebase --abort is always available to return to the pre-rebase state.',
      bn: 'রিবেস কনফ্লিক্ট একটি কমিটের মাঝ-রিপ্লেতে থামায়। মার্কার ঠিক করে স্টেজের পর --continue পরের কমিটে রিপ্লে চালায়। এখানে হাতে কমিটে বিপথগামী ডুপ্লিকেট তৈরি হয় — ক্লাসিক রিবেস-কনফ্লিক্ট ভুল। আর git rebase --abort সবসময় প্রি-রিবেস অবস্থায় ফেরায়।',
    },
    interviewTip: {
      en: '"Resolve the same, finish differently" is the memorable contrast — then name --continue vs commit explicitly.',
      bn: '"সমাধান এক, সমাপ্তি আলাদা" স্মরণীয় বৈপরীত্য — তারপর --continue বনাম কমিট স্পষ্ট নাম বলুন।',
    },
    commonMistake: {
      en: 'Running git commit mid-rebase, forking the replay into a duplicated mess that is painful to unwind.',
      bn: 'রিবেস মাঝে git commit চালিয়ে রিপ্লে ডুপ্লিকেট জটে ভাগ করা যা খোলা কষ্টকর।',
    },
    relatedCommands: ['git.rebase', 'git.add'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: ['git.troubleshooting.rebase-conflict'],
    relatedPractice: [],
    relatedInternals: ['git.internals.rebase-rewrites-history'],
    tags: ['rebase', 'conflict', 'continue'],
    order: 58,
  },
  {
    id: 'git.interview.push-rejected-fix',
    category: 'troubleshooting',
    difficulty: 'intermediate',
    type: 'scenario',
    question: {
      en: 'git push is rejected as non-fast-forward. What happened, and what are your safe options?',
      bn: 'git push নন-ফাস্ট-ফরোয়ার্ডে প্রত্যাখ্যাত। কী ঘটেছে, নিরাপদ বিকল্প কী?',
    },
    shortAnswer: {
      en: 'The remote moved first — someone else’s commits arrived before yours. Fetch, review, then merge or rebase before pushing again.',
      bn: 'রিমোট আগে সরেছে — আপনার আগে অন্য কারো কমিট পৌঁছেছে। fetch করুন, পর্যালোচনা করুন, তারপর মার্জ বা রিবেস করে আবার পুশ করুন।',
    },
    explanation: {
      en: 'Push only fast-forwards; it refuses to orphan the commits you lack. The rejection protects teammates. Safe path: git fetch, read origin/main, then either merge (preserves both lines) or rebase your private work (linear history), then push the reconciled tip.',
      bn: 'পুশ শুধু ফাস্ট-ফরোয়ার্ড করে; নেই এমন কমিট এতিম করতে প্রত্যাখ্যান করে। প্রত্যাখ্যান সহকর্মী রক্ষা করে। নিরাপদ পথ: git fetch, origin/main পড়ুন, তারপর মার্জ (উভয় লাইন সংরক্ষণ) বা ব্যক্তিগত কাজ রিবেস (লিনিয়ার হিস্ট্রি) করে মিলিত টিপ পুশ করুন।',
    },
    interviewTip: {
      en: 'Rule out force-push explicitly and early — interviewers treat "--force as first resort" as a red flag.',
      bn: 'ফোর্স-পুশ স্পষ্ট ও তাড়াতাড়ি বাদ দিন — "--force প্রথম উপায়" ইন্টারভিউয়াররা লাল পতাকা ধরেন।',
    },
    commonMistake: {
      en: 'Force-pushing to "win" the race, silently deleting the teammate commits that caused the rejection.',
      bn: 'দৌড়ে "জিততে" ফোর্স-পুশ করে প্রত্যাখ্যান ঘটানো সহকর্মী কমিট নীরবে মোছা।',
    },
    relatedCommands: ['git.push', 'git.fetch', 'git.pull'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: ['git.troubleshooting.push-rejected', 'git.troubleshooting.diverged'],
    relatedPractice: [],
    relatedInternals: ['git.internals.remote-tracking-references'],
    tags: ['push', 'rejected', 'non-fast-forward'],
    order: 59,
  },
  {
    id: 'git.interview.diverged-strategy',
    category: 'troubleshooting',
    difficulty: 'intermediate',
    type: 'scenario',
    question: {
      en: 'Your branch is ahead by 2 and behind by 1 — diverged. How do you decide between merge and rebase to reconcile?',
      bn: 'ব্রাঞ্চ 2 এগিয়ে 1 পিছিয়ে — ডাইভার্জড। মেলাতে মার্জ বনাম রিবেস কীভাবে ঠিক করবেন?',
    },
    shortAnswer: {
      en: 'Merge if the branch is shared or you want both lines preserved; rebase only if it is private and you want linear history.',
      bn: 'ব্রাঞ্চ শেয়ার্ড হলে বা উভয় লাইন সংরক্ষণ চাইলে মার্জ; শুধু ব্যক্তিগত ও লিনিয়ার হিস্ট্রি চাইলে রিবেস।',
    },
    explanation: {
      en: 'Divergence means genuinely different work on both sides — there is no automatic right answer. Merging records the truth (both lines, one join commit) at the cost of branchiness. Rebasing replays your 2 commits onto their tip for cleanliness, but rewrites identities — safe only while nobody else holds your commits.',
      bn: 'ডাইভারজেন্স মানে উভয় পক্ষে সত্যিকারের ভিন্ন কাজ — স্বয়ংক্রিয় সঠিক উত্তর নেই। মার্জ সত্য রেকর্ড করে (উভয় লাইন, এক জয়েন কমিট) শাখাময়তার বিনিময়ে। রিবেস 2 কমিট তাদের টিপে রিপ্লে করে পরিষ্কারে, কিন্তু পরিচয় পুনর্লেখে — শুধু নিরাপদ যতক্ষণ অন্য কেউ কমিট ধরে না।',
    },
    interviewTip: {
      en: 'Ask a clarifying question first ("is this branch shared?") — interviewers reward scoping before solving.',
      bn: 'আগে স্পষ্ট প্রশ্ন করুন ("ব্রাঞ্চ কি শেয়ার্ড?") — সমাধানের আগে পরিধিতে ইন্টারভিউয়াররা পুরস্কার দেন।',
    },
    commonMistake: {
      en: 'Always rebasing because "linear looks cleaner", even on branches teammates already pulled.',
      bn: '"লিনিয়ার পরিষ্কার দেখায়" বলে সবসময় রিবেস, সহকর্মীরা ইতিমধ্যে পুল করা ব্রাঞ্চেও।',
    },
    relatedCommands: ['git.merge', 'git.rebase', 'git.status'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: ['git.troubleshooting.diverged'],
    relatedPractice: [],
    relatedInternals: ['git.internals.dag-structure'],
    tags: ['diverged', 'strategy', 'merge-vs-rebase'],
    order: 60,
  },
  {
    id: 'git.interview.deleted-branch-recovery',
    category: 'troubleshooting',
    difficulty: 'intermediate',
    type: 'scenario',
    question: {
      en: 'You deleted a branch that still had needed commits. How do you get it back?',
      bn: 'দরকারি কমিটসহ ব্রাঞ্চ মুছে ফেলেছেন। কীভাবে ফেরাবেন?',
    },
    shortAnswer: {
      en: 'Find the old tip in git reflog, then recreate the branch pointer at that hash — deleting removed the name, not the commits.',
      bn: 'git reflog-এ পুরনো টিপ খুঁজে সেই হ্যাশে ব্রাঞ্চ পয়েন্টার পুনর্নির্মাণ করুন — মোছায় নাম গেছে, কমিট নয়।',
    },
    explanation: {
      en: 'git branch -d removes a reference file; the commits stay reachable through the reflog for weeks. Read the log for the tip hash (the "checkout: moving from feature" line usually), then git switch -c feature <hash> or git branch feature <hash> restores the pointer exactly.',
      bn: 'git branch -d রেফারেন্স ফাইল সরায়; কমিট রিফ্লগে সপ্তাহ ধরে পৌঁছানো যায়। টিপ হ্যাশে লগ পড়ুন ("checkout: moving from feature" লাইন সাধারণত), তারপর git switch -c feature <hash> বা git branch feature <hash> পয়েন্টার হুবহু ফেরায়।',
    },
    interviewTip: {
      en: '"Deleting a branch deletes a pointer, not history" — lead with the model and the recovery becomes obvious.',
      bn: '"ব্রাঞ্চ মোছা পয়েন্টার মোছে, হিস্ট্রি নয়" দিয়ে শুরু করুন — মডেলে উদ্ধার স্পষ্ট হয়।',
    },
    commonMistake: {
      en: 'Assuming deletion equals destruction and redoing days of work that reflog could restore in seconds.',
      bn: 'মোছা সমান ধ্বংস ভেবে দিনের কাজ আবার করা যা রিফ্লগ সেকেন্ডে ফেরাতে পারত।',
    },
    relatedCommands: ['git.branch', 'git.switch'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: ['git.troubleshooting.deleted-branch', 'git.troubleshooting.recover-commit'],
    relatedPractice: ['git.practice.recover-deleted-branch'],
    relatedInternals: ['git.internals.reflog'],
    tags: ['branch', 'delete', 'recovery', 'reflog'],
    order: 61,
  },
  {
    id: 'git.interview.lost-commit-reflog',
    category: 'troubleshooting',
    difficulty: 'advanced',
    type: 'scenario',
    question: {
      en: 'A hard reset orphaned good commits and you know no hashes. How does reflog save you, step by step?',
      bn: 'হার্ড রিসেট ভালো কমিট এতিম করেছে, হ্যাশ জানেন না। রিফ্লগ ধাপে ধাপে কীভাবে বাঁচায়?',
    },
    shortAnswer: {
      en: 'git reflog lists every HEAD movement with old and new values — find the pre-reset entry, verify with git show, then reset or branch to that hash.',
      bn: 'git reflog পুরনো ও নতুন মানসহ প্রতিটি HEAD নড়াচড়া তালিকা করে — প্রি-রিসেট এন্ট্রি খুঁজুন, git show-তে যাচাই করে সেই হ্যাশে রিসেট বা ব্রাঞ্চ করুন।',
    },
    explanation: {
      en: 'Reset moves pointers; it rarely deletes objects immediately. The reflog entry "reset: moving to HEAD~2" sits right above the commit you came from. Inspect it, point a branch at it (safest — never lose the only copy twice), verify with log, and only then move your working branch.',
      bn: 'রিসেট পয়েন্টার সরায়; অবজেক্ট সাথে সাথে মোছে না। "reset: moving to HEAD~2" রিফ্লগ এন্ট্রির ঠিক ওপরে এসেছেন যেখান থেকে। পরিদর্শন করুন, ব্রাঞ্চ বসান (নিরাপদ — একমাত্র কপি দুবার হারাবেন না), log-এ যাচাই করে তারপর ওয়ার্কিং ব্রাঞ্চ সরান।',
    },
    interviewTip: {
      en: 'Emphasize "branch first, reset second" — interviewers check whether your recovery itself is recoverable.',
      bn: '"আগে ব্রাঞ্চ, পরে রিসেট" জোর দিন — ইন্টারভিউয়াররা যাচাই করেন আপনার উদ্ধার নিজে উদ্ধারযোগ্য কিনা।',
    },
    commonMistake: {
      en: 'Resetting --hard again toward a guessed hash, destroying the very trail you are following.',
      bn: 'অনুমান হ্যাশে আবার --hard রিসেট করে অনুসরণ করা পথই ধ্বংস করা।',
    },
    relatedCommands: ['git.reset', 'git.switch'],
    relatedLessons: ['git.fundamentals.head'],
    relatedTroubleshooting: ['git.troubleshooting.recover-commit', 'git.troubleshooting.reset-hard'],
    relatedPractice: ['git.practice.command-recover-lost-commit'],
    relatedInternals: ['git.internals.reflog', 'git.internals.unreachable-objects-expiry'],
    tags: ['reflog', 'reset', 'recovery', 'advanced'],
    order: 62,
  },
  {
    id: 'git.interview.reset-hard-danger',
    category: 'troubleshooting',
    difficulty: 'intermediate',
    type: 'scenario',
    question: {
      en: 'Someone suggests git reset --hard to "clean up". What exactly is at risk, and what do you do first?',
      bn: 'কেউ "পরিষ্কারে" git reset --hard প্রস্তাব করে। ঠিক কী ঝুঁকিতে, আগে কী করবেন?',
    },
    shortAnswer: {
      en: 'Uncommitted work is destroyed permanently — it was never an object Git can restore. First: stage or commit anything worth keeping.',
      bn: 'আনকমিটেড কাজ স্থায়ী ধ্বংস হয় — এটি কখনো অবজেক্ট ছিল না যা গিট ফেরাতে পারে। আগে: রাখার মতো সব স্টেজ বা কমিট করুন।',
    },
    explanation: {
      en: '--hard overwrites index and working tree to match the target, discarding everything uncommitted. Committed work remains recoverable via reflog; uncommitted bytes simply cease to exist. The professional habit: git stash or a WIP commit before any destructive command.',
      bn: '--hard টার্গেটে মেলাতে ইনডেক্স ও ওয়ার্কিং ট্রি ওভাররাইট করে, আনকমিটেড সব বাতিল করে। কমিটেড কাজ রিফ্লগে উদ্ধারযোগ্য থাকে; আনকমিটেড বাইট অস্তিত্ব হারায়। পেশাদার অভ্যাস: ধ্বংসাত্মক কমান্ডের আগে git stash বা WIP কমিট।',
    },
    interviewTip: {
      en: 'State the uncommitted/committed boundary crisply — that single distinction is the whole question.',
      bn: 'আনকমিটেড/কমিটেড সীমানা স্পষ্ট বলুন — সেই এক পার্থক্যই পুরো প্রশ্ন।',
    },
    commonMistake: {
      en: 'Believing reflog can restore uncommitted edits — it journals references, never working-tree bytes.',
      bn: 'রিফ্লগ আনকমিটেড এডিট ফেরাতে পারে বিশ্বাস — এটি রেফারেন্সের জার্নাল, ওয়ার্কিং-ট্রি বাইটের নয়।',
    },
    relatedCommands: ['git.reset', 'git.status'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: ['git.troubleshooting.reset-hard', 'git.troubleshooting.deleted-changes'],
    relatedPractice: [],
    relatedInternals: ['git.internals.unreachable-objects-expiry'],
    tags: ['reset-hard', 'danger', 'uncommitted'],
    order: 63,
  },
  {
    id: 'git.interview.secret-committed',
    category: 'troubleshooting',
    difficulty: 'advanced',
    type: 'scenario',
    question: {
      en: 'An API key was committed and pushed. Deleting it in the next commit is not enough — why, and what is the real response?',
      bn: 'API কী কমিট ও পুশ হয়েছে। পরের কমিটে মোছা যথেষ্ট নয় — কেন, আসল প্রতিক্রিয়া কী?',
    },
    shortAnswer: {
      en: 'History still contains the key in the old commit, readable forever. Rotate/revoke the key immediately, then purge history deliberately with team coordination.',
      bn: 'পুরনো কমিটে কী হিস্ট্রিতে থাকে, চিরকাল পাঠযোগ্য। সাথে সাথে কী রোটেট/বাতিল করুন, তারপর টিম সমন্বয়ে ইচ্ছাকৃত হিস্ট্রি পরিষ্কার করুন।',
    },
    explanation: {
      en: 'Git history is append-only memory: a follow-up deletion only hides the current tip, while clones, forks, and caches keep serving the exposed commit. Secrets response is incident response — revoke first (assume compromise), then rewrite history with filter-repo/BFG, force-push with agreement, and tell everyone to re-clone affected refs.',
      bn: 'গিট হিস্ট্রি শুধু-যোগ স্মৃতি: ফলো-আপ মোছা শুধু বর্তমান টিপ লুকায়, ক্লোন, ফোর্ক ও ক্যাশ প্রকাশিত কমিট দিতে থাকে। সিক্রেট প্রতিক্রিয়া ঘটনা প্রতিক্রিয়া — আগে বাতিল (আপস ধরে নিন), তারপর filter-repo/BFG-তে হিস্ট্রি পুনর্লিখন, সম্মতিতে ফোর্স-পুশ, সবাইকে আক্রান্ত ref পুনঃক্লোন বলুন।',
    },
    interviewTip: {
      en: '"Revoke first, rewrite second" in that order — interviewers specifically test whether cleanup comes before containment.',
      bn: '"আগে বাতিল, পরে পুনর্লিখন" এই ক্রমে — পরিষ্কারের আগে নিয়ন্ত্রণ আসে কিনা ইন্টারভিউয়াররা বিশেষ পরীক্ষা করেন।',
    },
    commonMistake: {
      en: 'Quietly deleting the file and moving on, leaving a live credential in public history indefinitely.',
      bn: 'নীরবে ফাইল মুছে এগিয়ে যাওয়া, পাবলিক হিস্ট্রিতে লাইভ ক্রেডেনশিয়াল অনির্দিষ্ট রেখে।',
    },
    relatedCommands: ['git.log'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: ['git.troubleshooting.committed-secret', 'git.troubleshooting.remove-file-from-commit'],
    relatedPractice: [],
    relatedInternals: [],
    tags: ['secret', 'security', 'history-rewrite'],
    order: 64,
  },
  {
    id: 'git.interview.detached-head-fix',
    category: 'troubleshooting',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'You did experimental work in detached HEAD state and want to keep it. What is the safe move?',
      bn: 'ডিটাচড HEAD অবস্থায় পরীক্ষামূলক কাজ করেছেন ও রাখতে চান। নিরাপদ চাল কী?',
    },
    shortAnswer: {
      en: 'Create a branch where you stand — git switch -c experiment — which instantly gives the commits a permanent home.',
      bn: 'যেখানে দাঁড়িয়ে সেখানে ব্রাঞ্চ তৈরি করুন — git switch -c experiment — যা সাথে সাথে কমিটে স্থায়ী ঠিকানা দেয়।',
    },
    explanation: {
      en: 'Detached commits exist but belong to no ref, so switching away orphans them. Naming a branch attaches a ref in one step; everything becomes reachable, reviewable, and pushable again.',
      bn: 'ডিটাচড কমিট আছে কিন্তু কোনো ref-এর নয়, তাই সরে গেলে এতিম হয়। ব্রাঞ্চ নাম দিলে এক ধাপে ref যুক্ত হয়; সব পৌঁছানো, পর্যালোচনা ও পুশযোগ্য হয়।',
    },
    interviewTip: {
      en: 'One command, zero drama — "branch where you stand" is the memorable phrasing.',
      bn: 'এক কমান্ড, শূন্য নাটক — "যেখানে দাঁড়িয়ে সেখানে ব্রাঞ্চ" স্মরণীয় বাক্য।',
    },
    commonMistake: {
      en: 'Switching away "just to check something", orphaning the work, then discovering reflog the hard way.',
      bn: '"শুধু কিছু দেখতে" সরে গিয়ে কাজ এতিম করা, তারপর কঠিনে রিফ্লগ আবিষ্কার।',
    },
    options: [
      { id: 'a', label: 'git switch -c experiment', correct: true },
      { id: 'b', label: 'git switch main', correct: false },
      { id: 'c', label: 'git reset --hard HEAD', correct: false },
      { id: 'd', label: 'git stash list', correct: false },
    ],
    relatedCommands: ['git.switch', 'git.checkout'],
    relatedLessons: ['git.fundamentals.head'],
    relatedTroubleshooting: ['git.troubleshooting.detached-head'],
    relatedPractice: [],
    relatedInternals: ['git.internals.head-deep-dive'],
    tags: ['detached-head', 'branch', 'recovery'],
    order: 65,
  },
  /* ---------------- Internals (10) ---------------- */
  {
    id: 'git.interview.blob-content',
    category: 'internals',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'What does a blob store, and what does it deliberately NOT know?',
      bn: 'ব্লব কী সংরক্ষণ করে, আর ইচ্ছাকৃত কী জানে না?',
    },
    shortAnswer: {
      en: 'A blob stores raw file bytes only — no filename, path, or timestamp. Trees supply all naming.',
      bn: 'ব্লব শুধু কাঁচা ফাইল বাইট রাখে — ফাইলনাম, পথ বা সময় নয়। ট্রি সব নাম দেয়।',
    },
    explanation: {
      en: 'This separation is why deduplication is free: ten identical files in ten folders all point at one blob. Rename a file without changing bytes and zero new blobs are created — only a tree entry changes.',
      bn: 'এই বিচ্ছেদে ডিডুপ্লিকেশন বিনামূল্য: দশ ফোল্ডারে দশ একই ফাইল একটি ব্লবের দিকে যায়। বাইট না বদলে ফাইল পুনর্নামে শূন্য নতুন ব্লব তৈরি হয় — শুধু ট্রি এন্ট্রি বদলায়।',
    },
    interviewTip: {
      en: 'Use the rename-without-blobs example — it turns an abstract claim into observable proof.',
      bn: 'ব্লব ছাড়া পুনর্নাম উদাহরণ দিন — বিমূর্ত দাবি পর্যবেক্ষণযোগ্য প্রমাণে বদলায়।',
    },
    commonMistake: {
      en: 'Saying blobs "are files" — files are tree entries plus blobs; blobs alone are anonymous bytes.',
      bn: 'ব্লব "হলো ফাইল" বলা — ফাইল হলো ট্রি এন্ট্রি সাথে ব্লব; একা ব্লব নামহীন বাইট।',
    },
    relatedCommands: ['git.show'],
    relatedLessons: [],
    relatedTroubleshooting: [],
    relatedPractice: [],
    relatedInternals: ['git.internals.blob-objects'],
    tags: ['blob', 'objects', 'deduplication'],
    order: 66,
  },
  {
    id: 'git.interview.tree-role',
    category: 'internals',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'What problem do tree objects solve that blobs cannot?',
      bn: 'ব্লব যা পারে না, ট্রি অবজেক্ট কোন সমস্যা সমাধান করে?',
    },
    shortAnswer: {
      en: 'Structure: trees map names to blobs and subtrees, turning anonymous bytes into a navigable directory snapshot.',
      bn: 'কাঠামো: ট্রি নাম ব্লব ও সাবট্রিতে ম্যাপ করে, নামহীন বাইটকে নেভিগেটযোগ্য ডিরেক্টরি স্ন্যাপশটে বদলায়।',
    },
    explanation: {
      en: 'Without trees, Git would have content with no filenames, no folders, and no way to reconstruct a checkout. Each commit points at exactly one root tree; nesting handles arbitrary depth. git ls-tree reveals this structure without touching your files.',
      bn: 'ট্রি ছাড়া গিটে ফাইলনাম, ফোল্ডার ছাড়া কন্টেন্ট থাকত, চেকআউট পুনর্গঠনের উপায় থাকত না। প্রতিটি কমিট ঠিক একটি রুট ট্রির দিকে যায়; নেস্টিং ইচ্ছামতো গভীরতা সামলায়। git ls-tree ফাইল না ছুঁয়ে এই কাঠামো দেখায়।',
    },
    interviewTip: {
      en: 'Connect trees to checkout: "trees are why a commit can become files again." Purpose-first answers land.',
      bn: 'ট্রিকে চেকআউটে যুক্ত করুন: "ট্রি আছে বলে কমিট আবার ফাইল হতে পারে।" উদ্দেশ্য-আগে উত্তর বসে।',
    },
    commonMistake: {
      en: 'Skipping trees entirely — jumping from commits to blobs leaves "where do filenames live?" unanswered.',
      bn: 'ট্রি পুরো বাদ — কমিট থেকে ব্লবে লাফে "ফাইলনাম কোথায় থাকে?" উত্তরহীন থাকে।',
    },
    relatedCommands: ['git.show'],
    relatedLessons: [],
    relatedTroubleshooting: [],
    relatedPractice: [],
    relatedInternals: ['git.internals.tree-objects'],
    tags: ['tree', 'structure', 'snapshot'],
    order: 67,
  },
  {
    id: 'git.interview.commit-anatomy',
    category: 'internals',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'List everything a commit object contains, and explain what a merge commit adds.',
      bn: 'কমিট অবজেক্টে সবকিছু তালিকা করুন, মার্জ কমিট কী যোগ করে ব্যাখ্যা করুন।',
    },
    shortAnswer: {
      en: 'Tree pointer, parent list, author, committer, message. A merge commit simply adds a second parent.',
      bn: 'ট্রি পয়েন্টার, প্যারেন্ট তালিকা, লেখক, কমিটার, বার্তা। মার্জ কমিট শুধু দ্বিতীয় প্যারেন্ট যোগ করে।',
    },
    explanation: {
      en: 'Author wrote the change; committer recorded it (often the same person, diverging on cherry-picks and rebases). The tree freezes the snapshot; parents freeze the position in history. Nothing about branches lives inside — branches are outside pointers that move across these frozen facts.',
      bn: 'লেখক পরিবর্তন লিখেছে; কমিটার রেকর্ড করেছে (প্রায়ই একই ব্যক্তি, cherry-pick ও রিবেসে ভিন্ন)। ট্রি স্ন্যাপশট হিমায়িত করে; প্যারেন্ট ইতিহাসে অবস্থান হিমায়িত করে। ভেতরে ব্রাঞ্চ সম্পর্কে কিছু নেই — ব্রাঞ্চ বাইরের পয়েন্টার যা হিমায়িত তথ্যে সরে।',
    },
    interviewTip: {
      en: 'Separate author from committer confidently — most candidates blur them, so precision stands out.',
      bn: 'লেখক ও কমিটার আত্মবিশ্বাসে আলাদা করুন — বেশিরভাগ প্রার্থী গুলিয়ে ফেলে, তাই নির্ভুলতা দাঁড়ায়।',
    },
    commonMistake: {
      en: 'Claiming commits store diffs or branch names — both live outside the object (diffs are computed, branches are refs).',
      bn: 'কমিট ডিফ বা ব্রাঞ্চ নাম রাখে দাবি — উভয় অবজেক্টের বাইরে (ডিফ গণনা হয়, ব্রাঞ্চ ref)।',
    },
    relatedCommands: ['git.show', 'git.log'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-interpret-graph'],
    relatedInternals: ['git.internals.commit-objects'],
    tags: ['commit', 'anatomy', 'parents'],
    order: 68,
  },
  {
    id: 'git.interview.reference-model',
    category: 'internals',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'What do branches, tags, and HEAD have in common structurally?',
      bn: 'গাঠনিকভাবে ব্রাঞ্চ, ট্যাগ ও HEAD-এ মিল কী?',
    },
    shortAnswer: {
      en: 'They are all references — human names for object IDs. Branches move, tags stay fixed, HEAD usually points at a branch.',
      bn: 'সব রেফারেন্স — অবজেক্ট ID-এর মানব-নাম। ব্রাঞ্চ সরে, ট্যাগ স্থির থাকে, HEAD সাধারণত ব্রাঞ্চের দিকে যায়।',
    },
    explanation: {
      en: 'refs/heads/* advance with commits, refs/tags/* pin milestones, and HEAD is a symbolic ref to the current branch (or a raw hash when detached). Remote-tracking refs like origin/main are the same idea pointed at remembered remote state. One mechanism, four jobs.',
      bn: 'refs/heads/* কমিটে এগোয়, refs/tags/* মাইলফলক পিন করে, HEAD বর্তমান ব্রাঞ্চের সিম্বলিক ref (বা ডিটাচডে কাঁচা হ্যাশ)। origin/main-এর মতো রিমোট-ট্র্যাকিং ref মনে রাখা রিমোট অবস্থায় একই ধারণা। এক কৌশল, চার কাজ।',
    },
    interviewTip: {
      en: 'Unify first ("all references"), then differentiate — taxonomies delivered top-down sound senior.',
      bn: 'আগে একত্র করুন ("সব রেফারেন্স"), তারপর আলাদা করুন — ওপর-নিচ শ্রেণিবিন্যাস সিনিয়র শোনায়।',
    },
    commonMistake: {
      en: 'Treating HEAD as fundamentally different machinery — it is a ref with a special job, not a separate system.',
      bn: 'HEAD-কে মৌলিক ভিন্ন যন্ত্র ভাবা — এটি বিশেষ কাজের ref, আলাদা সিস্টেম নয়।',
    },
    relatedCommands: ['git.branch', 'git.log'],
    relatedLessons: ['git.fundamentals.branch', 'git.fundamentals.head'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-follow-head'],
    relatedInternals: ['git.internals.what-is-a-reference', 'git.internals.branch-references'],
    tags: ['references', 'unifying-model'],
    order: 69,
  },
  {
    id: 'git.interview.head-deep',
    category: 'internals',
    difficulty: 'advanced',
    type: 'conceptual',
    question: {
      en: 'What is the mechanical difference between attached and detached HEAD?',
      bn: 'সংযুক্ত ও বিচ্ছিন্ন HEAD-এ যান্ত্রিক পার্থক্য কী?',
    },
    shortAnswer: {
      en: 'Attached HEAD holds a ref path (ref: refs/heads/main); detached HEAD holds a raw commit hash. Commits advance branches only in the attached case.',
      bn: 'সংযুক্ত HEAD-এ ref পথ থাকে (ref: refs/heads/main); বিচ্ছিন্ন HEAD-এ কাঁচা কমিট হ্যাশ। কমিট শুধু সংযুক্ত ক্ষেত্রে ব্রাঞ্চ এগিয়ে নেয়।',
    },
    explanation: {
      en: 'The .git/HEAD file literally contains either text. On commit, Git follows the symbolic ref to a branch and advances it; with a raw hash there is no branch to advance, so new commits dangle. Detached work is safe to inspect and safe to keep — but only if you name a branch before leaving.',
      bn: '.git/HEAD ফাইলে আক্ষরিক পাঠ্য থাকে। কমিটে গিট সিম্বলিক ref অনুসরণ করে ব্রাঞ্চ এগিয়ে নেয়; কাঁচা হ্যাশে এগোনোর ব্রাঞ্চ নেই, তাই নতুন কমিট ঝুলে। ডিটাচড কাজ পরিদর্শনে নিরাপদ ও রাখায় নিরাপদ — কিন্তু যাওয়ার আগে ব্রাঞ্চ নাম দিলেই।',
    },
    interviewTip: {
      en: 'Quote the file contents ("ref: refs/heads/main" vs a hash) — filesystem-level specifics end the debate instantly.',
      bn: 'ফাইল কন্টেন্ট উদ্ধৃত করুন ("ref: refs/heads/main" বনাম হ্যাশ) — ফাইলসিস্টেম-স্তর নির্দিষ্টতা সাথে সাথে বিতর্ক শেষ করে।',
    },
    commonMistake: {
      en: 'Believing detached HEAD corrupts the repository — it changes exactly one tiny file, reversibly.',
      bn: 'ডিটাচড HEAD রিপোজিটরি নষ্ট করে বিশ্বাস — এটি ঠিক একটি ক্ষুদ্র ফাইল বদলায়, প্রত্যাবর্তনযোগ্যভাবে।',
    },
    relatedCommands: ['git.switch', 'git.checkout'],
    relatedLessons: ['git.fundamentals.head'],
    relatedTroubleshooting: ['git.troubleshooting.detached-head'],
    relatedPractice: [],
    relatedInternals: ['git.internals.head-deep-dive'],
    tags: ['head', 'detached', 'mechanics'],
    order: 70,
  },
  {
    id: 'git.interview.reflog-mechanics',
    category: 'internals',
    difficulty: 'advanced',
    type: 'conceptual',
    question: {
      en: 'What does the reflog record, and what are its hard limits?',
      bn: 'রিফ্লগ কী রেকর্ড করে, এবং কঠিন সীমা কী?',
    },
    shortAnswer: {
      en: 'Every local reference movement with old and new values. Limits: local only, expiring entries, and it journals references — never working-tree bytes.',
      bn: 'পুরনো ও নতুন মানসহ প্রতিটি লোকাল রেফারেন্স নড়াচড়া। সীমা: শুধু লোকাল, মেয়াদোত্তীর্ণ এন্ট্রি, রেফারেন্সের জার্নাল — ওয়ার্কিং-ট্রি বাইট কখনো নয়।',
    },
    explanation: {
      en: 'Each commit, reset, merge, checkout, and rebase appends HEAD@{n} entries. That journal is why "lost" commits are usually one branch command away from recovery. But entries expire (~90/30 days), nothing syncs to remotes, and uncommitted file edits were never objects — so reflog cannot conjure them.',
      bn: 'প্রতিটি কমিট, রিসেট, মার্জ, চেকআউট ও রিবেস HEAD@{n} এন্ট্রি যোগ করে। সেই জার্নালে "হারানো" কমিট সাধারণত এক ব্রাঞ্চ কমান্ড দূরে। কিন্তু এন্ট্রির মেয়াদ শেষ হয় (~৯০/৩০ দিন), রিমোটে কিছু সিঙ্ক হয় না, আনকমিটেড ফাইল এডিট কখনো অবজেক্ট ছিল না — তাই রিফ্লগ সেগুলো আনতে পারে না।',
    },
    interviewTip: {
      en: 'Lead with one limit, not just the power — interviewers test whether your safety nets have edges.',
      bn: 'শক্তি নয়, একটি সীমা দিয়ে শুরু করুন — নিরাপত্তা জালে কিনারা আছে কিনা ইন্টারভিউয়াররা পরীক্ষা করেন।',
    },
    commonMistake: {
      en: 'Calling reflog a backup — backups are remote, permanent, and complete; reflog is none of the three.',
      bn: 'রিফ্লগকে ব্যাকআপ বলা — ব্যাকআপ রিমোট, স্থায়ী ও সম্পূর্ণ; রিফ্লগ তিনটির কোনোটিই নয়।',
    },
    relatedCommands: ['git.switch', 'git.reset'],
    relatedLessons: ['git.fundamentals.head'],
    relatedTroubleshooting: ['git.troubleshooting.recover-commit', 'git.troubleshooting.reset-hard'],
    relatedPractice: ['git.practice.command-recover-lost-commit'],
    relatedInternals: ['git.internals.reflog', 'git.internals.unreachable-objects-expiry'],
    tags: ['reflog', 'recovery', 'limits'],
    order: 71,
  },
  {
    id: 'git.interview.object-database',
    category: 'internals',
    difficulty: 'advanced',
    type: 'conceptual',
    question: {
      en: 'Sketch what lives inside .git beyond the working files.',
      bn: '.git-এর ভেতরে ওয়ার্কিং ফাইল ছাড়া কী থাকে খসড়া করুন।',
    },
    shortAnswer: {
      en: 'objects/ (content-addressed blobs, trees, commits, tags), refs/ (branch and tag pointers), HEAD (current position), index (proposed commit), and logs/ (reflog journals).',
      bn: 'objects/ (কন্টেন্ট-ঠিকানাযুক্ত ব্লব, ট্রি, কমিট, ট্যাগ), refs/ (ব্রাঞ্চ ও ট্যাগ পয়েন্টার), HEAD (বর্তমান অবস্থান), index (প্রস্তাবিত কমিট) ও logs/ (রিফ্লগ জার্নাল)।',
    },
    explanation: {
      en: 'The split to emphasize: objects/ is immutable content; everything else is mutable pointers and staging. Cloning copies the database; checking out materializes from it; fetching adds to it; garbage collection prunes what nothing reaches.',
      bn: 'জোর দেওয়ার বিভাজন: objects/ অপরিবর্তনীয় কন্টেন্ট; বাকি সব পরিবর্তনশীল পয়েন্টার ও স্টেজিং। ক্লোনিং ডাটাবেস কপি করে; চেকআউট থেকে বাস্তবায়ন করে; fetch যোগ করে; গারবেজ কালেকশন পৌঁছানো যায় না তা ছাঁটে।',
    },
    interviewTip: {
      en: 'Draw the five entries from memory — whiteboard recall of .git layout is a strong senior signal.',
      bn: 'স্মৃতি থেকে পাঁচটি এন্ট্রি আঁকুন — .git বিন্যাসের হোয়াইটবোর্ড স্মৃতি শক্তিশালী সিনিয়র সংকেত।',
    },
    commonMistake: {
      en: 'Forgetting the index and reflog — the two pieces that explain staging mysteries and recoveries.',
      bn: 'ইনডেক্স ও রিফ্লগ ভুলে যাওয়া — স্টেজিং রহস্য ও পুনরুদ্ধার ব্যাখ্যা করা দুটি অংশ।',
    },
    relatedCommands: ['git.status'],
    relatedLessons: ['git.fundamentals.repository'],
    relatedTroubleshooting: [],
    relatedPractice: [],
    relatedInternals: ['git.internals.object-database'],
    tags: ['.git', 'objects', 'layout'],
    order: 72,
  },
  {
    id: 'git.interview.content-addressing',
    category: 'internals',
    difficulty: 'advanced',
    type: 'conceptual',
    question: {
      en: 'What is hashed to produce a Git object ID — and what famous thing is NOT hashed?',
      bn: 'গিট অবজেক্ট ID তৈরি কী হ্যাশ করা হয় — আর কোন বিখ্যাত জিনিস হ্যাশ হয় না?',
    },
    shortAnswer: {
      en: 'Object type, size, and content bytes. Filenames are never hashed — they live in tree entries outside the blob.',
      bn: 'অবজেক্ট টাইপ, আকার ও কন্টেন্ট বাইট। ফাইলনাম কখনো হ্যাশ হয় না — ব্লবের বাইরে ট্রি এন্ট্রিতে থাকে।',
    },
    explanation: {
      en: 'The hash covers a header (e.g. "blob 412\\0") plus raw bytes, which is why identical content anywhere shares one ID forever, and why any corruption is self-evident. Filenames stay out because trees already map names to hashes — hashing them into blobs would break deduplication.',
      bn: 'হ্যাশ হেডার (যেমন "blob 412\\0") সাথে কাঁচা বাইট ঢাকে, তাই যেকোনো জায়গার একই কন্টেন্ট চিরকাল এক ID ভাগ করে, ক্ষতি স্ব-প্রকাশ্য হয়। ফাইলনাম বাইরে থাকে কারণ ট্রি ইতিমধ্যে নাম হ্যাশে ম্যাপ করে — ব্লবে হ্যাশ করলে ডিডুপ্লিকেশন ভাঙত।',
    },
    interviewTip: {
      en: '"Filenames are not hashed" is the mic-drop — deliver it, then explain trees carry names instead.',
      bn: '"ফাইলনাম হ্যাশ হয় না" মাইক-ড্রপ — বলুন, তারপর ব্যাখ্যা করুন বদলে ট্রি নাম বহন করে।',
    },
    commonMistake: {
      en: 'Assuming renames create new blobs — unchanged bytes keep their IDs; only tree entries change.',
      bn: 'পুনর্নাম নতুন ব্লব তৈরি করে ভাবা — অপরিবর্তিত বাইট ID রাখে; শুধু ট্রি এন্ট্রি বদলায়।',
    },
    relatedCommands: ['git.show'],
    relatedLessons: ['git.fundamentals.what-is-git'],
    relatedTroubleshooting: [],
    relatedPractice: [],
    relatedInternals: ['git.internals.object-ids', 'git.internals.blob-objects'],
    tags: ['hash', 'content-addressing', 'sha'],
    order: 73,
  },
  {
    id: 'git.interview.dag-acyclic',
    category: 'internals',
    difficulty: 'advanced',
    type: 'conceptual',
    question: {
      en: 'Git history is a DAG. Why is it impossible for it to contain a cycle?',
      bn: 'গিট হিস্ট্রি DAG। এতে চক্র থাকা অসম্ভব কেন?',
    },
    shortAnswer: {
      en: 'A commit’s ID is computed over its parents’ IDs, so a commit can never be its own ancestor — time only flows backwards along edges.',
      bn: 'কমিট ID প্যারেন্ট ID-এর ওপর গণনা হয়, তাই কমিট নিজের পূর্বপুরুষ হতে পারে না — এজ ধরে সময় শুধু পেছনে বয়।',
    },
    explanation: {
      en: 'To forge a cycle, a commit would need to hash content containing its own hash — a cryptographic impossibility (like signing your own birth certificate before birth). This guarantee is what makes ancestry queries, merges, and garbage collection well-defined: every walk terminates.',
      bn: 'চক্র জাল করতে কমিটকে নিজ হ্যাশ ধারণকারী কন্টেন্ট হ্যাশ করতে হতো — ক্রিপ্টোগ্রাফিক অসম্ভব (জন্মের আগে নিজ জন্ম সনদে স্বাক্ষরের মতো)। এই গ্যারান্টিতে অ্যানসেস্ট্রি প্রশ্ন, মার্জ ও গারবেজ কালেকশন সুনির্দিষ্ট হয়: প্রতিটি হাঁটা শেষ হয়।',
    },
    interviewTip: {
      en: 'The birth-certificate analogy lands well — then connect it to why git log can never loop forever.',
      bn: 'জন্ম-সনদ উপমা ভালো বসে — তারপর যুক্ত করুন কেন git log কখনো চিরকাল ঘোরে না।',
    },
    commonMistake: {
      en: 'Treating DAG as jargon for "graph" — the acyclic guarantee is load-bearing, not decorative.',
      bn: 'DAG-কে "গ্রাফ"-এর পরিভাষা ভাবা — অ্যাসাইক্লিক গ্যারান্টি ভারবাহী, শোভাময় নয়।',
    },
    relatedCommands: ['git.log'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-interpret-graph'],
    relatedInternals: ['git.internals.dag-structure'],
    tags: ['dag', 'acyclic', 'theory'],
    order: 74,
  },
  {
    id: 'git.interview.reachability-gc',
    category: 'internals',
    difficulty: 'advanced',
    type: 'conceptual',
    question: {
      en: 'What does "unreachable" mean, and when does Git actually delete such objects?',
      bn: '"অপ্রাপ্য" মানে কী, এবং গিট আসলে কখন এমন অবজেক্ট মুছে?',
    },
    shortAnswer: {
      en: 'Unreachable means no reference path leads to it. Git deletes only after reflog grace periods expire — unreachable is a warning state, not instant deletion.',
      bn: 'অপ্রাপ্য মানে কোনো রেফারেন্স পথ সেখানে নেয় না। গিট মুছে শুধু রিফ্লগ গ্রেস পিরিয়ড শেষে — অপ্রাপ্য সতর্ক অবস্থা, তাৎক্ষণিক মোছা নয়।',
    },
    explanation: {
      en: 'Reachability is computed by walking backwards from every ref. Newly unreachable objects linger while reflog entries reference them (~90/30 days), keeping mistakes reversible. Garbage collection finally removes what nothing has pointed at beyond grace — which is why recovery has a clock, and why uncommitted bytes were never candidates at all.',
      bn: 'প্রতিটি ref থেকে পেছনে হেঁটে রিচেবিলিটি গণনা হয়। নতুন অপ্রাপ্য অবজেক্ট রিফ্লগ এন্ট্রি রেফারেন্স করা পর্যন্ত থাকে (~৯০/৩০ দিন), ভুল ফেরতযোগ্য রেখে। গারবেজ কালেকশন শেষে গ্রেস পেরোনো যা কিছু নির্দেশ করে না তা সরায় — তাই উদ্ধারে ঘড়ি আছে, আনকমিটেড বাইট কখনো প্রার্থী ছিল না।',
    },
    interviewTip: {
      en: 'Give the timeline explicitly (unreachable → grace → collected) — interviewers want the lifecycle, not just the definition.',
      bn: 'সময়রেখা স্পষ্ট দিন (অপ্রাপ্য → গ্রেস → সংগৃহীত) — ইন্টারভিউয়াররা সংজ্ঞা নয়, জীবনচক্র চান।',
    },
    commonMistake: {
      en: 'Promising indefinite recoverability — honesty about expiry is what separates seniors here.',
      bn: 'অনির্দিষ্ট উদ্ধারযোগ্যতার প্রতিশ্রুতি — মেয়াদে সততা এখানে সিনিয়র আলাদা করে।',
    },
    relatedCommands: ['git.log'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: ['git.troubleshooting.recover-commit'],
    relatedPractice: [],
    relatedInternals: ['git.internals.reachability', 'git.internals.garbage-collection', 'git.internals.unreachable-objects-expiry'],
    tags: ['reachability', 'gc', 'expiry'],
    order: 75,
  },
  /* ---------------- Mixed Scenarios (5) ---------------- */
  {
    id: 'git.interview.scenario-ahead-behind',
    category: 'scenarios',
    difficulty: 'intermediate',
    type: 'state',
    question: {
      en: 'Your branch is ahead by 1 and the remote moved too. What does git status mean, and what are your options?',
      bn: 'ব্রাঞ্চ 1 এগিয়ে আর রিমোটও সরেছে। git status মানে কী, বিকল্প কী?',
    },
    shortAnswer: {
      en: 'Diverged: both sides have unique commits. Either merge (preserve both lines) or fetch then rebase your private work — never force-push shared history.',
      bn: 'ডাইভার্জড: উভয় পক্ষে অনন্য কমিট। মার্জ (উভয় লাইন সংরক্ষণ) বা fetch করে ব্যক্তিগত কাজ রিবেস — শেয়ার্ড হিস্ট্রি ফোর্স-পুশ কখনো নয়।',
    },
    explanation: {
      en: 'Ahead-only wants a push; behind-only wants a pull. Divergence means genuinely different work on both sides, so the only honest moves integrate: merge records the join, rebase replays yours atop theirs (private branches only).',
      bn: 'শুধু এগিয়ে পুশ চায়; শুধু পিছিয়ে পুল চায়। ডাইভারজেন্স মানে উভয় পক্ষে সত্যিকারের ভিন্ন কাজ, তাই সৎ চালে একীভূত: মার্জ জয়েন রেকর্ড করে, রিবেস তাদের ওপর আপনারটা রিপ্লে করে (শুধু ব্যক্তিগত ব্রাঞ্চ)।',
    },
    interviewTip: {
      en: 'Say "diverged" then translate: "ahead 1, behind 1 — both sides moved." Counts prove status literacy.',
      bn: '"diverged" বলে অনুবাদ করুন: "ahead 1, behind 1 — উভয় পক্ষ সরেছে।" সংখ্যা status সাক্ষরতা প্রমাণ করে।',
    },
    commonMistake: {
      en: 'Force-pushing a shared branch to "fix" divergence — erasing the teammate side of the fork.',
      bn: 'শেয়ার্ড ব্রাঞ্চে ডাইভারজেন্স "ঠিক" করতে ফোর্স-পুশ — ফোর্কের সহকর্মী পক্ষ মোছা।',
    },
    stateSnapshot: {
      files: [
        { name: 'README.md', workStatus: 'clean', staged: false },
        { name: 'app.js', workStatus: 'clean', staged: false },
        { name: 'package.json', workStatus: 'clean', staged: false },
      ],
      commits: [
        { id: 'C1', message: 'Initial commit', parents: [] },
        { id: 'C2', message: 'Teammate docs', parents: ['C1'] },
        { id: 'L1', message: 'My feature tweak', parents: ['C1'] },
      ],
      localBranches: { main: 'L1' },
      remoteTracking: { 'origin/main': 'C2' },
      serverBranches: { main: 'C2' },
      serverOnly: [],
      currentBranch: 'main',
      seq: 10,
    },
    snapshotView: 'graph',
    options: [
      { id: 'a', label: 'Diverged — merge or rebase privately, never force-push shared history', correct: true },
      { id: 'b', label: 'Simply behind — pull will fast-forward', correct: false },
      { id: 'c', label: 'Simply ahead — push will succeed', correct: false },
      { id: 'd', label: 'Corrupted — re-clone immediately', correct: false },
    ],
    relatedCommands: ['git.status', 'git.fetch', 'git.pull'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: ['git.troubleshooting.diverged'],
    relatedPractice: [],
    relatedInternals: ['git.internals.dag-structure'],
    tags: ['diverged', 'ahead-behind', 'scenario'],
    order: 76,
  },
  {
    id: 'git.interview.scenario-dirty-switch',
    category: 'scenarios',
    difficulty: 'beginner',
    type: 'state',
    question: {
      en: 'app.js is modified and unstaged. What happens if you try to switch branches right now?',
      bn: 'app.js পরিবর্তিত ও আনস্টেজড। এখন ব্রাঞ্চ বদলালে কী হয়?',
    },
    shortAnswer: {
      en: 'Git may refuse to protect your edits — commit, stash, or discard first, then switch on a clean tree.',
      bn: 'গিট এডিট রক্ষায় প্রত্যাখ্যান করতে পারে — আগে কমিট, স্ট্যাশ বা বাতিল, তারপর পরিষ্কার ট্রিতে সুইচ।',
    },
    explanation: {
      en: 'Switching rewrites working-tree files, which would clobber uncommitted edits, so Git blocks when the target differs. Parking the work first makes every switch safe and reviewable.',
      bn: 'সুইচ ওয়ার্কিং-ট্রি ফাইল পুনর্লিখন করে, যা আনকমিটেড এডিট নষ্ট করত, তাই টার্গেট ভিন্ন হলে গিট আটকায়। আগে কাজ পার্ক করলে প্রতিটি সুইচ নিরাপদ ও পর্যালোচনাযোগ্য হয়।',
    },
    interviewTip: {
      en: 'Name the guardrail: "Git blocks to protect edits I have not saved yet." Protection framing wins.',
      bn: 'গার্ডরেলের নাম বলুন: "এখনো না-বাঁচানো এডিট রক্ষায় গিট আটকায়।" সুরক্ষা ফ্রেমিং জেতে।',
    },
    commonMistake: {
      en: 'Assuming uncommitted edits always follow you — then losing work on a conflicting switch.',
      bn: 'আনকমিটেড এডিট সবসময় সাথে যাবে ধরে — তারপর বিরোধী সুইচে কাজ হারানো।',
    },
    stateSnapshot: {
      files: [
        { name: 'README.md', workStatus: 'clean', staged: false },
        { name: 'app.js', workStatus: 'modified', staged: false },
        { name: 'package.json', workStatus: 'clean', staged: false },
      ],
      commits: [{ id: 'C1', message: 'Initial commit', parents: [] }],
      localBranches: { main: 'C1', feature: 'C1' },
      remoteTracking: { 'origin/main': 'C1' },
      serverBranches: { main: 'C1' },
      serverOnly: [],
      currentBranch: 'main',
      seq: 2,
    },
    snapshotView: 'areas',
    options: [
      { id: 'a', label: 'Likely blocked — park the edits (commit/stash/discard), then switch', correct: true },
      { id: 'b', label: 'Always fine — uncommitted edits follow you automatically', correct: false },
      { id: 'c', label: 'The edits are auto-committed during the switch', correct: false },
      { id: 'd', label: 'The other branch is deleted for safety', correct: false },
    ],
    relatedCommands: ['git.switch', 'git.status'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.switch-branches'],
    relatedInternals: [],
    tags: ['switch', 'dirty-tree', 'scenario'],
    order: 77,
  },
  {
    id: 'git.interview.scenario-stale-fetch',
    category: 'scenarios',
    difficulty: 'intermediate',
    type: 'state',
    question: {
      en: 'After git fetch, origin/main moved to C2 but your main is still on C1. A teammate asks if you are "updated". What is the precise answer?',
      bn: 'git fetch-এর পর origin/main C2-তে গেল কিন্তু main C1-তে। সহকর্মী জিজ্ঞেস করল "আপডেটেড?" নির্ভুল উত্তর কী?',
    },
    shortAnswer: {
      en: 'Aware but not updated: you downloaded C2 and can see it, but your branch still points at C1 until you merge or rebase.',
      bn: 'সচেতন কিন্তু আপডেটেড নয়: C2 ডাউনলোড করে দেখতে পারেন, কিন্তু মার্জ বা রিবেস না করা পর্যন্ত ব্রাঞ্চ C1-তে।',
    },
    explanation: {
      en: 'Fetch updates your photograph (origin/main), never your position (main). "Updated" means integrated — the fetch gave you the information; only merge, rebase, or pull completes the job.',
      bn: 'Fetch ছবি (origin/main) আপডেট করে, অবস্থান (main) নয়। "আপডেটেড" মানে একীভূত — fetch তথ্য দিয়েছে; শুধু মার্জ, রিবেস বা পুল কাজ শেষ করে।',
    },
    interviewTip: {
      en: 'Use the photograph line: "fetch updated my picture, not my position." Metaphors stick.',
      bn: 'ছবির লাইন ব্যবহার করুন: "fetch ছবি আপডেট করেছে, অবস্থান নয়।" রূপক মনে থাকে।',
    },
    commonMistake: {
      en: 'Claiming fetch alone makes you "updated" — integration is still pending.',
      bn: 'শুধু fetch-এ "আপডেটেড" দাবি — একীভূতকরণ এখনো বাকি।',
    },
    stateSnapshot: {
      files: [
        { name: 'README.md', workStatus: 'clean', staged: false },
        { name: 'app.js', workStatus: 'clean', staged: false },
        { name: 'package.json', workStatus: 'clean', staged: false },
      ],
      commits: [
        { id: 'C1', message: 'Initial commit', parents: [] },
        { id: 'C2', message: 'Teammate docs', parents: ['C1'] },
      ],
      localBranches: { main: 'C1' },
      remoteTracking: { 'origin/main': 'C2' },
      serverBranches: { main: 'C2' },
      serverOnly: [],
      currentBranch: 'main',
      seq: 3,
    },
    snapshotView: 'graph',
    options: [
      { id: 'a', label: 'Informed, not updated — main still needs integrating', correct: true },
      { id: 'b', label: 'Fully updated — fetch moved main to C2', correct: false },
      { id: 'c', label: 'Behind and unaware — fetch changed nothing', correct: false },
      { id: 'd', label: 'Diverged — must force-push', correct: false },
    ],
    relatedCommands: ['git.fetch', 'git.log'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: ['git.troubleshooting.behind-remote'],
    relatedPractice: ['git.practice.fetch-changes'],
    relatedInternals: ['git.internals.remote-tracking-references'],
    tags: ['fetch', 'tracking', 'scenario'],
    order: 78,
  },
  {
    id: 'git.interview.scenario-small-pr',
    category: 'scenarios',
    difficulty: 'intermediate',
    type: 'scenario',
    question: {
      en: 'Your pull request touches 40 files across three features. A senior asks you to split it. Why are they right, and how?',
      bn: 'পুল রিকোয়েস্ট তিন ফিচারে ৪০ ফাইল ছুঁয়েছে। সিনিয়র ভাগ করতে বলেছে। কেন ঠিক, কীভাবে?',
    },
    shortAnswer: {
      en: 'Huge PRs get skimmed, not reviewed. Split by feature into stacked or sequential PRs, each independently reviewable and revertible.',
      bn: 'বিশাল PR চোখ বুলানো হয়, রিভিউ নয়। ফিচারে ভাগ করে স্ট্যাকড বা ধারাবাহিক PR করুন, প্রতিটি স্বাধীন পর্যালোচনা ও প্রত্যাবর্তনযোগ্য।',
    },
    explanation: {
      en: 'Review quality collapses past a few hundred lines: bugs hide, context evaporates, approvals become rubber stamps. Small PRs get fast thorough reviews, clean CI signals per change, and safe partial reverts. Branch per feature from an updated base, and open them in dependency order.',
      bn: 'কয়েকশ লাইন পেরোলে রিভিউ মান ভেঙে: বাগ লুকায়, প্রেক্ষাপট উবে যায়, অনুমোদন রাবার-স্ট্যাম্প হয়। ছোট PR দ্রুত পুঙ্খানুপুঙ্খ রিভিউ, প্রতি পরিবর্তনে পরিষ্কার CI সংকেত ও নিরাপদ আংশিক রিভার্ট পায়। ফিচারে ব্রাঞ্চ করুন হালনাগাদ বেস থেকে, নির্ভরতা ক্রমে খুলুন।',
    },
    interviewTip: {
      en: 'Agree enthusiastically — seniors test whether you defend your big PR or learn from the feedback.',
      bn: 'উৎসাহে সম্মত হোন — সিনিয়ররা পরীক্ষা করেন বড় PR রক্ষা করেন না মতামত থেকে শেখেন।',
    },
    commonMistake: {
      en: 'Arguing "but it all works together" — reviewability and revertability are team properties, not personal ones.',
      bn: '"কিন্তু সব একসাথে কাজ করে" তর্ক — পর্যালোচনাযোগ্যতা ও প্রত্যাবর্তনযোগ্যতা টিম বৈশিষ্ট্য, ব্যক্তিগত নয়।',
    },
    relatedCommands: ['git.branch', 'git.log'],
    relatedLessons: [],
    relatedTroubleshooting: ['git.troubleshooting.pull-conflict'],
    relatedPractice: ['git.practice.feature-branch-workflow'],
    relatedInternals: [],
    tags: ['pr', 'review', 'scope', 'collaboration'],
    order: 79,
  },
  {
    id: 'git.interview.scenario-secret-response',
    category: 'scenarios',
    difficulty: 'advanced',
    type: 'scenario',
    question: {
      en: 'CI just flagged an AWS key you committed yesterday — already pushed and pulled by teammates. State your first three actions in order.',
      bn: 'CI গতকাল কমিট করা AWS কী চিহ্নিত করেছে — ইতিমধ্যে পুশ ও সহকর্মীরা পুল করেছে। ক্রমে প্রথম তিন কাজ বলুন।',
    },
    shortAnswer: {
      en: 'Revoke the key immediately, then purge history deliberately with team coordination, then verify no live copies remain.',
      bn: 'সাথে সাথে কী বাতিল করুন, তারপর টিম সমন্বয়ে ইচ্ছাকৃত হিস্ট্রি পরিষ্কার করুন, লাইভ কপি নেই যাচাই করুন।',
    },
    explanation: {
      en: 'Order matters because deletion alone never recalls pushed bytes: clones, forks, and CI logs keep serving the commit. Revocation kills the blast radius first; history surgery (filter-repo, coordinated force-push, re-clones) cleans second; scanning proves third. Anyone who starts by editing files has the sequence backwards.',
      bn: 'ক্রম গুরুত্বপূর্ণ কারণ মোছা একা পুশড বাইট ফেরায় না: ক্লোন, ফোর্ক ও CI লগ কমিট দিতে থাকে। বাতিল আগে বিস্ফোরণ ব্যাসার্ধ মারে; হিস্ট্রি সার্জারি (filter-repo, সমন্বিত ফোর্স-পুশ, পুনঃক্লোন) পরে পরিষ্কার করে; স্ক্যানিং তৃতীয়ে প্রমাণ করে। ফাইল এডিটে শুরু করা ক্রম উল্টো।',
    },
    interviewTip: {
      en: 'Say "assume compromise" out loud — incident-response vocabulary signals production experience.',
      bn: '"আপস ধরে নিন" জোরে বলুন — ঘটনা-প্রতিক্রিয়া শব্দভাণ্ডার প্রোডাকশন অভিজ্ঞতার সংকেত।',
    },
    commonMistake: {
      en: 'Opening with git rm and a quiet follow-up commit while the live key sits in every clone’s history.',
      bn: 'git rm ও নীরব ফলো-আপ কমিটে শুরু করে প্রতিটি ক্লোনের হিস্ট্রিতে লাইভ কী রেখে।',
    },
    relatedCommands: ['git.log'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: ['git.troubleshooting.committed-secret'],
    relatedPractice: [],
    relatedInternals: [],
    tags: ['secret', 'security', 'incident', 'advanced'],
    order: 80,
  },
];
