/**
 * Interview questions — branching & history (15) + remote & collaboration (10).
 * Data only. Stable ids (`git.interview.<slug>`), bilingual copy.
 */
import { InterviewQuestion } from '@/types/interview';

export const HISTORY_QUESTIONS: InterviewQuestion[] = [
  /* ---------------- Branching & History (15) ---------------- */
  {
    id: 'git.interview.branch-concept',
    category: 'branching',
    difficulty: 'beginner',
    type: 'conceptual',
    question: {
      en: 'Explain branches to a junior developer in thirty seconds.',
      bn: 'জুনিয়র ডেভেলপারকে ত্রিশ সেকেন্ডে ব্রাঞ্চ বোঝান।',
    },
    shortAnswer: {
      en: 'A branch is a lightweight movable pointer to one commit. New commits advance whichever branch you have checked out.',
      bn: 'ব্রাঞ্চ হলো একটি কমিটের দিকে হালকা চলমান পয়েন্টার। চেক-আউট যে ব্রাঞ্চে, নতুন কমিট সেটিকে এগিয়ে নেয়।',
    },
    explanation: {
      en: 'That is the whole mechanism: creating a branch writes a 41-byte file with a hash, switching moves HEAD to it, committing advances it. Parallel timelines, isolated experiments, and safe code review all fall out of this one tiny pointer.',
      bn: 'পুরো কৌশল এটাই: ব্রাঞ্চ তৈরি হ্যাশসহ ৪১-বাইট ফাইল লেখে, সুইচ HEAD সেখানে নেয়, কমিট এগিয়ে নেয়। সমান্তরাল টাইমলাইন, আলাদা পরীক্ষা ও নিরাপদ কোড রিভিউ এই একটি ক্ষুদ্র পয়েন্টার থেকে আসে।',
    },
    interviewTip: {
      en: 'Lead with the pointer definition, then give the file analogy second. Precision first, intuition second.',
      bn: 'পয়েন্টার সংজ্ঞা দিয়ে শুরু, তারপর ফাইল উপমা। আগে নির্ভুলতা, পরে অনুভূতি।',
    },
    commonMistake: {
      en: 'Describing branches as folders or copies, which makes every follow-up about merging and rebasing harder.',
      bn: 'ব্রাঞ্চকে ফোল্ডার বা কপি বর্ণনা, যা মার্জ ও রিবেসের প্রতিটি ফলো-আপ কঠিন করে।',
    },
    relatedCommands: ['git.branch', 'git.switch'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.create-feature-branch'],
    relatedInternals: ['git.internals.branch-references'],
    tags: ['branch', 'pointer', 'basics'],
    order: 31,
  },
  {
    id: 'git.interview.head-concept',
    category: 'branching',
    difficulty: 'beginner',
    type: 'conceptual',
    question: {
      en: 'What does HEAD point to right now on your machine, and how would you check?',
      bn: 'মেশিনে HEAD এখন কী নির্দেশ করে, এবং কীভাবে যাচাই করবেন?',
    },
    shortAnswer: {
      en: 'Normally your checked-out branch (which points at its tip commit). git status names the branch; git log shows the commit.',
      bn: 'সাধারণত চেক-আউট ব্রাঞ্চ (যা টিপ কমিটের দিকে থাকে)। git status ব্রাঞ্চের নাম বলে; git log কমিট দেখায়।',
    },
    explanation: {
      en: 'HEAD → branch → commit is the chain you verify in two glances: status for the branch name, log for the commit it resolves to. If status instead says "detached HEAD", HEAD points straight at a commit with no branch involved.',
      bn: 'HEAD → ব্রাঞ্চ → কমিট শৃঙ্খল দুই দৃষ্টিতে যাচাই করেন: ব্রাঞ্চ নামে status, সমাধান কমিটে log। status বদলে "detached HEAD" বললে HEAD ব্রাঞ্চ ছাড়া সরাসরি কমিটে যায়।',
    },
    interviewTip: {
      en: 'Answer with the commands you would literally type — interviewers trust operators over orators.',
      bn: 'আক্ষরিক টাইপ করা কমান্ড দিয়ে উত্তর দিন — ইন্টারভিউয়াররা বক্তার চেয়ে চালককে বিশ্বাস করেন।',
    },
    commonMistake: {
      en: 'Saying HEAD "is" the latest commit — it is a pointer one step removed, and that step is the whole branching model.',
      bn: 'HEAD "হলো" সর্বশেষ কমিট বলা — এটি এক ধাপ সরানো পয়েন্টার, আর সেই ধাপই পুরো ব্রাঞ্চিং মডেল।',
    },
    relatedCommands: ['git.status', 'git.log'],
    relatedLessons: ['git.fundamentals.head'],
    relatedTroubleshooting: ['git.troubleshooting.detached-head'],
    relatedPractice: ['git.practice.command-identify-current-branch'],
    relatedInternals: ['git.internals.head-deep-dive'],
    tags: ['head', 'pointer', 'verify'],
    order: 32,
  },
  {
    id: 'git.interview.detached-head',
    category: 'branching',
    difficulty: 'intermediate',
    type: 'scenario',
    question: {
      en: 'You checked out a commit hash to inspect old code, did some work, and now git status says "detached HEAD". What happened, and how do you keep the work?',
      bn: 'পুরনো কোড দেখতে কমিট হ্যাশ চেকআউট করে কাজ করলেন, এখন git status বলে "detached HEAD"। কী ঘটেছে, কাজ কীভাবে রাখবেন?',
    },
    shortAnswer: {
      en: 'HEAD points directly at a commit with no branch, so new commits belong to nothing. Create a branch where you stand to keep them.',
      bn: 'HEAD ব্রাঞ্চ ছাড়া সরাসরি কমিটে আছে, তাই নতুন কমিট কোনোটির নয়। রাখতে যেখানে দাঁড়িয়ে সেখানে ব্রাঞ্চ তৈরি করুন।',
    },
    explanation: {
      en: 'Checking out a hash bypasses every branch pointer, so HEAD holds a raw hash. Commits still work, but switching away orphans them since no ref tracks them. git switch -c rescue names the spot instantly; alternatively note the hash from git log or reflog and branch from it later.',
      bn: 'হ্যাশ চেকআউট প্রতিটি ব্রাঞ্চ পয়েন্টার এড়িয়ে যায়, তাই HEAD-এ কাঁচা হ্যাশ থাকে। কমিট চলে, কিন্তু সরে গেলে ref ট্র্যাক না করায় এতিম হয়। git switch -c rescue সাথে সাথে জায়গার নাম দেয়; বিকল্পে git log বা reflog থেকে হ্যাশ নোট করে পরে ব্রাঞ্চ করুন।',
    },
    exampleCommand: 'git switch -c rescue',
    interviewTip: {
      en: 'Show you stay calm: detached HEAD is a normal state for inspection, dangerous only when combined with new commits.',
      bn: 'শান্ত থাকা দেখান: পরিদর্শনে ডিটাচড HEAD স্বাভাবিক অবস্থা, শুধু নতুন কমিটে বিপজ্জনক।',
    },
    commonMistake: {
      en: 'Panicking and running random resets, or assuming the work is already lost — it is all still in the object database.',
      bn: 'আতঙ্কে এলোমেলো রিসেট, বা কাজ ইতিমধ্যে হারিয়েছে ভাবা — সব অবজেক্ট ডাটাবেসে আছে।',
    },
    relatedCommands: ['git.switch', 'git.checkout', 'git.log'],
    relatedLessons: ['git.fundamentals.head'],
    relatedTroubleshooting: ['git.troubleshooting.detached-head'],
    relatedPractice: [],
    relatedInternals: ['git.internals.head-deep-dive'],
    tags: ['detached-head', 'recovery', 'branch'],
    order: 33,
  },
  {
    id: 'git.interview.merge-vs-rebase',
    category: 'branching',
    difficulty: 'intermediate',
    type: 'compare',
    question: {
      en: 'What is the difference between merge and rebase?',
      bn: 'merge ও rebase-এর মধ্যে পার্থক্য কী?',
    },
    shortAnswer: {
      en: 'Merge combines histories by creating a merge commit when necessary, while rebase replays commits onto a new base and creates rewritten commit identities.',
      bn: 'মার্জ প্রয়োজনে মার্জ কমিট তৈরি করে হিস্ট্রি একত্র করে, আর রিবেস নতুন বেসে কমিট রিপ্লে করে পুনর্লিখিত কমিট পরিচয় তৈরি করে।',
    },
    explanation: {
      en: 'Merge preserves true chronology: both lines stay visible, joined by a merge commit — honest but branchy. Rebase rewrites each commit onto the target tip, producing linear history with brand-new hashes. That rewrite is why the golden rule exists: never rebase commits others have already pulled.',
      bn: 'মার্জ সত্য কালানুক্রম সংরক্ষণ করে: উভয় লাইন দৃশ্যমান, মার্জ কমিটে যুক্ত — সৎ কিন্তু শাখাময়। রিবেস প্রতিটি কমিট টার্গেট টিপে পুনর্লেখে, একদম নতুন হ্যাশে লিনিয়ার হিস্ট্রি দেয়। এই পুনর্লেখেই গোল্ডেন রুল: অন্যরা ইতিমধ্যে পুল করা কমিট কখনো রিবেস নয়।',
    },
    exampleCommand: 'git merge feature/login   # or:  git rebase main',
    interviewTip: {
      en: 'Finish with when you would choose each: merge for shared truth, rebase for private cleanup. Judgment beats definitions.',
      bn: 'কখন কোনটি বেছে নেবেন দিয়ে শেষ করুন: শেয়ার্ড সত্যে মার্জ, ব্যক্তিগত পরিষ্কারে রিবেস। বিচার সংজ্ঞাকে হারায়।',
    },
    commonMistake: {
      en: 'Declaring one universally better — teams choose per workflow, and rebasing shared history strands collaborators.',
      bn: 'একটিকে সার্বজনীন শ্রেষ্ঠ ঘোষণা — টিম ওয়ার্কফ্লোতে বেছে নেয়, শেয়ার্ড হিস্ট্রি রিবেসে সহকর্মী আটকায়।',
    },
    relatedCommands: ['git.merge', 'git.rebase', 'git.log'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: ['git.troubleshooting.merge-conflict', 'git.troubleshooting.rebase-conflict'],
    relatedPractice: ['git.practice.merge-feature', 'git.practice.rebase-feature'],
    relatedInternals: ['git.internals.rebase-rewrites-history', 'git.internals.commit-objects'],
    tags: ['merge', 'rebase', 'compare', 'classic'],
    order: 34,
  },
  {
    id: 'git.interview.fast-forward',
    category: 'branching',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'When does a merge fast-forward, and how is that different from a true merge?',
      bn: 'মার্জ কখন ফাস্ট-ফরোয়ার্ড হয়, আর সত্য মার্জ থেকে কীভাবে আলাদা?',
    },
    shortAnswer: {
      en: 'When the target has no unique commits, Git just slides its pointer forward — no new commit. Otherwise it records a merge commit joining both lines.',
      bn: 'টার্গেটে অনন্য কমিট না থাকলে গিট পয়েন্টার এগিয়ে দেয় — নতুন কমিট নেই। নইলে উভয় লাইন যুক্ত মার্জ কমিট রেকর্ড করে।',
    },
    explanation: {
      en: 'Fast-forward is a pointer move, not a join: main simply advances to feature’s tip. A true merge creates commit M with two parents, forever recording that two lines of development converged. git log --graph makes the difference visible instantly.',
      bn: 'ফাস্ট-ফরোয়ার্ড পয়েন্টার সরণ, যুক্তি নয়: main ফিচারের টিপে এগিয়ে যায়। সত্য মার্জ দুই প্যারেন্টে M কমিট তৈরি করে, দুই উন্নয়ন লাইন একত্র চিরতরে রেকর্ড করে। git log --graph পার্থক্য সাথে সাথে দৃশ্যমান করে।',
    },
    interviewTip: {
      en: 'Sketch both cases on paper if allowed — interviewers forgive slow drawing but not hand-waving.',
      bn: 'অনুমতি থাকলে উভয় ক্ষেত্রে কাগজে আঁকুন — ধীর আঁকা ক্ষমা হয়, হাত নাড়া নয়।',
    },
    commonMistake: {
      en: 'Expecting a merge commit every time — then "losing" history that was simply fast-forwarded.',
      bn: 'প্রতিবার মার্জ কমিট আশা — তারপর ফাস্ট-ফরোয়ার্ড হওয়া হিস্ট্রি "হারানো"।',
    },
    relatedCommands: ['git.merge', 'git.log'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-fast-forward-merge'],
    relatedInternals: ['git.internals.commit-objects'],
    tags: ['merge', 'fast-forward', 'pointer'],
    order: 35,
  },
  {
    id: 'git.interview.rebase-golden-rule',
    category: 'branching',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'Why is rebasing a shared public branch potentially dangerous?',
      bn: 'শেয়ার্ড পাবলিক ব্রাঞ্চ রিবেস সম্ভাব্য বিপজ্জনক কেন?',
    },
    shortAnswer: {
      en: 'Rebase mints new commit identities, so teammates holding the old ones end up on a divergent, incompatible history.',
      bn: 'রিবেস নতুন কমিট পরিচয় তৈরি করে, তাই পুরনোগুলো ধরা সহকর্মীরা ডাইভার্জড, অসামঞ্জস্য হিস্ট্রিতে পড়েন।',
    },
    explanation: {
      en: 'Your teammates’ branches, reviews, and local work all reference the original hashes. After your rewrite, their history and the remote disagree on what "the truth" is — reconciling means painful forced updates on every side. Private branches have no audience, so rewriting them harms nobody.',
      bn: 'সহকর্মীদের ব্রাঞ্চ, রিভিউ ও লোকাল কাজ সব মূল হ্যাশ রেফারেন্স করে। পুনর্লেখের পর তাদের হিস্ট্রি ও রিমোট "সত্য" কীতে দ্বিমত হয় — মেলাতে প্রতিটি পক্ষে কষ্টকর ফোর্সড আপডেট। ব্যক্তিগত ব্রাঞ্চের দর্শক নেই, তাই পুনর্লেখে ক্ষতি নেই।',
    },
    interviewTip: {
      en: 'Name who gets hurt (teammates with old hashes) rather than reciting the rule — consequences persuade.',
      bn: 'নিয়ম আবৃত্তির বদলে কে আহত হয় নাম বলুন (পুরনো হ্যাশধারী সহকর্মী) — পরিণতি প্ররোচিত করে।',
    },
    commonMistake: {
      en: 'Rebasing main or a shared feature branch "to keep it clean", then force-pushing colleagues into a mess.',
      bn: '"পরিষ্কারে" main বা শেয়ার্ড ফিচার ব্রাঞ্চ রিবেস করে ফোর্স-পুশে সহকর্মীদের জটে ফেলা।',
    },
    relatedCommands: ['git.rebase', 'git.push'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: ['git.troubleshooting.rebase-conflict', 'git.troubleshooting.force-push'],
    relatedPractice: ['git.practice.command-rebase-rewrites-history'],
    relatedInternals: ['git.internals.rebase-rewrites-history'],
    tags: ['rebase', 'golden-rule', 'shared-history'],
    order: 36,
  },
  {
    id: 'git.interview.switch-vs-checkout',
    category: 'branching',
    difficulty: 'beginner',
    type: 'compare',
    question: {
      en: 'What is the difference between git switch and git checkout for changing branches?',
      bn: 'ব্রাঞ্চ বদলে git switch ও git checkout-এর মধ্যে পার্থক্য কী?',
    },
    shortAnswer: {
      en: 'git switch does one thing — move between branches — while git checkout is an overloaded legacy command that also restores files and can silently discard work.',
      bn: 'git switch একটি কাজ করে — ব্রাঞ্চে যাওয়া — আর git checkout ওভারলোডেড পুরনো কমান্ড যা ফাইলও পুনরুদ্ধার করে ও নীরবে কাজ মুছে দিতে পারে।',
    },
    explanation: {
      en: 'checkout’s double duty (switch branches AND restore files) caused real data loss: git checkout -- file discards edits without asking. Git split the job — switch for branches, restore for files — so each command’s danger is explicit and separate.',
      bn: 'checkout-এর দ্বৈত দায়িত্ব (ব্রাঞ্চ বদল ও ফাইল পুনরুদ্ধার) আসল ডেটা ক্ষতি ঘটিয়েছে: git checkout -- file না জিজ্ঞেসে এডিট মুছে। গিট কাজ ভাগ করেছে — ব্রাঞ্চে switch, ফাইলে restore — যাতে প্রতিটি কমান্ডের বিপদ স্পষ্ট ও আলাদা।',
    },
    interviewTip: {
      en: 'Recommend switch for all new work — preferring the safe modern tool shows current habits.',
      bn: 'সব নতুন কাজে switch সুপারিশ করুন — নিরাপদ আধুনিক টুল পছন্দ বর্তমান অভ্যাস দেখায়।',
    },
    commonMistake: {
      en: 'Copy-pasting checkout -- <file> from old tutorials without realizing it destroys uncommitted edits.',
      bn: 'পুরনো টিউটোরিয়াল থেকে checkout -- <file> কপি-পেস্ট, না বুঝে এটি আনকমিটেড এডিট ধ্বংস করে।',
    },
    relatedCommands: ['git.switch', 'git.checkout', 'git.restore'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.switch-branches'],
    relatedInternals: [],
    tags: ['switch', 'checkout', 'compare', 'safety'],
    order: 37,
  },
  {
    id: 'git.interview.branch-vs-tag',
    category: 'branching',
    difficulty: 'intermediate',
    type: 'compare',
    question: {
      en: 'What is the difference between a branch and a tag?',
      bn: 'ব্রাঞ্চ ও ট্যাগের মধ্যে পার্থক্য কী?',
    },
    shortAnswer: {
      en: 'A branch is a movable pointer that advances with new commits; a tag is a fixed, human-readable name pinned to one commit — typically a release.',
      bn: 'ব্রাঞ্চ হলো চলমান পয়েন্টার যা নতুন কমিটে এগোয়; ট্যাগ হলো এক কমিটে পিন করা স্থির, মানব-পাঠযোগ্য নাম — সাধারণত রিলিজ।',
    },
    explanation: {
      en: 'Branches are for lines of development that grow; tags are milestones that must not move (v1.0.0 should mean the same bytes forever). Annotated tags even carry their own message, tagger, and checksum. Deleting and recreating a release tag is a trust violation — that is the real distinction.',
      bn: 'ব্রাঞ্চ বাড়তে থাকা উন্নয়ন লাইনে; ট্যাগ মাইলফলকে যা সরানো উচিত নয় (v1.0.0 মানে চিরকাল একই বাইট)। অ্যানোটেটেড ট্যাগে নিজস্ব বার্তা, ট্যাগার ও চেকসামও থাকে। রিলিজ ট্যাগ মুছে নতুন বানানো বিশ্বাসভঙ্গ — এটাই আসল পার্থক্য।',
    },
    interviewTip: {
      en: 'End with releases: "branches grow, tags mark" is the quotable summary.',
      bn: 'রিলিজ দিয়ে শেষ করুন: "ব্রাঞ্চ বাড়ে, ট্যাগ চিহ্নিত করে" উদ্ধৃতযোগ্য সারাংশ।',
    },
    commonMistake: {
      en: 'Using a branch name as a release marker — branches move, so v1.0-on-a-branch silently changes meaning.',
      bn: 'রিলিজ চিহ্নে ব্রাঞ্চ নাম — ব্রাঞ্চ সরে, তাই v1.0-অন-ব্রাঞ্চ নীরবে অর্থ বদলায়।',
    },
    relatedCommands: ['git.branch', 'git.log'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: [],
    relatedPractice: [],
    relatedInternals: ['git.internals.annotated-tags', 'git.internals.lightweight-vs-annotated-tags'],
    tags: ['branch', 'tag', 'compare', 'release'],
    order: 38,
  },
  {
    id: 'git.interview.commit-parents',
    category: 'branching',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'How many parents can a commit have, and what does each case mean?',
      bn: 'কমিটের কয়টি প্যারেন্ট থাকতে পারে, প্রতিটি ক্ষেত্রে মানে কী?',
    },
    shortAnswer: {
      en: 'Zero (root commit starting history), one (ordinary commit continuing a line), or two-plus (a merge joining lines).',
      bn: 'শূন্য (হিস্ট্রি শুরু করা রুট কমিট), এক (লাইন চালিয়ে যাওয়া সাধারণ কমিট), বা দুই-বেশি (লাইন যুক্ত করা মার্জ)।',
    },
    explanation: {
      en: 'Parent count classifies commits completely: roots begin graphs, single-parent commits extend them, and multi-parent commits are merges recording a join. Tools like git log --first-parent exploit this — showing only first parents renders the "main line" of history.',
      bn: 'প্যারেন্ট সংখ্যা কমিট সম্পূর্ণ শ্রেণিবদ্ধ করে: রুট গ্রাফ শুরু করে, এক-প্যারেন্ট বাড়ায়, বহু-প্যারেন্ট মার্জ যুক্তি রেকর্ড করে। git log --first-parent-এর মতো টুল এটাই কাজে লাগায় — শুধু ফার্স্ট প্যারেন্ট দেখিয়ে হিস্ট্রির "মূল লাইন" রেন্ডার করে।',
    },
    interviewTip: {
      en: 'Mention --first-parent unprompted — it proves you have actually navigated messy real histories.',
      bn: 'না জিজ্ঞেসেই --first-parent উল্লেখ করুন — এতে প্রমাণ হয় সত্যিকারের অগোছালো হিস্ট্রি ঘুরেছেন।',
    },
    commonMistake: {
      en: 'Assuming every commit has exactly one parent — then being unable to explain what a merge commit even is.',
      bn: 'প্রতিটি কমিটের ঠিক এক প্যারেন্ট ভাবা — তারপর মার্জ কমিট কী ব্যাখ্যা করতে না পারা।',
    },
    relatedCommands: ['git.log', 'git.show'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-interpret-graph'],
    relatedInternals: ['git.internals.commit-objects', 'git.internals.parent-relationships'],
    tags: ['commit', 'parents', 'merge'],
    order: 39,
  },
  {
    id: 'git.interview.when-to-branch',
    category: 'branching',
    difficulty: 'beginner',
    type: 'scenario',
    question: {
      en: 'You need to fix an urgent production bug while a half-finished feature sits uncommitted. What is the safe sequence?',
      bn: 'অর্ধ-সমাপ্ত ফিচার আনকমিটেড থাকতে জরুরি প্রোডাকশন বাগ ঠিক করতে হবে। নিরাপদ ক্রম কী?',
    },
    shortAnswer: {
      en: 'Commit or stash the work in progress, switch to main, branch a hotfix, fix, test, merge, and push — then return to the feature.',
      bn: 'চলমান কাজ কমিট বা স্ট্যাশ করুন, main-এ যান, হটফিক্স ব্রাঞ্চ করুন, ঠিক করুন, পরীক্ষা করুন, মার্জ ও পুশ করুন — তারপর ফিচারে ফিরুন।',
    },
    explanation: {
      en: 'Switching with a dirty tree risks carrying half-done edits into the hotfix or blocking the switch entirely. Parking the work first (a WIP commit you will amend, or a stash) keeps both efforts isolated and reviewable.',
      bn: 'নোংরা ট্রিতে সুইচ অর্ধ-সমাপ্ত এডিট হটফিক্সে টেনে নিতে বা সুইচ আটকাতে পারে। কাজ আগে পার্ক করা (সংশোধন করা WIP কমিট বা স্ট্যাশ) উভয় প্রচেষ্টা আলাদা ও পর্যালোচনাযোগ্য রাখে।',
    },
    interviewTip: {
      en: 'Narrate it as habit, not heroics: "I always park work before switching context." Calm process wins.',
      bn: 'বীরত্ব নয়, অভ্যাসে বলুন: "প্রসঙ্গ বদলের আগে সবসময় কাজ পার্ক করি।" শান্ত প্রক্রিয়া জেতে।',
    },
    commonMistake: {
      en: 'Fixing the bug on top of uncommitted feature work, then untangling the two in one messy commit.',
      bn: 'আনকমিটেড ফিচার কাজের ওপর বাগ ঠিক করে একটি অগোছালো কমিটে দুটো খোলা।',
    },
    relatedCommands: ['git.switch', 'git.commit', 'git.branch'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.feature-branch-workflow'],
    relatedInternals: [],
    tags: ['branch', 'hotfix', 'workflow', 'scenario'],
    order: 40,
  },
  {
    id: 'git.interview.merge-commit-anatomy',
    category: 'branching',
    difficulty: 'advanced',
    type: 'graph',
    question: {
      en: 'This merge commit M has parents C3 and F2. Which side is the "mainline", and how would --first-parent display it?',
      bn: 'এই মার্জ কমিট M-এর প্যারেন্ট C3 ও F2। কোন পক্ষ "mainline", এবং --first-parent কীভাবে দেখাবে?',
    },
    shortAnswer: {
      en: 'The first parent (C3, the branch you were on) is the mainline; --first-parent walks only first parents, hiding the merged-in feature line.',
      bn: 'ফার্স্ট প্যারেন্ট (C3, যে ব্রাঞ্চে ছিলেন) mainline; --first-parent শুধু ফার্স্ট প্যারেন্ট হাঁটে, মার্জড ফিচার লাইন লুকিয়ে।',
    },
    explanation: {
      en: 'Merge order matters: the checked-out branch becomes parent #1, the merged branch parent #2. First-parent traversal therefore tells the story "as main experienced it", which is why release notes and mainline graphs use it.',
      bn: 'মার্জ ক্রম গুরুত্বপূর্ণ: চেক-আউট ব্রাঞ্চ প্যারেন্ট #1 হয়, মার্জড ব্রাঞ্চ #2। ফার্স্ট-প্যারেন্ট ট্রাভার্সাল তাই "main যেমন অনুভব করেছে" গল্প বলে, রিলিজ নোট ও mainline গ্রাফ এটাই ব্যবহার করে।',
    },
    interviewTip: {
      en: 'Point at the graph: "C3 was checked out, so it is parent one." Tracing beats reciting.',
      bn: 'গ্রাফে দেখান: "C3 চেক-আউট ছিল, তাই প্যারেন্ট এক।" মুখস্থের চেয়ে ট্রেস জেতে।',
    },
    commonMistake: {
      en: 'Treating both parents as equal and missing why --first-parent hides the feature line.',
      bn: 'উভয় প্যারেন্ট সমান ধরে --first-parent কেন ফিচার লাইন লুকায় তা মিস করা।',
    },
    stateSnapshot: {
      files: [
        { name: 'README.md', workStatus: 'clean', staged: false },
        { name: 'app.js', workStatus: 'clean', staged: false },
        { name: 'package.json', workStatus: 'clean', staged: false },
      ],
      commits: [
        { id: 'C1', message: 'Initial commit', parents: [] },
        { id: 'C2', message: 'Homepage copy', parents: ['C1'] },
        { id: 'C3', message: 'Release prep', parents: ['C2'] },
        { id: 'F1', message: 'Add login form', parents: ['C2'] },
        { id: 'F2', message: 'Validate login input', parents: ['F1'] },
        { id: 'M', message: "Merge branch 'feature'", parents: ['C3', 'F2'] },
      ],
      localBranches: { main: 'M', feature: 'F2' },
      remoteTracking: { 'origin/main': 'C3' },
      serverBranches: { main: 'M' },
      serverOnly: [],
      currentBranch: 'main',
      seq: 10,
    },
    snapshotView: 'graph',
    options: [
      { id: 'a', label: 'C3 is first parent (mainline); --first-parent hides the F1–F2 line', correct: true },
      { id: 'b', label: 'F2 is first parent (mainline); --first-parent hides C1–C3', correct: false },
      { id: 'c', label: 'Both parents are equal; --first-parent shows everything', correct: false },
      { id: 'd', label: 'M has no parents; it starts a new history', correct: false },
    ],
    relatedCommands: ['git.log', 'git.merge'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-interpret-graph'],
    relatedInternals: ['git.internals.commit-objects', 'git.internals.commit-graphs'],
    tags: ['merge', 'parents', 'first-parent', 'graph'],
    order: 41,
  },
  {
    id: 'git.interview.divergence-meaning',
    category: 'branching',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'git status says your branch has "diverged" from origin/main. What does that actually mean?',
      bn: 'git status বলে ব্রাঞ্চ origin/main থেকে "diverged" করেছে। আসলে মানে কী?',
    },
    shortAnswer: {
      en: 'Both sides gained commits the other lacks: you are ahead by some and behind by others. Neither fast-forward is possible.',
      bn: 'উভয় পক্ষে অন্যের নেই এমন কমিট এসেছে: কিছুতে এগিয়ে, কিছুতে পিছিয়ে। কোনো ফাস্ট-ফরোয়ার্ড সম্ভব নয়।',
    },
    explanation: {
      en: 'Ahead-only means "push to catch the remote up"; behind-only means "pull to catch yourself up". Diverged means both are true at once, so you must choose: merge (preserving both lines) or rebase (replaying yours atop theirs).',
      bn: 'শুধু এগিয়ে মানে "রিমোট ধরতে পুশ"; শুধু পিছিয়ে মানে "নিজে ধরতে পুল"। ডাইভার্জড মানে দুটোই একসাথে সত্য, তাই বেছে নিতে হবে: মার্জ (উভয় লাইন সংরক্ষণ) বা রিবেস (তাদের ওপর আপনারটা রিপ্লে)।',
    },
    interviewTip: {
      en: 'Translate the jargon into counts: "ahead 2, behind 1" is clearer than "diverged" and shows status literacy.',
      bn: 'পরিভাষা সংখ্যায় অনুবাদ করুন: "ahead 2, behind 1" "diverged"-এর চেয়ে স্পষ্ট ও status সাক্ষরতা দেখায়।',
    },
    commonMistake: {
      en: 'Force-pushing to "fix" divergence on a shared branch — erasing the teammates’ side of the fork.',
      bn: 'শেয়ার্ড ব্রাঞ্চে ডাইভারজেন্স "ঠিক" করতে ফোর্স-পুশ — ফোর্কের সহকর্মীদের পক্ষ মোছা।',
    },
    relatedCommands: ['git.status', 'git.fetch', 'git.pull'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: ['git.troubleshooting.diverged'],
    relatedPractice: [],
    relatedInternals: ['git.internals.dag-structure'],
    tags: ['divergence', 'ahead-behind', 'status'],
    order: 42,
  },
  {
    id: 'git.interview.conflict-why',
    category: 'branching',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'Why do merge conflicts happen, and what is Git actually asking you to decide?',
      bn: 'মার্জ কনফ্লিক্ট কেন হয়, এবং গিট আসলে কী সিদ্ধান্ত চায়?',
    },
    shortAnswer: {
      en: 'Both sides changed the same lines since their common ancestor, so no algorithm can safely choose. Git asks a human to compose the correct result.',
      bn: 'কমন অ্যানসেস্টরের পর উভয় পক্ষ একই লাইন বদলেছে, তাই কোনো অ্যালগরিদম নিরাপদে বেছে নিতে পারে না। গিট মানুষকে সঠিক ফল রচনা করতে বলে।',
    },
    explanation: {
      en: 'Git auto-merges everything it can prove safe: different lines, or identical changes on both sides. Conflicts mark exactly the hunks where automation ran out of knowledge — your job is to read both intents, write the true outcome, remove the markers, and stage the resolution.',
      bn: 'গিট নিরাপদ প্রমাণ সব স্বয়ং-মার্জ করে: ভিন্ন লাইন, বা উভয় পক্ষে একই পরিবর্তন। কনফ্লিক্ট ঠিক সেই হাঙ্ক চিহ্নিত করে যেখানে অটোমেশন জ্ঞান শেষ — কাজ উভয় উদ্দেশ্য পড়া, সত্য ফল লেখা, মার্কার সরানো ও সমাধান স্টেজ করা।',
    },
    interviewTip: {
      en: 'Emphasize "same lines since the common ancestor" — precision about the trigger beats generic conflict talk.',
      bn: '"কমন অ্যানসেস্টরের পর একই লাইন" জোর দিন — ট্রিগারে নির্ভুলতা সাধারণ কনফ্লিক্ট কথাকে হারায়।',
    },
    commonMistake: {
      en: 'Treating conflict markers as corruption to delete blindly — or committing files with markers still inside.',
      bn: 'কনফ্লিক্ট মার্কারকে অন্ধভাবে মুছতে দূষণ ভাবা — বা মার্কারসহ ফাইল কমিট করা।',
    },
    relatedCommands: ['git.merge', 'git.status', 'git.add'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: ['git.troubleshooting.merge-conflict'],
    relatedPractice: ['git.practice.merge-conflict-flow'],
    relatedInternals: [],
    tags: ['conflict', 'merge', 'markers'],
    order: 43,
  },
  {
    id: 'git.interview.ancestry-notation',
    category: 'branching',
    difficulty: 'advanced',
    type: 'conceptual',
    question: {
      en: 'What do HEAD~3 and M^2 mean, and when would you use each?',
      bn: 'HEAD~3 ও M^2 মানে কী, প্রতিটি কখন ব্যবহার করবেন?',
    },
    shortAnswer: {
      en: 'HEAD~3 walks three first-parent steps back from HEAD; M^2 selects the second parent of merge M (the merged-in side).',
      bn: 'HEAD~3 HEAD থেকে তিন ফার্স্ট-প্যারেন্ট ধাপ পেছনে হাঁটে; M^2 মার্জ M-এর দ্বিতীয় প্যারেন্ট (মার্জড পক্ষ) বেছে নেয়।',
    },
    explanation: {
      en: 'Tilde counts generations along first parents — perfect for "three commits ago on this line". Caret selects which parent of a merge to follow — essential for diffing or reverting exactly the merged-in side (git revert -m 1 uses the same numbering).',
      bn: 'টিল্ড ফার্স্ট প্যারেন্টে প্রজন্ম গুনে — "এই লাইনে তিন কমিট আগে" উপযুক্ত। কaret মার্জের কোন প্যারেন্ট অনুসরণ করবে বেছে নেয় — মার্জড পক্ষের ঠিক diff বা revert-এ অপরিহার্য (git revert -m 1 একই সংখ্যায়ন ব্যবহার করে)।',
    },
    interviewTip: {
      en: 'Give one use each: ~ for "ago", ^ for "which side of a merge". Interviewers test whether notation is muscle memory.',
      bn: 'প্রতিটির একটি ব্যবহার দিন: ~ "আগে"-তে, ^ "মার্জের কোন পক্ষে"। নোটেশন পেশী-স্মৃতি কিনা ইন্টারভিউয়াররা পরীক্ষা করেন।',
    },
    commonMistake: {
      en: 'Using HEAD~2 to mean "the merge source" — tilde never switches sides; only ^ selects parents.',
      bn: 'HEAD~2 দিয়ে "মার্জ উৎস" বোঝানো — টিল্ড কখনো পক্ষ বদলায় না; শুধু ^ প্যারেন্ট বেছে নেয়।',
    },
    relatedCommands: ['git.show', 'git.log', 'git.revert'],
    relatedLessons: ['git.fundamentals.commit'],
    relatedTroubleshooting: [],
    relatedPractice: [],
    relatedInternals: ['git.internals.parent-relationships'],
    tags: ['ancestry', 'notation', 'advanced'],
    order: 44,
  },
  {
    id: 'git.interview.when-not-to-branch',
    category: 'branching',
    difficulty: 'beginner',
    type: 'scenario',
    question: {
      en: 'A one-line typo fix on a solo project — branch or commit straight to main?',
      bn: 'একক প্রজেক্টে এক-লাইন বানান ফিক্স — ব্রাঞ্চ না সরাসরি main-এ কমিট?',
    },
    shortAnswer: {
      en: 'Commit straight to main. Branches pay off for review, risk, or parallel work — none of which exist here.',
      bn: 'সরাসরি main-এ কমিট করুন। ব্রাঞ্চ রিভিউ, ঝুঁকি বা সমান্তরাল কাজে লাভ দেয় — এখানে কোনোটিই নেই।',
    },
    explanation: {
      en: 'Branching discipline means matching ceremony to risk: a trivial solo fix gains nothing from a pull request cycle. Save branches (and reviews) for work that benefits from isolation, discussion, or rollback safety.',
      bn: 'ব্রাঞ্চিং শৃঙ্খলা মানে ঝুঁকিতে আচার মেলানো: তুচ্ছ একক ফিক্সে পুল রিকোয়েস্ট চক্রে লাভ নেই। ব্রাঞ্চ (ও রিভিউ) রাখুন যে কাজে আলাদাকরণ, আলোচনা বা রোলব্যাক নিরাপত্তা লাভ দেয়।',
    },
    interviewTip: {
      en: 'Showing restraint impresses more than process maximalism — judgment about when NOT to branch is senior thinking.',
      bn: 'সংযম দেখানো প্রক্রিয়া সর্বোচ্চতাবাদের চেয়ে মুগ্ধ করে — কখন ব্রাঞ্চ নয় বিচার সিনিয়র চিন্তা।',
    },
    commonMistake: {
      en: 'Branching for everything including typo fixes, then drowning in stale branches nobody merges.',
      bn: 'বানান ফিক্সসহ সবকিছুতে ব্রাঞ্চ করে কেউ মার্জ না করা পুরনো ব্রাঞ্চে ডোবা।',
    },
    relatedCommands: ['git.commit', 'git.branch'],
    relatedLessons: ['git.fundamentals.branch'],
    relatedTroubleshooting: [],
    relatedPractice: [],
    relatedInternals: [],
    tags: ['branch', 'judgment', 'workflow'],
    order: 45,
  },
  /* ---------------- Remote & Collaboration (10) ---------------- */
  {
    id: 'git.interview.origin-meaning',
    category: 'remote',
    difficulty: 'beginner',
    type: 'conceptual',
    question: {
      en: 'What is "origin", and is it special to Git?',
      bn: '"origin" কী, এবং এটি কি গিটে বিশেষ?',
    },
    shortAnswer: {
      en: 'Origin is just the default nickname for the remote you cloned from — a convention, not a keyword. You could rename it freely.',
      bn: 'Origin শুধু ক্লোন করা রিমোটের ডিফল্ট ডাকনাম — প্রচলন, কি-ওয়ার্ড নয়। ইচ্ছামতো পুনর্নাম করা যায়।',
    },
    explanation: {
      en: 'git clone registers the source URL under the name origin out of courtesy. Remotes are an arbitrary name→URL map (git remote -v proves it), and teams routinely add upstream, staging, or teammate remotes alongside it.',
      bn: 'git clone সৌজন্যে উৎস URL origin নামে নিবন্ধন করে। রিমোট হলো ইচ্ছামতো নাম→URL ম্যাপ (git remote -v প্রমাণ করে), টিম নিয়মিত upstream, staging বা সহকর্মী রিমোট পাশে যোগ করে।',
    },
    interviewTip: {
      en: '"Convention, not keyword" is the whole answer in four words — then prove it with git remote -v.',
      bn: '"প্রচলন, কি-ওয়ার্ড নয়" চার শব্দে পুরো উত্তর — তারপর git remote -v দিয়ে প্রমাণ করুন।',
    },
    commonMistake: {
      en: 'Treating origin as a magic word Git requires — then freezing when a repo uses a different remote name.',
      bn: 'origin-কে গিটের জাদু শব্দ ভাবা — ভিন্ন রিমোট নামের রেপোতে জমে যাওয়া।',
    },
    relatedCommands: ['git.remote', 'git.clone'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: ['git.troubleshooting.wrong-remote'],
    relatedPractice: ['git.practice.command-connect-remote'],
    relatedInternals: [],
    tags: ['origin', 'remote', 'convention'],
    order: 46,
  },
  {
    id: 'git.interview.upstream-meaning',
    category: 'remote',
    difficulty: 'beginner',
    type: 'conceptual',
    question: {
      en: 'What does "upstream" mean, in both its common uses?',
      bn: 'উভয় সাধারণ ব্যবহারে "upstream" মানে কী?',
    },
    shortAnswer: {
      en: 'Usually the original project your fork tracks (a remote nickname), or the remote branch your local branch follows (its tracking relationship).',
      bn: 'সাধারণত মূল প্রজেক্ট যা ফোর্ক ট্র্যাক করে (রিমোট ডাকনাম), বা রিমোট ব্রাঞ্চ যা লোকাল ব্রাঞ্চ অনুসরণ করে (ট্র্যাকিং সম্পর্ক)।',
    },
    explanation: {
      en: 'In fork workflows, git remote add upstream <original-url> lets you fetch the source project. Separately, git push -u sets "the upstream of main to origin/main" — the tracking link that lets bare git pull and git push work. Same word, two relationships: project-level and branch-level.',
      bn: 'ফোর্ক ওয়ার্কফ্লোতে git remote add upstream <original-url> উৎস প্রজেক্ট fetch করতে দেয়। আলাদাভাবে, git push -u "main-এর upstream origin/main-এ" সেট করে — ট্র্যাকিং লিঙ্ক যা খালি git pull ও git push চালায়। এক শব্দ, দুই সম্পর্ক: প্রজেক্ট-স্তর ও ব্রাঞ্চ-স্তর।',
    },
    interviewTip: {
      en: 'Disambiguate unprompted ("there are two meanings...") — precision under ambiguity is exactly what senior interviews probe.',
      bn: 'না জিজ্ঞেসেই দ্ব্যর্থতা দূর করুন ("দুটি অর্থ আছে...") — অস্পষ্টতায় নির্ভুলতা সিনিয়র ইন্টারভিউ ঠিক এটাই খোঁজে।',
    },
    commonMistake: {
      en: 'Using upstream to mean origin always — then misreading every fork-workflow instruction.',
      bn: 'সবসময় upstream মানে origin ব্যবহার — তারপর প্রতিটি ফোর্ক-ওয়ার্কফ্লো নির্দেশ ভুল পড়া।',
    },
    relatedCommands: ['git.remote', 'git.fetch', 'git.push'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-origin-vs-upstream'],
    relatedInternals: [],
    tags: ['upstream', 'fork', 'tracking'],
    order: 47,
  },
  {
    id: 'git.interview.tracking-branches',
    category: 'remote',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'What is origin/main, and how is it different from both main and the remote’s main?',
      bn: 'origin/main কী, এবং main ও রিমোটের main উভয় থেকে কীভাবে আলাদা?',
    },
    shortAnswer: {
      en: 'origin/main is your local memory of where the remote’s main was at last fetch. Your main moves when you commit; the remote’s moves when anyone pushes.',
      bn: 'origin/main হলো শেষ fetch-এ রিমোটের main কোথায় ছিল তার লোকাল স্মৃতি। কমিটে আপনার main সরে; যে কেউ পুশ করলে রিমোটের main সরে।',
    },
    explanation: {
      en: 'Three pointers share one name: your main (moves on commit), origin/main (moves on fetch/push), and the remote’s actual main (moves on anyone’s push). git status "behind/ahead" compares your main against your memory — which is why fetching first can change the message without touching your work.',
      bn: 'তিনটি পয়েন্টার এক নাম ভাগ করে: আপনার main (কমিটে সরে), origin/main (fetch/push-এ সরে), রিমোটের আসল main (যেকোনো পুশে সরে)। git status "behind/ahead" main-কে স্মৃতির সাথে তুলনা করে — তাই আগে fetch বার্তা বদলাতে পারে কাজ না ছুঁয়ে।',
    },
    interviewTip: {
      en: 'Name all three explicitly — most candidates conflate at least two, so separation stands out.',
      bn: 'তিনটি স্পষ্ট নাম বলুন — বেশিরভাগ প্রার্থী অন্তত দুটি গুলিয়ে ফেলে, তাই আলাদা করা দাঁড়ায়।',
    },
    commonMistake: {
      en: 'Reading origin/main as live remote state — it can be arbitrarily stale until you fetch.',
      bn: 'origin/main-কে লাইভ রিমোট অবস্থা পড়া — fetch না করা পর্যন্ত ইচ্ছামতো পুরনো হতে পারে।',
    },
    relatedCommands: ['git.fetch', 'git.status'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: ['git.troubleshooting.behind-remote'],
    relatedPractice: ['git.practice.fetch-changes'],
    relatedInternals: ['git.internals.remote-tracking-references'],
    tags: ['tracking', 'origin/main', 'fetch'],
    order: 48,
  },
  {
    id: 'git.interview.fetch-workflow',
    category: 'remote',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'Before starting work each morning, what is the safest first sync step?',
      bn: 'প্রতিদিন সকালে কাজ শুরুর আগে নিরাপদ প্রথম সিঙ্ক ধাপ কী?',
    },
    shortAnswer: {
      en: 'git fetch — refresh your picture of the remote without moving anything, then decide how to integrate.',
      bn: 'git fetch — কিছু না সরিয়ে রিমোটের ছবি রিফ্রেশ করুন, তারপর কীভাবে একীভূত করবেন সিদ্ধান্ত নিন।',
    },
    explanation: {
      en: 'Fetching gathers information and changes nothing: no merges, no rebases, no surprises. Reading git log origin/main next tells you whether a fast-forward pull, a careful merge, or waiting is right.',
      bn: 'Fetch তথ্য সংগ্রহ করে কিছু বদলায় না: মার্জ নেই, রিবেস নেই, চমক নেই। পরে git log origin/main পড়ে বলে ফাস্ট-ফরোয়ার্ড পুল, সতর্ক মার্জ, না অপেক্ষা ঠিক।',
    },
    interviewTip: {
      en: 'Frame it as a habit, not a command — "I fetch before I decide anything" shows process maturity.',
      bn: 'কমান্ড নয়, অভ্যাসে বলুন — "কিছু সিদ্ধান্তের আগে fetch করি" প্রক্রিয়া পরিপক্কতা দেখায়।',
    },
    commonMistake: {
      en: 'Pulling blindly first thing and inheriting a surprise merge on top of yesterday’s unfinished work.',
      bn: 'প্রথমে অন্ধ পুল করে গতকালের অসমাপ্ত কাজের ওপর চমক মার্জ পাওয়া।',
    },
    options: [
      { id: 'a', label: 'git fetch, then inspect before integrating', correct: true },
      { id: 'b', label: 'git pull --rebase immediately', correct: false },
      { id: 'c', label: 'git push to test the connection', correct: false },
      { id: 'd', label: 'git clone again fresh', correct: false },
    ],
    relatedCommands: ['git.fetch', 'git.log'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: [],
    relatedPractice: [],
    relatedInternals: [],
    tags: ['fetch', 'habit', 'morning-routine'],
    order: 49,
  },
  {
    id: 'git.interview.pull-hygiene',
    category: 'remote',
    difficulty: 'intermediate',
    type: 'scenario',
    question: {
      en: 'You have uncommitted changes and need teammates’ updates urgently. What is the safe sequence, and why not just pull?',
      bn: 'আনকমিটেড পরিবর্তন আছে ও সহকর্মীদের আপডেট জরুরি দরকার। নিরাপদ ক্রম কী, শুধু পুল কেন নয়?',
    },
    shortAnswer: {
      en: 'Commit or stash first, then fetch, review, and pull. Pulling over dirty files risks a conflicted merge tangled with unfinished work.',
      bn: 'আগে কমিট বা স্ট্যাশ, তারপর fetch, পর্যালোচনা ও পুল। নোংরা ফাইলে পুল অসমাপ্ত কাজে জটানো কনফ্লিক্ট মার্জের ঝুঁকি নেয়।',
    },
    explanation: {
      en: 'Pull refuses or complicates when the tree is dirty because it must merge into files you are mid-edit on. Parking work first (commit, or stash for truly temporary shelter) gives the merge a clean, reviewable base — and makes any conflict purely about the incoming change.',
      bn: 'ট্রি নোংরা থাকলে পুল প্রত্যাখ্যান বা জটিল করে কারণ মাঝ-এডিট ফাইলে মার্জ করতে হয়। আগে কাজ পার্ক (কমিট, বা সত্যিই অস্থায়ী আশ্রয়ে স্ট্যাশ) করলে মার্জ পরিষ্কার, পর্যালোচনাযোগ্য বেস পায় — কনফ্লিক্ট খাঁটি আগত পরিবর্তনে হয়।',
    },
    interviewTip: {
      en: 'Say "stash is a shelf, not storage" if you mention it — interviewers smile at precise stash framing.',
      bn: 'উল্লেখ করলে বলুন "স্ট্যাশ তাক, স্টোরেজ নয়" — নির্ভুল স্ট্যাশ বর্ণনায় ইন্টারভিউয়াররা হাসেন।',
    },
    commonMistake: {
      en: 'git stash as a junk drawer — stashes with no message rot until nobody dares touch them.',
      bn: 'জঞ্জাল ড্রয়ার হিসেবে git stash — বার্তাহীন স্ট্যাশ পচে যতক্ষণ কেউ ছুঁতে সাহস না পায়।',
    },
    relatedCommands: ['git.pull', 'git.fetch', 'git.commit'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: ['git.troubleshooting.pull-conflict'],
    relatedPractice: [],
    relatedInternals: [],
    tags: ['pull', 'stash', 'dirty-tree', 'scenario'],
    order: 50,
  },
  {
    id: 'git.interview.fork-workflow',
    category: 'remote',
    difficulty: 'beginner',
    type: 'choice',
    question: {
      en: 'You want to contribute to an open-source repo you cannot push to. What is the correct sequence?',
      bn: 'পুশ করতে পারেন না এমন ওপেন-সোর্স রেপোতে অবদান চান। সঠিক ক্রম কী?',
    },
    shortAnswer: {
      en: 'Fork on GitHub, clone your fork, branch, push to your fork, then open a pull request to the original.',
      bn: 'গিটহাবে ফোর্ক করুন, ফোর্ক ক্লোন করুন, ব্রাঞ্চ করুন, ফোর্কে পুশ করুন, তারপর মূলে পুল রিকোয়েস্ট খুলুন।',
    },
    explanation: {
      en: 'Forking gives you a pushable copy under your account; cloning brings it local; the pull request proposes your branch back to the original. You never need permission on the original — only a good proposal.',
      bn: 'ফোর্কিং অ্যাকাউন্টে পুশযোগ্য কপি দেয়; ক্লোনিং লোকাল আনে; পুল রিকোয়েস্ট ব্রাঞ্চ মূলে প্রস্তাব করে। মূলে অনুমতি কখনো দরকার নেই — শুধু ভালো প্রস্তাব।',
    },
    interviewTip: {
      en: 'Emphasize that forks exist because pushing requires permission — access control is the reason for the whole dance.',
      bn: 'জোর দিন ফোর্ক আছে কারণ পুশে অনুমতি লাগে — অ্যাক্সেস কন্ট্রোল পুরো নাচের কারণ।',
    },
    commonMistake: {
      en: 'Cloning the original then wondering why push is denied — the fork step is what grants you a writable copy.',
      bn: 'মূল ক্লোন করে পুশ কেন নিষেধ ভাবা — ফোর্ক ধাপই লেখযোগ্য কপি দেয়।',
    },
    options: [
      { id: 'a', label: 'Fork → clone fork → branch → push → pull request', correct: true },
      { id: 'b', label: 'Clone original → push → pull request', correct: false },
      { id: 'c', label: 'Download ZIP → email patches', correct: false },
      { id: 'd', label: 'Push directly to the original', correct: false },
    ],
    relatedCommands: ['git.clone', 'git.push', 'git.remote'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-fork-clone-pr-flow'],
    relatedInternals: [],
    tags: ['fork', 'clone', 'open-source', 'pr'],
    order: 51,
  },
  {
    id: 'git.interview.clone-depth',
    category: 'remote',
    difficulty: 'advanced',
    type: 'conceptual',
    question: {
      en: 'When would you use a shallow clone, and what do you give up?',
      bn: 'কখন শ্যালো ক্লোন ব্যবহার করবেন, আর কী ছাড় দেবেন?',
    },
    shortAnswer: {
      en: 'Use --depth for huge repos when you only need recent history (CI, quick experiments). You lose full log/blame archaeology and some operations need deepening.',
      bn: 'শুধু সাম্প্রতিক হিস্ট্রি দরকারে বিশাল রেপোতে (CI, দ্রুত পরীক্ষা) --depth ব্যবহার করুন। পূর্ণ log/blame প্রত্নতত্ত্ব হারান ও কিছু অপারেশনে গভীর করা লাগে।',
    },
    explanation: {
      en: 'Shallow clones truncate history at N commits, downloading far less. The tradeoff: commands that walk ancestors (blame across eras, bisect into the past, some merges) hit the graft boundary. git fetch --deepen or --unshallow restores full history when you outgrow the shortcut.',
      bn: 'শ্যালো ক্লোন N কমিটে হিস্ট্রি ছাঁটে, অনেক কম ডাউনলোড করে। বিনিময়: পূর্বপুরুষ হাঁটা কমান্ড (যুগ পেরিয়ে blame, অতীতে bisect, কিছু মার্জ) গ্রাফট সীমানায় আটকায়। শর্টকাট ছাড়ালে git fetch --deepen বা --unshallow পূর্ণ হিস্ট্রি ফেরায়।',
    },
    interviewTip: {
      en: 'Name CI pipelines as the use case — it shows you optimize for real constraints, not trivia.',
      bn: 'ব্যবহার হিসেবে CI পাইপলাইন নাম বলুন — এতে বোঝায় বাস্তব সীমায় অপ্টিমাইজ করেন, তুচ্ছ নয়।',
    },
    commonMistake: {
      en: 'Shallow-cloning by default everywhere, then filing "mysterious" bug reports when history-dependent tools misbehave.',
      bn: 'সর্বত্র ডিফল্টে শ্যালো-ক্লোন করে হিস্ট্রি-নির্ভর টুল ভুল করলে "রহস্যময়" বাগ রিপোর্ট করা।',
    },
    relatedCommands: ['git.clone', 'git.fetch'],
    relatedLessons: ['git.fundamentals.remote-repository'],
    relatedTroubleshooting: [],
    relatedPractice: [],
    relatedInternals: [],
    tags: ['clone', 'shallow', 'performance', 'advanced'],
    order: 52,
  },
  {
    id: 'git.interview.pr-review',
    category: 'remote',
    difficulty: 'intermediate',
    type: 'scenario',
    question: {
      en: 'A teammate requests changes on your pull request. Walk through exactly what you do next.',
      bn: 'সহকর্মী পুল রিকোয়েস্টে পরিবর্তন চেয়েছে। পরে ঠিক কী করবেন বলুন।',
    },
    shortAnswer: {
      en: 'Read every comment, push fix commits to the same branch (the PR updates itself), reply where useful, and re-request review.',
      bn: 'প্রতিটি মন্তব্য পড়ুন, একই ব্রাঞ্চে ফিক্স কমিট পুশ করুন (PR নিজে আপডেট হয়), দরকারে জবাব দিন, পুনরায় রিভিউ চান।',
    },
    explanation: {
      en: 'No new PR is needed — the same branch feeds the same review thread. Fix commits keep history reviewable (reviewers diff the fix, not the whole PR), replies close the loop socially, and re-requesting review puts it back in their queue explicitly.',
      bn: 'নতুন PR দরকার নেই — একই ব্রাঞ্চ একই রিভিউ থ্রেড খাওয়ায়। ফিক্স কমিট হিস্ট্রি পর্যালোচনাযোগ্য রাখে (রিভিউয়াররা ফিক্স diff করে, পুরো PR নয়), জবাব সামাজিকভাবে চক্র শেষ করে, পুনরায় রিভিউ চাওয়া স্পষ্ট সারিতে ফেরায়।',
    },
    interviewTip: {
      en: 'Mention re-requesting explicitly — juniors fix silently and wonder why nobody re-reviews.',
      bn: 'পুনরায় রিভিউ চাওয়া স্পষ্ট উল্লেখ করুন — জুনিয়ররা নীরবে ঠিক করে ভাবে কেন কেউ পুনরায় দেখে না।',
    },
    commonMistake: {
      en: 'Force-pushing a "clean" rewrite mid-review, invalidating every inline comment’s context.',
      bn: 'রিভিউ মাঝে "পরিষ্কার" পুনর্লেখে ফোর্স-পুশ করে প্রতিটি ইনলাইন মন্তব্যের প্রেক্ষাপট বাতিল।',
    },
    relatedCommands: ['git.push', 'git.commit'],
    relatedLessons: [],
    relatedTroubleshooting: ['git.troubleshooting.pull-conflict'],
    relatedPractice: ['git.practice.command-respond-to-review'],
    relatedInternals: [],
    tags: ['pr', 'review', 'collaboration'],
    order: 53,
  },
  {
    id: 'git.interview.branch-protection',
    category: 'remote',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'What does branch protection on main typically enforce, and why do teams want it?',
      bn: 'main-এ ব্রাঞ্চ সুরক্ষা সাধারণত কী কার্যকর করে, টিম কেন চায়?',
    },
    shortAnswer: {
      en: 'No direct pushes, required pull-request reviews, and passing status checks — so nothing reaches main unreviewed or untested.',
      bn: 'সরাসরি পুশ নেই, বাধ্যতামূলক পুল-রিকোয়েস্ট রিভিউ ও পাসিং স্ট্যাটাস চেক — যাতে অপর্যালোচিত বা অপরীক্ষিত কিছু main-এ না পৌঁছায়।',
    },
    explanation: {
      en: 'Protection converts good intentions into defaults: every change arrives via reviewed PR, CI must be green, and force-pushes are blocked. Teams trade a little velocity for a main branch that is always releasable.',
      bn: 'সুরক্ষা ভালো উদ্দেশ্যকে ডিফল্টে বদলায়: প্রতিটি পরিবর্তন রিভিউড PR-এ আসে, CI সবুজ হতে হবে, ফোর্স-পুশ বন্ধ। টিম সামান্য গতি দিয়ে সবসময় রিলিজযোগ্য main কেনে।',
    },
    interviewTip: {
      en: 'Connect it to incidents you have seen — "after one bad direct push, we protected main" tells a story.',
      bn: 'দেখা ঘটনার সাথে যুক্ত করুন — "এক খারাপ সরাসরি পুশের পর main সুরক্ষিত করেছি" গল্প বলে।',
    },
    commonMistake: {
      en: 'Seeing protection as bureaucracy and working around it with admin overrides instead of better PRs.',
      bn: 'সুরক্ষাকে আমলাতন্ত্র দেখে ভালো PR-এর বদলে অ্যাডমিন ওভাররাইডে এড়ানো।',
    },
    relatedCommands: ['git.push', 'git.merge'],
    relatedLessons: [],
    relatedTroubleshooting: ['git.troubleshooting.push-rejected'],
    relatedPractice: [],
    relatedInternals: [],
    tags: ['branch-protection', 'ci', 'main', 'policy'],
    order: 54,
  },
  {
    id: 'git.interview.code-review-focus',
    category: 'remote',
    difficulty: 'intermediate',
    type: 'conceptual',
    question: {
      en: 'When reviewing a pull request, what do you actually look for beyond "does it work"?',
      bn: 'পুল রিকোয়েস্ট রিভিউয়ে "কাজ করে" ছাড়া আসলে কী দেখেন?',
    },
    shortAnswer: {
      en: 'Correctness edge cases, readability for future maintainers, test coverage, and whether the change matches its stated intent.',
      bn: 'সঠিকতার এজ কেস, ভবিষ্যৎ রক্ষণাবেক্ষণকারীর পাঠযোগ্যতা, টেস্ট কভারেজ, এবং পরিবর্তন ঘোষিত উদ্দেশ্যে মেলে কিনা।',
    },
    explanation: {
      en: 'Working code is table stakes. Reviews catch what authors cannot see: missed null paths, unclear names that will confuse in six months, untested branches, and scope creep hiding inside the diff. Good reviewers also praise what is clean — review is teaching, not gatekeeping.',
      bn: 'কাজ করা কোড ন্যূনতম শর্ত। রিভিউ ধরে যা লেখক দেখতে পায় না: মিস নাল পথ, অস্পষ্ট নাম যা ছয় মাসে বিভ্রান্ত করবে, অপরীক্ষিত ব্রাঞ্চ, diff-এ লুকানো স্কোপ বৃদ্ধি। ভালো রিভিউয়ার পরিষ্কারটার প্রশংসাও করে — রিভিউ শেখানো, পাহারা নয়।',
    },
    interviewTip: {
      en: 'Give one concrete thing you always check (naming, tests, error paths) — specificity beats "I review carefully".',
      bn: 'সবসময় যাচাই করা একটি সুনির্দিষ্ট জিনিস দিন (নামকরণ, টেস্ট, এরর পথ) — নির্দিষ্টতা "যত্নে রিভিউ করি"-কে হারায়।',
    },
    commonMistake: {
      en: 'Rubber-stamping with "LGTM" on a 2,000-line diff, or nitpicking formatting while missing logic bugs.',
      bn: '২,০০০-লাইন diff-এ "LGTM" রাবার-স্ট্যাম্প, বা লজিক বাগ মিস করে ফরম্যাটিংয়ে খুঁত ধরা।',
    },
    relatedCommands: ['git.diff'],
    relatedLessons: [],
    relatedTroubleshooting: [],
    relatedPractice: ['git.practice.command-respond-to-review'],
    relatedInternals: [],
    tags: ['review', 'pr', 'quality'],
    order: 55,
  },
];
