import { DetailedCommand } from '@/types/content';

/**
 * Initial Git Command Library (19 foundational commands)
 *
 * Each command is structured to provide:
 * 1. What it does (en & bn)
 * 2. When to use it
 * 3. Exact syntax & realistic examples
 * 4. Internal Git mechanics (how the object store / index updates)
 * 5. Common options/flags
 * 6. Common mistakes & prevention
 * 7. Technical interview questions & insights
 */
export const GIT_COMMANDS: DetailedCommand[] = [
  {
    id: 'git.init',
    command: 'git init',
    slug: 'init',
    order: 1,
    frequentlyUsed: false,
    whenNotToUse: 'Do not run inside an already-tracked repository — it creates a confusing nested repo.',
    whenNotToUseBn: 'ইতিমধ্যে ট্র্যাক করা রিপোজিটরির ভেতরে চালাবেন না — এতে বিভ্রান্তিকর নেস্টেড রিপো তৈরি হয়।',
    relatedLessons: ['git.fundamentals.what-is-git', 'git.fundamentals.repository'],
    aliases: [],
    searchKeywords: ['setup', 'initialize', 'new repo', 'start', 'create'],
    category: 'setup',
    difficulty: 'beginner',
    title: 'Initialize Repository',
    titleBn: 'রিপোজিটরি শুরু করা',
    whatItDoes: 'Initializes a new empty Git repository or reinitializes an existing one in the current directory.',
    whatItDoesBn: 'বর্তমান ডিরেক্টরিতে একটি নতুন ফাঁকা গিট রিপোজিটরি তৈরি করে অথবা বিদ্যমান রিপো পুনরায় সেট করে।',
    whenToUse: 'When starting a brand new project on your local machine before making commits.',
    whenToUseBn: 'যখন লোকাল কম্পিউটারে কোনো নতুন প্রজেক্ট শুরু করবেন এবং সেখানে সংস্করণ নিয়ন্ত্রণ চান।',
    syntax: 'git init [directory-name]',
    whatHappensInternally: 'Creates a hidden `.git` directory containing `HEAD`, `config`, `description`, `hooks/`, `info/`, and the empty `objects/` and `refs/` databases.',
    whatHappensInternallyBn: 'বর্তমান ফোল্ডারে একটি লুকায়িত `.git` ডিরেক্টরি তৈরি করে যার ভেতরে `objects/`, `refs/`, এবং `HEAD` ফাইল থাকে।',
    examples: [
      {
        command: 'git init',
        description: 'Initialize Git in the current directory',
        descriptionBn: 'বর্তমান ডিরেক্টরিতে গিট শুরু করুন',
        output: 'Initialized empty Git repository in /home/user/project/.git/',
      },
      {
        command: 'git init my-awesome-app',
        description: 'Create a new directory called my-awesome-app and initialize Git inside it',
        descriptionBn: 'my-awesome-app নামে নতুন ফোল্ডার বানিয়ে গিট শুরু করুন',
        output: 'Initialized empty Git repository in /home/user/my-awesome-app/.git/',
      },
    ],
    commonOptions: [
      { flag: '--initial-branch=<name>', description: 'Specify default branch name (e.g. main) instead of master', descriptionBn: 'ডিফল্ট ব্রাঞ্চের নাম নির্ধারণ (যেমন main)' },
      { flag: '--bare', description: 'Create a bare repository (no working directory, used on central servers)', descriptionBn: 'বেয়ার রিপো তৈরি (সরাসরি কোড এডিট ছাড়া সেন্ট্রাল সার্ভারের জন্য)' },
    ],
    commonMistakes: [
      {
        mistake: 'Running git init inside an existing Git repository (nested repos)',
        mistakeBn: 'বিদ্যমান কোনো গিট রিপোর ভেতরে আবার git init চালানো',
        howToAvoid: 'Always run `git status` first to verify whether the parent folder is already tracked.',
        howToAvoidBn: 'প্রথমে `git status` চালিয়ে নিশ্চিত হোন যে ফোল্ডারটি ইতিমধ্যে কোনো রিপোর অধীনে আছে কিনা।',
      },
    ],
    interviewInsight: {
      question: 'What actually happens to your filesystem when you run git init?',
      questionBn: 'git init কমান্ড চালালে ফাইলসিস্টেমে মূলত কী পরিবর্তন ঘটে?',
      answer: 'Git creates a hidden directory called `.git`. This directory holds the entire database of objects (blobs, trees, commits, tags), references (branches, tags), and configuration. The enclosing folder becomes the Working Tree.',
      answerBn: 'গিট একটি লুকায়িত `.git` ফোল্ডার তৈরি করে। এটি গিটের সম্পূর্ণ অবজেক্ট ডাটাবেস ও রেফারেন্স ধারণ করে এবং বাইরের ফোল্ডারটি ওয়ার্কিং ট্রি হিসেবে কাজ করে।',
    },
    tags: ['setup', 'init', 'basics', 'repository'],
    relatedCommands: ['git.clone', 'git.status'],
  },
  {
    id: 'git.clone',
    command: 'git clone',
    slug: 'clone',
    order: 2,
    frequentlyUsed: false,
    whenNotToUse: 'Do not clone when you already have a local copy — use git fetch or git pull to update instead.',
    whenNotToUseBn: 'লোকাল কপি থাকা অবস্থায় আবার ক্লোন করবেন না — আপডেটের জন্য git fetch বা git pull ব্যবহার করুন।',
    relatedLessons: ['git.fundamentals.remote-repository', 'git.fundamentals.git-vs-github', 'github.repositories.clone-repository', 'github.collaboration.fork-vs-clone'],
    aliases: [],
    searchKeywords: ['download', 'copy', 'remote', 'github', 'duplicate'],
    category: 'setup',
    difficulty: 'beginner',
    title: 'Clone Remote Repository',
    titleBn: 'রিমোট রিপোজিটরি ক্লোন করা',
    whatItDoes: 'Clones a remote repository into a newly created local directory, setting up remote tracking branches and checking out an initial branch.',
    whatItDoesBn: 'রিমোট সার্ভার থেকে সম্পূর্ণ রিপোজিটরি এবং তার ইতিহাস কপি করে আপনার কম্পিউটারে নিয়ে আসে।',
    whenToUse: 'When joining an existing project on GitHub/GitLab or contributing to open-source.',
    whenToUseBn: 'যখন বিদ্যমান কোনো টিম প্রজেক্ট বা ওপেন-সোর্স কোডে কাজ শুরু করতে চান।',
    syntax: 'git clone <url> [directory-name]',
    whatHappensInternally: 'Copies the complete object database, creates remote-tracking branches under `refs/remotes/origin/`, creates the `origin` remote, and unpacks the default branch into the working tree.',
    whatHappensInternallyBn: 'সম্পূর্ণ অবজেক্ট ডাটাবেস ডাউনলোড করে, `origin` নামে রিমোট কানেকশন সেট করে এবং ডিফল্ট ব্রাঞ্চ ওয়ার্কিং ডিরেক্টরিতে চেকআউট করে।',
    examples: [
      {
        command: 'git clone https://github.com/facebook/react.git',
        description: 'Clone React repository into a local folder named react',
        descriptionBn: 'রিমোট থেকে React রিপোজিটরি ক্লোন করুন',
        output: 'Cloning into \'react\'...\nremote: Enumerating objects: 243912, done.\nReceiving objects: 100% (243912/243912), done.',
      },
      {
        command: 'git clone --depth 1 https://github.com/torvalds/linux.git',
        description: 'Shallow clone saving bandwidth by fetching only the latest single commit',
        descriptionBn: 'শুধুমাত্র সর্বশেষ কমিটটি ক্লোন করে দ্রুত ডাউনলোড সম্পন্ন করা',
      },
    ],
    commonOptions: [
      { flag: '--depth <n>', description: 'Create a shallow clone with history truncated to the specified number of commits', descriptionBn: 'নির্দিষ্ট সংখ্যক সর্বশেষ কমিট পর্যন্ত ক্লোন করা' },
      { flag: '--branch <name>', description: 'Checkout specific branch instead of the remote HEAD default branch', descriptionBn: 'নির্দিষ্ট ব্রাঞ্চ সরাসরি চেকআউট করা' },
    ],
    interviewInsight: {
      question: 'What is the difference between git clone and git pull?',
      questionBn: 'git clone এবং git pull এর মধ্যে পার্থক্য কী?',
      answer: 'git clone initializes a new local repository from scratch by downloading the entire repository database and creating remote references. git pull updates an already cloned, existing local branch by fetching new remote commits and merging them.',
      answerBn: 'git clone সম্পূর্ণ নতুন একটি রিপোজিটরি নামিয়ে আনে। পক্ষান্তরে git pull ইতিমধ্যে ক্লোন করা বিদ্যমান রিপোজিটরিতে নতুন পরিবর্তনগুলো এনে মার্জ করে।',
    },
    tags: ['setup', 'clone', 'download', 'remote'],
    relatedCommands: ['git.init', 'git.fetch', 'git.pull'],
  },
  {
    id: 'git.status',
    command: 'git status',
    slug: 'status',
    order: 3,
    frequentlyUsed: true,
    whenNotToUse: 'Avoid parsing its human-readable output in scripts — use git status --porcelain for machine output.',
    whenNotToUseBn: 'স্ক্রিপ্টে এর সাধারণ আউটপুট পার্স করবেন না — মেশিন-রিডেবল আউটপুটের জন্য --porcelain ব্যবহার করুন।',
    relatedLessons: ['git.fundamentals.working-directory', 'git.fundamentals.three-areas'],
    aliases: ['st'],
    searchKeywords: ['inspect', 'state', 'staged', 'unstaged', 'untracked', 'check', 'daily'],
    category: 'inspection',
    difficulty: 'beginner',
    title: 'Show Working Tree Status',
    titleBn: 'ওয়ার্কিং ট্রির অবস্থা নিরীক্ষণ',
    whatItDoes: 'Displays paths that have differences between the index file and the current HEAD commit, paths that have differences between the working tree and the index file, and paths in the working tree that are not tracked by Git.',
    whatItDoesBn: 'ওয়ার্কিং ডিরেক্টরি এবং স্টেজিং এরিয়াতে থাকা ফাইলগুলোর বর্তমান অবস্থা দেখায়।',
    whenToUse: 'Use constantly before and after running staging, commit, merge, or rebase operations.',
    whenToUseBn: 'যেকোনো কমিট, মার্জ বা ফাইল যোগ করার আগে ও পরে সর্বদা রান করুন।',
    syntax: 'git status [options]',
    whatHappensInternally: 'Compares file modification timestamps, file hashes, and sizes between the working filesystem, index staging file (`.git/index`), and the latest HEAD commit tree.',
    whatHappensInternallyBn: 'লোকাল ডিস্ক, স্টেজিং ইনডেক্স এবং বর্তমান কমিটের মধ্যে ফাইলের হ্যাশ ও সময় তুলনা করে।',
    examples: [
      {
        command: 'git status',
        description: 'Standard detailed status report',
        descriptionBn: 'বিস্তারিত স্ট্যাটাস রিপোর্ট',
        output: 'On branch main\nChanges not staged for commit:\n  modified:   src/App.tsx\n\nUntracked files:\n  src/utils/helpers.ts',
      },
      {
        command: 'git status -s',
        description: 'Short, compact two-letter status display',
        descriptionBn: 'সংক্ষিপ্ত দ্বি-অক্ষর বিশিষ্ট স্ট্যাটাস ভিউ',
        output: ' M src/App.tsx\n?? src/utils/helpers.ts',
      },
    ],
    commonOptions: [
      { flag: '-s, --short', description: 'Give output in the short-format', descriptionBn: 'সংক্ষিপ্ত ফরম্যাটে আউটপুট প্রদর্শন' },
      { flag: '-b, --branch', description: 'Show the branch and tracking info even in short-format', descriptionBn: 'সংক্ষিপ্ত ফরম্যাটেও ব্রাঞ্চ নাম ও আপস্ট্রিম স্ট্যাটাস দেখানো' },
    ],
    interviewInsight: {
      question: 'What do the two columns in git status --short indicate?',
      questionBn: 'git status --short আউটপুটের দুটি কলাম কী নির্দেশ করে?',
      answer: 'The first column represents the staging index status (relative to HEAD), and the second column represents the working tree status (relative to the index). For example, `MM` means staged modifications plus unstaged modifications.',
      answerBn: 'প্রথম কলাম স্টেজিং ইনডেক্স এবং দ্বিতীয় কলাম ওয়ার্কিং ডিরেক্টরির অবস্থা বোঝায়। যেমন `MM` মানে স্টেজিং এবং ওয়ার্কিং উভয় স্থানেই পরিবর্তন রয়েছে।',
    },
    tags: ['inspection', 'status', 'daily'],
    relatedCommands: ['git.diff', 'git.add', 'git.log'],
  },
  {
    id: 'git.add',
    command: 'git add',
    slug: 'add',
    order: 4,
    frequentlyUsed: true,
    whenNotToUse: 'Do not stage files you have not reviewed — a blind git add . can sweep in secrets or build artifacts.',
    whenNotToUseBn: 'পর্যালোচনা না করে ফাইল স্টেজ করবেন না — যাচাই ছাড়া git add . চালালে গোপন তথ্য বা বিল্ড ফাইল ঢুকে যেতে পারে।',
    relatedLessons: ['git.fundamentals.staging-area', 'git.fundamentals.three-areas'],
    aliases: [],
    searchKeywords: ['stage', 'index', 'track', 'daily', 'prepare'],
    category: 'daily',
    difficulty: 'beginner',
    title: 'Stage File Modifications',
    titleBn: 'ফাইল স্টেজিং এরিয়াতে যোগ করা',
    whatItDoes: 'Adds file contents to the staging index, preparing them to be included in the next commit snapshot.',
    whatItDoesBn: 'ফাইলের সর্বশেষ পরিবর্তনগুলোকে স্টেজিং ইনডেক্সে যুক্ত করে পরবর্তী কমিটের জন্য প্রস্তুত করে।',
    whenToUse: 'After making code modifications and before running `git commit`.',
    whenToUseBn: 'কোডে পরিবর্তন আনার পর এবং `git commit` দেওয়ার ঠিক আগে।',
    syntax: 'git add <pathspec> [options]',
    whatHappensInternally: 'Reads the file contents from disk, compresses them into blob objects with SHA-1/256 hashes, stores them inside `.git/objects/`, and writes the file path, permissions, and hash into `.git/index`.',
    whatHappensInternallyBn: 'ফাইলের কনটেন্ট হ্যাশ করে `.git/objects/` এ ব্লব (blob) অবজেক্ট তৈরি করে এবং ইনডেক্স ফাইলে রেকর্ড যুক্ত করে।',
    examples: [
      {
        command: 'git add .',
        description: 'Stage all modified and newly created files in current directory',
        descriptionBn: 'বর্তমান ডিরেক্টরির সব নতুন ও পরিবর্তিত ফাইল স্টেজ করুন',
      },
      {
        command: 'git add src/components/Button.tsx',
        description: 'Stage a specific single file',
        descriptionBn: 'শুধুমাত্র নির্দিষ্ট একটি ফাইল স্টেজ করুন',
      },
      {
        command: 'git add -p',
        description: 'Interactive patch mode: review and stage hunk by hunk',
        descriptionBn: 'ইন্টারেক্টিভ প্যাচ মোড: কোডের প্রতিটি ব্লক আলাদাভাবে যাচাই করে স্টেজ করা',
      },
    ],
    commonOptions: [
      { flag: '-p, --patch', description: 'Interactively choose hunks of patch between index and working tree', descriptionBn: 'কোডের নির্দিষ্ট অংশ বা হাঙ্ক (hunk) আলাদা করে স্টেজ করা' },
      { flag: '-u, --update', description: 'Update tracked files only; ignores newly created untracked files', descriptionBn: 'শুধুমাত্র ইতিমধ্যে ট্র্যাকড ফাইলের পরিবর্তন স্টেজ করা' },
    ],
    commonMistakes: [
      {
        mistake: 'Carelessly running `git add .` without checking `git status` or having a `.gitignore`',
        mistakeBn: '`.gitignore` ছাড়া বা `git status` না দেখে সব ফাইল নির্বিচারে স্টেজ করা',
        howToAvoid: 'Always configure a `.gitignore` to prevent committing `.env`, `node_modules`, or build artifacts.',
        howToAvoidBn: '`.gitignore` ফাইলে সংবেদনশীল ফাইল এবং `node_modules` যোগ করে নিন।',
      },
    ],
    interviewInsight: {
      question: 'What is the purpose of Git\'s staging area (index) instead of committing directly?',
      questionBn: 'সরাসরি কমিট না করে স্টেজিং এরিয়ার মতো মধ্যবর্তী স্তর রাখার সুবিধা কী?',
      answer: 'The staging area decouples what you edit from what you commit. It allows developers to craft clean, atomic, logical commits containing only related modifications, even if they edited ten different files simultaneously.',
      answerBn: 'স্টেজিং এরিয়া এডিটিং এবং কমিটিংকে পৃথক করে। এর ফলে একই সাথে অনেক ফাইলে কাজ করলেও ছোট ছোট যৌক্তিক ও পরিষ্কার কমিট তৈরি করা সম্ভব হয়।',
    },
    tags: ['daily', 'add', 'stage', 'index'],
    relatedCommands: ['git.status', 'git.restore', 'git.commit'],
  },
  {
    id: 'git.commit',
    command: 'git commit',
    slug: 'commit',
    order: 5,
    frequentlyUsed: true,
    whenNotToUse: 'Do not commit broken or untested work to a shared branch — keep history atomic and green.',
    whenNotToUseBn: 'শেয়ার্ড ব্রাঞ্চে ভাঙা বা পরীক্ষা না করা কোড কমিট করবেন না — ইতিহাস পরিষ্কার রাখুন।',
    relatedLessons: ['git.fundamentals.commit', 'git.fundamentals.local-repository'],
    aliases: ['ci'],
    searchKeywords: ['save', 'snapshot', 'record', 'message', 'daily'],
    category: 'daily',
    difficulty: 'beginner',
    title: 'Record Repository Snapshot',
    titleBn: 'রিপোজিটরির স্থায়ী স্ন্যাপশট সংরক্ষণ',
    whatItDoes: 'Creates a new commit object capturing the current staged index, records the author/committer information, timestamp, commit message, and points to the parent commit.',
    whatItDoesBn: 'স্টেজিং এরিয়াতে থাকা সমস্ত ফাইলের একটি স্থায়ী ক্রিপ্টোগ্রাফিক স্ন্যাপশট লোকাল রিপোজিটরিতে সেভ করে।',
    whenToUse: 'When a logical, atomic piece of work (feature, fix, refactor) is tested and ready to save.',
    whenToUseBn: 'যখন কোনো একটি নির্দিষ্ট কাজ সম্পন্ন হয় এবং তার স্থায়ী রেকর্ড সংরক্ষণ করতে চান।',
    syntax: 'git commit -m "commit message" [options]',
    whatHappensInternally: 'Generates tree objects representing directories, creates a commit object pointing to the root tree, references parent commit(s), and updates the active branch reference (`refs/heads/<branch>`) to the new commit hash.',
    whatHappensInternallyBn: 'রুট ট্রি অবজেক্ট তৈরি করে, প্যারেন্ট কমিটের রেফারেন্স দেয় এবং বর্তমান ব্রাঞ্চের পয়েন্টারকে নতুন কমিটের দিকে এগিয়ে নেয়।',
    examples: [
      {
        command: 'git commit -m "feat: implement user password reset"',
        description: 'Record commit with inline commit message',
        descriptionBn: 'ইনলাইন মেসেজ দিয়ে কমিট সংরক্ষণ করুন',
        output: '[main 3f2a1b1] feat: implement user password reset\n 2 files changed, 45 insertions(+), 3 deletions(-)',
      },
      {
        command: 'git commit --amend -m "feat: implement user password reset with email token"',
        description: 'Amend the most recent commit message or include newly staged files',
        descriptionBn: 'সর্বশেষ কমিটের মেসেজ বা ফাইলে সংশোধন আনা',
      },
    ],
    commonOptions: [
      { flag: '-m <msg>', description: 'Use the given message as the commit message', descriptionBn: 'টার্মিনাল থেকেই সরাসরি কমিট মেসেজ দেওয়া' },
      { flag: '-a, --all', description: 'Automatically stage tracked files that have been modified or deleted', descriptionBn: 'ট্র্যাক করা ফাইলগুলোর পরিবর্তন স্বয়ংক্রিয়ভাবে স্টেজ করে কমিট করা' },
      { flag: '--amend', description: 'Replace the tip of the current branch with a new combined commit', descriptionBn: 'সর্বশেষ কমিটটি প্রতিস্থাপন/সংশোধন করা' },
    ],
    commonMistakes: [
      {
        mistake: 'Amending a commit that has already been pushed to a shared public branch',
        mistakeBn: 'শেয়ার্ড বা পাবলিক ব্রাঞ্চে ইতিমধ্যে পুশ করা কমিটকে `--amend` করা',
        howToAvoid: 'Only amend commits that exist exclusively in your local, unpushed repository.',
        howToAvoidBn: 'শুধুমাত্র লোকাল আনপুশড কমিটেই `--amend` ব্যবহার করুন।',
      },
    ],
    interviewInsight: {
      question: 'What makes a good Git commit message?',
      questionBn: 'একটি আদর্শ গিট কমিট মেসেজের বৈশিষ্ট্য কী?',
      answer: 'A good commit is atomic (does one thing well), written in imperative mood ("feat: add auth" rather than "added auth"), starts with a clear short summary (<50 chars), and includes a detailed body explaining WHY the change was made if complex.',
      answerBn: 'কমিট মেসেজ ইম্পারেটিভ মুডে (যেমন "Fix bug", "Fixed bug" নয়) লেখা উচিত, ৫০ অক্ষরের মধ্যে সামারি থাকা এবং কেন পরিবর্তন করা হলো তা স্পষ্ট করা উচিত।',
    },
    tags: ['daily', 'commit', 'snapshot', 'history'],
    relatedCommands: ['git.add', 'git.log', 'git.status'],
  },
  {
    id: 'git.log',
    command: 'git log',
    slug: 'log',
    order: 6,
    frequentlyUsed: true,
    whenNotToUse: 'Do not use plain git log to review uncommitted working-tree changes — use git status or git diff for that.',
    whenNotToUseBn: 'আনকমিটেড পরিবর্তন দেখতে git log ব্যবহার করবেন না — এর জন্য git status বা git diff ব্যবহার করুন।',
    relatedLessons: ['git.fundamentals.commit', 'git.fundamentals.local-repository'],
    aliases: ['lg'],
    searchKeywords: ['history', 'commits', 'inspect', 'graph', 'timeline'],
    category: 'inspection',
    difficulty: 'beginner',
    title: 'Inspect Commit History',
    titleBn: 'কমিট হিস্ট্রি বা ইতিহাস পর্যবেক্ষণ',
    whatItDoes: 'Shows the chronological commit history reachable from the current HEAD or specified references.',
    whatItDoesBn: 'বর্তমান ব্রাঞ্চের সমস্ত পূর্ববর্তী কমিটগুলোর বিস্তারিত তালিকা প্রদর্শন করে।',
    whenToUse: 'When reviewing past changes, finding commit hashes, or understanding project evolution.',
    whenToUseBn: 'পূর্ববর্তী কোড পরিবর্তন দেখতে এবং নির্দিষ্ট কমিট হ্যাশ খুঁজে পেতে।',
    syntax: 'git log [options] [revision-range]',
    whatHappensInternally: 'Traverses parent pointers starting from the current HEAD reference backwards through the Directed Acyclic Graph (DAG) of commit objects.',
    whatHappensInternallyBn: 'বর্তমান HEAD থেকে শুরু করে প্যারেন্ট পয়েন্টার ধরে ধরে পূর্বের কমিটগুলোর গ্রাফ ব্রাউজ করে।',
    examples: [
      {
        command: 'git log --oneline -n 5',
        description: 'Show the 5 most recent commits compactly in one line each',
        descriptionBn: 'সর্বশেষ ৫টি কমিট এক লাইনে সংক্ষেপে দেখুন',
        output: '3f2a1b1 feat: implement user password reset\n9a8b7c6 fix: typo in login validation\n4d5e6f7 refactor: auth token generation\n1a2b3c4 docs: update API endpoints in readme\n0f1e2d3 feat: initial project scaffolding',
      },
      {
        command: 'git log --graph --oneline --all',
        description: 'ASCII graph visualizing branches and merges across all references',
        descriptionBn: 'গ্রাফ আকারে সমস্ত ব্রাঞ্চ ও মার্জের দৃশ্যপট পর্যবেক্ষণ',
      },
    ],
    commonOptions: [
      { flag: '--oneline', description: 'Shorthand for --pretty=oneline --abbrev-commit', descriptionBn: 'প্রতিটি কমিট এক লাইনে সংক্ষেপে দেখানো' },
      { flag: '--graph', description: 'Draw a text-based graphical representation of the commit history', descriptionBn: 'ব্রাঞ্চ ও মার্জের টেক্সট গ্রাফ আঁকা' },
      { flag: '-n <number>', description: 'Limit the number of commits to output', descriptionBn: 'নির্দিষ্ট সংখ্যক কমিট প্রদর্শন করা' },
    ],
    interviewInsight: {
      question: 'What is the structure of Git history: linear list or DAG?',
      questionBn: 'গিটের ইতিহাস কি লিনিয়ার লিস্ট নাকি ডিরেক্টেড অ্যাসাইক্লিক গ্রাফ (DAG)?',
      answer: 'Git history is a Directed Acyclic Graph (DAG). Each commit points backward to zero, one, or multiple parent commits (in the case of merges). Cycles are mathematically impossible because child commits contain the SHA hash of their parents.',
      answerBn: 'গিট হিস্ট্রি একটি DAG (Directed Acyclic Graph)। প্রতিটি কমিট তার পূর্ববর্তী প্যারেন্ট কমিটকে নির্দেশ করে। কমিট হ্যাশের কারণে এতে কোনো সাইকেল তৈরি হওয়া অসম্ভব।',
    },
    tags: ['inspection', 'log', 'history', 'dag'],
    relatedCommands: ['git.status', 'git.diff', 'git.show'],
  },
  {
    id: 'git.diff',
    command: 'git diff',
    slug: 'diff',
    order: 7,
    frequentlyUsed: true,
    whenNotToUse: 'Do not rely on bare git diff to see staged changes — add --staged or staged work stays invisible.',
    whenNotToUseBn: 'স্টেজড পরিবর্তন দেখতে খালি git diff এর ওপর নির্ভর করবেন না — --staged ফ্ল্যাগ যোগ করুন।',
    relatedLessons: ['git.fundamentals.working-directory', 'git.fundamentals.staging-area'],
    aliases: ['d'],
    searchKeywords: ['changes', 'patch', 'compare', 'review', 'difference'],
    category: 'inspection',
    difficulty: 'beginner',
    title: 'Show Changes Between Commits & Trees',
    titleBn: 'ফাইল বা কমিটের মধ্যে পরিবর্তনের পার্থক্য দেখা',
    whatItDoes: 'Computes and displays line-by-line differences between modifications in the working tree, staging area, or between commits.',
    whatItDoesBn: 'কোডের কোন কোন লাইনে পরিবর্তন হয়েছে তা সুস্পষ্টভাবে প্রদর্শন করে।',
    whenToUse: 'Before running `git add` to review what you changed, or before `git commit` to verify what is staged.',
    whenToUseBn: 'ফাইল স্টেজ করার পূর্বে এবং কমিট দেওয়ার আগে কোড লাইনগুলো পর্যালোচনায়।',
    syntax: 'git diff [options] [<commit>] [--] [<path>...]',
    whatHappensInternally: 'Runs Eugene Myers\' diff algorithm comparing blob contents line by line, displaying additions (`+`) and deletions (`-`).',
    whatHappensInternallyBn: 'দুটি ব্লবের মধ্যে লাইন বাই লাইন তুলনা করে সংযোজিত ও অপসারিত লাইন প্রদর্শন করে।',
    examples: [
      {
        command: 'git diff',
        description: 'Show unstaged changes in working tree compared to the staging index',
        descriptionBn: 'স্টেজিং ইনডেক্সের তুলনায় ওয়ার্কিং ট্রির আনস্টেজড পরিবর্তন দেখুন',
      },
      {
        command: 'git diff --staged',
        description: 'Show staged changes ready for commit compared to the latest HEAD commit',
        descriptionBn: 'স্টেজিং এরিয়াতে থাকা ফাইলগুলোর পরিবর্তন HEAD এর সাপেক্ষে দেখুন',
      },
    ],
    commonOptions: [
      { flag: '--staged / --cached', description: 'View changes staged in the index ready for the next commit', descriptionBn: 'স্টেজিং এরিয়ার পরিবর্তনগুলো দেখা' },
      { flag: '--stat', description: 'Show summary of altered lines instead of full diff view', descriptionBn: 'প্রতি ফাইলে কয়টি লাইন পরিবর্তন হয়েছে তার পরিসংখ্যান দেখা' },
    ],
    interviewInsight: {
      question: 'What is the exact difference between `git diff` and `git diff --staged`?',
      questionBn: '`git diff` এবং `git diff --staged` এর মধ্যে পার্থক্য কী?',
      answer: '`git diff` shows modifications in your working directory that have NOT yet been staged. `git diff --staged` (or `--cached`) shows modifications that HAVE been staged and will be recorded in the next commit.',
      answerBn: '`git diff` শুধুমাত্র আনস্টেজড পরিবর্তনগুলো দেখায়। পক্ষান্তরে `git diff --staged` দেখায় যা ইতিমধ্যে স্টেজিং এরিয়াতে যুক্ত হয়েছে এবং পরবর্তী কমিটে সেভ হবে।',
    },
    tags: ['inspection', 'diff', 'code-review'],
    relatedCommands: ['git.status', 'git.add', 'git.show'],
  },
  {
    id: 'git.show',
    command: 'git show',
    slug: 'show',
    order: 8,
    frequentlyUsed: false,
    whenNotToUse: 'Do not use git show for browsing long multi-commit history — git log is the right tool for that.',
    whenNotToUseBn: 'দীর্ঘ কমিট ইতিহাস দেখতে git show ব্যবহার করবেন না — এর জন্য git log উপযুক্ত।',
    relatedLessons: ['git.fundamentals.commit'],
    aliases: [],
    searchKeywords: ['inspect', 'object', 'commit details', 'view'],
    category: 'inspection',
    difficulty: 'beginner',
    title: 'Show Specific Git Objects',
    titleBn: 'নির্দিষ্ট কমিট বা অবজেক্টের বিস্তারিত তথ্য দেখা',
    whatItDoes: 'Shows one or more objects (commits, tags, trees, blobs) along with log metadata and textual diff.',
    whatItDoesBn: 'যেকোনো নির্দিষ্ট কমিটের মেসেজ, রচয়িতা ও পরিবর্তিত কোডের লাইনগুলো প্রদর্শন করে।',
    whenToUse: 'When inspecting what changed in a specific commit hash found via `git log`.',
    whenToUseBn: 'লগ থেকে পাওয়া কোনো নির্দিষ্ট কমিট বিস্তারিত দেখতে।',
    syntax: 'git show [options] <object>',
    whatHappensInternally: 'Decompresses the object from `.git/objects/`, parses its header type, and renders the content and patch.',
    whatHappensInternallyBn: 'অবজেক্ট ডাটাবেস থেকে সংশ্লিষ্ট কমিট অবজেক্টটি ডিকম্প্রেস করে তার কনটেন্ট ও ডিফ প্রদর্শন করে।',
    examples: [
      {
        command: 'git show HEAD',
        description: 'Show details and diff of the most recent commit',
        descriptionBn: 'সর্বশেষ কমিটটির বিবরণ ও ডিফ দেখুন',
      },
      {
        command: 'git show 3f2a1b1',
        description: 'Inspect a specific commit by hash',
        descriptionBn: 'নির্দিষ্ট কমিট হ্যাশ দিয়ে বিস্তারিত দেখুন',
      },
    ],
    commonOptions: [
      { flag: '--stat', description: 'Show file change count summary instead of full line diff', descriptionBn: 'ডিফের বদলে ফাইলের পরিবর্তনের সামারি দেখা' },
    ],
    interviewInsight: {
      question: 'Can git show display objects other than commits?',
      questionBn: 'git show কি কমিট ছাড়া অন্য কোনো অবজেক্ট দেখাতে পারে?',
      answer: 'Yes. It can show annotated tags, directory trees, and raw file blobs directly by hash or revision (e.g. `git show HEAD:package.json`).',
      answerBn: 'হ্যাঁ। এটি ট্যাগ, ডিরেক্টরি ট্রি এবং ফাইল ব্লবও সরাসরি দেখাতে পারে।',
    },
    tags: ['inspection', 'show', 'commit'],
    relatedCommands: ['git.log', 'git.diff'],
  },
  {
    id: 'git.branch',
    command: 'git branch',
    slug: 'branch',
    order: 9,
    frequentlyUsed: true,
    whenNotToUse: 'Do not use git branch to switch branches — it only lists or creates them; use git switch to move.',
    whenNotToUseBn: 'ব্রাঞ্চ পরিবর্তন করতে git branch ব্যবহার করবেন না — এটি শুধু তালিকা বা তৈরি করে; সুইচ করতে git switch ব্যবহার করুন।',
    relatedLessons: ['git.fundamentals.branch', 'github.branching.feature-branches'],
    aliases: ['br'],
    searchKeywords: ['list', 'create', 'delete', 'branches', 'daily'],
    category: 'branching',
    difficulty: 'beginner',
    title: 'List, Create, or Delete Branches',
    titleBn: 'ব্রাঞ্চ তৈরি, তালিকা দেখা বা মুছে ফেলা',
    whatItDoes: 'Inspects existing branches, creates new branches, or deletes completed topic branches.',
    whatItDoesBn: 'আপনার প্রজেক্টের সমস্ত শাখা বা ব্রাঞ্চের তালিকা দেখায় অথবা নতুন ব্রাঞ্চ তৈরি করে।',
    whenToUse: 'When beginning a new feature, bugfix, or listing all active branches.',
    whenToUseBn: 'নতুন ফিচার বা বাগ ফিক্সের জন্য আলাদা শাখা খুলতে বা ব্রাঞ্চ তালিকা দেখতে।',
    syntax: 'git branch [options] [<branchname>]',
    whatHappensInternally: 'A Git branch is simply a 41-byte text file inside `.git/refs/heads/<name>` containing a 40-character SHA-1/256 commit hash. Creating a branch is virtually instantaneous.',
    whatHappensInternallyBn: 'গিটের ব্রাঞ্চ মূলত ৪১ বাইটের একটি সাধারণ টেক্সট ফাইল যা একটি কমিট হ্যাশ নির্দেশ করে। ফলে ব্রাঞ্চ তৈরি অত্যন্ত দ্রুত সম্পন্ন হয়।',
    examples: [
      {
        command: 'git branch',
        description: 'List local branches with an asterisk (*) indicating current active branch',
        descriptionBn: 'লোকাল ব্রাঞ্চগুলোর তালিকা দেখা (তারকাচিহ্নিত ব্রাঞ্চটি সক্রিয়)',
        output: '* main\n  feature/login\n  hotfix/payment-error',
      },
      {
        command: 'git branch feature/payment-gateway',
        description: 'Create a new branch pointer at current HEAD without switching to it',
        descriptionBn: 'বর্তমান কমিটে নতুন একটি ব্রাঞ্চ পয়েন্টার তৈরি করা (সুইচ না করে)',
      },
      {
        command: 'git branch -d feature/login',
        description: 'Safely delete a merged topic branch',
        descriptionBn: 'মার্জ সম্পন্ন হওয়া ব্রাঞ্চ নিরাপদে মুছে ফেলা',
      },
    ],
    commonOptions: [
      { flag: '-a, --all', description: 'List both local and remote-tracking branches', descriptionBn: 'লোকাল ও রিমোট উভয় প্রকার ব্রাঞ্চের তালিকা দেখা' },
      { flag: '-d', description: 'Delete fully merged branch safely', descriptionBn: 'মার্জ হওয়া ব্রাঞ্চ নিরাপদে ডিলিট করা' },
      { flag: '-D', description: 'Force delete branch regardless of its merge status', descriptionBn: 'মার্জ না হলেও জোরপূর্বক ব্রাঞ্চ ডিলিট করা' },
    ],
    interviewInsight: {
      question: 'Why are Git branches called "lightweight" compared to SVN or CVS?',
      questionBn: 'এসভিএন বা সিভিএস এর তুলনায় গিট ব্রাঞ্চকে কেন "লাইটওয়েট" বলা হয়?',
      answer: 'In older VCS like SVN, branching required copying the entire directory tree into a new folder on the server. In Git, a branch is merely a 41-byte text file storing a commit hash pointer. Creating, switching, or deleting a branch has zero file duplication.',
      answerBn: 'SVN-এ ব্রাঞ্চ তৈরি মানে পুরো প্রজেক্ট ফোল্ডার কপি করা। আর গিটে একটি ব্রাঞ্চ মানে মাত্র ৪১ বাইটের একটি টেক্সট ফাইল যা একটি কমিটের হ্যাশ ধরে রাখে। এতে কোনো কোড ডুপ্লিকেট হয় না।',
    },
    tags: ['branching', 'branch', 'workflow'],
    relatedCommands: ['git.switch', 'git.checkout', 'git.merge'],
  },
  {
    id: 'git.switch',
    command: 'git switch',
    slug: 'switch',
    order: 10,
    frequentlyUsed: true,
    whenNotToUse: 'Do not use git switch to restore individual files — use git restore for file-level recovery.',
    whenNotToUseBn: 'একক ফাইল ফিরিয়ে আনতে git switch ব্যবহার করবেন না — ফাইলের জন্য git restore ব্যবহার করুন।',
    relatedLessons: ['git.fundamentals.branch', 'git.fundamentals.head'],
    aliases: ['sw'],
    searchKeywords: ['checkout', 'change branch', 'move', 'navigate'],
    category: 'branching',
    difficulty: 'beginner',
    title: 'Switch Branches Safely',
    titleBn: 'নিরাপদে ব্রাঞ্চ পরিবর্তন করা',
    whatItDoes: 'Switches the current HEAD to specified branch, updating files in the working tree to match that branch’s latest commit.',
    whatItDoesBn: 'বর্তমান সক্রিয় ব্রাঞ্চ পরিবর্তন করে অন্য ব্রাঞ্চে যায় এবং ওয়ার্কিং ডিরেক্টরির ফাইল আপডেট করে।',
    whenToUse: 'Introduced in Git 2.23 as a cleaner, dedicated alternative to `git checkout` for switching branches.',
    whenToUseBn: 'ব্রাঞ্চ পরিবর্তনের জন্য `git checkout` এর আধুনিক ও সুরক্ষিত বিকল্প হিসেবে।',
    syntax: 'git switch [options] <branchname>',
    whatHappensInternally: 'Updates the symbolic reference in `.git/HEAD` to point to `refs/heads/<branchname>` and synchronizes the working tree files to match the target commit tree.',
    whatHappensInternallyBn: '`.git/HEAD` ফাইলটিকে টার্গেট ব্রাঞ্চের দিকে নির্দেশ করায় এবং ওয়ার্কিং ফাইলের কনটেন্ট আপডেট করে।',
    examples: [
      {
        command: 'git switch feature/login',
        description: 'Switch to existing branch',
        descriptionBn: 'বিদ্যমান ব্রাঞ্চে সুইচ করুন',
        output: 'Switched to branch \'feature/login\'',
      },
      {
        command: 'git switch -c feature/oauth',
        description: 'Create and immediately switch to a new branch in one step',
        descriptionBn: 'এক কমান্ডেই নতুন ব্রাঞ্চ তৈরি করে সেখানে সুইচ করুন',
        output: 'Switched to a new branch \'feature/oauth\'',
      },
    ],
    commonOptions: [
      { flag: '-c, --create <new-branch>', description: 'Create and switch to a new branch', descriptionBn: 'নতুন ব্রাঞ্চ তৈরি ও একই সাথে সুইচ করা' },
    ],
    interviewInsight: {
      question: 'Why did Git introduce `git switch` and `git restore` in version 2.23?',
      questionBn: 'গিট ২.২৩ সংস্করণে `git switch` ও `git restore` কেন যুক্ত করা হয়েছিল?',
      answer: 'Historically, `git checkout` was overloaded with two completely distinct responsibilities: switching branches and discarding/restoring working tree files. `git switch` was introduced exclusively for branch switching to eliminate confusion and prevent accidental file loss.',
      answerBn: 'অতীতে `git checkout` একই সাথে ব্রাঞ্চ পরিবর্তন এবং ফাইল মুছে ফেলার কাজ করত, যা বিভ্রান্তিকর ছিল। তাই ব্রাঞ্চ পরিবর্তনের জন্য আলাদাভাবে `git switch` তৈরি করা হয়।',
    },
    tags: ['branching', 'switch', 'checkout'],
    relatedCommands: ['git.branch', 'git.checkout', 'git.restore'],
  },
  {
    id: 'git.checkout',
    command: 'git checkout',
    slug: 'checkout',
    order: 11,
    frequentlyUsed: true,
    whenNotToUse: 'Avoid git checkout for discarding files — its overloaded role is error-prone; prefer git switch and git restore.',
    whenNotToUseBn: 'ফাইল বাতিল করতে git checkout এড়িয়ে চলুন — বিভ্রান্তি এড়াতে git switch ও git restore ব্যবহার করুন।',
    relatedLessons: ['git.fundamentals.branch', 'git.fundamentals.head'],
    aliases: ['co'],
    searchKeywords: ['switch', 'restore', 'detached', 'legacy', 'classic'],
    category: 'branching',
    difficulty: 'beginner',
    title: 'Switch Branches or Restore Files',
    titleBn: 'ব্রাঞ্চ পরিবর্তন বা ফাইল রিস্টোর',
    whatItDoes: 'Updates files in the working tree to match the version in the index or specified tree-ish, or switches branches.',
    whatItDoesBn: 'ব্রাঞ্চ সুইচ করতে অথবা পূর্ববর্তী কোনো কমিট বা স্টেটের ফাইল ফিরিয়ে আনতে ব্যবহৃত হয়।',
    whenToUse: 'Still widely used in developer tutorials and legacy scripts for switching branches and creating new branches.',
    whenToUseBn: 'ব্রাঞ্চ তৈরি ও পরিবর্তনের ক্লাসিক কমান্ড হিসেবে।',
    syntax: 'git checkout [options] <branch | commit | file>',
    whatHappensInternally: 'Points `HEAD` to another branch or specific detached commit, and extracts the corresponding tree into the working directory.',
    whatHappensInternallyBn: 'HEAD কে নির্দিষ্ট ব্রাঞ্চ বা কমিটে সেট করে সেই অনুযায়ী ফাইল ডিস্কে বসিয়ে দেয়।',
    examples: [
      {
        command: 'git checkout -b feature/search-filters',
        description: 'Classic command to create and checkout a new branch',
        descriptionBn: 'নতুন ব্রাঞ্চ তৈরি ও সক্রিয় করার ক্লাসিক কমান্ড',
      },
      {
        command: 'git checkout main',
        description: 'Switch back to the main branch',
        descriptionBn: 'মূল main ব্রাঞ্চে ফিরে যান',
      },
    ],
    commonOptions: [
      { flag: '-b <new-branch>', description: 'Create and checkout a new branch named <new-branch>', descriptionBn: 'নতুন ব্রাঞ্চ তৈরি করে চেকআউট করা' },
    ],
    interviewInsight: {
      question: 'What is a "Detached HEAD" state in Git?',
      questionBn: 'গিটে "Detached HEAD" অবস্থা বলতে কী বোঝায়?',
      answer: 'A Detached HEAD occurs when HEAD points directly to a specific commit hash rather than a named branch reference. Any new commits created in this state have no branch pointing to them and may be orphaned when you switch away.',
      answerBn: 'যখন HEAD কোনো ব্রাঞ্চের নামের পরিবর্তে সরাসরি নির্দিষ্ট কমিট হ্যাশকে নির্দেশ করে তখন তাকে Detached HEAD বলে। এই অবস্থায় নতুন কমিট করলে তা কোনো ব্রাঞ্চে যুক্ত হয় না।',
    },
    tags: ['branching', 'checkout', 'detached-head'],
    relatedCommands: ['git.switch', 'git.restore', 'git.branch'],
  },
  {
    id: 'git.merge',
    command: 'git merge',
    slug: 'merge',
    order: 12,
    frequentlyUsed: true,
    whenNotToUse: 'Do not merge an unreviewed or failing branch into main — verify tests and resolve conflicts first.',
    whenNotToUseBn: 'পর্যালোচনা বা টেস্ট ছাড়া কোনো ব্রাঞ্চ main এ মার্জ করবেন না — আগে কনফ্লিক্ট মিটিয়ে নিন।',
    relatedLessons: ['git.fundamentals.branch', 'github.pr.merging-pr', 'github.branching.merging-branches'],
    aliases: [],
    searchKeywords: ['combine', 'join', 'fast-forward', 'conflict', 'integrate'],
    category: 'branching',
    difficulty: 'intermediate',
    title: 'Join Multiple Development Histories',
    titleBn: 'একাধিক ব্রাঞ্চের কোড মার্জ বা একত্রীকরণ',
    whatItDoes: 'Incorporates changes from the named commits (usually other branches) into the current active branch.',
    whatItDoesBn: 'অন্য কোনো শাখার সমস্ত কোড পরিবর্তনকে বর্তমান সক্রিয় শাখার সাথে যুক্ত করে।',
    whenToUse: 'When a feature branch is finished, tested, and ready to be merged back into `main`.',
    whenToUseBn: 'যখন ফিচারের কাজ শেষ হয় এবং তা প্রধান কোডবেসে যুক্ত করতে চান।',
    syntax: 'git merge [options] <branchname>',
    whatHappensInternally: 'Performs either a Fast-Forward (moving the branch pointer directly forward) or a 3-way merge (combining common ancestor, current branch, and incoming branch), creating a new merge commit with two parents.',
    whatHappensInternallyBn: 'ফাস্ট-ফরোয়ার্ড মার্জ অথবা ৩-ওয়ে মার্জের মাধ্যমে নতুন একটি মার্জ কমিট তৈরি করে যার দুটি প্যারেন্ট কমিট থাকে।',
    examples: [
      {
        command: 'git merge feature/auth',
        description: 'Merge feature/auth branch into current checked-out branch',
        descriptionBn: 'বর্তমান ব্রাঞ্চে feature/auth শাখার কোড মার্জ করুন',
      },
      {
        command: 'git merge --no-ff feature/auth',
        description: 'Force creation of a merge commit even if fast-forward is possible',
        descriptionBn: 'ফাস্ট-ফরোয়ার্ড সম্ভব হলেও স্পষ্ট মার্জ কমিট তৈরি করা',
      },
    ],
    commonOptions: [
      { flag: '--no-ff', description: 'Create a merge commit even when the merge resolves as a fast-forward', descriptionBn: 'সর্বদা মার্জ কমিট তৈরি করা' },
      { flag: '--abort', description: 'Abort the current conflict resolution process and reconstruct the pre-merge state', descriptionBn: 'মার্জ কনফ্লিক্ট দেখা দিলে মার্জ বাতিল করে পূর্বাবস্থায় ফেরা' },
    ],
    interviewInsight: {
      question: 'What is the difference between a Fast-Forward merge and a 3-Way merge?',
      questionBn: 'Fast-Forward মার্জ এবং 3-Way মার্জের মধ্যে পার্থক্য কী?',
      answer: 'A Fast-Forward occurs when the target branch has no new commits since the feature branched off; Git simply advances the pointer without creating a new commit. A 3-way merge occurs when both branches diverged; Git uses a common ancestor to combine changes and creates a dedicated merge commit.',
      answerBn: 'যদি মূল শাখায় কোনো নতুন কাজ না হয়ে থাকে, তবে পয়েন্টার সরাসরি এগিয়ে যায় (Fast-Forward)। কিন্তু উভয় শাখায় নতুন কমিট থাকলে গিট কমন অ্যানসেস্টর ব্যবহার করে একটি মার্জ কমিট বানায় (3-Way Merge)।',
    },
    tags: ['branching', 'merge', 'conflict'],
    relatedCommands: ['git.branch', 'git.rebase', 'git.status'],
  },
  {
    id: 'git.rebase',
    command: 'git rebase',
    slug: 'rebase',
    order: 13,
    frequentlyUsed: false,
    whenNotToUse: 'Never rebase commits already pushed to a shared branch — it rewrites public history.',
    whenNotToUseBn: 'শেয়ার্ড ব্রাঞ্চে পুশ করা কমিটে কখনো রিব্যাস করবেন না — এটি পাবলিক ইতিহাস বদলে দেয়।',
    relatedLessons: ['git.fundamentals.branch', 'git.fundamentals.commit'],
    aliases: [],
    searchKeywords: ['replay', 'linear', 'rewrite', 'interactive', 'squash', 'history'],
    category: 'branching',
    difficulty: 'intermediate',
    title: 'Reapply Commits on Top of Another Base Tip',
    titleBn: 'লিনিয়ার ইতিহাসে নতুন বেসের ওপর কমিট প্রতিস্থাপন',
    whatItDoes: 'Reapplies commits from your current branch on top of another base tip, creating a clean linear commit history without merge bubbles.',
    whatItDoesBn: 'বর্তমান ব্রাঞ্চের কমিটগুলোকে অন্য ব্রাঞ্চের সর্বশেষ কমিটের পর ধারাবাহিকভাবে বসিয়ে সরলরৈখিক ইতিহাস দেয়।',
    whenToUse: 'When updating your local feature branch with the latest `main` changes before opening a pull request.',
    whenToUseBn: 'পুল রিকোয়েস্ট দেওয়ার আগে প্রধান ব্রাঞ্চের নতুন কোড এনে নিজের হিস্ট্রি পরিষ্কার রাখতে।',
    syntax: 'git rebase [options] <upstream>',
    whatHappensInternally: 'Finds the common ancestor, saves temporary diffs of your branch\'s commits, resets your branch to upstream, and replays each commit sequentially with new hashes.',
    whatHappensInternallyBn: 'কমন অ্যানসেস্টর খুঁজে আপনার কমিটগুলো আলাদা করে টার্গেট ব্রাঞ্চে একটি একটি করে পুনরায় প্লে করে নতুন হ্যাশ তৈরি করে।',
    examples: [
      {
        command: 'git rebase main',
        description: 'Rebase current branch onto the tip of main',
        descriptionBn: 'বর্তমান শাখাকে main শাখার ওপরে রিব্যাস করুন',
      },
      {
        command: 'git rebase -i HEAD~3',
        description: 'Interactive rebase: squash, edit, reword, or drop the last 3 commits',
        descriptionBn: 'ইন্টারেক্টিভ রিব্যাস: পূর্ববর্তী ৩টি কমিট মার্জ বা এডিট করা',
      },
    ],
    commonOptions: [
      { flag: '-i, --interactive', description: 'Make a list of the commits which are about to be rebased and open editor', descriptionBn: 'ইন্টারেক্টিভ মোডে কমিট সাজানো' },
      { flag: '--continue', description: 'Restart the rebasing process after resolving a merge conflict', descriptionBn: 'কনফ্লিক্ট সমাধানের পর রিব্যাস চালু রাখা' },
      { flag: '--abort', description: 'Abort the rebase operation and reset HEAD to the original branch', descriptionBn: 'রিব্যাস বাতিল করে পূর্বাবস্থায় ফেরা' },
    ],
    commonMistakes: [
      {
        mistake: 'Rebasing commits that have already been pushed to a public/shared branch',
        mistakeBn: 'অন্যদের সাথে শেয়ার করা পাবলিক ব্রাঞ্চে রিব্যাস চালানো (The Golden Rule of Rebasing)',
        howToAvoid: 'Never rebase public shared branches; only rebase local, private topic branches.',
        howToAvoidBn: 'পাবলিক ব্রাঞ্চে কখনোই রিব্যাস করবেন না; শুধুমাত্র নিজের লোকাল ব্রাঞ্চে ব্যবহার করুন।',
      },
    ],
    interviewInsight: {
      question: 'What is the Golden Rule of Git Rebase?',
      questionBn: 'Git Rebase এর সুবর্ণ নিয়ম (Golden Rule) কী?',
      answer: 'Never rebase commits that exist outside your local repository and have been published to a shared branch. Rebasing rewrites commit SHA hashes, creating divergent history that causes serious confusion for teammates.',
      answerBn: 'শেয়ার্ড বা পাবলিক ব্রাঞ্চে কখনোই রিব্যাস করতে নেই। কারণ রিব্যাস কমিটের হ্যাশ পরিবর্তন করে ইতিহাস নতুন করে লেখে, যা সহকর্মীদের কাজে মারাত্মক বিভ্রান্তি তৈরি করে।',
    },
    tags: ['branching', 'rebase', 'history-rewrite', 'advanced'],
    relatedCommands: ['git.merge', 'git.log', 'git.reset'],
  },
  {
    id: 'git.remote',
    command: 'git remote',
    slug: 'remote',
    order: 14,
    frequentlyUsed: false,
    whenNotToUse: 'Do not add a duplicate remote without checking first — run git remote -v to inspect existing entries.',
    whenNotToUseBn: 'যাচাই না করে ডুপ্লিকেট রিমোট যোগ করবেন না — আগে git remote -v দিয়ে দেখে নিন।',
    relatedLessons: ['git.fundamentals.remote-repository', 'git.fundamentals.git-vs-github', 'github.basics.origin-and-upstream', 'github.collaboration.configuring-upstream'],
    aliases: [],
    searchKeywords: ['origin', 'url', 'upstream', 'server', 'github'],
    category: 'remote',
    difficulty: 'beginner',
    title: 'Manage Tracked Repositories',
    titleBn: 'রিমোট সার্ভার সংযোগ পরিচালনা',
    whatItDoes: 'Manages the set of tracked remote repositories whose branches you track.',
    whatItDoesBn: 'GitHub বা GitLab এর মতো রিমোট সার্ভারের সংযোগ যোগ, দেখা বা মুছে ফেলে।',
    whenToUse: 'When connecting a local repository to GitHub, or inspecting remote URLs.',
    whenToUseBn: 'লোকাল রিপোজিটরিকে গিটহাবের সাথে যুক্ত করার সময়।',
    syntax: 'git remote [options] [add | remove | rename | -v]',
    whatHappensInternally: 'Updates configuration entries inside `.git/config` under `[remote "<name>"]` storing the remote fetch/push URLs.',
    whatHappensInternallyBn: '`.git/config` ফাইলে রিমোটের নাম ও URL সংরক্ষণ করে।',
    examples: [
      {
        command: 'git remote -v',
        description: 'List all configured remotes with their fetch and push URLs',
        descriptionBn: 'বর্তমান রিমোট সার্ভারগুলোর নাম ও URL দেখুন',
        output: 'origin  https://github.com/user/gitverse.git (fetch)\norigin  https://github.com/user/gitverse.git (push)',
      },
      {
        command: 'git remote add origin https://github.com/user/gitverse.git',
        description: 'Add a new remote named origin pointing to GitHub',
        descriptionBn: 'origin নামে নতুন রিমোট সংযোগ যোগ করুন',
      },
    ],
    commonOptions: [
      { flag: '-v, --verbose', description: 'Be a little more verbose and show remote url after name', descriptionBn: 'রিমোটের নাম ও URL বিস্তারিত দেখা' },
    ],
    interviewInsight: {
      question: 'Is "origin" a special keyword in Git?',
      questionBn: '"origin" কি গিটের কোনো বিশেষ সংরক্ষিত কি-ওয়ার্ড?',
      answer: 'No. "origin" is merely a default convention for the primary remote repository name created automatically by `git clone`. You can name your remote anything (e.g. `upstream`, `production`, `github`).',
      answerBn: 'না। "origin" কোনো সংরক্ষিত শব্দ নয়, এটি শুধুমাত্র একটি বহুল ব্যবহৃত কনভেনশন বা ডিফল্ট নাম। আপনি যেকোনো নাম দিতে পারেন।',
    },
    tags: ['remote', 'github', 'setup'],
    relatedCommands: ['git.push', 'git.pull', 'git.fetch'],
  },
  {
    id: 'git.fetch',
    command: 'git fetch',
    slug: 'fetch',
    order: 15,
    frequentlyUsed: false,
    whenNotToUse: 'Do not use git fetch when you actually want your files updated — it only downloads; follow with a merge or use pull.',
    whenNotToUseBn: 'ফাইল আপডেট চাইলে শুধু git fetch যথেষ্ট নয় — এটি কেবল ডাউনলোড করে; পরে মার্জ করুন বা pull ব্যবহার করুন।',
    relatedLessons: ['git.fundamentals.remote-repository', 'github.repositories.fetch-from-github', 'github.collaboration.keep-fork-updated'],
    aliases: [],
    searchKeywords: ['download', 'remote', 'update', 'prune', 'safe'],
    category: 'remote',
    difficulty: 'intermediate',
    title: 'Download Objects & Refs from Remote',
    titleBn: 'রিমোট থেকে কোড অবজেক্ট ডাউনলোড করা (মার্জ ছাড়া)',
    whatItDoes: 'Downloads commits, files, and refs from a remote repository into your local repository without altering your working tree or merging into current branches.',
    whatItDoesBn: 'রিমোটের সমস্ত নতুন পরিবর্তন লোকাল রিপোতে নামিয়ে আনে কিন্তু আপনার বর্তমান কোডে স্বয়ংক্রিয়ভাবে কোনো মার্জ করে না।',
    whenToUse: 'When you want to see what teammates have pushed without disrupting your own current work.',
    whenToUseBn: 'সহকর্মীরা কী পুশ করেছে তা নিজের কোড পরিবর্তন না করেই পর্যবেক্ষণ করতে।',
    syntax: 'git fetch [<remote>]',
    whatHappensInternally: 'Updates remote tracking references under `.git/refs/remotes/<remote>/` and stores downloaded objects in `.git/objects/`. Working files and `HEAD` remain untouched.',
    whatHappensInternallyBn: '`.git/refs/remotes/` এ রিমোট পয়েন্টার আপডেট করে এবং অবজেক্ট ডাউনলোড করে। ওয়ার্কিং ফাইলে কোনো হাত দেয় না।',
    examples: [
      {
        command: 'git fetch origin',
        description: 'Fetch all branches and commits from remote origin',
        descriptionBn: 'রিমোট origin থেকে সমস্ত নতুন পরিবর্তন ডাউনলোড করুন',
      },
      {
        command: 'git fetch --prune',
        description: 'Remove local remote-tracking branches that no longer exist on the remote',
        descriptionBn: 'রিমোটে মুছে যাওয়া ব্রাঞ্চগুলোর লোকাল ট্র্যাকিং মুছে পরিষ্কার করা',
      },
    ],
    commonOptions: [
      { flag: '--prune', description: 'Before fetching, remove any remote-tracking references that no longer exist on the remote', descriptionBn: 'রিমোটে ডিলিট হওয়া ব্রাঞ্চগুলো লোকাল থেকেও মুছে ফেলা' },
      { flag: '--all', description: 'Fetch all remotes', descriptionBn: 'সমস্ত রিমোট থেকে ডাটা ফেচ করা' },
    ],
    interviewInsight: {
      question: 'Why is `git fetch` safer than `git pull`?',
      questionBn: '`git pull` এর তুলনায় `git fetch` কেন অধিক নিরাপদ?',
      answer: '`git fetch` only downloads data into your local Git database without modifying your working files or triggering unexpected merge conflicts. You can review the fetched commits with `git log origin/main` before deciding to merge.',
      answerBn: '`git fetch` কোনো স্বয়ংক্রিয় মার্জ করে না, ফলে আপনার বর্তমান কোডে কোনো কনফ্লিক্ট বা অনাকাঙ্ক্ষিত পরিবর্তন হয় না। কোড দেখে নিয়ে পরে মার্জ করা যায়।',
    },
    tags: ['remote', 'fetch', 'download'],
    relatedCommands: ['git.pull', 'git.push', 'git.merge'],
  },
  {
    id: 'git.pull',
    command: 'git pull',
    slug: 'pull',
    order: 16,
    frequentlyUsed: true,
    whenNotToUse: 'Avoid git pull with precious uncommitted local changes — stash or commit first to prevent surprise merges.',
    whenNotToUseBn: 'গুরুত্বপূর্ণ আনকমিটেড পরিবর্তন থাকা অবস্থায় pull করবেন না — আগে stash বা commit করে নিন।',
    relatedLessons: ['git.fundamentals.remote-repository', 'github.repositories.pull-changes', 'github.team.sync-before-work'],
    aliases: ['pl'],
    searchKeywords: ['sync', 'update', 'fetch', 'merge', 'download', 'daily'],
    category: 'remote',
    difficulty: 'beginner',
    title: 'Fetch and Integrate with Another Repository',
    titleBn: 'রিমোট থেকে কোড এনে লোকাল কোডে মার্জ করা',
    whatItDoes: 'Incorporates changes from a remote repository into the current branch. Equivalent to running `git fetch` followed immediately by `git merge`.',
    whatItDoesBn: 'রিমোট সার্ভার থেকে নতুন কমিটগুলো নামিয়ে এনে সরাসরি বর্তমান ব্রাঞ্চের সাথে মার্জ করে।',
    whenToUse: 'When beginning your workday or before opening a pull request to synchronize with teammate contributions.',
    whenToUseBn: 'কাজের শুরুতে বা পুশ করার আগে টিম মেম্বারদের কোডের সাথে নিজের কোড আপডেট করতে।',
    syntax: 'git pull [options] [<remote>] [<branch>]',
    whatHappensInternally: 'Executes `git fetch` behind the scenes, and then executes `git merge FETCH_HEAD` into the checked-out branch.',
    whatHappensInternallyBn: 'পটভূমিতে প্রথমে `git fetch` চালায় এবং সাথে সাথে `git merge` চালিয়ে ফাইল আপডেট করে।',
    examples: [
      {
        command: 'git pull origin main',
        description: 'Fetch and merge origin/main into current branch',
        descriptionBn: 'origin/main থেকে পরিবর্তন এনে লোকাল ব্রাঞ্চে মার্জ করুন',
      },
      {
        command: 'git pull --rebase origin main',
        description: 'Fetch and rebase local commits on top of incoming remote commits',
        descriptionBn: 'মার্জ কমিট ছাড়া ক্লিন রিব্যাস দিয়ে কোড আপডেট করা',
      },
    ],
    commonOptions: [
      { flag: '--rebase', description: 'Rebase the current branch on top of the upstream branch after fetch', descriptionBn: 'মার্জের বদলে রিব্যাস করে আপডেট করা' },
    ],
    interviewInsight: {
      question: 'What is the exact composition of `git pull`?',
      questionBn: '`git pull` মূলত কোন দুটি কমান্ডের সমন্বয়ে গঠিত?',
      answer: '`git pull = git fetch + git merge`. When run with `--rebase`, it is `git fetch + git rebase`.',
      answerBn: '`git pull = git fetch + git merge`। আর `--rebase` ফ্ল্যাগ দিলে এটি `git fetch + git rebase` হিসেবে কাজ করে।',
    },
    tags: ['remote', 'pull', 'sync'],
    relatedCommands: ['git.fetch', 'git.push', 'git.merge'],
  },
  {
    id: 'git.push',
    command: 'git push',
    slug: 'push',
    order: 17,
    frequentlyUsed: true,
    whenNotToUse: 'Never force-push to a shared branch — you can permanently erase teammates’ commits.',
    whenNotToUseBn: 'শেয়ার্ড ব্রাঞ্চে কখনো ফোর্স-পুশ করবেন না — এতে সহকর্মীদের কমিট চিরতরে মুছে যেতে পারে।',
    relatedLessons: ['git.fundamentals.remote-repository', 'github.repositories.push-to-github'],
    aliases: ['ps'],
    searchKeywords: ['upload', 'publish', 'share', 'upstream', 'daily'],
    category: 'remote',
    difficulty: 'beginner',
    title: 'Update Remote Refs and Associated Objects',
    titleBn: 'লোকাল কমিট রিমোট সার্ভারে আপলোড করা',
    whatItDoes: 'Updates remote refs using local refs, uploading the necessary commit objects, trees, and blobs to make the remote match.',
    whatItDoesBn: 'আপনার লোকাল ব্রাঞ্চের নতুন সমস্ত কমিট রিমোট সার্ভারে (যেমন GitHub) আপলোড করে।',
    whenToUse: 'After making commits locally and wanting to share them with teammates or create a Pull Request.',
    whenToUseBn: 'লোকালে কমিট করার পর কোড ব্যাকআপ রাখতে বা সহকর্মীদের সাথে শেয়ার করতে।',
    syntax: 'git push [options] [<remote>] [<branch>]',
    whatHappensInternally: 'Negotiates missing objects with the remote server, packs required blobs/trees/commits into a packfile, streams it over SSH/HTTPS, and updates the remote branch ref.',
    whatHappensInternallyBn: 'প্রয়োজনীয় অবজেক্টগুলো প্যাক করে রিমোট সার্ভারে পাঠায় এবং রিমোট ব্রাঞ্চ পয়েন্টার আপডেট করে।',
    examples: [
      {
        command: 'git push origin main',
        description: 'Push commits from local main branch to remote origin',
        descriptionBn: 'লোকাল main ব্রাঞ্চের কমিট রিমোট সার্ভারে পুশ করুন',
      },
      {
        command: 'git push -u origin feature/auth',
        description: 'Push new branch and set up upstream tracking link',
        descriptionBn: 'নতুন ব্রাঞ্চ পুশ করে আপস্ট্রিম ট্র্যাকিং লিঙ্ক সেট করা',
      },
    ],
    commonOptions: [
      { flag: '-u, --set-upstream', description: 'For every branch that is up to date or successfully pushed, add upstream tracking reference', descriptionBn: 'ভবিষ্যতের জন্য আপস্ট্রিম ট্র্যাকিং লিঙ্ক সেট করা' },
      { flag: '--force-with-lease', description: 'Safer force push that ensures nobody else has pushed commits in the meantime', descriptionBn: 'সুরক্ষিত ফোর্স পুশ যা অন্য কারো নতুন কাজ নষ্ট হওয়া রোধ করে' },
    ],
    commonMistakes: [
      {
        mistake: 'Carelessly using `git push --force` which overwrites teammate commits on remote',
        mistakeBn: 'নির্বিচারে `git push --force` দিয়ে অন্যের পুশ করা কোড মুছে ফেলা',
        howToAvoid: 'Use `--force-with-lease` instead, which fails if remote branch has new commits you haven\'t inspected.',
        howToAvoidBn: 'সর্বদা `--force-with-lease` ব্যবহার করুন যাতে নতুন পুশ থাকলে তা বন্ধ থাকে।',
      },
    ],
    interviewInsight: {
      question: 'What is the difference between `git push --force` and `git push --force-with-lease`?',
      questionBn: '`--force` এবং `--force-with-lease` এর মধ্যে মূল পার্থক্য কী?',
      answer: '`git push --force` blindly overwrites the remote branch even if a teammate pushed new commits while you were working. `git push --force-with-lease` only allows the overwrite if your local remote-tracking reference matches the actual remote tip, preventing team code loss.',
      answerBn: '`--force` অন্ধের মতো রিমোট ওভাররাইট করে অন্যের কোড নষ্ট করতে পারে। কিন্তু `--force-with-lease` যাচাই করে যে রিমোটে আপনার অগোচরে কেউ নতুন পুশ করেছে কিনা; থাকলে এটি পুশ আটকে দেয়।',
    },
    tags: ['remote', 'push', 'sync', 'github'],
    relatedCommands: ['git.pull', 'git.fetch', 'git.remote'],
  },
  {
    id: 'git.restore',
    command: 'git restore',
    slug: 'restore',
    order: 18,
    frequentlyUsed: false,
    whenNotToUse: 'Do not use git restore on files you might still need — discarded working-tree changes cannot be recovered.',
    whenNotToUseBn: 'প্রয়োজন হতে পারে এমন ফাইলে git restore চালাবেন না — বাতিল করা পরিবর্তন ফিরিয়ে আনা যায় না।',
    relatedLessons: ['git.fundamentals.working-directory', 'git.fundamentals.staging-area'],
    aliases: [],
    searchKeywords: ['unstage', 'discard', 'undo', 'revert file', 'recover'],
    category: 'recovery',
    difficulty: 'beginner',
    title: 'Restore Working Tree Files',
    titleBn: 'ফাইল পূর্বাবস্থায় ফিরিয়ে আনা বা আনস্টেজ করা',
    whatItDoes: 'Restores specified paths in the working tree with some contents from a restore source (index or a commit).',
    whatItDoesBn: 'ওয়ার্কিং ডিরেক্টরিতে করা অবাঞ্ছিত পরিবর্তন বাতিল করতে বা স্টেজিং থেকে ফাইল আনস্টেজ করতে ব্যবহৃত হয়।',
    whenToUse: 'When you want to discard unwanted local experimental changes or unstage a file mistakenly added via `git add`.',
    whenToUseBn: 'যখন কোনো ফাইলে করা পরিবর্তন ফেলে দিয়ে আগের অবস্থায় ফিরতে চান।',
    syntax: 'git restore [options] <pathspec>...',
    whatHappensInternally: 'Overwrites the file on disk with the blob version from `.git/index` or specified commit tree.',
    whatHappensInternallyBn: 'ডিস্কের ফাইলটিকে স্টেজিং ইনডেক্স বা নির্দিষ্ট কমিটের ব্লব কনটেন্ট দিয়ে ওভাররাইট করে।',
    examples: [
      {
        command: 'git restore src/App.tsx',
        description: 'Discard all unstaged modifications in App.tsx back to the clean version',
        descriptionBn: 'App.tsx ফাইলের আনস্টেজড পরিবর্তন বাতিল করে আগের কোডে ফিরে যাওয়া',
      },
      {
        command: 'git restore --staged config.json',
        description: 'Unstage config.json without losing your edits in the working tree',
        descriptionBn: 'ফাইল এডিট অক্ষত রেখে স্টেজিং এরিয়া থেকে আনস্টেজ করা',
      },
    ],
    commonOptions: [
      { flag: '--staged', description: 'Restore the index instead of the working tree (unstage files)', descriptionBn: 'ফাইলকে স্টেজিং ইনডেক্স থেকে বের (unstage) করা' },
      { flag: '--source=<tree>', description: 'Restore the working tree files with the content from the given commit', descriptionBn: 'নির্দিষ্ট কোনো কমিট থেকে ফাইল রিস্টোর করা' },
    ],
    interviewInsight: {
      question: 'How does `git restore --staged <file>` differ from `git rm --cached <file>`?',
      questionBn: '`git restore --staged` এবং `git rm --cached` এর মধ্যে পার্থক্য কী?',
      answer: '`git restore --staged` merely unstages modified file changes while keeping the file tracked by Git. `git rm --cached` stops tracking the file entirely, staging a deletion for that file in the repository.',
      answerBn: '`git restore --staged` শুধুমাত্র বর্তমান পরিবর্তনকে আনস্টেজ করে কিন্তু ফাইল ট্র্যাকিং বজায় রাখে। আর `git rm --cached` ফাইলটির ট্র্যাকিং সম্পূর্ণ বন্ধ করে দেয়।',
    },
    tags: ['recovery', 'restore', 'unstage', 'undo'],
    relatedCommands: ['git.reset', 'git.checkout', 'git.status'],
  },
  {
    id: 'git.reset',
    command: 'git reset',
    slug: 'reset',
    order: 19,
    frequentlyUsed: false,
    whenNotToUse: 'Do not use git reset --hard on shared or pushed history — prefer git revert for public commits.',
    whenNotToUseBn: 'শেয়ার্ড বা পুশ করা ইতিহাসে git reset --hard ব্যবহার করবেন না — পাবলিক কমিটের জন্য revert ব্যবহার করুন।',
    relatedLessons: ['git.fundamentals.head', 'git.fundamentals.three-areas', 'git.fundamentals.commit'],
    aliases: [],
    searchKeywords: ['undo', 'uncommit', 'hard', 'soft', 'mixed', 'rewind', 'danger'],
    category: 'recovery',
    difficulty: 'intermediate',
    title: 'Reset Current HEAD to the Specified State',
    titleBn: 'কমিট পয়েন্টার রিসেট বা পূর্বের অবস্থায় ফেরানো',
    whatItDoes: 'Resets the current HEAD to the specified state, optionally updating the index and working tree to match.',
    whatItDoesBn: 'বর্তমান ব্রাঞ্চ পয়েন্টার বা HEAD কে পেছনের কোনো নির্দিষ্ট কমিটে ফিরিয়ে নেয়।',
    whenToUse: 'When you want to undo commits, unstage changes, or completely revert to an earlier project checkpoint.',
    whenToUseBn: 'ভুল কমিট আনডু করতে অথবা অতীতের কোনো নির্দিষ্ট সেভ পয়েন্টে ফিরতে।',
    syntax: 'git reset [options] [<commit>]',
    whatHappensInternally: 'Moves the current branch pointer (`refs/heads/<branch>`) backward. In `--soft`, index and working tree stay untouched. In `--mixed` (default), index is reset. In `--hard`, index and working tree are completely overwritten.',
    whatHappensInternallyBn: 'বর্তমান ব্রাঞ্চ পয়েন্টারকে পেছনের কমিটের দিকে ফিরিয়ে দেয়। `--soft` মোডে শুধু কমিট আনডু হয়, `--hard` মোডে কোডও ডিলিট হয়ে যায়।',
    examples: [
      {
        command: 'git reset --soft HEAD~1',
        description: 'Undo the last commit while keeping all changes staged in the index',
        descriptionBn: 'সর্বশেষ কমিট আনডু করুন কিন্তু কোড পরিবর্তনগুলো স্টেজ করা অবস্থায় রাখুন',
      },
      {
        command: 'git reset --mixed HEAD~1',
        description: 'Default reset: undo commit and unstage changes, keeping file edits on disk',
        descriptionBn: 'কমিট আনডু ও আনস্টেজ করুন কিন্তু ডিস্কের ফাইল সুরক্ষিত রাখুন',
      },
      {
        command: 'git reset --hard HEAD~1',
        description: 'Destructive reset: permanently discard the last commit and all file modifications',
        descriptionBn: 'সর্বশেষ কমিট এবং ফাইলে করা সব পরিবর্তন চিরতরে মুছে ফেলুন',
      },
    ],
    commonOptions: [
      { flag: '--soft', description: 'Does not touch the index file or the working tree at all', descriptionBn: 'স্টেজিং ইনডেক্স ও ওয়ার্কিং ট্রির কোড অক্ষত রেখে কেবল কমিট পেছানো' },
      { flag: '--mixed', description: 'Resets the index but not the working tree (default)', descriptionBn: 'ইনডেক্স রিসেট করে কিন্তু ডিস্কের ফাইল রাখে (ডিফল্ট)' },
      { flag: '--hard', description: 'Resets the index and working tree. Any changes are discarded permanently', descriptionBn: 'ইনডেক্স ও ডিস্কের কোড মুছে সম্পূর্ণ পরিষ্কার করা (সতর্কতা আবশ্যক)' },
    ],
    commonMistakes: [
      {
        mistake: 'Using `git reset --hard` when you meant `--soft`, destroying uncommitted work',
        mistakeBn: '`--soft` এর জায়গায় ভুল করে `--hard` চালিয়ে ফেলে সমস্ত কোড হারিয়ে ফেলা',
        howToAvoid: 'Use `git reflog` immediately to find the dangling commit hash and restore it.',
        howToAvoidBn: 'ভুল হলে দ্রুত `git reflog` চালিয়ে হারিয়ে যাওয়া কমিট খুঁজে রিকভার করুন।',
      },
    ],
    interviewInsight: {
      question: 'Explain the difference between `git reset --soft`, `--mixed`, and `--hard`.',
      questionBn: '`git reset` এর `--soft`, `--mixed` এবং `--hard` মোডের পার্থক্য কী?',
      answer: 'All three move the HEAD branch pointer backward. `--soft` leaves both staging index and working tree untouched. `--mixed` (the default) resets the staging index but keeps working tree edits. `--hard` resets both staging index and working tree, permanently discarding changes.',
      answerBn: 'তিনটি মোডই ব্রাঞ্চ পয়েন্টার পেছনে নেয়। `--soft` এ স্টেজিং ও ফাইল দুই-ই থাকে। `--mixed` এ স্টেজিং খালি হয় কিন্তু ফাইল থাকে। আর `--hard` এ স্টেজিং ও ডিস্কের ফাইল উভয় স্থান থেকেই পরিবর্তন মুছে যায়।',
    },
    tags: ['recovery', 'reset', 'undo', 'danger'],
    relatedCommands: ['git.restore', 'git.revert', 'git.checkout'],
  },
  {
    id: 'git.cat-file',
    command: 'git cat-file',
    slug: 'cat-file',
    order: 20,
    frequentlyUsed: false,
    whenNotToUse: 'Do not use plumbing output in scripts without -p/-t; raw object bytes need the right flag.',
    whenNotToUseBn: 'পতাকা ছাড়া স্ক্রিপ্টে প্লাম্বিং আউটপুট ব্যবহার করবেন না; কাঁচা অবজেক্ট বাইটে সঠিক ফ্ল্যাগ দরকার।',
    relatedLessons: ['git.internals.objects-overview', 'git.internals.blob-objects'],
    aliases: [],
    searchKeywords: ['plumbing', 'internals', 'inspect object', 'object type', 'advanced'],
    category: 'advanced',
    difficulty: 'advanced',
    title: 'Inspect Git Objects (Plumbing)',
    titleBn: 'গিট অবজেক্ট পরিদর্শন (প্লাম্বিং)',
    whatItDoes: 'Displays the content or type of any object in the object database. An advanced, read-only inspection tool.',
    whatItDoesBn: 'অবজেক্ট ডাটাবেসের যেকোনো অবজেক্টের কন্টেন্ট বা টাইপ দেখায়। অ্যাডভান্সড, শুধু-পড়া পরিদর্শন টুল।',
    whenToUse: 'When learning internals and you want to see what a blob, tree, commit, or tag actually contains.',
    whenToUseBn: 'ইন্টারনালস শেখার সময় ব্লব, ট্রি, কমিট বা ট্যাগে আসলে কী আছে দেখতে চাইলে।',
    syntax: 'git cat-file (-p | -t | -s) <object>',
    whatHappensInternally: 'Looks up the object by hash in .git/objects (or packs) and pretty-prints (-p), reports its type (-t), or reports its size (-s). Nothing is written.',
    whatHappensInternallyBn: '.git/objects (বা প্যাক) থেকে হ্যাশে অবজেক্ট খুঁজে সুন্দরভাবে দেখায় (-p), টাইপ জানায় (-t) বা আকার জানায় (-s)। কিছু লেখা হয় না।',
    examples: [
      {
        command: 'git cat-file -p HEAD',
        description: 'Pretty-print whatever object HEAD resolves to',
        descriptionBn: 'HEAD যে অবজেক্টে পৌঁছায় তা সুন্দরভাবে দেখুন',
      },
      {
        command: 'git cat-file -t 9f3a2c1',
        description: 'Report only the object type (blob, tree, commit, or tag)',
        descriptionBn: 'শুধু অবজেক্ট টাইপ জানুন (ব্লব, ট্রি, কমিট বা ট্যাগ)',
      },
    ],
    commonOptions: [
      { flag: '-p', description: 'Pretty-print the object content based on its type', descriptionBn: 'টাইপ অনুযায়ী অবজেক্ট কন্টেন্ট সুন্দরভাবে দেখানো' },
      { flag: '-t', description: 'Show only the object type instead of content', descriptionBn: 'কন্টেন্টের বদলে শুধু অবজেক্ট টাইপ দেখানো' },
      { flag: '-s', description: 'Show only the object size in bytes', descriptionBn: 'শুধু বাইটে অবজেক্ট আকার দেখানো' },
    ],
    tags: ['plumbing', 'internals', 'advanced', 'objects', 'inspect'],
    relatedCommands: ['git.show', 'git.log'],
  },
  {
    id: 'git.rev-parse',
    command: 'git rev-parse',
    slug: 'rev-parse',
    order: 21,
    frequentlyUsed: false,
    whenNotToUse: 'Avoid parsing its output by hand in tutorials; prefer git status and git log for daily questions.',
    whenNotToUseBn: 'টিউটোরিয়ালে হাতে আউটপুট পার্স এড়িয়ে চলুন; দৈনন্দিন প্রশ্নে git status ও git log ব্যবহার করুন।',
    relatedLessons: ['git.internals.what-is-a-reference', 'git.internals.head-deep-dive'],
    aliases: [],
    searchKeywords: ['plumbing', 'internals', 'resolve reference', 'object id', 'hash', 'advanced'],
    category: 'advanced',
    difficulty: 'advanced',
    title: 'Resolve References to Object IDs (Plumbing)',
    titleBn: 'রেফারেন্স থেকে অবজেক্ট ID (প্লাম্বিং)',
    whatItDoes: 'Translates any reference expression (HEAD, branch names, HEAD~3, tags) into the raw object hash it points at.',
    whatItDoesBn: 'যেকোনো রেফারেন্স এক্সপ্রেশন (HEAD, ব্রাঞ্চ নাম, HEAD~3, ট্যাগ) কাঁচা অবজেক্ট হ্যাশে অনুবাদ করে।',
    whenToUse: 'When you need the exact hash behind a name — for inspection, scripting, or understanding pointer chains.',
    whenToUseBn: 'নামের পেছনে নির্ভুল হ্যাশ দরকার হলে — পরিদর্শন, স্ক্রিপ্টিং বা পয়েন্টার শৃঙ্খল বোঝায়।',
    syntax: 'git rev-parse <expression>',
    whatHappensInternally: 'Walks symbolic refs, branch files, reflog syntax, and ancestry operators to a single object ID. Conceptually: it answers "what hash does this name mean right now?"',
    whatHappensInternallyBn: 'সিম্বলিক ref, ব্রাঞ্চ ফাইল, রিফ্লগ সিনট্যাক্স ও অ্যানসেস্ট্রি অপারেটর হেঁটে এক অবজেক্ট ID-তে পৌঁছায়। ধারণাগতভাবে: "এই নাম এখন কোন হ্যাশ বোঝায়?" এর উত্তর দেয়।',
    examples: [
      {
        command: 'git rev-parse HEAD',
        description: 'Show the commit ID HEAD currently resolves to',
        descriptionBn: 'HEAD বর্তমানে যে কমিট ID-তে পৌঁছায় তা দেখুন',
        output: '9f3a2c1e4b5d6f708192a3b4c5d6e7f8090a1b2c',
      },
      {
        command: 'git rev-parse --show-toplevel',
        description: 'Print the working tree root of the current repository',
        descriptionBn: 'বর্তমান রিপোজিটরির ওয়ার্কিং ট্রি রুট দেখুন',
      },
    ],
    commonOptions: [
      { flag: '--show-toplevel', description: 'Print the absolute path of the working tree root', descriptionBn: 'ওয়ার্কিং ট্রি রুটের পরম পথ দেখানো' },
      { flag: '--verify', description: 'Verify the expression names exactly one valid object', descriptionBn: 'যাচাই করা এক্সপ্রেশন ঠিক একটি বৈধ অবজেক্ট নির্দেশ করে' },
    ],
    tags: ['plumbing', 'internals', 'advanced', 'references', 'hash'],
    relatedCommands: ['git.show', 'git.log'],
  },
  {
    id: 'git.ls-tree',
    command: 'git ls-tree',
    slug: 'ls-tree',
    order: 22,
    frequentlyUsed: false,
    whenNotToUse: 'Do not use it to browse checked-out files; plain ls and your editor are faster for that.',
    whenNotToUseBn: 'চেক-আউট ফাইল দেখতে ব্যবহার করবেন না; তাতে সাধারণ ls ও এডিটর দ্রুত।',
    relatedLessons: ['git.internals.tree-objects', 'git.internals.commit-objects'],
    aliases: [],
    searchKeywords: ['plumbing', 'internals', 'tree', 'list snapshot', 'advanced'],
    category: 'advanced',
    difficulty: 'advanced',
    title: 'List Tree Objects (Plumbing)',
    titleBn: 'ট্রি অবজেক্ট তালিকা (প্লাম্বিং)',
    whatItDoes: 'Lists the entries of any tree object: file modes, object types, hashes, and names — without checking anything out.',
    whatItDoesBn: 'যেকোনো ট্রি অবজেক্টের এন্ট্রি তালিকা করে: ফাইল মোড, অবজেক্ট টাইপ, হ্যাশ ও নাম — কিছু চেকআউট না করে।',
    whenToUse: 'When you want to see exactly what a commit snapshot contains at the object level.',
    whenToUseBn: 'কোনো কমিট স্ন্যাপশটে অবজেক্ট স্তরে ঠিক কী আছে দেখতে চাইলে।',
    syntax: 'git ls-tree [<options>] <tree-ish>',
    whatHappensInternally: 'Reads the named tree object and prints one line per entry. Conceptually: it renders the directory listing Git stored.',
    whatHappensInternallyBn: 'নাম দেওয়া ট্রি অবজেক্ট পড়ে প্রতি এন্ট্রিতে এক লাইন দেখায়। ধারণাগতভাবে: গিটের সংরক্ষিত ডিরেক্টরি তালিকা রেন্ডার করে।',
    examples: [
      {
        command: 'git ls-tree HEAD',
        description: 'List the root tree of the current commit',
        descriptionBn: 'বর্তমান কমিটের রুট ট্রি তালিকা করুন',
        output: '100644 blob 9f3a2c1\tREADME.md\n040000 tree ab12cd3\tsrc',
      },
    ],
    commonOptions: [
      { flag: '-r', description: 'Recurse into subtrees and list nested entries', descriptionBn: 'সাবট্রিতে ঢুকে নেস্টেড এন্ট্রি তালিকা করা' },
      { flag: '--name-only', description: 'Show only entry names without modes and hashes', descriptionBn: 'মোড ও হ্যাশ ছাড়া শুধু এন্ট্রি নাম দেখানো' },
    ],
    tags: ['plumbing', 'internals', 'advanced', 'tree', 'snapshot'],
    relatedCommands: ['git.show', 'git.log'],
  },
  {
    id: 'git.show-ref',
    command: 'git show-ref',
    slug: 'show-ref',
    order: 23,
    frequentlyUsed: false,
    whenNotToUse: 'For everyday branch listing, git branch is friendlier and shows the current branch.',
    whenNotToUseBn: 'দৈনন্দিন ব্রাঞ্চ তালিকায় git branch বন্ধুসুলভ ও বর্তমান ব্রাঞ্চ দেখায়।',
    relatedLessons: ['git.internals.what-is-a-reference', 'git.internals.branch-references'],
    aliases: [],
    searchKeywords: ['plumbing', 'internals', 'references', 'list refs', 'advanced'],
    category: 'advanced',
    difficulty: 'advanced',
    title: 'List References (Plumbing)',
    titleBn: 'রেফারেন্স তালিকা (প্লাম্বিং)',
    whatItDoes: 'Displays every reference in the repository alongside the object hash it currently points to.',
    whatItDoesBn: 'রিপোজিটরির প্রতিটি রেফারেন্স সাথে বর্তমানে যে অবজেক্ট হ্যাশের দিকে যায় তা দেখায়।',
    whenToUse: 'When learning internals and you want the complete map of names → hashes in one place.',
    whenToUseBn: 'ইন্টারনালস শেখার সময় এক জায়গায় নাম → হ্যাশের সম্পূর্ণ মানচিত্র চাইলে।',
    syntax: 'git show-ref [--head] [<pattern>...]',
    whatHappensInternally: 'Iterates refs/heads, refs/tags, refs/remotes (plus packed-refs) and prints each hash-name pair. Read-only.',
    whatHappensInternallyBn: 'refs/heads, refs/tags, refs/remotes (সাথে packed-refs) ঘুরে প্রতিটি হ্যাশ-নাম জোড়া দেখায়। শুধু-পড়া।',
    examples: [
      {
        command: 'git show-ref --head',
        description: 'List all references including HEAD',
        descriptionBn: 'HEAD-সহ সব রেফারেন্স তালিকা করুন',
        output: '9f3a2c1e... refs/heads/main\nab12cd34... refs/remotes/origin/main',
      },
    ],
    commonOptions: [
      { flag: '--head', description: 'Also show the HEAD reference itself', descriptionBn: 'HEAD রেফারেন্স নিজেও দেখানো' },
    ],
    tags: ['plumbing', 'internals', 'advanced', 'references'],
    relatedCommands: ['git.branch', 'git.log'],
  },
  {
    id: 'git.update-ref',
    command: 'git update-ref',
    slug: 'update-ref',
    order: 24,
    frequentlyUsed: false,
    whenNotToUse: 'Never use casually: it moves pointers with no safety checks. Prefer branch, reset, and switch.',
    whenNotToUseBn: 'কখনো হালকাভাবে ব্যবহার করবেন না: নিরাপত্তা যাচাই ছাড়া পয়েন্টার সরায়। branch, reset ও switch ব্যবহার করুন।',
    relatedLessons: ['git.internals.branch-references', 'git.internals.head-deep-dive'],
    aliases: [],
    searchKeywords: ['plumbing', 'internals', 'move reference', 'dangerous', 'advanced'],
    category: 'advanced',
    difficulty: 'advanced',
    title: 'Move a Reference Directly (Plumbing)',
    titleBn: 'সরাসরি রেফারেন্স সরানো (প্লাম্বিং)',
    whatItDoes: 'Writes a hash into a reference, moving a branch or tag pointer with no working-tree changes and no safety checks.',
    whatItDoesBn: 'রেফারেন্সে হ্যাশ লেখে, ওয়ার্কিং-ট্রি পরিবর্তন ও নিরাপত্তা যাচাই ছাড়া ব্রাঞ্চ বা ট্যাগ পয়েন্টার সরায়।',
    whenToUse: 'Almost never directly — understand it as the primitive behind branch creation, reset, and symbolic-ref updates.',
    whenToUseBn: 'প্রায় কখনো সরাসরি নয় — ব্রাঞ্চ তৈরি, রিসেট ও সিম্বলিক-ref আপডেটের পেছনে আদিম ক্রিয়া হিসেবে বুঝুন।',
    syntax: 'git update-ref <ref> <newvalue> [<oldvalue>]',
    whatHappensInternally: 'Overwrites the ref file (or packed-refs entry) and appends a reflog record. Conceptually: the raw "move pointer" operation every safe command wraps with checks.',
    whatHappensInternallyBn: 'ref ফাইল (বা packed-refs এন্ট্রি) ওভাররাইট করে ও রিফ্লগ রেকর্ড যোগ করে। ধারণাগতভাবে: কাঁচা "পয়েন্টার সরাও" ক্রিয়া যা প্রতিটি নিরাপদ কমান্ড যাচাইসহ মোড়ায়।',
    examples: [
      {
        command: 'git update-ref refs/heads/feature 9f3a2c1',
        description: 'Point branch feature at a specific commit (illustrative — prefer safe commands)',
        descriptionBn: 'ব্রাঞ্চ feature নির্দিষ্ট কমিটে বসান (উদাহরণ — নিরাপদ কমান্ড ব্যবহার করুন)',
      },
    ],
    commonOptions: [],
    commonMistakes: [
      {
        mistake: 'Moving refs by hand and orphaning commits',
        mistakeBn: 'হাতে ref সরিয়ে কমিট এতিম করা',
        howToAvoid: 'Use branch, reset, and switch, which validate before moving anything.',
        howToAvoidBn: 'branch, reset ও switch ব্যবহার করুন, যা সরানোর আগে যাচাই করে।',
      },
    ],
    tags: ['plumbing', 'internals', 'advanced', 'references', 'danger'],
    relatedCommands: ['git.branch', 'git.reset'],
  },
  {
    id: 'git.reflog',
    command: 'git reflog',
    slug: 'reflog',
    order: 25,
    frequentlyUsed: false,
    whenNotToUse: 'Do not treat it as a backup: entries expire and it never leaves your machine.',
    whenNotToUseBn: 'ব্যাকআপ ভাববেন না: এন্ট্রির মেয়াদ শেষ হয় ও মেশিন ছাড়ে না।',
    relatedLessons: ['git.internals.reflog', 'git.internals.unreachable-objects-expiry'],
    aliases: [],
    searchKeywords: ['reflog', 'recover', 'lost commit', 'undo reset', 'internals', 'history'],
    category: 'recovery',
    difficulty: 'advanced',
    title: 'Read the Reference Journal',
    titleBn: 'রেফারেন্স জার্নাল পড়ুন',
    whatItDoes: 'Shows the local journal of where HEAD and branches pointed after each movement — the basis of most commit recovery.',
    whatItDoesBn: 'প্রতিটি নড়াচড়ার পর HEAD ও ব্রাঞ্চ কোথায় ছিল তার লোকাল জার্নাল দেখায় — বেশিরভাগ কমিট উদ্ধারের ভিত্তি।',
    whenToUse: 'After a bad reset, deleted branch, or abandoned commit — to find the hash to restore.',
    whenToUseBn: 'ভুল রিসেট, মোছা ব্রাঞ্চ বা পরিত্যক্ত কমিটের পর — পুনরুদ্ধারের হ্যাশ খুঁজতে।',
    syntax: 'git reflog [show <ref>]',
    whatHappensInternally: 'Reads .git/logs/HEAD and per-branch logs: timestamped old-value → new-value records Git appends on every pointer movement. Local only; entries expire.',
    whatHappensInternallyBn: '.git/logs/HEAD ও প্রতি-ব্রাঞ্চ লগ পড়ে: প্রতিটি পয়েন্টার নড়াচড়ায় গিটের যোগ করা সময়-চিহ্নিত পুরনো-মান → নতুন-মান রেকর্ড। শুধু লোকাল; এন্ট্রির মেয়াদ শেষ হয়।',
    examples: [
      {
        command: 'git reflog',
        description: 'List recent HEAD movements with reasons',
        descriptionBn: 'কারণসহ সাম্প্রতিক HEAD নড়াচড়া তালিকা করুন',
        output: '9f3a2c1 HEAD@{0}: reset: moving to HEAD~2\nab12cd3 HEAD@{1}: commit: fix login validation',
      },
    ],
    commonOptions: [
      { flag: '--date=iso', description: 'Show timestamps so expiry windows are visible', descriptionBn: 'টাইমস্ট্যাম্প দেখানো যাতে মেয়াদ উইন্ডো দৃশ্যমান হয়' },
    ],
    tags: ['recovery', 'reflog', 'internals', 'undo', 'advanced'],
    relatedCommands: ['git.reset', 'git.log'],
  },
  {
    id: 'git.count-objects',
    command: 'git count-objects',
    slug: 'count-objects',
    order: 26,
    frequentlyUsed: false,
    whenNotToUse: 'Not a cleanup tool by itself — pair findings with git gc when action is needed.',
    whenNotToUseBn: 'একা পরিষ্কার টুল নয় — ব্যবস্থা দরকারে git gc-এর সাথে জুড়ুন।',
    relatedLessons: ['git.internals.loose-objects', 'git.internals.packfiles'],
    aliases: [],
    searchKeywords: ['plumbing', 'internals', 'disk usage', 'loose objects', 'pack', 'advanced'],
    category: 'advanced',
    difficulty: 'advanced',
    title: 'Report Object Store Usage (Plumbing)',
    titleBn: 'অবজেক্ট স্টোর ব্যবহার রিপোর্ট (প্লাম্বিং)',
    whatItDoes: 'Reports loose object counts, pack counts, and disk usage of the object database.',
    whatItDoesBn: 'অবজেক্ট ডাটাবেসের লুজ অবজেক্ট সংখ্যা, প্যাক সংখ্যা ও ডিস্ক ব্যবহার রিপোর্ট করে।',
    whenToUse: 'When curious how big the database is or whether packing would help.',
    whenToUseBn: 'ডাটাবেস কত বড় বা প্যাকিং সাহায্য করবে কিনা জানতে চাইলে।',
    syntax: 'git count-objects -v',
    whatHappensInternally: 'Counts files under .git/objects and summarizes pack indexes. Read-only.',
    whatHappensInternallyBn: '.git/objects-এর ফাইল গুনে প্যাক ইনডেক্স সারসংক্ষেপ দেয়। শুধু-পড়া।',
    examples: [
      {
        command: 'git count-objects -v',
        description: 'Verbose breakdown of loose objects, packs, and size',
        descriptionBn: 'লুজ অবজেক্ট, প্যাক ও আকারের বিস্তারিত বিবরণ',
        output: 'count: 12\nsize: 48 KiB\nin-pack: 2431\nsize-pack: 512 KiB',
      },
    ],
    commonOptions: [
      { flag: '-v', description: 'Verbose human-readable breakdown', descriptionBn: 'বিস্তারিত মানব-পাঠযোগ্য বিবরণ' },
    ],
    tags: ['plumbing', 'internals', 'advanced', 'storage'],
    relatedCommands: ['git.fetch', 'git.commit'],
  },
  {
    id: 'git.gc',
    command: 'git gc',
    slug: 'gc',
    order: 27,
    frequentlyUsed: false,
    whenNotToUse: 'Do not run expecting deleted commits back — gc removes, never recovers. Recover first, then let gc tidy.',
    whenNotToUseBn: 'মোছা কমিট ফেরত আশায় চালাবেন না — gc সরায়, উদ্ধার করে না। আগে উদ্ধার, তারপর gc-কে গোছাতে দিন।',
    relatedLessons: ['git.internals.garbage-collection', 'git.internals.unreachable-objects-expiry'],
    aliases: [],
    searchKeywords: ['plumbing', 'internals', 'cleanup', 'pack', 'prune', 'advanced', 'maintenance'],
    category: 'advanced',
    difficulty: 'advanced',
    title: 'Tidy the Object Database (Plumbing)',
    titleBn: 'অবজেক্ট ডাটাবেস গোছানো (প্লাম্বিং)',
    whatItDoes: 'Packs loose objects, prunes expired reflog entries, and deletes long-unreachable objects. Reachable history is never touched.',
    whatItDoesBn: 'লুজ অবজেক্ট প্যাক করে, মেয়াদোত্তীর্ণ রিফ্লগ এন্ট্রি ছাঁটে, দীর্ঘ-অপ্রাপ্য অবজেক্ট মোছে। পৌঁছানো ইতিহাস কখনো ছোঁয়া হয় না।',
    whenToUse: 'Rarely by hand — Git auto-runs housekeeping. Run it when you understand packing and want an explicit tidy.',
    whenToUseBn: 'হাতে কদাচিৎ — গিট স্বয়ংক্রিয় গৃহস্থালি চালায়। প্যাকিং বুঝে স্পষ্ট গোছানো চাইলে চালান।',
    syntax: 'git gc [--auto]',
    whatHappensInternally: 'Repacks objects, expires old reflog entries per configuration, and removes objects unreachable beyond grace periods. Conceptually: safe tidying with structural guarantees.',
    whatHappensInternallyBn: 'অবজেক্ট পুনঃপ্যাক করে, কনফিগারেশনমতে পুরনো রিফ্লগ এন্ট্রির মেয়াদ শেষ করে, গ্রেস পিরিয়ড পেরোনো অপ্রাপ্য অবজেক্ট সরায়। ধারণাগতভাবে: গাঠনিক গ্যারান্টিসহ নিরাপদ গোছানো।',
    examples: [
      {
        command: 'git gc',
        description: 'Run a full housekeeping pass over the object database',
        descriptionBn: 'অবজেক্ট ডাটাবেসে পূর্ণ গৃহস্থালি চালান',
      },
    ],
    commonOptions: [
      { flag: '--auto', description: 'Only run if accumulated clutter passes thresholds', descriptionBn: 'জঞ্জাল সীমা পেরোলেই চালানো' },
    ],
    commonMistakes: [
      {
        mistake: 'Running gc hoping to recover deleted work',
        mistakeBn: 'মোছা কাজ ফেরত আশায় gc চালানো',
        howToAvoid: 'Recover via reflog first; gc destroys what recovery needs.',
        howToAvoidBn: 'আগে রিফ্লগে উদ্ধার করুন; gc উদ্ধারের প্রয়োজনীয় জিনিস ধ্বংস করে।',
      },
    ],
    tags: ['plumbing', 'internals', 'advanced', 'maintenance', 'cleanup'],
    relatedCommands: ['git.log', 'git.reset'],
  },
  {
    id: 'git.revert',
    command: 'git revert',
    slug: 'revert',
    order: 28,
    frequentlyUsed: false,
    whenNotToUse: 'Do not use git revert for private, unpushed mistakes — a simple reset keeps history clean without noise commits.',
    whenNotToUseBn: 'ব্যক্তিগত, পুশ-না-করা ভুলে git revert ব্যবহার করবেন না — সাধারণ রিসেটে অপ্রয়োজনীয় কমিট ছাড়াই হিস্ট্রি পরিষ্কার থাকে।',
    relatedLessons: ['git.fundamentals.commit', 'git.recovery.restore-and-revert'],
    aliases: [],
    searchKeywords: ['undo pushed', 'uncommit safely', 'reverse commit', 'shared history', 'public'],
    category: 'recovery',
    difficulty: 'intermediate',
    title: 'Revert a Commit Safely',
    titleBn: 'নিরাপদে কমিট প্রত্যাহার করা',
    whatItDoes: 'Creates a new commit that undoes the changes of a previous commit, leaving history intact.',
    whatItDoesBn: 'আগের কমিটের পরিবর্তন বাতিল করে নতুন একটি কমিট তৈরি করে, হিস্ট্রি অক্ষত রেখে।',
    whenToUse: 'When a bad commit is already pushed or shared — revert fixes it without rewriting history anyone else depends on.',
    whenToUseBn: 'খারাপ কমিট ইতিমধ্যে পুশ বা শেয়ার্ড হলে — অন্যের নির্ভর করা হিস্ট্রি না বদলে revert ঠিক করে।',
    syntax: 'git revert [<commit>]',
    whatHappensInternally: 'Applies the inverse diff of the target commit on top of HEAD and records it as a brand-new commit object with its own hash.',
    whatHappensInternallyBn: 'টার্গেট কমিটের বিপরীত ডিফ HEAD-এর ওপরে প্রয়োগ করে নিজস্ব হ্যাশসহ একদম নতুন কমিট অবজেক্ট রেকর্ড করে।',
    examples: [
      {
        command: 'git revert HEAD',
        description: 'Undo the latest commit with a new revert commit',
        descriptionBn: 'নতুন revert কমিটে সর্বশেষ কমিট বাতিল করা',
      },
      {
        command: 'git revert a1b2c3d',
        description: 'Undo a specific older commit without touching anything after it',
        descriptionBn: 'পরের কিছু না ছুঁয়ে নির্দিষ্ট পুরনো কমিট বাতিল করা',
      },
    ],
    commonOptions: [
      { flag: '--no-commit', description: 'Stage the revert without committing, so you can review first', descriptionBn: 'কমিট না করে revert স্টেজ করা, যাতে আগে পর্যালোচনা করা যায়' },
      { flag: '--no-edit', description: 'Accept the default revert message without opening an editor', descriptionBn: 'এডিটর না খুলে ডিফল্ট revert বার্তা মেনে নেওয়া' },
    ],
    commonMistakes: [
      {
        mistake: 'Using `git reset --hard` on a pushed branch instead of revert, forcing teammates to repair',
        mistakeBn: 'পুশড ব্রাঞ্চে revert-এর বদলে `git reset --hard` চালিয়ে সহকর্মীদের মেরামতে বাধ্য করা',
        howToAvoid: 'Ask first: has anyone else seen this commit? If yes, revert. Reset is for private history only.',
        howToAvoidBn: 'আগে জিজ্ঞেস করুন: এই কমিট আর কেউ দেখেছে? দেখলে revert। রিসেট শুধু ব্যক্তিগত হিস্ট্রিতে।',
      },
    ],
    interviewInsight: {
      question: 'Why is `git revert` safe for shared branches while `git reset` is not?',
      questionBn: 'শেয়ার্ড ব্রাঞ্চে `git revert` নিরাপদ কিন্তু `git reset` কেন নয়?',
      answer: 'Revert only adds history — a new commit that undoes the change — so every clone stays compatible. Reset moves the branch pointer backward, orphaning commits teammates already built on.',
      answerBn: 'Revert শুধু হিস্ট্রি যোগ করে — পরিবর্তন বাতিল করা নতুন কমিট — তাই প্রতিটি ক্লোন সামঞ্জস্যপূর্ণ থাকে। Reset ব্রাঞ্চ পয়েন্টার পেছনে সরায়, সহকর্মীদের গড়া কমিট এতিম করে।',
    },
    tags: ['recovery', 'revert', 'undo', 'shared', 'safe'],
    relatedCommands: ['git.reset', 'git.log', 'git.commit'],
  },
  {
    id: 'git.stash',
    command: 'git stash',
    slug: 'stash',
    order: 29,
    frequentlyUsed: false,
    whenNotToUse: 'Do not use stash as long-term storage — unnamed stashes rot. Commit on a branch for anything you must keep.',
    whenNotToUseBn: 'দীর্ঘমেয়াদি সংরক্ষণে stash ব্যবহার করবেন না — নামহীন স্ট্যাশ পচে যায়। রাখতেই হলে ব্রাঞ্চে কমিট করুন।',
    relatedLessons: ['git.fundamentals.working-directory', 'git.fundamentals.staging-area'],
    aliases: [],
    searchKeywords: ['shelve', 'save temporarily', 'wip', 'park changes', 'clean tree', 'shelf'],
    category: 'daily',
    difficulty: 'intermediate',
    title: 'Stash Changes Temporarily',
    titleBn: 'অস্থায়ীভাবে পরিবর্তন সরিয়ে রাখা',
    whatItDoes: 'Shelves uncommitted working-tree changes onto a stack so the tree goes clean, then restores them later.',
    whatItDoesBn: 'আনকমিটেড পরিবর্তন স্ট্যাকে সরিয়ে ট্রি পরিষ্কার করে, পরে ফিরিয়ে আনে।',
    whenToUse: 'When you must switch context — an urgent fix, a pull — but are mid-edit and not ready to commit.',
    whenToUseBn: 'প্রসঙ্গ বদলাতেই হবে — জরুরি ফিক্স, পুল — কিন্তু এডিটের মাঝে, কমিটে প্রস্তুত নন।',
    syntax: 'git stash [push] [-m "message"]',
    whatHappensInternally: 'Records the working-tree and index state as stash commit objects referenced by `refs/stash`, then resets the tree to HEAD.',
    whatHappensInternallyBn: '`refs/stash` রেফারেন্সে ওয়ার্কিং-ট্রি ও ইনডেক্স অবস্থা স্ট্যাশ কমিট অবজেক্টে রেকর্ড করে, তারপর ট্রি HEAD-এ রিসেট করে।',
    examples: [
      {
        command: 'git stash push -m "wip login form"',
        description: 'Shelve current edits with a readable name',
        descriptionBn: 'বোধগম্য নামে বর্তমান এডিট সরিয়ে রাখা',
      },
      {
        command: 'git stash pop',
        description: 'Restore the newest stash and remove it from the stack',
        descriptionBn: 'সর্বশেষ স্ট্যাশ ফিরিয়ে স্ট্যাক থেকে সরানো',
      },
    ],
    commonOptions: [
      { flag: 'list', description: 'Show all shelved stashes with their messages', descriptionBn: 'বার্তাসহ সব সরানো স্ট্যাশ তালিকা করা' },
      { flag: 'apply', description: 'Restore a stash but keep it on the stack as backup', descriptionBn: 'স্ট্যাশ ফিরিয়ে ব্যাকআপে স্ট্যাকে রাখা' },
      { flag: 'drop', description: 'Delete a stash you no longer need', descriptionBn: 'অপ্রয়োজনীয় স্ট্যাশ মুছে ফেলা' },
      { flag: '-u', description: 'Include untracked files in the stash', descriptionBn: 'আনট্র্যাকড ফাইলসহ স্ট্যাশ করা' },
    ],
    commonMistakes: [
      {
        mistake: 'Piling up message-less stashes until nobody dares touch them',
        mistakeBn: 'বার্তাহীন স্ট্যাশ জমিয়ে ফেলা যতক্ষণ কেউ ছুঁতে সাহস না পায়',
        howToAvoid: 'Always stash with -m and pop or drop within the day.',
        howToAvoidBn: 'সবসময় -m দিয়ে stash করুন এবং দিনের মধ্যে pop বা drop করুন।',
      },
    ],
    interviewInsight: {
      question: 'What is the difference between `git stash pop` and `git stash apply`?',
      questionBn: '`git stash pop` ও `git stash apply` এর পার্থক্য কী?',
      answer: 'Both restore the stash into the tree, but pop deletes it from the stack while apply keeps a backup copy. Prefer apply before risky merges, pop for the routine case.',
      answerBn: 'দুটোই স্ট্যাশ ট্রিতে ফেরায়, কিন্তু pop স্ট্যাক থেকে মুছে দেয় আর apply ব্যাকআপ রাখে। ঝুঁকিপূর্ণ মার্জের আগে apply, রুটিনে pop।',
    },
    tags: ['stash', 'shelve', 'wip', 'switch', 'daily'],
    relatedCommands: ['git.status', 'git.switch', 'git.restore'],
  },
  {
    id: 'git.tag',
    command: 'git tag',
    slug: 'tag',
    order: 30,
    frequentlyUsed: false,
    whenNotToUse: 'Do not tag every commit — tags mark meaningful points like releases, not routine checkpoints.',
    whenNotToUseBn: 'প্রতিটি কমিটে ট্যাগ দেবেন না — ট্যাগ রিলিজের মতো অর্থবহ পয়েন্ট চিহ্নিত করে, রুটিন চেকপয়েন্ট নয়।',
    relatedLessons: ['git.internals.lightweight-vs-annotated-tags'],
    aliases: [],
    searchKeywords: ['release', 'version', 'mark', 'label', 'annotate', 'v1'],
    category: 'history',
    difficulty: 'intermediate',
    title: 'Tag Release Points',
    titleBn: 'রিলিজ পয়েন্ট চিহ্নিত করা',
    whatItDoes: 'Attaches a fixed, human-readable name to a specific commit — usually a release.',
    whatItDoesBn: 'নির্দিষ্ট কমিটে স্থির, মানব-পাঠযোগ্য নাম যুক্ত করে — সাধারণত রিলিজে।',
    whenToUse: 'When cutting a release or marking any commit the team must find again by name.',
    whenToUseBn: 'রিলিজ কাটতে বা নামে খুঁজতে হবে এমন কমিট চিহ্নিত করতে।',
    syntax: 'git tag [-a <name> -m "message"] [<commit>]',
    whatHappensInternally: 'A lightweight tag is just a ref pointing at a commit. An annotated tag creates a full tag object (message, tagger, date) pointing at the commit.',
    whatHappensInternallyBn: 'লাইটওয়েট ট্যাগ কমিটে দেখানো সাধারণ ref। অ্যানোটেটেড ট্যাগ কমিটে দেখানো পূর্ণ ট্যাগ অবজেক্ট (বার্তা, ট্যাগার, তারিখ) তৈরি করে।',
    examples: [
      {
        command: 'git tag -a v1.2.0 -m "First stable release"',
        description: 'Mark the current commit as an annotated release',
        descriptionBn: 'বর্তমান কমিট অ্যানোটেটেড রিলিজে চিহ্নিত করা',
      },
      {
        command: 'git push origin v1.2.0',
        description: 'Publish one tag; tags never travel with a plain push',
        descriptionBn: 'একটি ট্যাগ প্রকাশ করা; সাধারণ পুশে ট্যাগ যায় না',
      },
    ],
    commonOptions: [
      { flag: '-a', description: 'Create an annotated tag with message and metadata', descriptionBn: 'বার্তা ও মেটাডেটাসহ অ্যানোটেটেড ট্যাগ তৈরি' },
      { flag: '-d <name>', description: 'Delete a local tag', descriptionBn: 'লোকাল ট্যাগ মুছে ফেলা' },
      { flag: '--list', description: 'List tags, optionally filtered by pattern', descriptionBn: 'প্যাটার্নে ফিল্টার করে ট্যাগ তালিকা' },
    ],
    commonMistakes: [
      {
        mistake: 'Assuming `git push` publishes tags — teammates never see the release',
        mistakeBn: '`git push` ট্যাগ পাঠায় ধরে নেওয়া — সহকর্মীরা রিলিজ দেখে না',
        howToAvoid: 'Push tags explicitly: `git push origin <tag>` or `--tags`.',
        howToAvoidBn: 'স্পষ্ট ট্যাগ পুশ করুন: `git push origin <tag>` বা `--tags`।',
      },
    ],
    interviewInsight: {
      question: 'What is the difference between a lightweight and an annotated tag?',
      questionBn: 'লাইটওয়েট ও অ্যানোটেটেড ট্যাগের পার্থক্য কী?',
      answer: 'A lightweight tag is a bare ref to a commit; an annotated tag is a real object with message, tagger, and date. Use annotated tags for releases so the marker carries its own provenance.',
      answerBn: 'লাইটওয়েট ট্যাগ কমিটে নগ্ন ref; অ্যানোটেটেড ট্যাগ বার্তা, ট্যাগার ও তারিখসহ আসল অবজেক্ট। রিলিজে অ্যানোটেটেড ব্যবহার করুন যাতে চিহ্ন নিজস্ব উৎস বহন করে।',
    },
    tags: ['tag', 'release', 'version', 'annotate'],
    relatedCommands: ['git.log', 'git.branch', 'git.push'],
  },
  {
    id: 'git.config',
    command: 'git config',
    slug: 'config',
    order: 31,
    frequentlyUsed: true,
    relatedLessons: ['git.fundamentals.repository'],
    aliases: [],
    searchKeywords: ['setup', 'username', 'email', 'identity', 'settings', 'global', 'local', 'system'],
    category: 'setup',
    difficulty: 'beginner',
    title: 'Configure Git Identity & Settings',
    titleBn: 'গিট পরিচয় ও সেটিংস কনফিগার করা',
    whatItDoes: 'Reads and writes Git settings — most importantly the name and email stamped on your commits.',
    whatItDoesBn: 'গিট সেটিংস পড়ে ও লেখে — সবচেয়ে গুরুত্বপূর্ণ কমিটে ছাপা নাম ও ইমেইল।',
    whenToUse: 'First thing on any new machine, and whenever a project needs different identity or behavior.',
    whenToUseBn: 'নতুন মেশিনে সবার আগে, এবং প্রজেক্টে ভিন্ন পরিচয় বা আচরণ দরকার হলে।',
    syntax: 'git config [--global] <key> <value>',
    whatHappensInternally: 'Writes key-value pairs to a config file: system-wide, `~/.gitconfig` for --global, or `.git/config` for the current repository. Local values override global ones.',
    whatHappensInternallyBn: 'কনফিগ ফাইলে key-value লেখে: সিস্টেমব্যাপী, --global-এ `~/.gitconfig`, বর্তমান রিপোতে `.git/config`। লোকাল মান গ্লোবালকে অগ্রাহ্য করে।',
    examples: [
      {
        command: 'git config --global user.name "Your Name"',
        description: 'Set the author name stamped on every commit',
        descriptionBn: 'প্রতিটি কমিটে ছাপা লেখকের নাম সেট করা',
      },
      {
        command: 'git config --global user.email "you@example.com"',
        description: 'Set the author email stamped on every commit',
        descriptionBn: 'প্রতিটি কমিটে ছাপা লেখকের ইমেইল সেট করা',
      },
      {
        command: 'git config --list',
        description: 'Show the effective settings from all levels',
        descriptionBn: 'সব স্তরের কার্যকর সেটিংস দেখানো',
      },
    ],
    commonOptions: [
      { flag: '--global', description: 'Write to your user file (~/.gitconfig) for all repositories', descriptionBn: 'সব রিপোতে ব্যবহারে ইউজার ফাইলে (~/.gitconfig) লেখা' },
      { flag: '--local', description: 'Write to the current repository only (the default)', descriptionBn: 'শুধু বর্তমান রিপোতে লেখা (ডিফল্ট)' },
      { flag: '--list', description: 'Show all effective settings', descriptionBn: 'সব কার্যকর সেটিংস দেখানো' },
    ],
    commonMistakes: [
      {
        mistake: 'Committing with a missing or joke identity, then pushing it to a shared project',
        mistakeBn: 'পরিচয় ছাড়া বা কৌতুক পরিচয়ে কমিট করে শেয়ার্ড প্রজেক্টে পুশ করা',
        howToAvoid: 'Run the two --global identity commands before your first commit on any machine.',
        howToAvoidBn: 'যেকোনো মেশিনে প্রথম কমিটের আগে দুটি --global পরিচয় কমান্ড চালান।',
      },
    ],
    tags: ['setup', 'config', 'identity', 'beginner'],
    relatedCommands: ['git.init', 'git.clone'],
  },
];
