import { CurriculumLesson } from '@/types/content';

/**
 * 12 Comprehensive Initial Lessons for Module 1: Git Fundamentals
 *
 * Each lesson provides deep conceptual understanding, practical commands,
 * mental model visualizer references, technical interview Q&A, and interactive quizzes.
 */
export const FUNDAMENTALS_LESSONS: CurriculumLesson[] = [
  {
    id: 'git.fundamentals.what-is-git',
    moduleId: 'git-fundamentals',
    slug: 'what-is-git',
    order: 1,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'What is Git & How Does it Work?',
    titleBn: 'গিট কী এবং এটি কীভাবে কাজ করে?',
    learningObjectives: [],
    learningObjectivesBn: [],
    keyTakeaways: [
      'Git is a local version control system that tracks every tiny change to your files.',
      'Working Directory holds your active files, which start untracked until selected.',
      'Staging Area serves as a preparation "waiting room" where git add starts official tracking.',
      'Local Repository permanently stores snapshots via git commit like loading a delivery truck.',
    ],
    sections: [
      {
        id: 'sec-overview',
        blocks: [
          {
            type: 'paragraph',
            text: 'Git is a version control system designed to manage code and solve two critical challenges in software development:',
            textBn: 'গিট হলো এমন একটি ভার্সন কন্ট্রোল সিস্টেম যা কোড পরিচালনা করতে এবং সফটওয়্যার ডেভেলপমেন্টের দুটি অতীব গুরুত্বপূর্ণ চ্যালেঞ্জ সমাধান করতে তৈরি করা হয়েছে:',
          },
          {
            type: 'keyConcept',
            title: 'Version Control & Tracking Changes',
            titleBn: 'ভার্সন কন্ট্রোল ও পরিবর্তনের ট্র্যাকিং',
            text: "When working on a project, you typically create multiple versions over time as you add features or make modifications. If a client or user wants you to roll back to a previous version after you have already made numerous edits, undoing those changes manually is extremely difficult.\n\nGit acts as a local tool that tracks every tiny change made to your files, allowing you to easily view your project's history, track edits, and revert to previous versions whenever needed.",
            textBn: "কোনো প্রজেক্টে কাজ করার সময় নতুন ফিচার যোগ করা বা বিভিন্ন পরিবর্তনের কারণে স্বাভাবিকভাবেই একাধিক ভার্সন তৈরি করতে হয়। তবে অনেকগুলো পরিবর্তনের পর যদি কোনো ক্লায়েন্ট বা ব্যবহারকারী আপনাকে পূর্বের একটি ভার্সনে ফিরে যেতে (roll back) বলে, ম্যানুয়ালি সেই পরিবর্তনগুলো আনডু করা অত্যন্ত কঠিন।\n\nগিট একটি লোকাল টুল হিসেবে কাজ করে যা আপনার ফাইলের প্রতিটি ছোটখাটো পরিবর্তন ট্র্যাক করে। এর ফলে আপনি সহজেই আপনার প্রজেক্টের সম্পূর্ণ ইতিহাস দেখতে পারেন, প্রতিটি পরিবর্তন পর্যবেক্ষণ করতে পারেন এবং প্রয়োজন অনুযায়ী যেকোনো পূর্ববর্তী ভার্সনে অনায়াসে ফিরে যেতে পারেন।",
          },
        ],
      },
      {
        id: 'sec-how-git-works',
        title: 'How Git Works: The 3 Local Areas',
        titleBn: 'গিট কীভাবে কাজ করে: ৩টি লোকাল এরিয়া',
        blocks: [
          {
            type: 'paragraph',
            text: 'Git manages files by moving them through a workflow of different local areas before saving them to an online server like GitHub:',
            textBn: 'গিটহাবের (GitHub) মতো কোনো অনলাইন সার্ভারে সেভ করার আগে, গিট আপনার ফাইলগুলোকে বিভিন্ন লোকাল এরিয়ার একটি সুনির্দিষ্ট ওয়ার্কফ্লোর মধ্য দিয়ে পরিচালনা করে:',
          },
          {
            type: 'keyConcept',
            title: '1. Working Directory',
            titleBn: '১. ওয়ার্কিং ডিরেক্টরি (Working Directory)',
            text: 'This is your actual project folder on your local computer where you create, edit, and delete files. When you first create or modify files here, they are considered untracked by Git because it is not actively monitoring or saving their state yet.',
            textBn: 'এটি আপনার লোকাল কম্পিউটারের মূল প্রজেক্ট ফোল্ডার, যেখানে আপনি ফাইল তৈরি, এডিট এবং ডিলিট করেন। যখন আপনি এখানে প্রথম কোনো ফাইল তৈরি বা পরিবর্তন করেন, তখন গিট সেগুলোকে "untracked" হিসেবে বিবেচনা করে—কারণ গিট তখনও সেগুলোর অবস্থা সক্রিয়ভাবে পর্যবেক্ষণ বা সংরক্ষণ করছে না।',
          },
          {
            type: 'keyConcept',
            title: '2. Staging Area (The Waiting Room)',
            titleBn: '২. স্টেজিং এরিয়া (অপেক্ষার ঘর / The Waiting Room)',
            text: 'You can think of this as a preparation space or "waiting room". If you have edited several files but only some are ready to be saved, you select those specific files and move them to the Staging Area using the git add command. Once added, Git officially begins tracking their changes.',
            textBn: 'আপনি এটিকে একটি প্রস্তুতির জায়গা বা "অপেক্ষার ঘর" (waiting room) হিসেবে ভাবতে পারেন। আপনি যদি কয়েকটি ফাইল এডিট করেন কিন্তু তার মধ্যে কেবল নির্দিষ্ট কিছু ফাইল সেভ করার জন্য প্রস্তুত থাকে, তবে আপনি সেই ফাইলগুলো বাছাই করে git add কমান্ডের মাধ্যমে স্টেজিং এরিয়ায় নিয়ে আসেন। একবার যুক্ত করার পর, গিট আনুষ্ঠানিকভাবে সেগুলোর পরিবর্তন ট্র্যাক করা শুরু করে।',
            commands: [
              {
                command: 'git add <file>',
                description: 'Selects specific modified files and moves them to the Staging Area to begin official tracking.',
                descriptionBn: 'নির্দিষ্ট পরিবর্তিত ফাইল বাছাই করে স্টেজিং এরিয়ায় পাঠায় এবং আনুষ্ঠানিকভাবে ট্র্যাকিং শুরু করে।',
              },
            ],
          },
          {
            type: 'keyConcept',
            title: '3. Local Repository',
            titleBn: '৩. লোকাল রিপোজিটরি (Local Repository)',
            text: 'When you are satisfied with the tracked changes in your Staging Area, you permanently save them to your Local Repository by executing a commit with the git commit -m "your message" command. Committing is like loading your packaged products onto a delivery truck—the snapshot of your project is safely saved on your computer. You can view this saved history using the git log command.',
            textBn: 'স্টেজিং এরিয়ার ট্র্যাক করা পরিবর্তনগুলো নিয়ে সন্তুষ্ট হলে, git commit -m "your message" কমান্ড চালিয়ে আপনি সেগুলোকে স্থায়ীভাবে লোকাল রিপোজিটরিতে সেভ করেন। কমিট করা হলো প্যাকেজ করা পণ্যগুলোকে একটি ডেলিভারি ট্রাকে লোড করার মতো—আপনার প্রজেক্টের সেই মুহূর্তের স্ন্যাপশট আপনার কম্পিউটারে নিরাপদে সংরক্ষিত হয়। আপনি git log কমান্ড ব্যবহার করে এই সংরক্ষিত অতীত ইতিহাস দেখতে পারেন।',
            commands: [
              {
                command: 'git commit -m "your message"',
                description: 'Permanently saves the staged snapshot to your Local Repository with a descriptive message.',
                descriptionBn: 'একটি স্পষ্ট বার্তাসহ স্টেজিং এরিয়ার স্ন্যাপশটকে লোকাল রিপোজিটরিতে স্থায়ীভাবে সংরক্ষণ করে।',
              },
              {
                command: 'git log',
                description: "Displays the saved commit history of your project on your computer.",
                descriptionBn: 'আপনার কম্পিউটারে সংরক্ষিত প্রজেক্টের সমস্ত কমিটের অতীত ইতিহাস প্রদর্শন করে।',
              },
            ],
          },
          {
            type: 'visualizer',
            initialState: 'working',
          },
          {
            type: 'callout',
            variant: 'tip',
            title: 'Everything Happens Locally First',
            titleBn: 'সবকিছু প্রথমে সম্পূর্ণ লোকালি সম্পন্ন হয়',
            text: 'Notice that Working Directory, Staging Area, and Local Repository all reside on your personal computer! You do not need internet access to add, commit, or view logs. You only need the internet when you decide to push your commits to an online platform like GitHub.',
            textBn: 'খেয়াল করুন যে ওয়ার্কিং ডিরেক্টরি, স্টেজিং এরিয়া এবং লোকাল রিপোজিটরি—এই ৩টি অঞ্চলই আপনার নিজস্ব কম্পিউটারে থাকে! তাই add, commit বা হিস্ট্রি লগ দেখার জন্য কোনো ইন্টারনেট প্রয়োজন নেই। কেবল যখন আপনি গিটহাবের মতো অনলাইন সার্ভারে কোড পাঠাতে চান, তখনই ইন্টারনেটের প্রয়োজন হয়।',
          },
        ],
      },
    ],
    relatedCommands: ['git-add', 'git-commit', 'git-log', 'git-status'],
    interviewQuestion: {
      id: 'int-what-is-git',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'What is Git, why is it used, and how do its three local areas work?',
      questionBn: 'গিট কী, এটি কেন ব্যবহার করা হয় এবং এর তিনটি লোকাল এরিয়া কীভাবে কাজ করে?',
      answer: 'Git is a version control system that tracks code changes and enables effortless rollbacks. Before saving to an online server like GitHub, Git moves files through three local areas on your machine: (1) Working Directory where files are created/edited and start untracked; (2) Staging Area (the preparation "waiting room") where specific files are staged using "git add" to begin official tracking; and (3) Local Repository where staged changes are permanently committed as a snapshot using "git commit -m", viewable via "git log".',
      answerBn: 'গিট হলো একটি ভার্সন কন্ট্রোল সিস্টেম যা ফাইলের পরিবর্তন গভীরভাবে ট্র্যাক করে এবং পূর্বের ভার্সনে সহজে ফিরে যেতে (roll back) সাহায্য করে। গিটহাবে সেভ করার আগে গিট ৩টি লোকাল এরিয়ায় কাজ করে: (১) ওয়ার্কিং ডিরেক্টরি—যেখানে ফাইল তৈরি/এডিট করা হয় এবং প্রথমে untracked থাকে; (২) স্টেজিং এরিয়া ("অপেক্ষার ঘর")—যেখানে git add দিয়ে নির্দিষ্ট ফাইল বাছাই করে ট্র্যাকিং শুরু করা হয়; এবং (৩) লোকাল রিপোজিটরি—যেখানে git commit চালিয়ে ডেলিভারি ট্রাকে তোলার মতো স্ন্যাপশট স্থায়ীভাবে সেভ করা হয়, যা git log দিয়ে দেখা যায়।',
      keyPoints: [
        'Solves version control and tracking changes locally without painful manual undoing',
        'Working Directory: active project folder where edits start untracked',
        'Staging Area: the "waiting room" where git add selects files to officially track',
        'Local Repository: permanent local storage created by git commit (like loading a delivery truck)',
        'git log allows viewing the full chronological commit history',
      ],
      keyPointsBn: [
        'ম্যানুয়ালি আনডু করার ঝামেলা ছাড়াই লোকালি পরিবর্তন ও ভার্সন ট্র্যাক করে',
        'ওয়ার্কিং ডিরেক্টরি: মূল প্রজেক্ট ফোল্ডার যেখানে ফাইল শুরুতে untracked থাকে',
        'স্টেজিং এরিয়া: "অপেক্ষার ঘর" যেখানে git add দিয়ে ফাইল ট্র্যাকিং শুরু হয়',
        'লোকাল রিপোজিটরি: git commit দিয়ে ডেলিভারি ট্রাকে পণ্যের মতো স্থায়ী স্ন্যাপশট সেভ হয়',
        'git log দিয়ে প্রজেক্টের সংরক্ষিত অতীত ইতিহাস দেখা যায়',
      ],
      followUpQuestions: [
        'Why does Git use a Staging Area instead of committing directly from the Working Directory?',
      ],
    },
    quiz: {
      id: 'quiz-what-is-git',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'Which Git area acts as a preparation "waiting room" where you select specific files with "git add" before committing?',
      questionBn: 'কোন গিট এরিয়াটি একটি প্রস্তুতিমূলক "অপেক্ষার ঘর" (waiting room) হিসেবে কাজ করে, যেখানে কমিট করার আগে "git add" দিয়ে নির্দিষ্ট ফাইল নির্বাচন করা হয়?',
      options: [
        { id: 'opt-a', text: 'GitHub Cloud Storage', textBn: 'গিটহাব ক্লাউড স্টোরেজ', isCorrect: false },
        { id: 'opt-b', text: 'Working Directory', textBn: 'ওয়ার্কিং ডিরেক্টরি', isCorrect: false },
        { id: 'opt-c', text: 'Staging Area (The Waiting Room)', textBn: 'স্টেজিং এরিয়া (অপেক্ষার ঘর)', isCorrect: true },
        { id: 'opt-d', text: 'Trash Bin', textBn: 'রিসাইকেল বিন', isCorrect: false },
      ],
      explanation: 'The Staging Area functions as a waiting room or preparation space. You move only the files ready to be saved using "git add", and Git officially tracks them before permanent commit.',
      explanationBn: 'স্টেজিং এরিয়া একটি অপেক্ষার ঘর বা প্রস্তুতির জায়গা হিসেবে কাজ করে। যে ফাইলগুলো সেভ করার জন্য প্রস্তুত, "git add" দিয়ে কেবল সেগুলোকে এখানে আনা হয় এবং স্থায়ী কমিটের আগে গিট সেগুলোকে আনুষ্ঠানিকভাবে ট্র্যাক করে।',
    },
  },
  {
    id: 'git.fundamentals.git-vs-github',
    moduleId: 'git-fundamentals',
    slug: 'git-vs-github',
    order: 2,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'Git vs GitHub: The Essential Distinction',
    titleBn: 'গিট বনাম গিটহাব: অত্যন্ত গুরুত্বপূর্ণ পার্থক্য',
    learningObjectives: [],
    learningObjectivesBn: [],
    keyTakeaways: [
      'Git is a local command-line tool installed on your computer to track version history.',
      'GitHub is a cloud platform providing web hosting and GUI collaboration for Git repositories.',
      'Developers work locally with Git (add, commit) and sync to GitHub (push, pull) to collaborate with their team.',
    ],
    sections: [
      {
        id: 'sec-overview',
        blocks: [
          {
            type: 'paragraph',
            text: 'Git and GitHub are not the same thing. While they work closely together to manage software projects, they serve entirely different roles:',
            textBn: 'গিট (Git) এবং গিটহাব (GitHub) একই জিনিস নয়। যদিও সফটওয়্যার প্রজেক্ট পরিচালনায় তারা ঘনিষ্ঠভাবে একসঙ্গে কাজ করে, তবুও তাদের ভূমিকা সম্পূর্ণ ভিন্ন:',
          },
          {
            type: 'keyConcept',
            title: 'Git: The Local Version Control Tool',
            titleBn: 'গিট: লোকাল ভার্সন কন্ট্রোল টুল',
            text: '• What it is: Git is a local tool or software that you install directly on your computer.\n• Function: It serves as a version control system that tracks the modifications you make to your code files over time. It allows you to track edits, keep records of your project history, and revert or roll back to previous versions when needed.\n• Interface: Git is a command-line utility; you interact with it by typing commands into an interface (like Git Bash).\n• Scope: It operates strictly on your local machine and only tracks the specific directories you explicitly choose to initialize.',
            textBn: '• এটি কী: গিট হলো একটি লোকাল সফটওয়্যার বা টুল যা আপনি সরাসরি আপনার নিজস্ব কম্পিউটারে ইনস্টল করেন।\n• কাজের ক্ষেত্র: এটি একটি ভার্সন কন্ট্রোল সিস্টেম হিসেবে কাজ করে যা সময়ের সাথে আপনার কোড ফাইলের প্রতিটি পরিবর্তন ট্র্যাক করে। এটি আপনাকে কোড এডিট পর্যবেক্ষণ করতে, প্রজেক্টের সম্পূর্ণ ইতিহাস সংরক্ষণ করতে এবং প্রয়োজনে পূর্ববর্তী যেকোনো ভার্সনে ফিরে যেতে (roll back) সাহায্য করে।\n• ইন্টারফেস: গিট মূলত একটি কমান্ড-লাইন ইউটিলিটি (Command-Line Utility); টার্মিনাল বা গিট ব্যাশের (Git Bash) মতো ইন্টারফেসে কমান্ড লিখে আপনি এর সাথে কাজ করেন।\n• পরিধি: এটি সম্পূর্ণভাবে আপনার লোকাল মেশিনে চলে এবং শুধুমাত্র যে ডিরেক্টরিগুলোকে আপনি স্পষ্টভাবে ট্র্যাক করতে বলেন (initialize করেন), সেগুলোর ওপরেই কাজ করে।',
          },
          {
            type: 'keyConcept',
            title: 'GitHub: The Cloud-Based Collaboration Platform',
            titleBn: 'গিটহাব: ক্লাউড-ভিত্তিক কোলাবোরেশন প্ল্যাটফর্ম',
            text: '• What it is: GitHub is an online, web-based hosting service or cloud platform.\n• Function: It acts as a remote repository where you can store your local folders, code, and projects in the cloud. It serves as a centralized host where multiple developers can share code and collaborate on a single project simultaneously.\n• Interface: Unlike the Git command line, GitHub provides a Graphical User Interface (GUI), letting you view, manage, and inspect your repositories visually via a web browser.\n• Scope: It exists on the web, serving as the shared hub where individual developers connect their local environments.',
            textBn: '• এটি কী: গিটহাব হলো একটি অনলাইন, ওয়েব-ভিত্তিক হোস্টিং সার্ভিস বা ক্লাউড প্ল্যাটফর্ম।\n• কাজের ক্ষেত্র: এটি একটি রিমোট রিপোজিটরি হিসেবে কাজ করে যেখানে আপনি আপনার লোকাল ফোল্ডার, কোড এবং প্রজেক্ট ক্লাউডে সংরক্ষণ করতে পারেন। এটি একটি সেন্ট্রালাইজড হাবের মতো কাজ করে যেখানে একাধিক ডেভেলপার একই সাথে কোড শেয়ার করতে এবং একটিমাত্র প্রজেক্টে দলগতভাবে কাজ করতে পারে।\n• ইন্টারফেস: গিটের কমান্ড লাইনের বিপরীতে, গিটহাবে রয়েছে আকর্ষণীয় গ্রাফিক্যাল ইউজার ইন্টারফেস (GUI); যার ফলে আপনি ওয়েব ব্রাউজারের মাধ্যমে ভিজ্যুয়ালি রিপোজিটরি পরিচালনা ও পরিদর্শন করতে পারেন।\n• পরিধি: এটি ওয়েবে অবস্থান করে এবং একটি কেন্দ্রীয় শেয়ার্ড হাব হিসেবে কাজ করে যার সাথে ডেভেলপাররা তাদের লোকাল মেশিন কানেক্ট করেন।',
          },
        ],
      },
      {
        id: 'sec-how-they-work-together',
        title: 'How They Work Together',
        titleBn: 'তারা কীভাবে একসঙ্গে কাজ করে',
        blocks: [
          {
            type: 'paragraph',
            text: 'To understand their relationship, consider the standard collaborative workflow:',
            textBn: 'তাদের মধ্যকার সম্পর্ক বোঝার জন্য সফটওয়্যার টিমের দৈনন্দিন কোলাবোরেশন ওয়ার্কফ্লোটি লক্ষ্য করুন:',
          },
          {
            type: 'list',
            ordered: true,
            items: [
              'You create a remote repository online on GitHub to act as a central storage point for your team.',
              'Team members use Git to clone (copy) that remote repository from GitHub onto their local computers.',
              'Each person writes code in their local working directories, using Git to track changes, stage files, and commit snapshots of their work locally.',
              'When ready, developers use Git to push (upload) those locally committed updates back to the shared repository on GitHub, making them available to the entire team.',
            ],
            itemsBn: [
              'প্রথমে আপনি গিটহাবে (GitHub) একটি রিমোট রিপোজিটরি তৈরি করেন যা পুরো টিমের কেন্দ্রীয় স্টোরেজ হিসেবে কাজ করে।',
              'দলের সদস্যরা গিট (Git) ব্যবহার করে গিটহাব থেকে সেই রিমোট রিপোজিটরিটি নিজেদের কম্পিউটারে ক্লোন (কপি) করে নেয়।',
              'প্রত্যেকে যার যার লোকাল ওয়ার্কিং ডিরেক্টরিতে কোড লেখে এবং গিট দিয়ে পরিবর্তনগুলো ট্র্যাক করে, ফাইল স্টেজ করে এবং লোকালি স্ন্যাপশট কমিট করে রাখে।',
              'কাজ সম্পন্ন হলে ডেভেলপাররা গিট ব্যবহার করে লোকাল কমিটগুলো পুশ (আপলোড) করে গিটহাবের শেয়ার্ড রিপোজিটরিতে পাঠিয়ে দেয়, যাতে বাকি সবাই সেই আপডেট পেতে পারে।',
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            title: 'Interview Distinction',
            titleBn: 'ইন্টারভিউয়ের উত্তর',
            text: 'Git is to GitHub what Linux is to Ubuntu, or what an engine is to a car. Git is the local version control engine; GitHub is the platform that wraps around it with cloud hosting and social collaboration.',
            textBn: 'গিট ও গিটহাবের সম্পর্ক ইঞ্জিনের সাথে গাড়ির মতো। গিট হলো মূল ইঞ্জিন যা লোকাল ভার্সন নিয়ন্ত্রণ করে; আর গিটহাব হলো প্ল্যাটফর্ম যা ক্লাউড স্টোরেজ এবং সোশ্যাল কোলাবোরেশন প্রদান করে।',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-git-vs-github',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'What is the fundamental difference between Git and GitHub, and can you use one without the other?',
      questionBn: 'গিট এবং গিটহাবের মধ্যে মৌলিক পার্থক্য কী, এবং একটি ছাড়া কি অন্যটি ব্যবহার করা যায়?',
      answer: 'Git is a local command-line version control tool installed on your computer to track file changes and history offline. GitHub is a cloud-based hosting service with a web GUI that stores Git repositories online for team collaboration. You can use Git entirely offline without GitHub, but GitHub fundamentally requires Git to operate.',
      answerBn: 'গিট হলো আপনার কম্পিউটারে ইনস্টল করা একটি লোকাল কমান্ড-লাইন ভার্সন কন্ট্রোল টুল, যা অফলাইনে ফাইলের পরিবর্তন ও ইতিহাস ট্র্যাক করে। অন্যদিকে গিটহাব হলো ওয়েব GUI সমৃদ্ধ একটি ক্লাউড হোস্টিং সার্ভিস, যা টিম কোলাবোরেশনের জন্য অনলাইনে গিট রিপোজিটরি সংরক্ষণ করে। আপনি গিটহাব ছাড়াই সম্পূর্ণ অফলাইনে গিট ব্যবহার করতে পারেন, তবে গিটহাবের ভিত্তিই হলো গিট।',
      keyPoints: [
        'Git is a local command-line tool; GitHub is a cloud hosting platform',
        'Git tracks files on your machine; GitHub acts as the remote shared hub for teams',
        'Git operates 100% offline without internet or GitHub',
        'GitHub requires Git underneath for versioning and synchronization',
      ],
      keyPointsBn: [
        'গিট হলো লোকাল কমান্ড-লাইন টুল; গিটহাব হলো ক্লাউড হোস্টিং প্ল্যাটফর্ম',
        'গিট আপনার লোকাল মেশিনে ফাইল ট্র্যাক করে; গিটহাব দলের সদস্যদের জন্য সেন্ট্রাল রিমোট হাব হিসেবে কাজ করে',
        'ইন্টারনেট বা গিটহাব ছাড়াই গিট ১০০% অফলাইনে কাজ করে',
        'ভার্সনিং এবং সিনক্রোনাইজেশনের জন্য গিটহাবের মূলে গিট আবশ্যক',
      ],
    },
    quiz: {
      id: 'quiz-git-vs-github',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'Which of the following statements is strictly TRUE?',
      questionBn: 'নিচের কোন উক্তিটি সম্পূর্ণরূপে সত্য?',
      options: [
        { id: 'opt-a', text: 'You must have an active internet connection and GitHub account to use Git.', textBn: 'গিট ব্যবহার করতে সর্বদা ইন্টারনেট সংযোগ এবং গিটহাব অ্যাকাউন্ট প্রয়োজন।', isCorrect: false },
        { id: 'opt-b', text: 'Git is the local version control software; GitHub is a cloud hosting platform for Git repositories.', textBn: 'গিট হলো লোকাল ভার্সন কন্ট্রোল সফটওয়্যার; গিটহাব হলো গিট রিপোর ক্লাউড হোস্টিং প্ল্যাটফর্ম।', isCorrect: true },
        { id: 'opt-c', text: 'GitHub was invented by Linus Torvalds as part of Linux.', textBn: 'লিনাস টরভাল্ডস লিনাক্সের অংশ হিসেবে গিটহাব আবিষ্কার করেছিলেন।', isCorrect: false },
        { id: 'opt-d', text: 'Running git commit automatically sends code to GitHub servers.', textBn: 'git commit কমান্ড দিলে স্বয়ংক্রিয়ভাবে কোড গিটহাবের সার্ভারে চলে যায়।', isCorrect: false },
      ],
      explanation: 'Git operates completely locally on your computer. GitHub is an online service that hosts Git repositories for remote backup and team collaboration.',
      explanationBn: 'গিট আপনার কম্পিউটারে সম্পূর্ণ স্বাধীনভাবে চলে। গিটহাব হলো একটি অনলাইন ক্লাউড প্ল্যাটফর্ম যা রিমোট শেয়ারিং ও ব্যাকআপে সাহায্য করে।',
    },
  },
  {
    id: 'git.fundamentals.repository',
    moduleId: 'git-fundamentals',
    slug: 'repository',
    order: 3,
    durationMinutes: 9,
    difficulty: 'beginner',
    title: 'The Repository (.git Directory Internals)',
    titleBn: 'রিপোজিটরি (.git ডিরেক্টরি ইন্টারনালস)',
    summary: 'A repository is simply your project folder combined with a hidden `.git` folder that tracks every change, saves your commit history, and remembers every version of your code.',
    summaryBn: 'একটি রিপোজিটরি মূলত আপনার প্রজেক্ট ফোল্ডার এবং তার ভেতরের লুকায়িত `.git` ফোল্ডারের সমন্বয়—যা ফাইলের প্রতিটি পরিবর্তন ট্র্যাক করে এবং কোডের সমস্ত অতীত ইতিহাস মনে রাখে।',
    learningObjectives: [
      'Define what makes a standard folder into a Git repository',
      'Inspect the anatomy of the hidden `.git` folder',
      'Understand the role of the object database and reference pointers',
    ],
    learningObjectivesBn: [
      'একটি সাধারণ ফোল্ডার কীভাবে গিট রিপোজিটরিতে রূপ নেয় তা বোঝা',
      'লুকায়িত `.git` ফোল্ডারের ভেতরের গুরুত্বপূর্ণ ফাইলগুলো চেনা',
      'অবজেক্ট ডাটাবেস এবং রেফারেন্স পয়েন্টারের ভূমিকা জানা',
    ],
    keyTakeaways: [
      'A Git repository consists of your Working Tree (visible files) plus the hidden `.git` directory.',
      'If you delete the `.git` directory, your project becomes a normal unversioned folder with all version history permanently erased.',
      'The repository contains objects (`.git/objects/`), branch references (`.git/refs/`), configuration (`.git/config`), and the current pointer (`.git/HEAD`).',
    ],
    sections: [
      {
        id: 'sec-repo-anatomy',
        title: 'Anatomy of the `.git` Directory',
        titleBn: '`.git` ডিরেক্টরির গঠন',
        blocks: [
          {
            type: 'paragraph',
            text: 'Running the `git init` command creates a hidden `.git` folder inside your project directory, which officially initializes Git and tells it to start tracking file changes in that folder. This single hidden folder serves as the entire database of your project’s version history. Within this directory structure, `HEAD` acts as a crucial pointer representing the current active commit or state you are currently on:',
            textBn: '`git init` কমান্ডটি আপনার প্রজেক্ট ডিরেক্টরির ভেতরে একটি লুকায়িত `.git` ফোল্ডার তৈরি করে, যা আনুষ্ঠানিকভাবে গিটকে ইনিশিয়ালাইজ করে এবং সেই ফোল্ডারে ফাইলের পরিবর্তনগুলো ট্র্যাক করা শুরু করার নির্দেশ দেয়। এই একক লুকায়িত ফোল্ডারটিই আপনার প্রজেক্টের সম্পূর্ণ ভার্সন হিস্ট্রি ডাটাবেস। এই কাঠামোর ভেতরে `HEAD` একটি গুরুত্বপূর্ণ পয়েন্টার হিসেবে কাজ করে, যা আপনি বর্তমানে কোন সক্রিয় কমিট বা স্টেটে আছেন তা নির্দেশ করে:',
          },
          {
            type: 'code',
            language: 'bash',
            filename: 'ls -la .git',
            code: `.git/
├── HEAD             # Points to the branch currently checked out
├── config           # Repository-specific configuration settings
├── description      # Used mainly by GitWeb
├── hooks/           # Client or server-side executable scripts
├── info/            # Global exclusion file
├── objects/         # The Content-Addressable Object Database (blobs, trees, commits, tags)
└── refs/            # Pointers to commit objects: heads/ (local branches) and tags/`,
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-git-repo',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'What happens if you delete the `.git` folder from your project directory?',
      questionBn: 'প্রজেক্ট ডিরেক্টরি থেকে `.git` ফোল্ডারটি মুছে দিলে কী হবে?',
      answer: 'Your visible project files in the working directory remain untouched on your disk, but the entire Git version history, all branches, stashes, tags, and commits are permanently destroyed. The folder becomes an ordinary unversioned directory.',
      answerBn: 'আপনার বর্তমান ফাইলগুলো ডিস্কে থেকে যাবে, কিন্তু সমস্ত ব্রাঞ্চ, পূর্ববর্তী কমিট হিস্ট্রি ও ট্যাগ চিরতরে মুছে যাবে। ফোল্ডারটি সাধারণ নন-গিট ফোল্ডারে পরিণত হবে।',
      keyPoints: [
        'The .git directory IS the repository',
        'Visible files are just a checkout of one specific commit snapshot',
      ],
    },
    quiz: {
      id: 'quiz-git-repo',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'Where does Git store all commit history, object blobs, and branch references?',
      questionBn: 'গিট তার সমস্ত কমিট হিস্ট্রি, অবজেক্ট ব্লব এবং ব্রাঞ্চ রেফারেন্স কোথায় সংরক্ষণ করে?',
      options: [
        { id: 'opt-a', text: 'In a hidden `.git` folder inside the project root directory', textBn: 'প্রজেক্ট রুটের ভেতরে থাকা একটি লুকায়িত `.git` ফোল্ডারে', isCorrect: true },
        { id: 'opt-b', text: 'Directly in the cloud on GitHub servers', textBn: 'সরাসরি গিটহাবের ক্লাউড সার্ভারে', isCorrect: false },
        { id: 'opt-c', text: 'In the computer\'s Windows Registry or macOS Keychain', textBn: 'উইন্ডোজ রেজিস্ট্রি বা ম্যাক কেইচেইনে', isCorrect: false },
        { id: 'opt-d', text: 'In temporary RAM memory that resets when you shut down', textBn: 'অস্থায়ী র‍্যাম মেমোরিতে যা রিবুট করলে মুছে যায়', isCorrect: false },
      ],
      explanation: 'The hidden `.git` folder contains the entire database (objects, refs, HEAD, and config). All version history lives right there on your disk.',
      explanationBn: '`.git` ফোল্ডারটিই মূলত গিটের সম্পূর্ণ ডাটাবেস ধারণ করে। সব অবজেক্ট, হিস্ট্রি ও ব্রাঞ্চ এখানেই সংরক্ষিত থাকে।',
    },
  },
  {
    id: 'git.fundamentals.working-directory',
    moduleId: 'git-fundamentals',
    slug: 'working-directory',
    order: 4,
    durationMinutes: 7,
    difficulty: 'beginner',
    title: 'The Working Directory (Working Tree)',
    titleBn: 'ওয়ার্কিং ডিরেক্টরি (ওয়ার্কিং ট্রি)',
    summary: 'Understand the first stage of Git’s architecture: your actual files on disk that you open, edit, delete, and test in your code editor.',
    summaryBn: 'গিটের আর্কিটেকচারের প্রথম স্তর: আপনার ডিস্কের আসল ফাইলসমূহ যা কোড এডিটরে খুলে আপনি কোড লেখেন ও পরীক্ষা করেন।',
    learningObjectives: [
      'Define the Working Tree as a single checkout from the Git database',
      'Distinguish between Tracked and Untracked files',
      'Explain how Git observes modifications in the working tree',
    ],
    learningObjectivesBn: [
      'ওয়ার্কিং ট্রি যে মূলত একটি নির্দিষ্ট কমিটের এক্সট্র্যাক্ট করা ফাইল সেট তা বোঝা',
      'ট্র্যাকড এবং আনট্র্যাকড ফাইলের পার্থক্য নিরূপণ',
      'গিট কীভাবে ডিস্কের ফাইল পরিবর্তনের ওপর নজর রাখে তা জানা',
    ],
    keyTakeaways: [
      'The Working Directory consists of real files extracted from a commit for you to edit.',
      'Files in the working directory are either Tracked (Git knows about them) or Untracked (new files Git does not follow yet).',
      'Modifications in the working directory are NOT saved in Git history until you stage and commit them.',
    ],
    sections: [
      {
        id: 'sec-working-tree',
        title: 'Your Active Workspace',
        titleBn: 'আপনার কাজের মূল ওয়ার্কস্পেস',
        blocks: [
          {
            type: 'paragraph',
            text: 'The Working Directory (also called the Working Tree) is a single checkout of one version of the project. These files are pulled out of the compressed database in the `.git` directory and placed on disk for you to view, compile, and edit.',
            textBn: 'ওয়ার্কিং ডিরেক্টরি হলো প্রজেক্টের একটি নির্দিষ্ট সংস্করণের চেকআউট। `.git` এর ভেতরের কম্প্রেসড ডাটাবেস থেকে ফাইলগুলোকে বের করে ডিস্কে সাজিয়ে রাখা হয় যাতে আপনি এডিট ও টেস্ট করতে পারেন।',
          },
          {
            type: 'command',
            command: 'git status',
            description: 'Inspect which files in your working directory have been modified or are untracked',
            descriptionBn: 'ওয়ার্কিং ডিরেক্টরিতে কোন ফাইলগুলো পরিবর্তিত বা আনট্র্যাকড তা দেখুন',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-working-directory',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'What is the difference between an untracked file and an unmodified tracked file?',
      questionBn: 'আনট্র্যাকড ফাইল এবং আনমডিফাইড ট্র্যাকড ফাইলের মধ্যে পার্থক্য কী?',
      answer: 'A tracked file is one that was present in the previous commit snapshot or has been added to the staging index; Git monitors it for changes. An untracked file is any file in your working directory that was neither in your last snapshot nor in your staging area.',
      answerBn: 'ট্র্যাকড ফাইল হলো যা আগের কমিট বা স্টেজিং ইনডেক্সে বিদ্যমান, যার পরিবর্তন গিট নজরদারিতে রাখে। আর আনট্র্যাকড ফাইল হলো নতুন ফাইল যা গিট এখনও রেকর্ড করা শুরু করেনি।',
      keyPoints: [
        'Untracked files are ignored by commit operations until staged with `git add`',
        '`.gitignore` allows permanently preventing untracked files from appearing in `git status`',
      ],
    },
    quiz: {
      id: 'quiz-working-directory',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'When you edit a line of code in VS Code, where does that change currently exist?',
      questionBn: 'যখন আপনি ভিএস কোডে একটি লাইন পরিবর্তন করেন, তখন সেই পরিবর্তনটি বর্তমানে কোথায় থাকে?',
      options: [
        { id: 'opt-a', text: 'Only in your Working Directory on your filesystem', textBn: 'শুধুমাত্র আপনার ফাইলসিস্টেমের ওয়ার্কিং ডিরেক্টরিতে', isCorrect: true },
        { id: 'opt-b', text: 'In Git\'s staging index automatically', textBn: 'স্বয়ংক্রিয়ভাবে গিটের স্টেজিং ইনডেক্সে', isCorrect: false },
        { id: 'opt-c', text: 'In the Local Repository commit history', textBn: 'লোকাল রিপোজিটরির কমিট হিস্ট্রিতে', isCorrect: false },
        { id: 'opt-d', text: 'On GitHub servers', textBn: 'গিটহাবের সার্ভারে', isCorrect: false },
      ],
      explanation: 'Until you run `git add`, changes remain solely in your working tree on your physical disk. Git knows they are modified, but hasn\'t saved them.',
      explanationBn: 'যতক্ষণ না আপনি `git add` চালাচ্ছেন, ততক্ষণ পরিবর্তনগুলো শুধু আপনার কম্পিউটারের ডিস্কের ফাইলেই থাকে। গিট তা এখনো সেভ করেনি।',
    },
  },
  {
    id: 'git.fundamentals.staging-area',
    moduleId: 'git-fundamentals',
    slug: 'staging-area',
    order: 5,
    durationMinutes: 9,
    difficulty: 'beginner',
    title: 'The Staging Area (The Index)',
    titleBn: 'স্টেজিং এরিয়া (ইনডেক্স)',
    summary: 'The staging area acts as a drafting table where you curate, organize and assemble clean atomic commits.',
    summaryBn: 'স্টেজিং এরিয়া যা একটি প্রস্তুতি টেবিল হিসেবে কাজ করে যেখানে আপনি পরবর্তী কমিট সাজিয়ে নেন।',
    learningObjectives: [
      'Understand the role of `.git/index` as the staging area',
      'Explain how the staging area allows splitting work into atomic commits',
      'Use `git add` and `git restore --staged` to curate the index',
    ],
    learningObjectivesBn: [
      'স্টেজিং এরিয়া হিসেবে `.git/index` ফাইলের কাজ বোঝা',
      'স্টেজিং এরিয়া কীভাবে পারমাণবিক ও সুসংগঠিত কমিট বানাতে সাহায্য করে তা জানা',
      '`git add` ও `git restore --staged` দিয়ে ইনডেক্স নিয়ন্ত্রণ করা',
    ],
    keyTakeaways: [
      'The Staging Area is technically a binary file named `index` stored inside the `.git` directory.',
      'It acts as the intermediate staging dock between your working tree edits and permanent commit history.',
      'The staging area allows you to stage 1 file out of 10 modified files, creating targeted, atomic commits.',
    ],
    sections: [
      {
        id: 'sec-staging-dock',
        title: 'The Cargo Loading Dock Analogy',
        titleBn: 'জাহাজের কার্গো ডকিং উপমা',
        blocks: [
          {
            type: 'paragraph',
            text: 'Think of your Working Directory as your factory floor where you manufacture goods. The Staging Area is the cargo shipping container on the dock. You don\'t ship goods the second you make them; you carefully place selected items into the container. When the container is packed with related items, `git commit` seals the container and loads it onto the ship.',
            textBn: 'ওয়ার্কিং ডিরেক্টরিকে একটি ফ্যাক্টরি এবং স্টেজিং এরিয়াকে একটি শিপিং কন্টেইনার ভাবুন। আপনি প্রতিটি তৈরি করা জিনিস সাথে সাথে জাহাজে পাঠান না; বরং কন্টেইনারে নির্দিষ্ট মালপত্র গুছিয়ে তোলেন। গোছানো শেষ হলে `git commit` দিয়ে কন্টেইনার সিল করে জাহাজে তুলে দেন।',
          },
          {
            type: 'command',
            command: 'git add src/auth/login.ts',
            description: 'Stage only login.ts while leaving other experimental edits unstaged',
            descriptionBn: 'অন্যান্য ফাইল অক্ষত রেখে শুধু login.ts ফাইলটি স্টেজ করুন',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-staging-area',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'Why does Git have a Staging Area, whereas systems like SVN or Mercurial commit directly from the working directory?',
      questionBn: 'SVN এর মতো সিস্টেম সরাসরি কমিট করলেও গিটে স্টেজিং এরিয়া থাকার কারণ কী?',
      answer: 'The Staging Area provides fine-grained control over what goes into each commit. It allows developers to craft atomic commits by staging individual files or even individual lines of code (via `git add -p`), decoupling the editing workflow from version recording.',
      answerBn: 'স্টেজিং এরিয়া কমিটের ওপর পূর্ণ নিয়ন্ত্রণ দেয়। এর মাধ্যমে ডেভেলপাররা ২০টি ফাইল এডিট করলেও একটি নির্দিষ্ট ফিচার সম্পর্কিত ফাইলগুলোকে বেছে বেছে ছোট ছোট নিখুঁত কমিটে রূপ দিতে পারেন।',
      keyPoints: [
        'Decouples editing from committing',
        'Enables atomic commits (each commit does one clear thing)',
        'Supports patch mode (`git add -p`) to stage partial file changes',
      ],
    },
    quiz: {
      id: 'quiz-staging-area',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'Which file on disk actually stores the state of the Staging Area?',
      questionBn: 'ডিস্কের কোন ফাইলটি মূলত স্টেজিং এরিয়ার অবস্থা ধারণ করে?',
      options: [
        { id: 'opt-a', text: '`.git/index`', textBn: '`.git/index`', isCorrect: true },
        { id: 'opt-b', text: '`staging.json`', textBn: '`staging.json`', isCorrect: false },
        { id: 'opt-c', text: '`.gitignore`', textBn: '`.gitignore`', isCorrect: false },
        { id: 'opt-d', text: '`package.json`', textBn: '`package.json`', isCorrect: false },
      ],
      explanation: 'The staging area is stored in a binary file located at `.git/index`. That is why the staging area is often interchangeably called the "Index".',
      explanationBn: 'স্টেজিং এরিয়া মূলত `.git/index` বাইনারি ফাইলে সংরক্ষিত থাকে। এজন্য এটিকে প্রায়শই "Index" বলা হয়।',
    },
  },
  {
    id: 'git.fundamentals.local-repository',
    moduleId: 'git-fundamentals',
    slug: 'local-repository',
    order: 6,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'The Local Repository',
    titleBn: 'লোকাল রিপোজিটরি',
    summary: 'Your local repository where permanent commit objects branch references, and the project graph reside completely on your machine.',
    summaryBn: 'লোকাল রিপোজিটরি যেখানে স্থায়ী কমিট অবজেক্ট, ব্রাঞ্চ রেফারেন্স ও প্রজেক্ট গ্রাফ সম্পূর্ণভাবে আপনার কম্পিউটারে অবস্থান করে।',
    learningObjectives: [
      'Understand that commits in the local repository are permanent and cryptographically secured',
      'Explain how Git tracks branches locally before pushing to any server',
      'Realize that a developer has full version control power even without network access',
    ],
    learningObjectivesBn: [
      'লোকাল রিপোজিটরির কমিট যে স্থায়ী ও ক্রিপ্টোগ্রাফিক্যালি সুরক্ষিত তা জানা',
      'সার্ভারে পুশ করার আগেই লোকাল ব্রাঞ্চগুলো কীভাবে কাজ করে তা বোঝা',
      'নেটওয়ার্ক ছাড়াই লোকালি সম্পূর্ণ ভার্সন কন্ট্রোল ব্যবহারের ক্ষমতা উপলব্ধি করা',
    ],
    keyTakeaways: [
      'The Local Repository is stored in the `.git/objects/` and `.git/refs/` directories.',
      'When you run `git commit`, your work is safely recorded locally without touching the network.',
      'You can create dozens of branches, rebase, merge, and inspect history without ever needing a remote server.',
    ],
    sections: [
      {
        id: 'sec-local-power',
        title: 'Complete Autonomy on Your Machine',
        titleBn: 'আপনার মেশিনে সম্পূর্ণ স্বায়ত্তশাসন',
        blocks: [
          {
            type: 'paragraph',
            text: 'In Git, "committing" and "sharing" are two separate steps. Running `git commit` stores your changes into your Local Repository. It does NOT send anything to GitHub. You can make 20 commits locally throughout the day and push them all at once when ready.',
            textBn: 'গিটে "কমিট করা" এবং "শেয়ার করা" দুটি আলাদা ধাপ। `git commit` চালালে কোড শুধু আপনার লোকাল রিপোজিটরিতে সেভ হয়, গিটহাবে যায় না। আপনি সারাদিনে ২০টি কমিট করে দিনশেষে একবারে পুশ করতে পারেন।',
          },
          {
            type: 'command',
            command: 'git commit -m "feat: complete user profile widget"',
            description: 'Records the staged snapshot permanently into your Local Repository',
            descriptionBn: 'স্টেজিং এরিয়ার স্ন্যাপশট লোকাল রিপোজিটরিতে স্থায়ীভাবে রেকর্ড করুন',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-local-repo',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'If you commit changes with `git commit`, are your changes visible to teammates on GitHub?',
      questionBn: '`git commit` দিলে সহকর্মীরা কি গিটহাবে সেই পরিবর্তনগুলো দেখতে পাবে?',
      answer: 'No. `git commit` records changes strictly in your local repository on your machine. To make those commits visible to teammates, you must explicitly run `git push` to transfer them to a shared remote repository.',
      answerBn: 'না। `git commit` শুধুমাত্র আপনার কম্পিউটারের লোকাল রিপোতে সেভ করে। সহকর্মীদের দেখাতে হলে আপনাকে অবশ্যই `git push` দিয়ে রিমোট সার্ভারে পাঠাতে হবে।',
      keyPoints: [
        'Commit = Save snapshot to local repository',
        'Push = Upload local commits to remote repository',
      ],
    },
    quiz: {
      id: 'quiz-local-repo',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'What does running `git commit` actually do?',
      questionBn: '`git commit` কমান্ড মূলত কী করে?',
      options: [
        { id: 'opt-a', text: 'Uploads your files to GitHub immediately', textBn: 'তাৎক্ষণিকভাবে আপনার ফাইল গিটহাবে আপলোড করে', isCorrect: false },
        { id: 'opt-b', text: 'Permanently records the staged changes as a new snapshot in your local repository', textBn: 'স্টেজিং পরিবর্তনগুলোকে লোকাল রিপোজিটরিতে স্থায়ী স্ন্যাপশট হিসেবে সেভ করে', isCorrect: true },
        { id: 'opt-c', text: 'Deletes your working tree files', textBn: 'ওয়ার্কিং ডিরেক্টরির সব ফাইল মুছে ফেলে', isCorrect: false },
        { id: 'opt-d', text: 'Installs new npm packages', textBn: 'নতুন প্যাকেজ ইনস্টল করে', isCorrect: false },
      ],
      explanation: '`git commit` packages the staged index into a commit snapshot stored in the local `.git` repository. It does not touch the network.',
      explanationBn: '`git commit` স্টেজিং এরিয়াকে লোকাল `.git` রিপোতে স্ন্যাপশট হিসেবে সেভ করে। এটি কোনো নেটওয়ার্ক ব্যবহার করে না।',
    },
  },
  {
    id: 'git.fundamentals.remote-repository',
    moduleId: 'git-fundamentals',
    slug: 'remote-repository',
    order: 7,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'The Remote Repository',
    titleBn: 'রিমোট রিপোজিটরি',
    summary: 'Remote versions of your project hosted on the internet or network, commonly referred to as `origin`.',
    summaryBn: 'ইন্টারনেটে সংরক্ষিত প্রজেক্টের রিমোট কপি, যা সাধারণত `origin` নামে পরিচিত।',
    learningObjectives: [
      'Define a Remote Repository and the default `origin` alias',
      'Understand Remote-Tracking Branches (e.g. `origin/main`)',
      'Explain how teams synchronize work using `fetch`, `pull`, and `push`',
    ],
    learningObjectivesBn: [
      'রিমোট রিপোজিটরি এবং ডিফল্ট `origin` নামের ভূমিকা বোঝা',
      'রিমোট-ট্র্যাকিং ব্রাঞ্চ (যেমন `origin/main`) কীভাবে কাজ করে তা জানা',
      'টিম কীভাবে `fetch`, `pull` ও `push` দিয়ে কোড শেয়ার করে তা উপলব্ধি করা',
    ],
    keyTakeaways: [
      'A Remote Repository is just a Git repository hosted on a shared server (e.g. GitHub, GitLab).',
      'Git tracks remote branches via local cached pointers like `refs/remotes/origin/main`.',
      'Commands like `git fetch`, `git pull`, and `git push` bridge your local repository and remote repositories.',
    ],
    sections: [
      {
        id: 'sec-remote-role',
        title: 'The Collaboration Hub',
        titleBn: 'টিম কোলাবোরেশনের কেন্দ্রবিন্দু',
        blocks: [
          {
            type: 'paragraph',
            text: 'A Remote Repository is typically a "bare" repository (a repository without a working directory) hosted on a central server. Because everyone pushes and pulls from this server, it serves as the authoritative sync hub for the entire engineering team.',
            textBn: 'রিমোট রিপোজিটরি সাধারণত একটি "বেয়ার" (bare) রিপোজিটরি যা কোনো সেন্ট্রাল সার্ভারে হোস্ট করা থাকে। প্রত্যেকে এখান থেকেই কোড পুশ ও পুল করে বলে এটি দলের প্রধান মিলনস্থল হিসেবে কাজ করে।',
          },
          {
            type: 'command',
            command: 'git remote -v',
            description: 'Inspect the configured remote URLs for fetching and pushing',
            descriptionBn: 'পুশ ও ফেচ করার জন্য কনফিগার করা রিমোট লিঙ্কগুলো দেখুন',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-remote-repo',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'What is a remote-tracking branch in Git (e.g., origin/main)?',
      questionBn: 'গিটে রিমোট-ট্র্যাকিং ব্রাঞ্চ (যেমন origin/main) বলতে কী বোঝায়?',
      answer: 'A remote-tracking branch is a local read-only bookmark that records where the remote branch was the last time you communicated with the server (via `fetch`, `pull`, or `push`). You cannot move it directly; Git updates it automatically during network sync.',
      answerBn: 'রিমোট-ট্র্যাকিং ব্রাঞ্চ হলো একটি লোকাল রিড-অনলি পয়েন্টার যা শেষবার সার্ভারের সাথে কথা বলার সময় রিমোট ব্রাঞ্চটি কোন কমিটে ছিল তার রেকর্ড রাখে। গিট নেটওয়ার্ক সিঙ্কের সময় এটি আপডেট করে।',
      keyPoints: [
        'Stored locally under `.git/refs/remotes/origin/`',
        'Updated only when network commands (`fetch`, `pull`, `push`) run',
      ],
    },
    quiz: {
      id: 'quiz-remote-repo',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'Which command uploads your local commits to the remote repository?',
      questionBn: 'কোন কমান্ডটি আপনার লোকাল কমিটগুলোকে রিমোট রিপোজিটরিতে আপলোড করে?',
      options: [
        { id: 'opt-a', text: '`git push`', textBn: '`git push`', isCorrect: true },
        { id: 'opt-b', text: '`git fetch`', textBn: '`git fetch`', isCorrect: false },
        { id: 'opt-c', text: '`git add`', textBn: '`git add`', isCorrect: false },
        { id: 'opt-d', text: '`git commit`', textBn: '`git commit`', isCorrect: false },
      ],
      explanation: '`git push` transfers commits from your local branch to the remote repository branch.',
      explanationBn: '`git push` কমান্ড লোকাল ব্রাঞ্চের নতুন কমিটগুলোকে রিমোট সার্ভারে ট্রান্সফার করে।',
    },
  },
  {
    id: 'git.fundamentals.commit',
    moduleId: 'git-fundamentals',
    slug: 'commit',
    order: 8,
    durationMinutes: 10,
    difficulty: 'beginner',
    title: 'What is a Commit?',
    titleBn: 'কমিট কী?',
    summary: 'Look under the hood of a Git commit: SHA-1/SHA-256 hashes, author metadata, tree references, parent pointers, and immutable snapshots.',
    summaryBn: 'গিট কমিটের অভ্যন্তরীণ গঠন: ক্রিপ্টোগ্রাফিক হ্যাশ, রচয়িতার তথ্য, ট্রি রেফারেন্স, প্যারেন্ট পয়েন্টার এবং অপরিবর্তনীয় স্ন্যাপশট।',
    learningObjectives: [],
    learningObjectivesBn: [],
    keyTakeaways: [
      'A commit is an immutable snapshot of your staged files saved directly into your local repository.',
      'The "Double-Edit" Trap: Git only commits what was actively staged; edits made after running git add are excluded unless staged again.',
      'A raw commit object contains: root tree pointer, parent commit hash(es), author & committer metadata, and the commit message.',
      'Every commit is mathematically immutable: changing any character or timestamp alters the cryptographic SHA hash entirely.',
    ],
    sections: [
      {
        id: 'sec-commit-concept',
        title: 'Permanent Snapshots & How Commits Work',
        titleBn: 'স্থায়ী স্ন্যাপশট এবং কমিট যেভাবে কাজ করে',
        blocks: [
          {
            type: 'paragraph',
            text: 'In Git, a **commit** represents a permanent, immutable snapshot of your files saved to your **Local Repository** at a specific point in time. Expanding on our courier delivery analogy: if the Staging Area is the prep table where you inspect and pack items into boxes, making a commit is loading those boxes onto the delivery truck—they are now safely sealed and recorded in your local project history.',
            textBn: 'গিটে একটি **কমিট** হলো কোনো নির্দিষ্ট মুহূর্তে আপনার **লোকাল রিপোজিটরি**-তে সংরক্ষিত ফাইলগুলোর একটি স্থায়ী ও অপরিবর্তনীয় স্ন্যাপশট। আমাদের কুরিয়ার সার্ভিসের রূপক দিয়ে বুঝলে: স্টেজিং এরিয়া যদি হয় প্যাকিং টেবিল যেখানে পার্সেল যাচাই-বাছাই করা হয়, তবে কমিট করা মানে হলো সেই বক্সগুলো ডেলিভারি ট্রাকে তুলে ফেলা—যা এখন সম্পূর্ণ সুরক্ষিত এবং প্রজেক্টের লোকাল ইতিহাসে সিলমোহরকৃত।',
          },
          {
            type: 'callout',
            variant: 'warning',
            title: 'The "Double-Edit" Trap',
            titleBn: 'বিপদজনক "ডাবল-এডিট" ফাঁদ',
            text: 'Git only commits what is actively in the **Staging Area**, not what is in your editor or Working Directory! If you stage a file (`git add demo.txt`), continue editing it in your code editor, and then run `git commit`, only the version from when you ran `git add` is saved into the commit snapshot. The subsequent edits remain uncommitted in your working directory unless you run `git add demo.txt` again before committing.',
            textBn: 'গিট কেবল **স্টেজিং এরিয়া**-তে থাকা ফাইলগুলোর সংস্করণই কমিট করে, এডিটর বা ওয়ার্কিং ডিরেক্টরিতে যা আছে তা নয়! আপনি যদি একটি ফাইল স্টেজ করেন (`git add demo.txt`), এরপর কোড এডিটরে তাতে আরও নতুন কোড লিখে সরাসরি `git commit` দেন, তবে `git add` করার মুহূর্তের কোডটুকুই কমিটে সংরক্ষিত হবে। পরবর্তী পরিবর্তনগুলো আনকমিটেড অবস্থায় ওয়ার্কিং ডিরেক্টরিতেই থেকে যাবে, যতক্ষণ না আপনি কমিট করার আগে পুনরায় `git add demo.txt` চালাচ্ছেন।',
          },
        ],
      },
      {
        id: 'sec-commit-anatomy',
        title: 'Anatomy of a Raw Commit Object',
        titleBn: 'একটি র কমিট অবজেক্টের অভ্যন্তরীণ রূপ',
        blocks: [
          {
            type: 'paragraph',
            text: 'If you inspect a commit object directly using `git cat-file -p <hash>`, you will see plain text that looks like this:',
            textBn: 'যদি আপনি `git cat-file -p <hash>` দিয়ে সরাসরি একটি কমিট অবজেক্ট দেখেন, তবে তার চেহারা দেখতে পাবেন এমন:',
          },
          {
            type: 'code',
            language: 'text',
            filename: 'raw commit object',
            code: `tree 7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b
parent 1f2e3d4c5b6a7f8e9d0c1b2a3f4e5d6c7b8a9f0e
author Linus Torvalds <torvalds@linux.org> 1113034234 -0700
committer Linus Torvalds <torvalds@linux.org> 1113034234 -0700

feat: implement initial git tree parser`,
          },
          {
            type: 'paragraph',
            text: 'Notice that the commit contains 4 essential components: 1. **Root Tree Hash** (snapshot of all files/directories). 2. **Parent Commit Hash** (pointer to the preceding commit). 3. **Author & Committer Metadata** (name, email, and precise timestamp). 4. **Commit Message**. Because a commit\'s unique SHA hash is computed over all these components combined, changing any byte alters its hash, ensuring total cryptographic immutability.',
            textBn: 'লক্ষ্য করুন একটি কমিটে ৪টি মূল উপাদান থাকে: ১. **রুট ট্রি হ্যাশ** (সব ফাইল ও ডিরেক্টরির স্ন্যাপশট)। ২. **প্যারেন্ট কমিট হ্যাশ** (পূর্ববর্তী কমিটের পয়েন্টার)। ৩. **রচয়িতা ও কমিটারের মেটাডাটা** (নাম, ইমেইল ও নির্ভুল সময়)। ৪. **কমিট মেসেজ**। এই সব উপাদান মিলিয়েই কমিটের অনন্য SHA হ্যাশ তৈরি হয়, তাই একটি অক্ষর বদলালেও হ্যাশ সম্পূর্ণ বদলে যায় এবং সর্বোচ্চ ক্রিপ্টোগ্রাফিক সুরক্ষা বজায় থাকে।',
          },
        ],
      },
      {
        id: 'sec-commit-lifecycle',
        title: 'Inspecting History and Undoing Commits',
        titleBn: 'ইতিহাস নিরীক্ষা এবং কমিট পূর্বাবস্থায় ফিরিয়ে আনা',
        blocks: [
          {
            type: 'paragraph',
            text: 'Every commit generates a unique cryptographic identifier (a SHA-1 or SHA-256 hash). You can inspect your project\'s historical timeline in reverse chronological order using `git log`. When you need to adjust or roll back changes, Git uses the `HEAD` pointer with `git reset` (using `--soft`, `--mixed`, or `--hard` modes).',
            textBn: 'প্রতিটি কমিট একটি অনন্য ক্রিপ্টোগ্রাফিক আইডেন্টিফায়ার (SHA-1 বা SHA-256 হ্যাশ) তৈরি করে। আপনি `git log` দিয়ে আপনার প্রজেক্টের টাইমলাইন নতুন থেকে পুরাতন ক্রমানুসারে দেখতে পারেন। এছাড়া কোনো ভুল হলে বা পরিবর্তন রোলব্যাক করতে চাইলে গিট `HEAD` পয়েন্টার এবং `git reset` (সফট, মিক্সড কিংবা হার্ড মোড) ব্যবহার করে।',
          },
          {
            type: 'callout',
            variant: 'note',
            title: 'Curriculum Roadmap',
            titleBn: 'পরবর্তী মডিউলের বিষয়বস্তু',
            text: 'Deep dive workflows for navigating your commit history are explored in **Everyday Workflows: Navigating Commit History (`git log`)**, while advanced rollback techniques are mastered in **Git Recovery: The Three Trees of `git reset`**.',
            textBn: 'কমিট ইতিহাস অনুসন্ধান ও ফিল্টারিং সংক্রান্ত বিস্তারিত বিষয় শেখানো হবে **Everyday Workflows: Navigating Commit History (`git log`)** পাঠে, এবং কমিট পূর্বাবস্থায় ফেরানোর বিস্তারিত টেকনিক শেখানো হবে **Git Recovery: The Three Trees of `git reset`** পাঠে।',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-commit-immutable',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'intermediate',
      question: 'Why is it said that commits in Git are immutable?',
      questionBn: 'কেন বলা হয় যে গিটের কমিটগুলো অপরিবর্তনীয় (immutable)?',
      answer: 'A commit’s unique ID is the cryptographic SHA hash calculated from its exact contents: the tree hash, author, timestamp, commit message, and crucially, its parent commit’s hash. Changing even one character or one second of time produces a completely different hash, creating a brand new commit rather than modifying the old one.',
      answerBn: 'একটি কমিটের আইডি হলো তার কনটেন্ট, সময়, মেসেজ এবং প্যারেন্টের হ্যাশের ক্রিপ্টোগ্রাফিক হ্যাশ। একটি অক্ষর বা সেকেন্ডও পরিবর্তন করলে হ্যাশ সম্পূর্ণ বদলে যায়, ফলে পুরনো কমিট পরিবর্তনের বদলে সম্পূর্ণ নতুন কমিট তৈরি হয়।',
      keyPoints: [
        'Commits are content-addressed by cryptographic hashes',
        'Altering a commit generates a new object with a new hash',
        'Guarantees total cryptographic audit integrity for code',
      ],
    },
    quiz: {
      id: 'quiz-commit',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'What links a commit to the previous version of the project?',
      questionBn: 'কোন জিনিসটি একটি কমিটকে প্রজেক্টের পূর্ববর্তী সংস্করণের সাথে যুক্ত করে?',
      options: [
        { id: 'opt-a', text: 'The parent commit hash stored inside the commit object', textBn: 'কমিট অবজেক্টের ভেতরে থাকা প্যারেন্ট কমিট হ্যাশ', isCorrect: true },
        { id: 'opt-b', text: 'A line number recorded in package.json', textBn: 'package.json ফাইলে থাকা লাইন নম্বর', isCorrect: false },
        { id: 'opt-c', text: 'A database table in SQL', textBn: 'SQL ডাটাবেসের একটি টেবিল', isCorrect: false },
        { id: 'opt-d', text: 'An IP address pointing to GitHub', textBn: 'গিটহাবের একটি আইপি অ্যাড্রেস', isCorrect: false },
      ],
      explanation: 'Every commit contains the hash of its parent commit(s). This chain of parent pointers forms the historical timeline graph of your project.',
      explanationBn: 'প্রতিটি কমিট তার পূর্ববর্তী প্যারেন্ট কমিটের হ্যাশ সংরক্ষণ করে। এই প্যারেন্ট পয়েন্টারের ধারাবাহিকতাই প্রজেক্টের ইতিহাস গ্রাফ তৈরি করে।',
    },
  },
  {
    id: 'git.fundamentals.branch',
    moduleId: 'git-fundamentals',
    slug: 'branch',
    order: 9,
    durationMinutes: 9,
    difficulty: 'beginner',
    title: 'What is a Branch?',
    titleBn: 'ব্রাঞ্চ কী?',
    summary: 'Branch is not a directory copy, but a simple 41-byte text file storing a commit hash pointer that automatically advances with each new commit.',
    summaryBn: 'ব্রাঞ্চ কোনো ফোল্ডার কপি নয়, বরং একটি ৪১ বাইটের টেক্সট ফাইল যা নতুন কমিটের সাথে সাথে স্বয়ংক্রিয়ভাবে এগিয়ে যায়।',
    learningObjectives: [],
    learningObjectivesBn: [],
    keyTakeaways: [
      'A branch provides an isolated workspace to develop features and fix bugs safely without affecting the main codebase.',
      'Git branches are not directory copies, but lightweight 41-byte pointer files containing a commit hash.',
      'Switching branches dynamically swaps the files in your Working Directory to match that branch’s snapshot.',
      'When feature development is complete, changes are merged back into main; full merge workflows are mastered in Module 4.',
    ],
    sections: [
      {
        id: 'sec-branch-problem',
        title: 'The Problem Branches Solve: Keeping Code Safe',
        titleBn: 'ব্রাঞ্চ যে সমস্যার সমাধান করে: কোড নিরাপদ রাখা',
        blocks: [
          {
            type: 'paragraph',
            text: 'In Git, a **branch** is an independent, isolated workspace that allows you to develop features, fix bugs, or experiment with changes safely without affecting the main working code. To understand why branches are essential, consider a real-world scenario:',
            textBn: 'গিটে একটি **ব্রাঞ্চ** হলো সম্পূর্ণ স্বাধীন ও পৃথক একটি কাজের পরিমণ্ডল, যা আপনাকে মূল কোডের কোনো ক্ষতি না করে নিরাপদে নতুন ফিচার তৈরি, বাগ ফিক্স কিংবা এক্সপেরিমেন্ট করার সুযোগ দেয়। ব্রাঞ্চিং কেন এত প্রয়োজনীয়, তা একটি বাস্তব উদাহরণ দিয়ে বোঝা যাক:',
          },
          {
            type: 'callout',
            variant: 'note',
            title: 'The Real-World Client Scenario',
            titleBn: 'বাস্তব জীবনের একটি দৃশ্যপট',
            text: '**The Scenario:** You built an application for a client, and it is currently running smoothly in production on your **main branch** (`main` or `master`).\n\n**The Risk:** The client asks for an urgent new feature. If you edit the code directly in your `main` branch, an accidental bug could crash the live application while users are actively using it!\n\n**The Branching Solution:** Instead of touching the live code, you create a **separate branch**. You work freely, add your features, and test them as much as you like in total isolation. Once you verify that the new feature is fully complete and bug-free, you safely join—or **merge**—those changes back into your `main` branch.',
            textBn: '**দৃশ্যপট:** আপনি ক্লায়েন্টের জন্য একটি অ্যাপ বানিয়েছেন যা বর্তমানে প্রোডাকশনে সক্রিয় এবং নির্ভুলভাবে চলছে আপনার **main ব্রাঞ্চ**-এ।\n\n**ঝুঁকি:** ক্লায়েন্ট হঠাৎ একটি নতুন ফিচার যোগ করতে বললেন। আপনি যদি সরাসরি `main` ব্রাঞ্চে কোড এডিট করতে শুরু করেন, তবে অনিচ্ছাকৃত কোনো বাগ লাইভ অ্যাপ্লিকেশন ক্র্যাশ করিয়ে দিতে পারে!\n\n**ব্রাঞ্চিং সমাধান:** সরাসরি লাইভ কোডে হাত না দিয়ে আপনি একটি **আলাদা ব্রাঞ্চ** তৈরি করবেন। সম্পূর্ণ নিরাপদ পরিবেশে ফিচারটি বানিয়ে টেস্ট করবেন। সবকিছু ১০০% প্রস্তুত ও বাগ-মুক্ত হলে নিরাপদে সেই কোড আবার `main` ব্রাঞ্চে **মার্জ (merge)** করে দেবেন।',
          },
        ],
      },
      {
        id: 'sec-branch-internals',
        title: 'How Branching Works Under the Hood',
        titleBn: 'অভ্যন্তরীণভাবে ব্রাঞ্চ যেভাবে কাজ করে',
        blocks: [
          {
            type: 'paragraph',
            text: 'In many legacy version control systems, creating a branch meant copying all project files into another directory. In Git, a branch is literally a **41-byte text file** inside `.git/refs/heads/<name>` that contains a 40-character commit hash pointer followed by a newline.',
            textBn: 'অনেক পুরনো ভার্সন কন্ট্রোল সিস্টেমে ব্রাঞ্চ তৈরি মানে পুরো প্রজেক্টের ফাইল অন্য ফোল্ডারে কপি করা। আর গিটে একটি ব্রাঞ্চ হলো `.git/refs/heads/<name>` এর ভেতরের মাত্র **৪১ বাইটের একটি টেক্সট ফাইল**, যা শুধু একটি ৪০ অক্ষরের কমিট হ্যাশ ধারণ করে।',
          },
          {
            type: 'callout',
            variant: 'important',
            title: 'Separate Timelines: The Disappearing File Mystery',
            titleBn: 'আলাদা টাইমলাইন: ফাইল উদাও ও ফিরে আসার রহস্য',
            text: 'When you create a file (e.g., `feature1.txt`) on your new branch and commit it, that file only exists on that branch’s timeline. If you switch back to your `main` branch, that file will instantly disappear from your computer folder because it is not part of `main`’s history! When you switch back to your feature branch, Git restores it immediately.',
            textBn: 'আপনি যখন নতুন ব্রাঞ্চে গিয়ে একটি ফাইল (যেমন `feature1.txt`) তৈরি করে কমিট করবেন, সেই ফাইলটি কেবল ওই নির্দিষ্ট ব্রাঞ্চের টাইমলাইনে থাকবে। আপনি যখন পুনরায় `main` ব্রাঞ্চে ফিরে আসবেন, আপনার কম্পিউটারের ফোল্ডার থেকে ফাইলটি তাৎক্ষণিকভাবে গায়েব হয়ে যাবে কারণ এটি `main` এর ইতিহাসে নেই! আবার ওই ব্রাঞ্চে সুইচ করলেই গিট ফাইলটি সঙ্গে সঙ্গে ফিরিয়ে আনবে।',
          },
        ],
      },
      {
        id: 'sec-branch-commands',
        title: 'Essential Branching Commands',
        titleBn: 'অপরিহার্য ব্রাঞ্চিং কমান্ডসমূহ',
        blocks: [
          {
            type: 'command',
            command: 'git branch',
            description: 'List all local branches. The branch you are currently on will have an asterisk (*) next to it.',
            descriptionBn: 'সকল লোকাল ব্রাঞ্চের তালিকা দেখুন। বর্তমান সক্রিয় ব্রাঞ্চটির পাশে একটি স্টার (*) চিহ্ন থাকবে।',
          },
          {
            type: 'command',
            command: 'git branch feature',
            description: 'Create a new branch pointer named "feature" at the current commit.',
            descriptionBn: 'বর্তমান কমিটকে পয়েন্ট করে "feature" নামে একটি নতুন ব্রাঞ্চ পয়েন্টার তৈরি করুন।',
          },
          {
            type: 'command',
            command: 'git switch feature',
            description: 'Switch your working directory to the "feature" branch (or classic `git checkout feature`).',
            descriptionBn: 'ওয়ার্কিং ডিরেক্টরিকে "feature" ব্রাঞ্চে পরিবর্তন করুন (বা সনাতন `git checkout feature`)।',
          },
          {
            type: 'callout',
            variant: 'tip',
            title: 'Create and Switch in One Command',
            titleBn: 'এক কমান্ডেই তৈরি ও সুইচ করুন',
            text: 'You can create and immediately switch to a new branch in a single step using `git switch -c feature` (or `git checkout -b feature`).',
            textBn: 'আপনি `git switch -c feature` (অথবা `git checkout -b feature`) দিয়ে এক কমান্ডেই নতুন ব্রাঞ্চ বানিয়ে সেখানে সুইচ করতে পারেন।',
          },
          {
            type: 'command',
            command: 'git merge feature',
            description: 'While on main, integrate the verified changes from the "feature" branch into main.',
            descriptionBn: 'main ব্রাঞ্চে থাকা অবস্থায় "feature" ব্রাঞ্চের পরীক্ষিত পরিবর্তনগুলোকে main-এ মার্জ করুন।',
          },
        ],
      },
      {
        id: 'sec-branch-conflicts-preview',
        title: 'What is a Merge Conflict?',
        titleBn: 'মার্জ কনফ্লিক্ট কী?',
        blocks: [
          {
            type: 'paragraph',
            text: 'Sometimes, branching and merging run into an issue known as a **merge conflict**. This happens if you modify the **exact same line of the exact same file** in two different branches and then try to merge them.',
            textBn: 'কখনো কখনো ব্রাঞ্চিং ও মার্জিংয়ের সময় **মার্জ কনফ্লিক্ট (Merge Conflict)** তৈরি হতে পারে। যখন দুটি ভিন্ন ব্রাঞ্চে **একই ফাইলের হুবহু একই লাইনে** ভিন্ন পরিবর্তন করে সেগুলো মার্জ করার চেষ্টা করা হয়, তখনই এটি ঘটে।',
          },
          {
            type: 'callout',
            variant: 'note',
            title: 'Curriculum Roadmap: Mastering Merges & Conflicts',
            titleBn: 'পরবর্তী মডিউলের রোডম্যাপ: মার্জিং ও কনফ্লিক্ট সমাধান',
            text: 'Because both branches claim different versions of the same line, Git pauses the merge and inserts conflict markers (`<<<<<<<`, `=======`, `>>>>>>>`). Complete step-by-step conflict resolution and 3-way merge mechanics are mastered in **Module 4: Merging & Conflict Resolution**.',
            textBn: 'যেহেতু দুটি ব্রাঞ্চেই একই লাইনের আলাদা কোড থাকে, তাই গিট মার্জ সাময়িকভাবে থামিয়ে কনফ্লিক্ট মার্কার (`<<<<<<<`, `=======`, `>>>>>>>`) যোগ করে। মার্জ কনফ্লিক্ট শনাক্ত ও নিখুঁত সমাধানের সম্পূর্ণ প্রক্রিয়া বিস্তারিতভাবে শেখানো হবে **Module 4: Merging & Conflict Resolution**-এ।',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-branch-mechanics',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'What happens physically inside the `.git` directory when you create a new branch?',
      questionBn: 'নতুন ব্রাঞ্চ তৈরি করলে `.git` ফোল্ডারের ভেতরে ফিজিক্যালি কী ঘটে?',
      answer: 'Git writes a small 41-byte text file named after your branch into `.git/refs/heads/<branchname>`. This file contains the exact 40-character SHA hash of the commit where you branched from. No code or files are copied.',
      answerBn: 'গিট `.git/refs/heads/` ফোল্ডারে ব্রাঞ্চের নামে ৪১ বাইটের একটি সাধারণ টেক্সট ফাইল লেখে, যার ভেতরে বর্তমান কমিটের ৪০ অক্ষরের হ্যাশ থাকে। কোনো কোড বা ফাইল কপি হয় না।',
      keyPoints: [
        'Instantaneous creation and deletion (O(1) complexity)',
        'Takes virtually zero disk space',
      ],
    },
    quiz: {
      id: 'quiz-branch',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'In Git, what is a branch fundamentally under the hood?',
      questionBn: 'অভ্যন্তরীণভাবে গিটের একটি ব্রাঞ্চ মূলত কী?',
      options: [
        { id: 'opt-a', text: 'A completely separate copy of all files in a new directory', textBn: 'নতুন ডিরেক্টরিতে প্রজেক্টের সমস্ত ফাইলের সম্পূর্ণ পৃথক কপি', isCorrect: false },
        { id: 'opt-b', text: 'A lightweight movable pointer to a specific commit', textBn: 'একটি নির্দিষ্ট কমিটকে নির্দেশ করা লাইটওয়েট চলমান পয়েন্টার', isCorrect: true },
        { id: 'opt-c', text: 'A special server on GitHub', textBn: 'গিটহাবের একটি বিশেষ সার্ভার', isCorrect: false },
        { id: 'opt-d', text: 'A locked database transaction', textBn: 'একটি লক করা ডাটাবেস ট্রানজ্যাকশন', isCorrect: false },
      ],
      explanation: 'A branch is simply a pointer pointing to a commit hash. When you make a new commit, the pointer moves forward to the new commit.',
      explanationBn: 'ব্রাঞ্চ হলো সাধারণ একটি পয়েন্টার যা একটি কমিট হ্যাশকে পয়েন্ট করে। নতুন কমিট করলে পয়েন্টারটি স্বয়ংক্রিয়ভাবে নতুন কমিটে চলে যায়।',
    },
  },
  {
    id: 'git.fundamentals.head',
    moduleId: 'git-fundamentals',
    slug: 'head',
    order: 10,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'Understanding HEAD: Where You Are in Git',
    titleBn: 'HEAD কী? আপনি গিটের কোথায় আছেন তা জানা',
    summary: 'HEAD is a special pointer that tells Git which branch or commit snapshot your working directory currently represents.',
    summaryBn: 'HEAD হলো একটি বিশেষ পয়েন্টার যা গিটকে বলে দেয় আপনার ওয়ার্কিং ডিরেক্টরি বর্তমানে কোন ব্রাঞ্চ বা কমিটে অবস্থান করছে।',
    learningObjectives: [],
    learningObjectivesBn: [],
    keyTakeaways: [
      'HEAD is Git’s internal "You Are Here" pointer, indicating which branch and snapshot your working directory currently represents.',
      'When you run `git branch`, the asterisk (*) visually marks the branch where HEAD is currently resting.',
      'Switching branches with `git checkout` or `git switch` automatically moves the HEAD pointer to your new active branch.',
      'A "Detached HEAD" occurs when HEAD points directly to a commit hash rather than a named branch.',
    ],
    sections: [
      {
        id: 'sec-head-concept',
        title: 'What is HEAD? The "You Are Here" Bookmark',
        titleBn: 'HEAD কী? গিটের "You Are Here" বুকমার্ক',
        blocks: [
          {
            type: 'paragraph',
            text: 'In Git, **HEAD** is simply a bookmark or a "You Are Here" GPS pin. It tells Git which branch and commit snapshot your Working Directory is currently linked to. Whenever you create a new commit, Git looks at HEAD to know exactly where to attach that commit.',
            textBn: 'গিটে **HEAD** হলো মূলত একটি ডিজিটাল বুকমার্ক বা মানচিত্রের "You Are Here" পিনের মতো। এটি গিটকে জানিয়ে দেয় যে আপনার ওয়ার্কিং ডিরেক্টরি এই মুহূর্তে কোন ব্রাঞ্চ ও কমিটের সাথে যুক্ত আছে। আপনি যখনই কোনো নতুন কমিট করেন, গিট HEAD-এর দিকে তাকিয়েই বুঝতে পারে নতুন কমিটটি কার সাথে জুড়তে হবে।',
          },
          {
            type: 'callout',
            variant: 'note',
            title: 'The Everyday Developer Workflow',
            titleBn: 'দৈনন্দিন ডেভেলপার ওয়ার্কফ্লো',
            text: 'In every Git project, the default branch is usually **`main`**. When you create a new branch (`git branch feature-login`) and run `git branch` to inspect your branches, you will see an asterisk (**`*`**) next to your active branch:\n\n```text\n* main\n  feature-login\n```\nThat asterisk (**`*`**) is visually showing you where **HEAD** is pointing right now!',
            textBn: 'প্রতিটি গিট প্রজেক্টে সাধারণত ডিফল্ট ব্রাঞ্চ থাকে **`main`**। যখন আপনি একটি নতুন ব্রাঞ্চ তৈরি করেন (`git branch feature-login`) এবং কোন ব্রাঞ্চে আছেন তা দেখার জন্য `git branch` চালান, তখন সক্রিয় ব্রাঞ্চটির পাশে একটি স্টার চিহ্ন (**`*`**) দেখতে পাবেন:\n\n```text\n* main\n  feature-login\n```\nএই স্টার চিহ্নটিই (**`*`**) মূলত নির্দেশ করে যে **HEAD** এই মুহূর্তে কোন ব্রাঞ্চের দিকে তাকিয়ে আছে!',
          },
        ],
      },
      {
        id: 'sec-head-switching',
        title: 'How HEAD Moves When Switching Branches',
        titleBn: 'ব্রাঞ্চ পরিবর্তনের সাথে HEAD যেভাবে সরে যায়',
        blocks: [
          {
            type: 'paragraph',
            text: 'You never need to manually edit internal files to move HEAD. Git moves HEAD for you automatically whenever you switch branches using `git switch` or `git checkout`:',
            textBn: 'HEAD পরিবর্তন করার জন্য আপনাকে নিজে থেকে কোনো ফাইল এডিট করতে হয় না। আপনি যখনই `git switch` বা `git checkout` দিয়ে ব্রাঞ্চ পরিবর্তন করেন, গিট স্বয়ংক্রিয়ভাবে HEAD-কে সরিয়ে দেয়:',
          },
          {
            type: 'command',
            command: 'git branch',
            description: 'Check your branches and see where HEAD is currently resting (marked with *).',
            descriptionBn: 'সকল ব্রাঞ্চ দেখুন এবং HEAD বর্তমানে কোথায় অবস্থান করছে তা জানুন (* চিহ্নিত)।',
          },
          {
            type: 'command',
            command: 'git checkout feature-login',
            description: 'Switch to feature-login (or use modern `git switch feature-login`). HEAD automatically moves to point to feature-login.',
            descriptionBn: 'feature-login ব্রাঞ্চে যান (বা আধুনিক `git switch feature-login` ব্যবহার করুন)। HEAD স্বয়ংক্রিয়ভাবে নতুন ব্রাঞ্চে সরে যাবে।',
          },
          {
            type: 'command',
            command: 'git commit -m "add login form"',
            description: 'When you commit, Git attaches the new commit to feature-login (because HEAD is on it) and advances both feature-login and HEAD together.',
            descriptionBn: 'কমিট করার সময় গিট feature-login-এ নতুন কমিট যুক্ত করে এবং ব্রাঞ্চ ও HEAD দুটিকেই একসাথে সামনে এগিয়ে নেয়।',
          },
        ],
      },
      {
        id: 'sec-head-detached',
        title: 'What is a "Detached HEAD"?',
        titleBn: '"Detached HEAD" বলতে কী বোঝায়?',
        blocks: [
          {
            type: 'paragraph',
            text: 'Normally, HEAD points to a named branch (e.g., `HEAD -> main -> commit`). This is called **Attached HEAD**.\n\nA **Detached HEAD** happens when HEAD points directly to a raw commit hash instead of a branch name (for example, if you run `git checkout <commit-hash>`). In this state, your bookmark is resting directly on past history without a named branch anchor.',
            textBn: 'স্বাভাবিক অবস্থায় HEAD সবসময় একটি ব্রাঞ্চ নামের দিকে তাকিয়ে থাকে (যেমন: `HEAD -> main -> commit`)। একে বলা হয় **Attached HEAD**।\n\nআর **Detached HEAD** তখনই ঘটে যখন HEAD কোনো ব্রাঞ্চ নামের বদলে সরাসরি কোনো পুরনো কমিট হ্যাশের ওপর বসে থাকে (যেমন আপনি যদি কোনো পুরনো কমিটে যেতে `git checkout <commit-hash>` চালান)। এই অবস্থায় আপনার বুকমার্কটি কোনো ব্রাঞ্চের নিরাপত্তা ছাড়া সরাসরি ইতিহাসের পাতায় আটকে থাকে।',
          },
          {
            type: 'callout',
            variant: 'tip',
            title: 'How to Safely Leave Detached HEAD',
            titleBn: 'Detached HEAD থেকে নিরাপদে ফেরার উপায়',
            text: 'Don\'t panic if you ever see a "detached HEAD" message! To return to your normal branch safely, simply switch back:\n```bash\ngit switch main\n# or: git checkout main\n```\nIf you made experimental changes in detached HEAD that you want to keep, save them into a brand new branch:\n```bash\ngit switch -c my-new-feature\n```',
            textBn: 'কখনো "detached HEAD" মেসেজ দেখলে ঘাবড়ানোর কিছু নেই! নিরাপদে আপনার স্বাভাবিক ব্রাঞ্চে ফিরে যেতে চাইলে লিখুন:\n```bash\ngit switch main\n# অথবা: git checkout main\n```\nআর যদি detached অবস্থায় নতুন কোনো এক্সপেরিমেন্টাল কাজ করে থাকেন যা আপনি সেভ করতে চান, তবে একটি নতুন ব্রাঞ্চ বানিয়ে নিন:\n```bash\ngit switch -c my-new-feature\n```',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-head-detached',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'intermediate',
      question: 'What is a "Detached HEAD" state and how do you get out of it safely?',
      questionBn: 'গিটে "Detached HEAD" অবস্থা কী এবং কীভাবে নিরাপদে এখান থেকে বের হওয়া যায়?',
      answer: 'Detached HEAD means HEAD points directly to a specific commit hash rather than a named branch. Any new commits made here are not connected to a branch and can be lost. To safely keep changes made in detached HEAD, run `git switch -c <new-branch-name>` to create a new branch attached to them.',
      answerBn: 'Detached HEAD অবস্থায় HEAD কোনো ব্রাঞ্চ নামের বদলে সরাসরি একটি কমিট হ্যাশকে নির্দেশ করে। এই অবস্থায় করা নতুন কাজ সেভ করতে `git switch -c <new-branch-name>` দিয়ে একটি নতুন ব্রাঞ্চ বানিয়ে নিলেই তা সুরক্ষিত থাকে।',
      keyPoints: [
        'Occurs when checking out a specific commit hash directly instead of a branch',
        'Easily resolved by returning with `git switch <branch>` or creating a new branch',
      ],
    },
    quiz: {
      id: 'quiz-head',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'In Git, what is HEAD and what does it indicate?',
      questionBn: 'গিটে HEAD কী এবং এটি কী নির্দেশ করে?',
      options: [
        { id: 'opt-a', text: 'A bookmark pointer indicating which branch or commit snapshot you are currently working on', textBn: 'একটি বুকমার্ক যা নির্দেশ করে আপনি বর্তমানে কোন ব্রাঞ্চ বা কমিট স্ন্যাপশটে কাজ করছেন', isCorrect: true },
        { id: 'opt-b', text: 'Your GitHub account password', textBn: 'আপনার গিটহাব অ্যাকাউন্টের পাসওয়ার্ড', isCorrect: false },
        { id: 'opt-c', text: 'A list of all deleted files', textBn: 'মুছে ফেলা সমস্ত ফাইলের তালিকা', isCorrect: false },
        { id: 'opt-d', text: 'The main server hosting your repository', textBn: 'রিপোজিটরি হোস্ট করা মূল সার্ভার', isCorrect: false },
      ],
      explanation: 'HEAD acts as Git\'s "You Are Here" pointer. It indicates the active branch and determines where your next commit will attach.',
      explanationBn: 'HEAD হলো গিটের "You Are Here" পয়েন্টার। এটি বর্তমান সক্রিয় ব্রাঞ্চ নির্দেশ করে এবং পরবর্তী কমিটটি কোথায় যুক্ত হবে তা নির্ধারণ করে।',
    },
  },
  {
    id: 'git.fundamentals.three-areas',
    moduleId: 'git-fundamentals',
    slug: 'three-areas',
    order: 11,
    durationMinutes: 10,
    difficulty: 'beginner',
    title: 'Git\'s Three Main Areas: The Unified Mental Model',
    titleBn: 'গিটের ৩টি মূল স্তর: পূর্ণাঙ্গ মানসিক নকশা (Mental Model)',
    summary: 'Bring the entire architecture together: Working Directory, Staging Area, and Git Directory (.git), plus Remote Sync. The foundational mental model every engineer must master.',
    summaryBn: 'সম্পূর্ণ আর্কিটেকচারকে একত্রিত করা: ওয়ার্কিং ডিরেক্টরি, স্টেজিং এরিয়া, লোকাল রিপোজিটরি এবং রিমোট সিঙ্ক। প্রতিটি ইঞ্জিনিয়ারের জন্য আবশ্যকীয় জ্ঞান।',
    learningObjectives: [
      'Master the lifecycle of a file across Git\'s 3 local areas plus the remote repository',
      'Trace file state transitions using `git add`, `git commit`, and `git push`',
      'Understand how to safely unstage and restore files across these layers',
    ],
    learningObjectivesBn: [
      'গিটের ৩টি স্তর ও রিমোটের মধ্য দিয়ে ফাইলের পূর্ণ জীবনচক্র আয়ত্ত করা',
      '`git add`, `git commit` ও `git push` এর মাধ্যমে ফাইলের ট্রানজিশন বোঝা',
      'এই স্তরগুলোর মধ্য দিয়ে ফাইল আনস্টেজ ও রিস্টোর করার পদ্ধতি জানা',
    ],
    keyTakeaways: [
      'Working Directory: Where you modify files on disk.',
      'Staging Area: Where you organize and curate files for the next snapshot.',
      'Local Repository: Where permanent cryptographic commit snapshots reside in `.git`.',
      'Remote Repository: Where team members synchronize and share committed snapshots.',
    ],
    sections: [
      {
        id: 'sec-unified-mental-model',
        title: 'The Unified Progression: Edit → Stage → Commit → Push',
        titleBn: 'ধারাবাহিক রূপান্তর: এডিট → স্টেজ → কমিট → পুশ',
        blocks: [
          {
            type: 'paragraph',
            text: 'Every single Git workflow in professional software engineering revolves around moving file snapshots through these stages. Once this mental model clicks, Git stops feeling like magic and starts feeling like an intuitive, predictable set of gears.',
            textBn: 'প্রফেশনাল সফটওয়্যার ইঞ্জিনিয়ারিংয়ের প্রতিটি গিট ওয়ার্কফ্লো এই স্তরগুলোর ওপর ভিত্তি করে পরিচালিত হয়। এই মানসিক নকশাটি পরিষ্কার হলে গিট আর রহস্যময় লাগে না, বরং অত্যন্ত যৌক্তিক ও অনুমানযোগ্য মনে হয়।',
          },
          {
            type: 'visualizer',
            initialState: 'working',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-three-areas',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'Walk me through the three main states a file can reside in within Git.',
      questionBn: 'গিটের ভেতরে একটি ফাইল কোন ৩টি মূল অবস্থায় থাকতে পারে তা বিস্তারিত বলুন।',
      answer: '1. Modified (Working Directory): You changed the file in your editor, but have not committed it. 2. Staged (Index): You marked a modified file in its current version to go into the next commit snapshot. 3. Committed (Local Repository): The data is safely and permanently stored in your local Git object database.',
      answerBn: '১. মডিফাইড (Working Directory): ফাইলে পরিবর্তন হয়েছে কিন্তু গিট ডাটাবেসে সেভ হয়নি। ২. স্টেজড (Staging Area): ফাইলটি পরবর্তী কমিটের জন্য প্রস্তুত করা হয়েছে। ৩. কমিটেড (Repository): পরিবর্তনটি লোকাল গিট ডাটাবেসে স্থায়ীভাবে সংরক্ষিত হয়েছে।',
      keyPoints: [
        'Working Tree -> Staging Area -> Git Repository',
        'Transitions triggered by `git add` and `git commit`',
      ],
    },
    quiz: {
      id: 'quiz-three-areas',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'Which sequence correctly represents the flow of saving code from your editor to GitHub?',
      questionBn: 'এডিটর থেকে গিটহাবে কোড সেভ করার সঠিক ক্রম কোনটি?',
      options: [
        { id: 'opt-a', text: 'Working Directory → Staging Area → Local Repository → Remote Repository', textBn: 'Working Directory → Staging Area → Local Repository → Remote Repository', isCorrect: true },
        { id: 'opt-b', text: 'Local Repository → Working Directory → Staging Area → GitHub', textBn: 'Local Repository → Working Directory → Staging Area → GitHub', isCorrect: false },
        { id: 'opt-c', text: 'Working Directory → GitHub → Staging Area', textBn: 'Working Directory → GitHub → Staging Area', isCorrect: false },
        { id: 'opt-d', text: 'Staging Area → Working Directory → Local Repository', textBn: 'Staging Area → Working Directory → Local Repository', isCorrect: false },
      ],
      explanation: 'You edit in the Working Directory, stage with `git add`, record locally with `git commit`, and sync remotely with `git push`.',
      explanationBn: 'প্রথমে ওয়ার্কিং ডিরেক্টরিতে এডিট, `git add` দিয়ে স্টেজ, `git commit` দিয়ে লোকাল সেভ, এবং শেষে `git push` দিয়ে রিমোট আপলোড।',
    },
  },
];
