import { CurriculumLesson } from '@/types/content';

/**
 * 12 Comprehensive Initial Lessons for Module 1: Git Fundamentals
 *
 * Each lesson provides deep conceptual understanding, practical commands,
 * mental model visualizer references, technical interview Q&A, and interactive quizzes.
 */
export const FUNDAMENTALS_LESSONS: CurriculumLesson[] = [
  {
    id: 'git.fundamentals.what-is-git',
    moduleId: 'git-fundamentals',
    slug: 'what-is-git',
    order: 1,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'What is Git & How Does it Work?',
    titleBn: 'গিট কী এবং এটি কীভাবে কাজ করে?',
    summary: 'Discover how Git revolutionized software engineering by treating version history as a sequence of cryptographic snapshots rather than file difference lists.',
    summaryBn: 'গিট কীভাবে ফাইলের ডিফারেন্স তালিকার পরিবর্তে ক্রিপ্টোগ্রাফিক স্ন্যাপশট হিসেবে ইতিহাস সংরক্ষণ করে সফটওয়্যার ইঞ্জিনিয়ারিংয়ে বিপ্লব এনেছে তা জানুন।',
    learningObjectives: [
      'Understand the difference between Centralized VCS and Distributed VCS',
      'Explain how Git stores data as cryptographic snapshots instead of deltas',
      'Understand why nearly every Git operation runs locally with zero network latency',
    ],
    learningObjectivesBn: [
      'সেন্ট্রালাইজড এবং ডিস্ট্রিবিউটেড ভার্সন কন্ট্রোলের মধ্যে পার্থক্য অনুধাবন',
      'গিট কীভাবে ডেল্টার বদলে স্ন্যাপশট হিসেবে ডাটা রাখে তা ব্যাখ্যা করা',
      'কেন গিটের প্রায় সমস্ত অপারেশন অফলাইনে তাৎক্ষণিকভাবে সম্পন্ন হয় তা জানা',
    ],
    keyTakeaways: [
      'Git is a Distributed Version Control System (DVCS) where every clone is a full repository backup.',
      'Git stores snapshots of your entire miniature filesystem, not diff chains.',
      'Cryptographic SHA hashes guarantee that not a single byte of your repository history can change without Git detecting it.',
    ],
    sections: [
      {
        id: 'sec-overview',
        title: 'The Core Mental Model: Snapshots, Not Deltas',
        titleBn: 'মূল মেন্টাল মডেল: ডেল্টা নয়, স্ন্যাপশট',
        blocks: [
          {
            type: 'paragraph',
            text: 'Most older Version Control Systems (like CVS, Subversion, and Perforce) store information as a list of file-based changes. These systems think of the information they keep as a set of files and the changes made to each file over time (commonly referred to as delta-based version control).',
            textBn: 'অধিকাংশ পুরনো ভার্সন কন্ট্রোল সিস্টেম (যেমন SVN বা CVS) ফাইলের পরিবর্তনগুলোকে তালিকা বা ডেল্টা (delta) হিসেবে সংরক্ষণ করত। অর্থাৎ তারা প্রতিটি ফাইলে সময়ের সাথে কী কী পরিবর্তন হয়েছে তার যোগ-বিয়োগের হিসাব রাখত।',
          },
          {
            type: 'paragraph',
            text: 'Git does not think of or store its data this way. Instead, Git thinks of its data more like a series of snapshots of a miniature filesystem. Every time you commit, Git takes a picture of what all your files look like at that moment and stores a reference to that snapshot.',
            textBn: 'গিট কিন্তু এভাবে কাজ করে না। গিট আপনার কোডবেসকে সময়ের সাথে একটি পূর্ণাঙ্গ মিনি ফাইলসিস্টেমের ছবি বা "স্ন্যাপশট" হিসেবে বিবেচনা করে। আপনি যখনই কমিট করেন, গিট সেই মুহূর্তের সমস্ত ফাইলের একটি স্থায়ী স্ন্যাপশট সংরক্ষণ করে।',
          },
          {
            type: 'keyConcept',
            title: 'If a file hasn\'t changed, Git doesn\'t duplicate it',
            titleBn: 'ফাইল অপরিবর্তিত থাকলে গিট নতুন করে কপি করে না',
            conceptKey: 'SNAPSHOT_EFFICIENCY',
            text: 'To be efficient, if files have not changed between commits, Git does not store the file again. Instead, it simply stores a link to the previous identical file blob it has already stored.',
            textBn: 'দক্ষতা বজায় রাখার জন্য, কোনো কমিটে যে ফাইলগুলো পরিবর্তিত হয়নি, গিট সেগুলোকে পুনরায় সেভ না করে পূর্বে সংরক্ষিত ফাইলের লিঙ্কের দিকে পয়েন্ট করে।',
          },
        ],
      },
      {
        id: 'sec-dvcs',
        title: 'Distributed Architecture',
        titleBn: 'ডিস্ট্রিবিউটেড আর্কিটেকচার',
        blocks: [
          {
            type: 'paragraph',
            text: 'In a Distributed VCS, clients don’t just check out the latest snapshot of the files from a central server; they fully mirror the repository, including its entire historical commit graph.',
            textBn: 'ডিস্ট্রিবিউটেড সিস্টেমে গ্রাহক শুধু সার্ভার থেকে কোড নামায় না, বরং পুরো রিপোজিটরির যাবতীয় পূর্ববর্তী ইতিহাসসহ একটি পূর্ণাঙ্গ কপি নিজের লোকাল ডিস্কে ধারণ করে।',
          },
          {
            type: 'callout',
            variant: 'tip',
            title: 'No Internet Needed for Daily Work',
            titleBn: 'দৈনন্দিন কাজে কোনো ইন্টারনেট সংযোগ প্রয়োজন হয় না',
            text: 'You can commit, branch, inspect logs, and diff files completely offline on an airplane or without WiFi. You only need network access when you explicitly run `git push` or `git fetch`.',
            textBn: 'আপনি বিমানে বা ইন্টারনেট ছাড়াও সম্পূর্ণ অফলাইনে কমিট, ব্রাঞ্চ তৈরি ও হিস্ট্রি দেখতে পারেন। শুধু `git push` বা `git pull` করার সময়ই ইন্টারনেটের প্রয়োজন হয়।',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-what-is-git',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'How does Git\'s storage model differ from traditional delta-based version control systems?',
      questionBn: 'ঐতিহ্যবাহী ডেল্টা-ভিত্তিক সিস্টেমের সাথে গিটের স্টোরেজ মডেলের পার্থক্য কী?',
      answer: 'Traditional VCS (like SVN) stores an initial baseline file followed by incremental diffs (deltas) for each version. Git stores snapshots of the entire project state at each commit. If a file hasn\'t changed, Git stores a pointer to the existing blob rather than recalculating deltas.',
      answerBn: 'SVN এর মতো সিস্টেমগুলো প্রতিটি ফাইলের পরিবর্তনের ডেল্টা বা পার্থক্য সঞ্চয় করে। আর গিট প্রতিটি কমিটে সম্পূর্ণ প্রজেক্টের একটি ক্রিপ্টোগ্রাফিক স্ন্যাপশট সংরক্ষণ করে। কোনো ফাইল অপরিবর্তিত থাকলে নতুন কপি না করে আগের পয়েন্টার ব্যবহার করে।',
      keyPoints: [
        'Git uses snapshots, SVN uses file deltas',
        'Unchanged files share identical SHA-1 blob pointers',
        'Allows nearly all Git operations (log, diff, commit) to run instantaneously offline',
      ],
      keyPointsBn: [
        'গিট স্ন্যাপশট ব্যবহার করে, ডেল্টা নয়',
        'অপরিবর্তিত ফাইলগুলো একই ব্লব শেয়ার করে',
        'অফলাইনে তাৎক্ষণিকভাবে হিস্ট্রি দেখার সুযোগ দেয়',
      ],
      followUpQuestions: [
        'How does Git ensure data integrity using cryptographic hashes?',
      ],
    },
    quiz: {
      id: 'quiz-what-is-git',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'How does Git store project changes across different commits?',
      questionBn: 'গিট বিভিন্ন কমিটে প্রজেক্টের পরিবর্তন কীভাবে সংরক্ষণ করে?',
      options: [
        { id: 'opt-a', text: 'As a list of diffs and line-by-line file deltas', textBn: 'ফাইলের লাইনভিত্তিক পার্থক্যের তালিকা (deltas) হিসেবে', isCorrect: false },
        { id: 'opt-b', text: 'As complete filesystem snapshots with pointers to unchanged files', textBn: 'পূর্ণাঙ্গ স্ন্যাপশট হিসেবে (অপরিবর্তিত ফাইলে পয়েন্টার রেখে)', isCorrect: true },
        { id: 'opt-c', text: 'By uploading zip files to GitHub automatically', textBn: 'স্বয়ংক্রিয়ভাবে গিটহাবে জিপ ফাইল আপলোড করার মাধ্যমে', isCorrect: false },
        { id: 'opt-d', text: 'By locking files on a centralized company server', textBn: 'সেন্ট্রাল সার্ভারে ফাইল লক করার মাধ্যমে', isCorrect: false },
      ],
      explanation: 'Git captures a snapshot of the entire project state. Unchanged files are referenced via existing SHA hashes rather than being duplicated.',
      explanationBn: 'গিট প্রজেক্টের পুরো অবস্থার স্ন্যাপশট নেয়। অপরিবর্তিত ফাইলগুলোকে রি-ডুপ্লিকেট না করে বিদ্যমান হ্যাশ দিয়ে রেফারেন্স দেয়।',
    },
  },
  {
    id: 'git.fundamentals.why-git',
    moduleId: 'git-fundamentals',
    slug: 'why-git',
    order: 2,
    durationMinutes: 7,
    difficulty: 'beginner',
    title: 'Why Git? Version Control Superpowers',
    titleBn: 'গিট কেন ব্যবহার করবেন? ভার্সন কন্ট্রোলের শক্তি',
    summary: 'Understand the business-critical reasons software teams rely on Git: reliable history, non-destructive experimentation, collaboration, and effortless rollbacks.',
    summaryBn: 'সফটওয়্যার টিমগুলো কেন গিটের ওপর নির্ভর করে: নির্ভরযোগ্য ইতিহাস, ঝুঁকিহীন পরীক্ষা-নিরীক্ষা, দলগত কোডিং এবং নির্বিঘ্ন রোলব্যাক।',
    learningObjectives: [
      'Recognize the risks of manual versioning (e.g. project_v2_final_final.zip)',
      'Explain how Git enables non-destructive experimentation via branches',
      'Understand auditability and accountability through cryptographic commit logs',
    ],
    learningObjectivesBn: [
      'ম্যানুয়াল ভার্সনিংয়ের (যেমন project_final_final.zip) ঝুঁকিগুলো চিহ্নিত করা',
      'ব্রাঞ্চিংয়ের মাধ্যমে ঝুঁকিহীন কোডিং পরীক্ষার সুবিধা বোঝা',
      'ক্রিপ্টোগ্রাফিক লগের মাধ্যমে কে কোন কোড লিখেছে তা ট্র্যাক করার পদ্ধতি জানা',
    ],
    keyTakeaways: [
      'Git replaces chaotic manual backups (`code_final_v2.zip`) with structured, searchable, reversible history.',
      'Developers can experiment freely on isolated branches without endangering the production code.',
      'Every commit provides auditability: who made the change, when, and most importantly, why.',
    ],
    sections: [
      {
        id: 'sec-the-problem',
        title: 'The Problem with Manual Versioning',
        titleBn: 'ম্যানুয়াল ব্যাকআপের সমস্যা',
        blocks: [
          {
            type: 'paragraph',
            text: 'Before version control, developers copied folders with names like `website_final`, `website_final_v2`, and `website_final_REAL_final`. This approach quickly leads to lost work, accidental overwrites, and no ability to determine which code broke a production release.',
            textBn: 'ভার্সন কন্ট্রোল আসার আগে ডেভেলপাররা `project_final`, `project_final2` নামে ফোল্ডার কপি করে ব্যাকআপ রাখতেন। এতে সহজেই ফাইল হারিয়ে যেত এবং কার কোডে বাগ তৈরি হয়েছে তা বের করা অসম্ভব হয়ে পড়ত।',
          },
          {
            type: 'callout',
            variant: 'important',
            title: 'The Four Superpowers of Git',
            titleBn: 'গিটের ৪টি মূল ক্ষমতা',
            text: '1. Time Travel: Return to any historical state in seconds.\n2. Branching: Work on multiple features concurrently in isolation.\n3. Accountability: Every line of code is attributed to an author and commit explanation.\n4. Distributed Redundancy: Every developer has a complete mirror of the repository.',
            textBn: '১. টাইম ট্রাভেল: সেকেন্ডের মধ্যে অতীতের যেকোনো কোড অবস্থায় ফেরা।\n২. ব্রাঞ্চিং: একই সাথে নিরাপদে একাধিক ফিচারে কাজ করা।\n৩. দায়বদ্ধতা: প্রতিটি লাইনের জন্য রচয়িতার ব্যাখ্যা ও সময় জানা।\n৪. ব্যাকআপ: দলের সবার কাছে পুরো রিপোজিটরির নির্ভুল কপি থাকা।',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-why-git',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'What are the main advantages of a Distributed VCS like Git over a Centralized VCS like SVN?',
      questionBn: 'SVN এর মতো সেন্ট্রালাইজড সিস্টেমের তুলনায় গিটের প্রধান সুবিধাগুলো কী?',
      answer: '1. No Single Point of Failure: If the central server crashes, any local clone can restore the complete repository history. 2. Performance: Most operations (log, commit, diff, branch) are instant and local. 3. Offline Work: Developers can work and commit without an internet connection.',
      answerBn: '১. কোনো সিঙ্গেল পয়েন্ট অব ফেইলিউর নেই: সেন্ট্রাল সার্ভার নষ্ট হলেও যেকোনো ক্লোন থেকে পুরো হিস্ট্রি ফিরিয়ে আনা যায়। ২. গতি: প্রায় সব কাজ লোকাল ডিস্কে বিদ্যুতগতিতে হয়। ৩. অফলাইন সাপোর্ট: ইন্টারনেট ছাড়াই কাজ করা যায়।',
      keyPoints: [
        'Full history on every machine eliminates single points of failure',
        'Sub-millisecond local operations for commit, diff, log, and checkout',
        'Enables flexible nonlinear branching and merging workflows',
      ],
    },
    quiz: {
      id: 'quiz-why-git',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'What happens if a central hosting server crashes in a distributed version control system like Git?',
      questionBn: 'ডিস্ট্রিবিউটেড ভার্সন কন্ট্রোলে সেন্ট্রাল সার্ভার নষ্ট হয়ে গেলে কী ঘটে?',
      options: [
        { id: 'opt-a', text: 'All past project history is permanently lost', textBn: 'পূর্ববর্তী সমস্ত প্রজেক্ট হিস্ট্রি চিরতরে হারিয়ে যায়', isCorrect: false },
        { id: 'opt-b', text: 'Any developer\'s local repository clone can fully restore the entire server', textBn: 'যেকোনো ডেভেলপারের লোকাল ক্লোন থেকে সম্পূর্ণ সার্ভার রিস্টোর করা সম্ভব', isCorrect: true },
        { id: 'opt-c', text: 'Developers cannot view their code on disk', textBn: 'ডেভেলপাররা তাদের লোকাল ফাইলও দেখতে পারে না', isCorrect: false },
        { id: 'opt-d', text: 'Commits must be rewritten from scratch', textBn: 'সব কমিট নতুন করে প্রথম থেকে লিখতে হয়', isCorrect: false },
      ],
      explanation: 'Because every clone is a complete repository mirror containing the full history graph, any local repository can restore the lost server.',
      explanationBn: 'যেহেতু প্রতিটি লোকাল ক্লোনে সম্পূর্ণ হিস্ট্রি গ্রাফ সংরক্ষিত থাকে, তাই যেকোনো ইউজারের কপি থেকেই সেন্ট্রাল সার্ভার পুরোপুরি রিকভার করা যায়।',
    },
  },
  {
    id: 'git.fundamentals.git-vs-github',
    moduleId: 'git-fundamentals',
    slug: 'git-vs-github',
    order: 3,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'Git vs GitHub: The Essential Distinction',
    titleBn: 'গিট বনাম গিটহাব: অত্যন্ত গুরুত্বপূর্ণ পার্থক্য',
    summary: 'A classic technical interview question: Git is the local version control command-line engine; GitHub is the cloud platform built on top of Git.',
    summaryBn: 'টেক ইন্টারভিউয়ের বহুল জিজ্ঞাসিত প্রশ্ন: গিট হলো লোকাল ভার্সন কন্ট্রোল ইঞ্জিন, আর গিটহাব হলো গিটের ওপর গড়ে ওঠা ক্লাউড প্ল্যাটফর্ম।',
    learningObjectives: [
      'Articulate the difference between Git (software engine) and GitHub (cloud service)',
      'Explain that Git functions completely without GitHub or any internet connection',
      'Identify the collaboration features GitHub adds (Pull Requests, Issues, Actions, Code Reviews)',
    ],
    learningObjectivesBn: [
      'গিট (সফটওয়্যার ইঞ্জিন) এবং গিটহাব (ক্লাউড সার্ভিস) এর পার্থক্য স্পষ্ট করা',
      'গিটহাব ছাড়াও গিট সম্পূর্ণ স্বাধীনভাবে লোকালি চলতে পারে তা জানা',
      'গিটহাব কী কী অতিরিক্ত সুবিধা দেয় (Pull Request, Issues, Actions) তা বোঝা',
    ],
    keyTakeaways: [
      'Git is an open-source command-line tool installed on your computer. It manages version history locally.',
      'GitHub is a commercial web hosting service (owned by Microsoft) that hosts Git repositories in the cloud.',
      'You can use Git without ever creating a GitHub account. Alternative hosts include GitLab, Bitbucket, and self-hosted servers.',
    ],
    sections: [
      {
        id: 'sec-comparison',
        title: 'Side-by-Side Comparison',
        titleBn: 'পাশাপাশি তুলনা',
        blocks: [
          {
            type: 'paragraph',
            text: 'One of the most frequent misconceptions among beginner software engineers is confusing Git with GitHub. They are related, but they are entirely different tools created by different people for different purposes.',
            textBn: 'নতুন সফটওয়্যার ইঞ্জিনিয়ারদের মধ্যে সবচেয়ে সাধারণ ভুল ধারণা হলো গিট ও গিটহাবকে একই জিনিস মনে করা। তারা পরস্পরের সাথে সম্পর্কিত হলেও সম্পূর্ণ ভিন্ন দুটি প্রযুক্তি।',
          },
          {
            type: 'callout',
            variant: 'interviewTip',
            title: 'Interview Distinction',
            titleBn: 'ইন্টারভিউয়ের উত্তর',
            text: 'Git is to GitHub what Linux is to Ubuntu, or what an engine is to a car. Git is the engine that does the versioning; GitHub is the platform that wraps around it with cloud storage and social collaboration.',
            textBn: 'গিট ও গিটহাবের সম্পর্ক ইঞ্জিনের সাথে গাড়ির মতো। গিট হলো মূল ইঞ্জিন যা ভার্সন নিয়ন্ত্রণ করে; আর গিটহাব হলো প্ল্যাটফর্ম যা ক্লাউড স্টোরেজ এবং সোশ্যাল কোলাবোরেশন প্রদান করে।',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-git-vs-github',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'Can you use Git without GitHub, and can you use GitHub without Git?',
      questionBn: 'গিটহাব ছাড়া কি গিট ব্যবহার করা যায়, এবং গিট ছাড়া কি গিটহাব ব্যবহার সম্ভব?',
      answer: 'You can definitely use Git without GitHub; Git is an independent command-line tool that performs all versioning locally on your machine. However, GitHub is built entirely around Git repositories, so GitHub fundamentally depends on Git under the hood.',
      answerBn: 'অবশ্যই গিটহাব ছাড়া গিট ব্যবহার করা যায়, কারণ গিট আপনার কম্পিউটারে স্বাধীনভাবে চলে। কিন্তু গিটহাবের মূল ভিত্তিই হলো গিট রিপোজিটরি, তাই গিট ছাড়া গিটহাব অসম্ভব।',
      keyPoints: [
        'Git is local open-source software created by Linus Torvalds in 2005',
        'GitHub is a cloud platform founded in 2008 and acquired by Microsoft in 2018',
        'Alternatives to GitHub include GitLab, Bitbucket, Gitea, and AWS CodeCommit',
      ],
    },
    quiz: {
      id: 'quiz-git-vs-github',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'Which of the following statements is strictly TRUE?',
      questionBn: 'নিচের কোন উক্তিটি সম্পূর্ণরূপে সত্য?',
      options: [
        { id: 'opt-a', text: 'You must have an active internet connection and GitHub account to use Git.', textBn: 'গিট ব্যবহার করতে সর্বদা ইন্টারনেট সংযোগ এবং গিটহাব অ্যাকাউন্ট প্রয়োজন।', isCorrect: false },
        { id: 'opt-b', text: 'Git is the local version control software; GitHub is a cloud hosting platform for Git repositories.', textBn: 'গিট হলো লোকাল ভার্সন কন্ট্রোল সফটওয়্যার; গিটহাব হলো গিট রিপোর ক্লাউড হোস্টিং প্ল্যাটফর্ম।', isCorrect: true },
        { id: 'opt-c', text: 'GitHub was invented by Linus Torvalds as part of Linux.', textBn: 'লিনাস টরভাল্ডস লিনাক্সের অংশ হিসেবে গিটহাব আবিষ্কার করেছিলেন।', isCorrect: false },
        { id: 'opt-d', text: 'Running git commit automatically sends code to GitHub servers.', textBn: 'git commit কমান্ড দিলে স্বয়ংক্রিয়ভাবে কোড গিটহাবের সার্ভারে চলে যায়।', isCorrect: false },
      ],
      explanation: 'Git operates completely locally on your computer. GitHub is an online service that hosts Git repositories for remote backup and team collaboration.',
      explanationBn: 'গিট আপনার কম্পিউটারে সম্পূর্ণ স্বাধীনভাবে চলে। গিটহাব হলো একটি অনলাইন ক্লাউড প্ল্যাটফর্ম যা রিমোট শেয়ারিং ও ব্যাকআপে সাহায্য করে।',
    },
  },
  {
    id: 'git.fundamentals.repository',
    moduleId: 'git-fundamentals',
    slug: 'repository',
    order: 4,
    durationMinutes: 9,
    difficulty: 'beginner',
    title: 'The Repository (.git Directory Internals)',
    titleBn: 'রিপোজিটরি (.git ডিরেক্টরি ইন্টারনালস)',
    summary: 'Demystify what a repository actually is: a collection of your project files paired with the hidden `.git` database tracking history, refs, and configuration.',
    summaryBn: 'রিপোজিটরি কী তা সুস্পষ্টভাবে জানা: আপনার প্রজেক্টের ফাইলসমূহ এবং পেছনের লুকায়িত `.git` ফোল্ডার যা ইতিহাস ও কনফিগারেশন সংরক্ষণ করে।',
    learningObjectives: [
      'Define what makes a standard folder into a Git repository',
      'Inspect the anatomy of the hidden `.git` folder',
      'Understand the role of the object database and reference pointers',
    ],
    learningObjectivesBn: [
      'একটি সাধারণ ফোল্ডার কীভাবে গিট রিপোজিটরিতে রূপ নেয় তা বোঝা',
      'লুকায়িত `.git` ফোল্ডারের ভেতরের গুরুত্বপূর্ণ ফাইলগুলো চেনা',
      'অবজেক্ট ডাটাবেস এবং রেফারেন্স পয়েন্টারের ভূমিকা জানা',
    ],
    keyTakeaways: [
      'A Git repository consists of your Working Tree (visible files) plus the hidden `.git` directory.',
      'If you delete the `.git` directory, your project becomes a normal unversioned folder with all version history permanently erased.',
      'The repository contains objects (`.git/objects/`), branch references (`.git/refs/`), configuration (`.git/config`), and the current pointer (`.git/HEAD`).',
    ],
    sections: [
      {
        id: 'sec-repo-anatomy',
        title: 'Anatomy of the `.git` Directory',
        titleBn: '`.git` ডিরেক্টরির গঠন',
        blocks: [
          {
            type: 'paragraph',
            text: 'When you run `git init`, Git creates a single hidden subfolder called `.git`. This single folder is the entire database of your project’s version history.',
            textBn: 'যখন আপনি `git init` চালান, তখন গিট `.git` নামে একটি লুকায়িত ফোল্ডার তৈরি করে। এই ফোল্ডারটিই মূলত আপনার প্রজেক্টের সম্পূর্ণ ইতিহাস ডাটাবেস।',
          },
          {
            type: 'code',
            language: 'bash',
            filename: 'ls -la .git',
            code: `.git/
├── HEAD             # Points to the branch currently checked out
├── config           # Repository-specific configuration settings
├── description      # Used mainly by GitWeb
├── hooks/           # Client or server-side executable scripts
├── info/            # Global exclusion file
├── objects/         # The Content-Addressable Object Database (blobs, trees, commits, tags)
└── refs/            # Pointers to commit objects: heads/ (local branches) and tags/`,
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-git-repo',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'What happens if you delete the `.git` folder from your project directory?',
      questionBn: 'প্রজেক্ট ডিরেক্টরি থেকে `.git` ফোল্ডারটি মুছে দিলে কী হবে?',
      answer: 'Your visible project files in the working directory remain untouched on your disk, but the entire Git version history, all branches, stashes, tags, and commits are permanently destroyed. The folder becomes an ordinary unversioned directory.',
      answerBn: 'আপনার বর্তমান ফাইলগুলো ডিস্কে থেকে যাবে, কিন্তু সমস্ত ব্রাঞ্চ, পূর্ববর্তী কমিট হিস্ট্রি ও ট্যাগ চিরতরে মুছে যাবে। ফোল্ডারটি সাধারণ নন-গিট ফোল্ডারে পরিণত হবে।',
      keyPoints: [
        'The .git directory IS the repository',
        'Visible files are just a checkout of one specific commit snapshot',
      ],
    },
    quiz: {
      id: 'quiz-git-repo',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'Where does Git store all commit history, object blobs, and branch references?',
      questionBn: 'গিট তার সমস্ত কমিট হিস্ট্রি, অবজেক্ট ব্লব এবং ব্রাঞ্চ রেফারেন্স কোথায় সংরক্ষণ করে?',
      options: [
        { id: 'opt-a', text: 'In a hidden `.git` folder inside the project root directory', textBn: 'প্রজেক্ট রুটের ভেতরে থাকা একটি লুকায়িত `.git` ফোল্ডারে', isCorrect: true },
        { id: 'opt-b', text: 'Directly in the cloud on GitHub servers', textBn: 'সরাসরি গিটহাবের ক্লাউড সার্ভারে', isCorrect: false },
        { id: 'opt-c', text: 'In the computer\'s Windows Registry or macOS Keychain', textBn: 'উইন্ডোজ রেজিস্ট্রি বা ম্যাক কেইচেইনে', isCorrect: false },
        { id: 'opt-d', text: 'In temporary RAM memory that resets when you shut down', textBn: 'অস্থায়ী র‍্যাম মেমোরিতে যা রিবুট করলে মুছে যায়', isCorrect: false },
      ],
      explanation: 'The hidden `.git` folder contains the entire database (objects, refs, HEAD, and config). All version history lives right there on your disk.',
      explanationBn: '`.git` ফোল্ডারটিই মূলত গিটের সম্পূর্ণ ডাটাবেস ধারণ করে। সব অবজেক্ট, হিস্ট্রি ও ব্রাঞ্চ এখানেই সংরক্ষিত থাকে।',
    },
  },
  {
    id: 'git.fundamentals.working-directory',
    moduleId: 'git-fundamentals',
    slug: 'working-directory',
    order: 5,
    durationMinutes: 7,
    difficulty: 'beginner',
    title: 'The Working Directory (Working Tree)',
    titleBn: 'ওয়ার্কিং ডিরেক্টরি (ওয়ার্কিং ট্রি)',
    summary: 'Understand the first stage of Git’s architecture: your actual files on disk that you open, edit, delete, and test in your code editor.',
    summaryBn: 'গিটের আর্কিটেকচারের প্রথম স্তর: আপনার ডিস্কের আসল ফাইলসমূহ যা কোড এডিটরে খুলে আপনি কোড লেখেন ও পরীক্ষা করেন।',
    learningObjectives: [
      'Define the Working Tree as a single checkout from the Git database',
      'Distinguish between Tracked and Untracked files',
      'Explain how Git observes modifications in the working tree',
    ],
    learningObjectivesBn: [
      'ওয়ার্কিং ট্রি যে মূলত একটি নির্দিষ্ট কমিটের এক্সট্র্যাক্ট করা ফাইল সেট তা বোঝা',
      'ট্র্যাকড এবং আনট্র্যাকড ফাইলের পার্থক্য নিরূপণ',
      'গিট কীভাবে ডিস্কের ফাইল পরিবর্তনের ওপর নজর রাখে তা জানা',
    ],
    keyTakeaways: [
      'The Working Directory consists of real files extracted from a commit for you to edit.',
      'Files in the working directory are either Tracked (Git knows about them) or Untracked (new files Git does not follow yet).',
      'Modifications in the working directory are NOT saved in Git history until you stage and commit them.',
    ],
    sections: [
      {
        id: 'sec-working-tree',
        title: 'Your Sandbox for Real Changes',
        titleBn: 'আপনার কাজের স্যান্ডবক্স',
        blocks: [
          {
            type: 'paragraph',
            text: 'The Working Directory (also called the Working Tree) is a single checkout of one version of the project. These files are pulled out of the compressed database in the `.git` directory and placed on disk for you to view, compile, and edit.',
            textBn: 'ওয়ার্কিং ডিরেক্টরি হলো প্রজেক্টের একটি নির্দিষ্ট সংস্করণের চেকআউট। `.git` এর ভেতরের কম্প্রেসড ডাটাবেস থেকে ফাইলগুলোকে বের করে ডিস্কে সাজিয়ে রাখা হয় যাতে আপনি এডিট ও টেস্ট করতে পারেন।',
          },
          {
            type: 'command',
            command: 'git status',
            description: 'Inspect which files in your working directory have been modified or are untracked',
            descriptionBn: 'ওয়ার্কিং ডিরেক্টরিতে কোন ফাইলগুলো পরিবর্তিত বা আনট্র্যাকড তা দেখুন',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-working-directory',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'What is the difference between an untracked file and an unmodified tracked file?',
      questionBn: 'আনট্র্যাকড ফাইল এবং আনমডিফাইড ট্র্যাকড ফাইলের মধ্যে পার্থক্য কী?',
      answer: 'A tracked file is one that was present in the previous commit snapshot or has been added to the staging index; Git monitors it for changes. An untracked file is any file in your working directory that was neither in your last snapshot nor in your staging area.',
      answerBn: 'ট্র্যাকড ফাইল হলো যা আগের কমিট বা স্টেজিং ইনডেক্সে বিদ্যমান, যার পরিবর্তন গিট নজরদারিতে রাখে। আর আনট্র্যাকড ফাইল হলো নতুন ফাইল যা গিট এখনও রেকর্ড করা শুরু করেনি।',
      keyPoints: [
        'Untracked files are ignored by commit operations until staged with `git add`',
        '`.gitignore` allows permanently preventing untracked files from appearing in `git status`',
      ],
    },
    quiz: {
      id: 'quiz-working-directory',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'When you edit a line of code in VS Code, where does that change currently exist?',
      questionBn: 'যখন আপনি ভিএস কোডে একটি লাইন পরিবর্তন করেন, তখন সেই পরিবর্তনটি বর্তমানে কোথায় থাকে?',
      options: [
        { id: 'opt-a', text: 'Only in your Working Directory on your filesystem', textBn: 'শুধুমাত্র আপনার ফাইলসিস্টেমের ওয়ার্কিং ডিরেক্টরিতে', isCorrect: true },
        { id: 'opt-b', text: 'In Git\'s staging index automatically', textBn: 'স্বয়ংক্রিয়ভাবে গিটের স্টেজিং ইনডেক্সে', isCorrect: false },
        { id: 'opt-c', text: 'In the Local Repository commit history', textBn: 'লোকাল রিপোজিটরির কমিট হিস্ট্রিতে', isCorrect: false },
        { id: 'opt-d', text: 'On GitHub servers', textBn: 'গিটহাবের সার্ভারে', isCorrect: false },
      ],
      explanation: 'Until you run `git add`, changes remain solely in your working tree on your physical disk. Git knows they are modified, but hasn\'t saved them.',
      explanationBn: 'যতক্ষণ না আপনি `git add` চালাচ্ছেন, ততক্ষণ পরিবর্তনগুলো শুধু আপনার কম্পিউটারের ডিস্কের ফাইলেই থাকে। গিট তা এখনো সেভ করেনি।',
    },
  },
  {
    id: 'git.fundamentals.staging-area',
    moduleId: 'git-fundamentals',
    slug: 'staging-area',
    order: 6,
    durationMinutes: 9,
    difficulty: 'beginner',
    title: 'The Staging Area (The Index)',
    titleBn: 'স্টেজিং এরিয়া (ইনডেক্স)',
    summary: 'Master Git’s secret superpower: the staging area acts as a drafting table where you curate, organize, and assemble clean atomic commits.',
    summaryBn: 'গিটের অন্যতম শক্তিশালী স্তর: স্টেজিং এরিয়া যা একটি প্রস্তুতি টেবিল হিসেবে কাজ করে যেখানে আপনি পরবর্তী কমিট সাজিয়ে নেন।',
    learningObjectives: [
      'Understand the role of `.git/index` as the staging area',
      'Explain how the staging area allows splitting work into atomic commits',
      'Use `git add` and `git restore --staged` to curate the index',
    ],
    learningObjectivesBn: [
      'স্টেজিং এরিয়া হিসেবে `.git/index` ফাইলের কাজ বোঝা',
      'স্টেজিং এরিয়া কীভাবে পারমাণবিক ও সুসংগঠিত কমিট বানাতে সাহায্য করে তা জানা',
      '`git add` ও `git restore --staged` দিয়ে ইনডেক্স নিয়ন্ত্রণ করা',
    ],
    keyTakeaways: [
      'The Staging Area is technically a binary file named `index` stored inside the `.git` directory.',
      'It acts as the intermediate staging dock between your working tree edits and permanent commit history.',
      'The staging area allows you to stage 1 file out of 10 modified files, creating targeted, atomic commits.',
    ],
    sections: [
      {
        id: 'sec-staging-dock',
        title: 'The Cargo Loading Dock Analogy',
        titleBn: 'জাহাজের কার্গো ডকিং উপমা',
        blocks: [
          {
            type: 'paragraph',
            text: 'Think of your Working Directory as your factory floor where you manufacture goods. The Staging Area is the cargo shipping container on the dock. You don\'t ship goods the second you make them; you carefully place selected items into the container. When the container is packed with related items, `git commit` seals the container and loads it onto the ship.',
            textBn: 'ওয়ার্কিং ডিরেক্টরিকে একটি ফ্যাক্টরি এবং স্টেজিং এরিয়াকে একটি শিপিং কন্টেইনার ভাবুন। আপনি প্রতিটি তৈরি করা জিনিস সাথে সাথে জাহাজে পাঠান না; বরং কন্টেইনারে নির্দিষ্ট মালপত্র গুছিয়ে তোলেন। গোছানো শেষ হলে `git commit` দিয়ে কন্টেইনার সিল করে জাহাজে তুলে দেন।',
          },
          {
            type: 'command',
            command: 'git add src/auth/login.ts',
            description: 'Stage only login.ts while leaving other experimental edits unstaged',
            descriptionBn: 'অন্যান্য ফাইল অক্ষত রেখে শুধু login.ts ফাইলটি স্টেজ করুন',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-staging-area',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'Why does Git have a Staging Area, whereas systems like SVN or Mercurial commit directly from the working directory?',
      questionBn: 'SVN এর মতো সিস্টেম সরাসরি কমিট করলেও গিটে স্টেজিং এরিয়া থাকার কারণ কী?',
      answer: 'The Staging Area provides fine-grained control over what goes into each commit. It allows developers to craft atomic commits by staging individual files or even individual lines of code (via `git add -p`), decoupling the editing workflow from version recording.',
      answerBn: 'স্টেজিং এরিয়া কমিটের ওপর পূর্ণ নিয়ন্ত্রণ দেয়। এর মাধ্যমে ডেভেলপাররা ২০টি ফাইল এডিট করলেও একটি নির্দিষ্ট ফিচার সম্পর্কিত ফাইলগুলোকে বেছে বেছে ছোট ছোট নিখুঁত কমিটে রূপ দিতে পারেন।',
      keyPoints: [
        'Decouples editing from committing',
        'Enables atomic commits (each commit does one clear thing)',
        'Supports patch mode (`git add -p`) to stage partial file changes',
      ],
    },
    quiz: {
      id: 'quiz-staging-area',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'Which file on disk actually stores the state of the Staging Area?',
      questionBn: 'ডিস্কের কোন ফাইলটি মূলত স্টেজিং এরিয়ার অবস্থা ধারণ করে?',
      options: [
        { id: 'opt-a', text: '`.git/index`', textBn: '`.git/index`', isCorrect: true },
        { id: 'opt-b', text: '`staging.json`', textBn: '`staging.json`', isCorrect: false },
        { id: 'opt-c', text: '`.gitignore`', textBn: '`.gitignore`', isCorrect: false },
        { id: 'opt-d', text: '`package.json`', textBn: '`package.json`', isCorrect: false },
      ],
      explanation: 'The staging area is stored in a binary file located at `.git/index`. That is why the staging area is often interchangeably called the "Index".',
      explanationBn: 'স্টেজিং এরিয়া মূলত `.git/index` বাইনারি ফাইলে সংরক্ষিত থাকে। এজন্য এটিকে প্রায়শই "Index" বলা হয়।',
    },
  },
  {
    id: 'git.fundamentals.local-repository',
    moduleId: 'git-fundamentals',
    slug: 'local-repository',
    order: 7,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'The Local Repository',
    titleBn: 'লোকাল রিপোজিটরি',
    summary: 'Explore the heart of Git: your local repository where permanent commit objects, branch references, and the project graph reside completely on your machine.',
    summaryBn: 'গিটের হৃদপিণ্ড: লোকাল রিপোজিটরি যেখানে স্থায়ী কমিট অবজেক্ট, ব্রাঞ্চ রেফারেন্স ও প্রজেক্ট গ্রাফ সম্পূর্ণভাবে আপনার কম্পিউটারে অবস্থান করে।',
    learningObjectives: [
      'Understand that commits in the local repository are permanent and cryptographically secured',
      'Explain how Git tracks branches locally before pushing to any server',
      'Realize that a developer has full version control power even without network access',
    ],
    learningObjectivesBn: [
      'লোকাল রিপোজিটরির কমিট যে স্থায়ী ও ক্রিপ্টোগ্রাফিক্যালি সুরক্ষিত তা জানা',
      'সার্ভারে পুশ করার আগেই লোকাল ব্রাঞ্চগুলো কীভাবে কাজ করে তা বোঝা',
      'নেটওয়ার্ক ছাড়াই লোকালি সম্পূর্ণ ভার্সন কন্ট্রোল ব্যবহারের ক্ষমতা উপলব্ধি করা',
    ],
    keyTakeaways: [
      'The Local Repository is stored in the `.git/objects/` and `.git/refs/` directories.',
      'When you run `git commit`, your work is safely recorded locally without touching the network.',
      'You can create dozens of branches, rebase, merge, and inspect history without ever needing a remote server.',
    ],
    sections: [
      {
        id: 'sec-local-power',
        title: 'Complete Autonomy on Your Machine',
        titleBn: 'আপনার মেশিনে সম্পূর্ণ স্বায়ত্তশাসন',
        blocks: [
          {
            type: 'paragraph',
            text: 'In Git, "committing" and "sharing" are two separate steps. Running `git commit` stores your changes into your Local Repository. It does NOT send anything to GitHub. You can make 20 commits locally throughout the day and push them all at once when ready.',
            textBn: 'গিটে "কমিট করা" এবং "শেয়ার করা" দুটি আলাদা ধাপ। `git commit` চালালে কোড শুধু আপনার লোকাল রিপোজিটরিতে সেভ হয়, গিটহাবে যায় না। আপনি সারাদিনে ২০টি কমিট করে দিনশেষে একবারে পুশ করতে পারেন।',
          },
          {
            type: 'command',
            command: 'git commit -m "feat: complete user profile widget"',
            description: 'Records the staged snapshot permanently into your Local Repository',
            descriptionBn: 'স্টেজিং এরিয়ার স্ন্যাপশট লোকাল রিপোজিটরিতে স্থায়ীভাবে রেকর্ড করুন',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-local-repo',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'If you commit changes with `git commit`, are your changes visible to teammates on GitHub?',
      questionBn: '`git commit` দিলে সহকর্মীরা কি গিটহাবে সেই পরিবর্তনগুলো দেখতে পাবে?',
      answer: 'No. `git commit` records changes strictly in your local repository on your machine. To make those commits visible to teammates, you must explicitly run `git push` to transfer them to a shared remote repository.',
      answerBn: 'না। `git commit` শুধুমাত্র আপনার কম্পিউটারের লোকাল রিপোতে সেভ করে। সহকর্মীদের দেখাতে হলে আপনাকে অবশ্যই `git push` দিয়ে রিমোট সার্ভারে পাঠাতে হবে।',
      keyPoints: [
        'Commit = Save snapshot to local repository',
        'Push = Upload local commits to remote repository',
      ],
    },
    quiz: {
      id: 'quiz-local-repo',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'What does running `git commit` actually do?',
      questionBn: '`git commit` কমান্ড মূলত কী করে?',
      options: [
        { id: 'opt-a', text: 'Uploads your files to GitHub immediately', textBn: 'তাৎক্ষণিকভাবে আপনার ফাইল গিটহাবে আপলোড করে', isCorrect: false },
        { id: 'opt-b', text: 'Permanently records the staged changes as a new snapshot in your local repository', textBn: 'স্টেজিং পরিবর্তনগুলোকে লোকাল রিপোজিটরিতে স্থায়ী স্ন্যাপশট হিসেবে সেভ করে', isCorrect: true },
        { id: 'opt-c', text: 'Deletes your working tree files', textBn: 'ওয়ার্কিং ডিরেক্টরির সব ফাইল মুছে ফেলে', isCorrect: false },
        { id: 'opt-d', text: 'Installs new npm packages', textBn: 'নতুন প্যাকেজ ইনস্টল করে', isCorrect: false },
      ],
      explanation: '`git commit` packages the staged index into a commit snapshot stored in the local `.git` repository. It does not touch the network.',
      explanationBn: '`git commit` স্টেজিং এরিয়াকে লোকাল `.git` রিপোতে স্ন্যাপশট হিসেবে সেভ করে। এটি কোনো নেটওয়ার্ক ব্যবহার করে না।',
    },
  },
  {
    id: 'git.fundamentals.remote-repository',
    moduleId: 'git-fundamentals',
    slug: 'remote-repository',
    order: 8,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'The Remote Repository',
    titleBn: 'রিমোট রিপোজিটরি',
    summary: 'Understand the fourth area of Git collaboration: remote versions of your project hosted on the internet or network, commonly referred to as `origin`.',
    summaryBn: 'গিটের ৪র্থ স্তর: ইন্টারনেটে সংরক্ষিত প্রজেক্টের রিমোট কপি, যা সাধারণত `origin` নামে পরিচিত।',
    learningObjectives: [
      'Define a Remote Repository and the default `origin` alias',
      'Understand Remote-Tracking Branches (e.g. `origin/main`)',
      'Explain how teams synchronize work using `fetch`, `pull`, and `push`',
    ],
    learningObjectivesBn: [
      'রিমোট রিপোজিটরি এবং ডিফল্ট `origin` নামের ভূমিকা বোঝা',
      'রিমোট-ট্র্যাকিং ব্রাঞ্চ (যেমন `origin/main`) কীভাবে কাজ করে তা জানা',
      'টিম কীভাবে `fetch`, `pull` ও `push` দিয়ে কোড শেয়ার করে তা উপলব্ধি করা',
    ],
    keyTakeaways: [
      'A Remote Repository is just a Git repository hosted on a shared server (e.g. GitHub, GitLab).',
      'Git tracks remote branches via local cached pointers like `refs/remotes/origin/main`.',
      'Commands like `git fetch`, `git pull`, and `git push` bridge your local repository and remote repositories.',
    ],
    sections: [
      {
        id: 'sec-remote-role',
        title: 'The Collaboration Hub',
        titleBn: 'টিম কোলাবোরেশনের কেন্দ্রবিন্দু',
        blocks: [
          {
            type: 'paragraph',
            text: 'A Remote Repository is typically a "bare" repository (a repository without a working directory) hosted on a central server. Because everyone pushes and pulls from this server, it serves as the authoritative sync hub for the entire engineering team.',
            textBn: 'রিমোট রিপোজিটরি সাধারণত একটি "বেয়ার" (bare) রিপোজিটরি যা কোনো সেন্ট্রাল সার্ভারে হোস্ট করা থাকে। প্রত্যেকে এখান থেকেই কোড পুশ ও পুল করে বলে এটি দলের প্রধান মিলনস্থল হিসেবে কাজ করে।',
          },
          {
            type: 'command',
            command: 'git remote -v',
            description: 'Inspect the configured remote URLs for fetching and pushing',
            descriptionBn: 'পুশ ও ফেচ করার জন্য কনফিগার করা রিমোট লিঙ্কগুলো দেখুন',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-remote-repo',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'What is a remote-tracking branch in Git (e.g., origin/main)?',
      questionBn: 'গিটে রিমোট-ট্র্যাকিং ব্রাঞ্চ (যেমন origin/main) বলতে কী বোঝায়?',
      answer: 'A remote-tracking branch is a local read-only bookmark that records where the remote branch was the last time you communicated with the server (via `fetch`, `pull`, or `push`). You cannot move it directly; Git updates it automatically during network sync.',
      answerBn: 'রিমোট-ট্র্যাকিং ব্রাঞ্চ হলো একটি লোকাল রিড-অনলি পয়েন্টার যা শেষবার সার্ভারের সাথে কথা বলার সময় রিমোট ব্রাঞ্চটি কোন কমিটে ছিল তার রেকর্ড রাখে। গিট নেটওয়ার্ক সিঙ্কের সময় এটি আপডেট করে।',
      keyPoints: [
        'Stored locally under `.git/refs/remotes/origin/`',
        'Updated only when network commands (`fetch`, `pull`, `push`) run',
      ],
    },
    quiz: {
      id: 'quiz-remote-repo',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'Which command uploads your local commits to the remote repository?',
      questionBn: 'কোন কমান্ডটি আপনার লোকাল কমিটগুলোকে রিমোট রিপোজিটরিতে আপলোড করে?',
      options: [
        { id: 'opt-a', text: '`git push`', textBn: '`git push`', isCorrect: true },
        { id: 'opt-b', text: '`git fetch`', textBn: '`git fetch`', isCorrect: false },
        { id: 'opt-c', text: '`git add`', textBn: '`git add`', isCorrect: false },
        { id: 'opt-d', text: '`git commit`', textBn: '`git commit`', isCorrect: false },
      ],
      explanation: '`git push` transfers commits from your local branch to the remote repository branch.',
      explanationBn: '`git push` কমান্ড লোকাল ব্রাঞ্চের নতুন কমিটগুলোকে রিমোট সার্ভারে ট্রান্সফার করে।',
    },
  },
  {
    id: 'git.fundamentals.commit',
    moduleId: 'git-fundamentals',
    slug: 'commit',
    order: 9,
    durationMinutes: 10,
    difficulty: 'beginner',
    title: 'What is a Commit? The Cryptographic Building Block',
    titleBn: 'কমিট কী? ক্রিপ্টোগ্রাফিক মূল একক',
    summary: 'Look under the hood of a Git commit: SHA-1/SHA-256 hashes, author metadata, tree references, parent pointers, and immutable snapshots.',
    summaryBn: 'গিট কমিটের অভ্যন্তরীণ গঠন: ক্রিপ্টোগ্রাফিক হ্যাশ, রচয়িতার তথ্য, ট্রি রেফারেন্স, প্যারেন্ট পয়েন্টার এবং অপরিবর্তনীয় স্ন্যাপশট।',
    learningObjectives: [
      'Dissect the anatomy of a Git commit object',
      'Understand why commits are mathematically immutable via SHA hashing',
      'Explain how parent pointers create Git\'s history graph (DAG)',
    ],
    learningObjectivesBn: [
      'গিট কমিট অবজেক্টের অভ্যন্তরীণ উপাদান বিশ্লেষণ করা',
      'SHA হ্যাশিংয়ের কারণে কেন কমিট অবজেক্ট অপরিবর্তনশীল তা জানা',
      'প্যারেন্ট পয়েন্টার কীভাবে গিটের হিস্ট্রি গ্রাফ (DAG) তৈরি করে তা বোঝা',
    ],
    keyTakeaways: [
      'A commit is an immutable snapshot object containing: a tree pointer, parent commit hash(es), author info, timestamp, and a commit message.',
      'Every commit is uniquely identified by a 40-character SHA-1 (or 64-character SHA-256) hash.',
      'Because the hash incorporates the parent hash, you cannot alter a past commit without changing the hashes of all subsequent commits.',
    ],
    sections: [
      {
        id: 'sec-commit-anatomy',
        title: 'Anatomy of a Raw Commit Object',
        titleBn: 'একটি র কমিট অবজেক্টের অভ্যন্তরীণ রূপ',
        blocks: [
          {
            type: 'paragraph',
            text: 'If you inspect a commit object directly using `git cat-file -p <hash>`, you will see plain text that looks like this:',
            textBn: 'যদি আপনি `git cat-file -p <hash>` দিয়ে সরাসরি একটি কমিট অবজেক্ট দেখেন, তবে তার চেহারা দেখতে পাবেন এমন:',
          },
          {
            type: 'code',
            language: 'text',
            filename: 'raw commit object',
            code: `tree 7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b
parent 1f2e3d4c5b6a7f8e9d0c1b2a3f4e5d6c7b8a9f0e
author Linus Torvalds <torvalds@linux.org> 1113034234 -0700
committer Linus Torvalds <torvalds@linux.org> 1113034234 -0700

feat: implement initial git tree parser`,
          },
          {
            type: 'paragraph',
            text: 'Notice that the commit contains only 4 essential things: 1. The root tree hash (snapshot of files). 2. The parent commit hash. 3. Author and committer metadata with timestamps. 4. The commit message.',
            textBn: 'লক্ষ্য করুন একটি কমিটে মাত্র ৪টি মূল জিনিস থাকে: ১. রুট ট্রি হ্যাশ (ফাইলের স্ন্যাপশট)। ২. প্যারেন্ট কমিটের হ্যাশ। ৩. রচয়িতার নাম, ইমেইল ও সময়। ৪. কমিট মেসেজ।',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-commit-immutable',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'intermediate',
      question: 'Why is it said that commits in Git are immutable?',
      questionBn: 'কেন বলা হয় যে গিটের কমিটগুলো অপরিবর্তনীয় (immutable)?',
      answer: 'A commit’s unique ID is the cryptographic SHA hash calculated from its exact contents: the tree hash, author, timestamp, commit message, and crucially, its parent commit’s hash. Changing even one character or one second of time produces a completely different hash, creating a brand new commit rather than modifying the old one.',
      answerBn: 'একটি কমিটের আইডি হলো তার কনটেন্ট, সময়, মেসেজ এবং প্যারেন্টের হ্যাশের ক্রিপ্টোগ্রাফিক হ্যাশ। একটি অক্ষর বা সেকেন্ডও পরিবর্তন করলে হ্যাশ সম্পূর্ণ বদলে যায়, ফলে পুরনো কমিট পরিবর্তনের বদলে সম্পূর্ণ নতুন কমিট তৈরি হয়।',
      keyPoints: [
        'Commits are content-addressed by cryptographic hashes',
        'Altering a commit generates a new object with a new hash',
        'Guarantees total cryptographic audit integrity for code',
      ],
    },
    quiz: {
      id: 'quiz-commit',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'What links a commit to the previous version of the project?',
      questionBn: 'কোন জিনিসটি একটি কমিটকে প্রজেক্টের পূর্ববর্তী সংস্করণের সাথে যুক্ত করে?',
      options: [
        { id: 'opt-a', text: 'The parent commit hash stored inside the commit object', textBn: 'কমিট অবজেক্টের ভেতরে থাকা প্যারেন্ট কমিট হ্যাশ', isCorrect: true },
        { id: 'opt-b', text: 'A line number recorded in package.json', textBn: 'package.json ফাইলে থাকা লাইন নম্বর', isCorrect: false },
        { id: 'opt-c', text: 'A database table in SQL', textBn: 'SQL ডাটাবেসের একটি টেবিল', isCorrect: false },
        { id: 'opt-d', text: 'An IP address pointing to GitHub', textBn: 'গিটহাবের একটি আইপি অ্যাড্রেস', isCorrect: false },
      ],
      explanation: 'Every commit contains the hash of its parent commit(s). This chain of parent pointers forms the historical timeline graph of your project.',
      explanationBn: 'প্রতিটি কমিট তার পূর্ববর্তী প্যারেন্ট কমিটের হ্যাশ সংরক্ষণ করে। এই প্যারেন্ট পয়েন্টারের ধারাবাহিকতাই প্রজেক্টের ইতিহাস গ্রাফ তৈরি করে।',
    },
  },
  {
    id: 'git.fundamentals.branch',
    moduleId: 'git-fundamentals',
    slug: 'branch',
    order: 10,
    durationMinutes: 9,
    difficulty: 'beginner',
    title: 'What is a Branch? Lightweight Movable Pointers',
    titleBn: 'ব্রাঞ্চ কী? লাইটওয়েট মুভেবল পয়েন্টার',
    summary: 'Discover the brilliance of Git branching: a branch is not a directory copy, but a simple 41-byte text file storing a commit hash pointer that automatically advances with each new commit.',
    summaryBn: 'গিট ব্রাঞ্চিংয়ের বিস্ময়কর আর্কিটেকচার: ব্রাঞ্চ কোনো ফোল্ডার কপি নয়, বরং একটি ৪১ বাইটের টেক্সট ফাইল যা নতুন কমিটের সাথে সাথে স্বয়ংক্রিয়ভাবে এগিয়ে যায়।',
    learningObjectives: [
      'Understand that a Git branch is simply a movable pointer to a commit',
      'Explain how branches allow parallel, risk-free feature development',
      'Contrast Git’s pointer branching with traditional file-copy branching',
    ],
    learningObjectivesBn: [
      'গিট ব্রাঞ্চ যে মূলত একটি কমিটের দিকে নির্দেশিত চলমান পয়েন্টার তা জানা',
      'ব্রাঞ্চ কীভাবে সমান্তরাল ও ঝুঁকিহীন ফিচার ডেভেলপমেন্ট নিশ্চিত করে তা বোঝা',
      'ফাইল কপি করার সাপেক্ষে গিটের পয়েন্টার ব্রাঞ্চিংয়ের শ্রেষ্ঠত্ব উপলব্ধি করা',
    ],
    keyTakeaways: [
      'A branch in Git is simply a lightweight movable pointer to one of your commits.',
      'The default branch in most modern Git repositories is named `main` (historically `master`).',
      'When you make a commit while on a branch, the branch pointer automatically moves forward to point to the new commit.',
    ],
    sections: [
      {
        id: 'sec-branch-pointer',
        title: 'A 41-Byte Text File',
        titleBn: 'মাত্র ৪১ বাইটের একটি টেক্সট ফাইল',
        blocks: [
          {
            type: 'paragraph',
            text: 'In many version control systems, creating a branch involves copying all project files into another directory. In Git, a branch is literally a single file inside `.git/refs/heads/` that contains a 40-character commit hash followed by a newline.',
            textBn: 'অনেক পুরনো সিস্টেমে ব্রাঞ্চ তৈরি মানে পুরো প্রজেক্টের ফাইল অন্য ফোল্ডারে কপি করা। আর গিটে একটি ব্রাঞ্চ হলো `.git/refs/heads/` এর ভেতরের একটি সাধারণ টেক্সট ফাইল যা শুধু একটি ৪০ অক্ষরের কমিট হ্যাশ ধারণ করে।',
          },
          {
            type: 'command',
            command: 'git switch -c feature/payments',
            description: 'Create and switch to a new branch called feature/payments in one command',
            descriptionBn: 'এক কমান্ডে feature/payments নামে নতুন ব্রাঞ্চ বানিয়ে সেখানে সুইচ করুন',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-branch-mechanics',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'What happens physically inside the `.git` directory when you create a new branch?',
      questionBn: 'নতুন ব্রাঞ্চ তৈরি করলে `.git` ফোল্ডারের ভেতরে ফিজিক্যালি কী ঘটে?',
      answer: 'Git writes a small 41-byte text file named after your branch into `.git/refs/heads/<branchname>`. This file contains the exact 40-character SHA hash of the commit where you branched from. No code or files are copied.',
      answerBn: 'গিট `.git/refs/heads/` ফোল্ডারে ব্রাঞ্চের নামে ৪১ বাইটের একটি সাধারণ টেক্সট ফাইল লেখে, যার ভেতরে বর্তমান কমিটের ৪০ অক্ষরের হ্যাশ থাকে। কোনো কোড বা ফাইল কপি হয় না।',
      keyPoints: [
        'Instantaneous creation and deletion (O(1) complexity)',
        'Takes virtually zero disk space',
      ],
    },
    quiz: {
      id: 'quiz-branch',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'In Git, what is a branch fundamentally under the hood?',
      questionBn: 'অভ্যন্তরীণভাবে গিটের একটি ব্রাঞ্চ মূলত কী?',
      options: [
        { id: 'opt-a', text: 'A completely separate copy of all files in a new directory', textBn: 'নতুন ডিরেক্টরিতে প্রজেক্টের সমস্ত ফাইলের সম্পূর্ণ পৃথক কপি', isCorrect: false },
        { id: 'opt-b', text: 'A lightweight movable pointer to a specific commit', textBn: 'একটি নির্দিষ্ট কমিটকে নির্দেশ করা লাইটওয়েট চলমান পয়েন্টার', isCorrect: true },
        { id: 'opt-c', text: 'A special server on GitHub', textBn: 'গিটহাবের একটি বিশেষ সার্ভার', isCorrect: false },
        { id: 'opt-d', text: 'A locked database transaction', textBn: 'একটি লক করা ডাটাবেস ট্রানজ্যাকশন', isCorrect: false },
      ],
      explanation: 'A branch is simply a pointer pointing to a commit hash. When you make a new commit, the pointer moves forward to the new commit.',
      explanationBn: 'ব্রাঞ্চ হলো সাধারণ একটি পয়েন্টার যা একটি কমিট হ্যাশকে পয়েন্ট করে। নতুন কমিট করলে পয়েন্টারটি স্বয়ংক্রিয়ভাবে নতুন কমিটে চলে যায়।',
    },
  },
  {
    id: 'git.fundamentals.head',
    moduleId: 'git-fundamentals',
    slug: 'head',
    order: 11,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'Understanding HEAD: Where You Are in Git',
    titleBn: 'HEAD কী? আপনি গিটের কোথায় আছেন তা জানা',
    summary: 'Demystify HEAD: the special pointer that tells Git which branch or commit snapshot your working directory currently represents.',
    summaryBn: 'HEAD এর রহস্য উন্মোচন: বিশেষ পয়েন্টার যা গিটকে বলে দেয় আপনার ওয়ার্কিং ডিরেক্টরি বর্তমানে কোন ব্রাঞ্চ বা কমিটে অবস্থান করছে।',
    learningObjectives: [
      'Explain the purpose of the `.git/HEAD` file',
      'Differentiate between attached HEAD (pointing to a branch) and detached HEAD (pointing to a raw commit)',
      'Understand how HEAD determines where new commits will attach',
    ],
    learningObjectivesBn: [
      '`.git/HEAD` ফাইলের মূল উদ্দেশ্য বোঝা',
      'Attached HEAD এবং Detached HEAD এর পার্থক্য পরিষ্কার করা',
      'HEAD কীভাবে নির্ধারণ করে যে নতুন কমিটটি কার সাথে যুক্ত হবে তা জানা',
    ],
    keyTakeaways: [
      'HEAD is a pointer that refers to the currently checked-out branch or commit.',
      'Normally, HEAD is an indirect pointer: `HEAD -> branch -> commit`.',
      'A "Detached HEAD" happens when HEAD points directly to a commit hash instead of a branch name.',
    ],
    sections: [
      {
        id: 'sec-head-pointer',
        title: 'You Are Here',
        titleBn: 'আপনি বর্তমানে এখানে আছেন',
        blocks: [
          {
            type: 'paragraph',
            text: 'Think of HEAD as a "You Are Here" pin on a map. It tells Git which branch you are actively working on. When you run `git switch main`, HEAD points to `main`. When you make a commit, Git attaches the new commit to whatever branch HEAD is currently pointing to.',
            textBn: 'ম্যাপের "You Are Here" পিনের মতো HEAD কাজ করে। এটি গিটকে জানায় আপনি বর্তমানে কোন ব্রাঞ্চে কাজ করছেন। `git switch main` দিলে HEAD নির্দেশ করে `main` কে। নতুন কমিট করলে তা HEAD এর ব্রাঞ্চেই যুক্ত হয়।',
          },
          {
            type: 'code',
            language: 'bash',
            filename: 'cat .git/HEAD',
            code: `ref: refs/heads/main`,
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-head-detached',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'intermediate',
      question: 'What is a "Detached HEAD" state and how do you get out of it safely?',
      questionBn: 'গিটে "Detached HEAD" অবস্থা কী এবং কীভাবে নিরাপদে এখান থেকে বের হওয়া যায়?',
      answer: 'Detached HEAD means the HEAD file points directly to a commit hash rather than a named branch. Any commits created here are not associated with a branch and can be garbage collected. To save changes made in detached HEAD, run `git switch -c <new-branch-name>` to attach a brand new branch pointer to them.',
      answerBn: 'Detached HEAD অবস্থায় HEAD কোনো ব্রাঞ্চ নামের বদলে সরাসরি একটি কমিট হ্যাশকে নির্দেশ করে। এই অবস্থায় করা পরিবর্তন সেভ করতে `git switch -c <new-branch-name>` দিয়ে নতুন ব্রাঞ্চ বানিয়ে নিলেই নিরাপদ থাকা যায়।',
      keyPoints: [
        'Occurs when you checkout a specific commit hash or remote tag directly',
        'Easily resolved by creating a new branch with `git switch -c <name>`',
      ],
    },
    quiz: {
      id: 'quiz-head',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'What does the `.git/HEAD` file usually contain in a normal Git repository?',
      questionBn: 'স্বাভাবিক অবস্থায় `.git/HEAD` ফাইলটির ভেতরে কী থাকে?',
      options: [
        { id: 'opt-a', text: 'A reference pointing to the currently checked-out branch (e.g. `ref: refs/heads/main`)', textBn: 'বর্তমানে সক্রিয় ব্রাঞ্চের দিকে নির্দেশকারী রেফারেন্স (যেমন `ref: refs/heads/main`)', isCorrect: true },
        { id: 'opt-b', text: 'Your GitHub account password', textBn: 'আপনার গিটহাব অ্যাকাউন্টের পাসওয়ার্ড', isCorrect: false },
        { id: 'opt-c', text: 'A list of all deleted files', textBn: 'মুছে ফেলা সমস্ত ফাইলের তালিকা', isCorrect: false },
        { id: 'opt-d', text: 'The URL of your internet router', textBn: 'আপনার ইন্টারনেট রাউটারের আইপি', isCorrect: false },
      ],
      explanation: 'HEAD points to the currently active branch reference. It acts as the anchor for where your next commit will be attached.',
      explanationBn: 'HEAD বর্তমান সক্রিয় ব্রাঞ্চ রেফারেন্সকে নির্দেশ করে। এটি ঠিক করে দেয় পরবর্তী কমিটটি কোথায় যুক্ত হবে।',
    },
  },
  {
    id: 'git.fundamentals.three-areas',
    moduleId: 'git-fundamentals',
    slug: 'three-areas',
    order: 12,
    durationMinutes: 10,
    difficulty: 'beginner',
    title: 'Git\'s Three Main Areas: The Unified Mental Model',
    titleBn: 'গিটের ৩টি মূল স্তর: পূর্ণাঙ্গ মানসিক নকশা (Mental Model)',
    summary: 'Bring the entire architecture together: Working Directory, Staging Area, and Git Directory (.git), plus Remote Sync. The foundational mental model every engineer must master.',
    summaryBn: 'সম্পূর্ণ আর্কিটেকচারকে একত্রিত করা: ওয়ার্কিং ডিরেক্টরি, স্টেজিং এরিয়া, লোকাল রিপোজিটরি এবং রিমোট সিঙ্ক। প্রতিটি ইঞ্জিনিয়ারের জন্য আবশ্যকীয় জ্ঞান।',
    learningObjectives: [
      'Master the lifecycle of a file across Git\'s 3 local areas plus the remote repository',
      'Trace file state transitions using `git add`, `git commit`, and `git push`',
      'Understand how to safely unstage and restore files across these layers',
    ],
    learningObjectivesBn: [
      'গিটের ৩টি স্তর ও রিমোটের মধ্য দিয়ে ফাইলের পূর্ণ জীবনচক্র আয়ত্ত করা',
      '`git add`, `git commit` ও `git push` এর মাধ্যমে ফাইলের ট্রানজিশন বোঝা',
      'এই স্তরগুলোর মধ্য দিয়ে ফাইল আনস্টেজ ও রিস্টোর করার পদ্ধতি জানা',
    ],
    keyTakeaways: [
      'Working Directory: Where you modify files on disk.',
      'Staging Area: Where you organize and curate files for the next snapshot.',
      'Local Repository: Where permanent cryptographic commit snapshots reside in `.git`.',
      'Remote Repository: Where team members synchronize and share committed snapshots.',
    ],
    sections: [
      {
        id: 'sec-unified-mental-model',
        title: 'The Unified Progression: Edit → Stage → Commit → Push',
        titleBn: 'ধারাবাহিক রূপান্তর: এডিট → স্টেজ → কমিট → পুশ',
        blocks: [
          {
            type: 'paragraph',
            text: 'Every single Git workflow in professional software engineering revolves around moving file snapshots through these stages. Once this mental model clicks, Git stops feeling like magic and starts feeling like an intuitive, predictable set of gears.',
            textBn: 'প্রফেশনাল সফটওয়্যার ইঞ্জিনিয়ারিংয়ের প্রতিটি গিট ওয়ার্কফ্লো এই স্তরগুলোর ওপর ভিত্তি করে পরিচালিত হয়। এই মানসিক নকশাটি পরিষ্কার হলে গিট আর রহস্যময় লাগে না, বরং অত্যন্ত যৌক্তিক ও অনুমানযোগ্য মনে হয়।',
          },
          {
            type: 'visualizer',
            initialState: 'working',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-three-areas',
      subjectId: 'git',
      category: 'Fundamentals',
      difficulty: 'beginner',
      question: 'Walk me through the three main states a file can reside in within Git.',
      questionBn: 'গিটের ভেতরে একটি ফাইল কোন ৩টি মূল অবস্থায় থাকতে পারে তা বিস্তারিত বলুন।',
      answer: '1. Modified (Working Directory): You changed the file in your editor, but have not committed it. 2. Staged (Index): You marked a modified file in its current version to go into the next commit snapshot. 3. Committed (Local Repository): The data is safely and permanently stored in your local Git object database.',
      answerBn: '১. মডিফাইড (Working Directory): ফাইলে পরিবর্তন হয়েছে কিন্তু গিট ডাটাবেসে সেভ হয়নি। ২. স্টেজড (Staging Area): ফাইলটি পরবর্তী কমিটের জন্য প্রস্তুত করা হয়েছে। ৩. কমিটেড (Repository): পরিবর্তনটি লোকাল গিট ডাটাবেসে স্থায়ীভাবে সংরক্ষিত হয়েছে।',
      keyPoints: [
        'Working Tree -> Staging Area -> Git Repository',
        'Transitions triggered by `git add` and `git commit`',
      ],
    },
    quiz: {
      id: 'quiz-three-areas',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'Which sequence correctly represents the flow of saving code from your editor to GitHub?',
      questionBn: 'এডিটর থেকে গিটহাবে কোড সেভ করার সঠিক ক্রম কোনটি?',
      options: [
        { id: 'opt-a', text: 'Working Directory → Staging Area → Local Repository → Remote Repository', textBn: 'Working Directory → Staging Area → Local Repository → Remote Repository', isCorrect: true },
        { id: 'opt-b', text: 'Local Repository → Working Directory → Staging Area → GitHub', textBn: 'Local Repository → Working Directory → Staging Area → GitHub', isCorrect: false },
        { id: 'opt-c', text: 'Working Directory → GitHub → Staging Area', textBn: 'Working Directory → GitHub → Staging Area', isCorrect: false },
        { id: 'opt-d', text: 'Staging Area → Working Directory → Local Repository', textBn: 'Staging Area → Working Directory → Local Repository', isCorrect: false },
      ],
      explanation: 'You edit in the Working Directory, stage with `git add`, record locally with `git commit`, and sync remotely with `git push`.',
      explanationBn: 'প্রথমে ওয়ার্কিং ডিরেক্টরিতে এডিট, `git add` দিয়ে স্টেজ, `git commit` দিয়ে লোকাল সেভ, এবং শেষে `git push` দিয়ে রিমোট আপলোড।',
    },
  },
];
