import { CurriculumLesson } from '@/types/content';

/**
 * Module 1 — Git's Mental Model (git-internals-mental-model)
 * Working Tree → Index → Repository, snapshots, references, HEAD.
 */
export const INTERNALS_MENTAL_MODEL_LESSONS: CurriculumLesson[] = [
  {
    id: 'git.internals.how-git-thinks',
    moduleId: 'git-internals-mental-model',
    slug: 'how-git-thinks',
    order: 1,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'How Git Thinks',
    titleBn: 'গিট কীভাবে ভাবে',
    summary: 'Git is a content-addressed object database plus references and a working area — not folders full of file versions.',
    summaryBn: 'গিট হলো কন্টেন্ট-অ্যাড্রেসড অবজেক্ট ডাটাবেস সাথে রেফারেন্স ও কাজের জায়গা — ফাইলের সংস্করণে ভরা ফোল্ডার নয়।',
    learningObjectives: [
      'Describe Git as an object database plus references',
      'Name the three areas Git moves content between',
      'Explain why the mental model predicts command behavior',
    ],
    learningObjectivesBn: [
      'অবজেক্ট ডাটাবেস সাথে রেফারেন্স হিসেবে গিটের বর্ণনা দেওয়া',
      'গিট যে তিনটি ক্ষেত্রের মধ্যে কন্টেন্ট স্থানান্তর করে তার নাম বলা',
      'কেন মেন্টাল মডেল কমান্ডের আচরণ অনুমান করতে সাহায্য করে তা ব্যাখ্যা করা',
    ],
    keyTakeaways: [
      'Git stores content-addressed objects (blobs, trees, commits, tags) in .git/objects.',
      'References (branches, tags, HEAD) are lightweight pointers to commits.',
      'Working Tree → Index → Repository is the core content pipeline.',
    ],
    sections: [
      {
        id: 'sec-model',
        title: 'Database Plus Pointers',
        titleBn: 'ডাটাবেস সাথে পয়েন্টার',
        blocks: [
          {
            type: 'paragraph',
            text: 'Forget "folders containing versions of files." Git is a small database that stores four kinds of objects — blobs (file content), trees (directory listings), commits (snapshots with metadata), and tags — each found by the hash of its own contents. Everything else in Git is a pointer: branches point to commits, HEAD points to your current position, and remote-tracking references remember where remotes were.',
            textBn: 'ভুলে যান "ফাইলের সংস্করণে ভরা ফোল্ডার"। গিট একটি ছোট ডাটাবেস যা চার ধরনের অবজেক্ট সংরক্ষণ করে — ব্লব (ফাইলের কন্টেন্ট), ট্রি (ডিরেক্টরি তালিকা), কমিট (মেটাডেটাসহ স্ন্যাপশট) এবং ট্যাগ — প্রতিটি নিজের কন্টেন্টের হ্যাশ দিয়ে খুঁজে পাওয়া যায়। গিটের বাকি সবকিছু পয়েন্টার: ব্রাঞ্চ কমিটের দিকে, HEAD বর্তমান অবস্থানের দিকে নির্দেশ করে, আর রিমোট-ট্র্যাকিং রেফারেন্স মনে রাখে রিমোট কোথায় ছিল।',
          },
          {
            type: 'keyConcept',
            title: 'Content addressing changes everything',
            titleBn: 'কন্টেন্ট অ্যাড্রেসিং সবকিছু বদলে দেয়',
            conceptKey: 'CONTENT_ADDRESSING',
            text: 'Because an object’s ID is derived from its bytes, identical content is stored exactly once, and any corruption is instantly detectable. History becomes a graph of immutable snapshots instead of a fragile pile of diffs.',
            textBn: 'যেহেতু অবজেক্টের ID তার বাইট থেকে তৈরি, একই কন্টেন্ট ঠিক একবার সংরক্ষিত হয়, এবং যেকোনো ক্ষতি সাথে সাথে ধরা পড়ে। ইতিহাস তখন ভঙ্গুর ডিফের স্তূপ না হয়ে অপরিবর্তনীয় স্ন্যাপশটের গ্রাফ হয়।',
          },
        ],
      },
      {
        id: 'sec-pipeline',
        title: 'The Three Areas',
        titleBn: 'তিনটি ক্ষেত্র',
        blocks: [
          {
            type: 'paragraph',
            text: 'Content flows in one direction: you edit files in the Working Tree, propose the next snapshot in the Index with git add, and permanently record it in the Repository with git commit. Almost every Git surprise disappears once you ask: which area am I changing right now?',
            textBn: 'কন্টেন্ট এক দিকে প্রবাহিত হয়: ওয়ার্কিং ট্রিতে ফাইল এডিট করেন, git add দিয়ে ইনডেক্সে পরবর্তী স্ন্যাপশট প্রস্তাব করেন, এবং git commit দিয়ে রিপোজিটরিতে স্থায়ীভাবে রেকর্ড করেন। এখন কোন ক্ষেত্রটি বদলাচ্ছি — এই প্রশ্ন করলেই প্রায় প্রতিটি গিট বিস্ময় দূর হয়।',
          },
          {
            type: 'code',
            code: 'Working Tree\n    ↓  git add\nIndex (staging area)\n    ↓  git commit\nRepository (.git)',
            language: 'text',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-how-git-thinks',
      subjectId: 'git',
      category: 'Internals',
      difficulty: 'intermediate',
      question: 'Explain Git’s architecture in one minute: what is stored, and what points at it?',
      questionBn: 'এক মিনিটে গিটের আর্কিটেকচার ব্যাখ্যা করুন: কী সংরক্ষিত হয়, আর কী সেদিকে নির্দেশ করে?',
      answer: 'Git stores four object types — blobs, trees, commits, tags — addressed by content hash in .git/objects. References (branches, tags), HEAD, the index, and the working tree all point into or stage content for that database.',
      answerBn: 'গিট চার ধরনের অবজেক্ট সংরক্ষণ করে — ব্লব, ট্রি, কমিট, ট্যাগ — .git/objects-এ কন্টেন্ট হ্যাশে ঠিকানাযুক্ত। রেফারেন্স (ব্রাঞ্চ, ট্যাগ), HEAD, ইনডেক্স ও ওয়ার্কিং ট্রি সবাই সেই ডাটাবেসের দিকে নির্দেশ করে বা কন্টেন্ট প্রস্তুত করে।',
      keyPoints: ['Objects: blob, tree, commit, tag', 'References are pointers, not copies', 'Index stages, working tree edits'],
      keyPointsBn: ['অবজেক্ট: ব্লব, ট্রি, কমিট, ট্যাগ', 'রেফারেন্স পয়েন্টার, কপি নয়', 'ইনডেক্স প্রস্তুত করে, ওয়ার্কিং ট্রি এডিট করে'],
    },
    relatedCommands: ['git.status', 'git.add', 'git.commit'],
    relatedLessons: ['git.fundamentals.what-is-git', 'git.fundamentals.three-areas'],
  },
  {
    id: 'git.internals.working-tree-index-repository',
    moduleId: 'git-internals-mental-model',
    slug: 'working-tree-index-repository',
    order: 2,
    durationMinutes: 10,
    difficulty: 'beginner',
    title: 'Working Tree, Index, Repository',
    titleBn: 'ওয়ার্কিং ট্রি, ইনডেক্স, রিপোজিটরি',
    summary: 'The three areas in depth: what lives where, and why git add stages rather than saves.',
    summaryBn: 'তিনটি ক্ষেত্র গভীরভাবে: কোথায় কী থাকে, এবং কেন git add সেভ না করে স্টেজ করে।',
    learningObjectives: [
      'Define the Working Tree, Index, and Repository precisely',
      'Explain what git add actually writes and where',
      'Predict what git status and git diff compare against',
    ],
    learningObjectivesBn: [
      'ওয়ার্কিং ট্রি, ইনডেক্স ও রিপোজিটরির নির্ভুল সংজ্ঞা দেওয়া',
      'ব্যাখ্যা করা git add আসলে কী লেখে এবং কোথায়',
      'অনুমান করা git status ও git diff কীসের সাথে তুলনা করে',
    ],
    keyTakeaways: [
      'Working Tree: checked-out files you edit. Index: the proposed next commit. Repository: permanent history.',
      'git add copies working-tree content into the index — it saves nothing permanently.',
      'git status compares all three areas; git diff defaults to working tree vs index.',
    ],
    sections: [
      {
        id: 'sec-areas',
        title: 'What Lives Where',
        titleBn: 'কোথায় কী থাকে',
        blocks: [
          {
            type: 'paragraph',
            text: 'The Working Tree is simply your checked-out files — the only area you edit directly. The Index (staging area) is a single file, .git/index, holding the exact blob list and metadata that the next commit will record. The Repository is everything under .git: objects plus references, i.e. all permanent history.',
            textBn: 'ওয়ার্কিং ট্রি হলো আপনার চেক-আউট করা ফাইল — একমাত্র ক্ষেত্র যা সরাসরি এডিট করেন। ইনডেক্স (স্টেজিং এরিয়া) একটি ফাইল, .git/index, যা পরবর্তী কমিট রেকর্ড করবে ঠিক সেই ব্লব তালিকা ও মেটাডেটা ধারণ করে। রিপোজিটরি হলো .git-এর অধীনে সবকিছু: অবজেক্ট সাথে রেফারেন্স, অর্থাৎ সমস্ত স্থায়ী ইতিহাস।',
          },
          {
            type: 'callout',
            variant: 'important',
            title: 'git add does not save',
            titleBn: 'git add সেভ করে না',
            text: 'Running git add copies the current file content into index blobs. Until git commit runs, nothing is permanent — resetting the index loses nothing from history because nothing entered it.',
            textBn: 'git add চালালে বর্তমান ফাইল কন্টেন্ট ইনডেক্স ব্লবে কপি হয়। git commit না চলা পর্যন্ত কিছুই স্থায়ী নয় — ইনডেক্স রিসেটে ইতিহাস থেকে কিছু হারায় না, কারণ কিছু ঢোকেইনি।',
          },
        ],
      },
      {
        id: 'sec-compare',
        title: 'What the Inspect Commands Compare',
        titleBn: 'পরিদর্শন কমান্ড কী তুলনা করে',
        blocks: [
          {
            type: 'list',
            items: [
              'git status: working tree vs index, plus index vs HEAD commit.',
              'git diff: working tree vs index (unstaged changes).',
              'git diff --staged: index vs HEAD commit (what the next commit contains).',
            ],
            itemsBn: [
              'git status: ওয়ার্কিং ট্রি বনাম ইনডেক্স, সাথে ইনডেক্স বনাম HEAD কমিট।',
              'git diff: ওয়ার্কিং ট্রি বনাম ইনডেক্স (আনস্টেজড পরিবর্তন)।',
              'git diff --staged: ইনডেক্স বনাম HEAD কমিট (পরবর্তী কমিটে কী আছে)।',
            ],
          },
          {
            type: 'command',
            command: 'git diff --staged',
            description: 'Preview exactly what the next commit will record.',
            descriptionBn: 'পরবর্তী কমিট ঠিক কী রেকর্ড করবে তা আগাম দেখুন।',
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-index-add',
      subjectId: 'git',
      difficulty: 'beginner',
      question: 'What does git add primarily update?',
      questionBn: 'git add মূলত কী আপডেট করে?',
      options: [
        { id: 'opt-a', text: 'The remote repository', textBn: 'রিমোট রিপোজিটরি', isCorrect: false },
        { id: 'opt-b', text: 'The index (staging area)', textBn: 'ইনডেক্স (স্টেজিং এরিয়া)', isCorrect: true },
        { id: 'opt-c', text: 'The GitHub pull request', textBn: 'গিটহাব পুল রিকোয়েস্ট', isCorrect: false },
        { id: 'opt-d', text: 'The commit history', textBn: 'কমিট হিস্ট্রি', isCorrect: false },
      ],
      explanation: 'git add writes working-tree content into .git/index. Only git commit moves staged content into permanent history.',
      explanationBn: 'git add ওয়ার্কিং-ট্রি কন্টেন্ট .git/index-এ লেখে। শুধু git commit স্টেজড কন্টেন্ট স্থায়ী ইতিহাসে নেয়।',
    },
    relatedCommands: ['git.status', 'git.add', 'git.diff'],
    relatedLessons: ['git.fundamentals.working-directory', 'git.fundamentals.staging-area', 'git.fundamentals.three-areas'],
  },
  {
    id: 'git.internals.commits-are-snapshots',
    moduleId: 'git-internals-mental-model',
    slug: 'commits-are-snapshots',
    order: 3,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'Commits Are Snapshots',
    titleBn: 'কমিট হলো স্ন্যাপশট',
    summary: 'A commit records a full project snapshot plus a link to its parent — never just a diff.',
    summaryBn: 'কমিট পূর্ণ প্রজেক্ট স্ন্যাপশট সাথে প্যারেন্টের লিঙ্ক রেকর্ড করে — শুধু ডিফ কখনো নয়।',
    learningObjectives: [
      'Explain snapshot vs diff storage',
      'Describe what unchanged files share between commits',
      'Explain why switching commits is fast',
    ],
    learningObjectivesBn: [
      'স্ন্যাপশট বনাম ডিফ স্টোরেজ ব্যাখ্যা করা',
      'বর্ণনা করা অপরিবর্তিত ফাইল কমিটগুলোর মধ্যে কী ভাগ করে',
      'কেন কমিট বদলানো দ্রুত তা ব্যাখ্যা করা',
    ],
    keyTakeaways: [
      'Each commit points to a complete tree snapshot, not a changeset.',
      'Unchanged files reuse identical blobs, so snapshots stay cheap.',
      'Checking out a commit means materializing its tree into the working tree.',
    ],
    sections: [
      {
        id: 'sec-snapshot',
        title: 'Snapshots, Not Diffs',
        titleBn: 'স্ন্যাপশট, ডিফ নয়',
        blocks: [
          {
            type: 'paragraph',
            text: 'Older systems stored each version as changes from the last. Git stores every commit as a pointer to a complete tree plus a pointer to its parent commit. Unchanged files cost nothing extra: parent and child simply reference the same blobs and subtrees.',
            textBn: 'পুরনো সিস্টেম প্রতিটি সংস্করণ আগেরটির থেকে পরিবর্তন হিসেবে রাখত। গিট প্রতিটি কমিট সম্পূর্ণ ট্রির পয়েন্টার সাথে প্যারেন্ট কমিটের পয়েন্টার হিসেবে রাখে। অপরিবর্তিত ফাইলে অতিরিক্ত খরচ নেই: প্যারেন্ট ও চাইল্ড একই ব্লব ও সাবট্রি রেফারেন্স করে।',
          },
          {
            type: 'code',
            code: 'C2 → tree T2 (README→B1, src→T1)\nC3 → tree T3 (README→B2, src→T1)   ← T1 shared, not copied',
            language: 'text',
          },
        ],
      },
    ],
    relatedCommands: ['git.commit', 'git.show', 'git.log'],
    relatedLessons: ['git.fundamentals.commit', 'git.fundamentals.what-is-git'],
  },
  {
    id: 'git.internals.branches-are-references',
    moduleId: 'git-internals-mental-model',
    slug: 'branches-are-references',
    order: 4,
    durationMinutes: 10,
    difficulty: 'intermediate',
    title: 'Branches Are References',
    titleBn: 'ব্রাঞ্চ হলো রেফারেন্স',
    summary: 'A branch is a movable 41-byte pointer to a commit. Creating one copies no files and rewrites no history.',
    summaryBn: 'ব্রাঞ্চ হলো কমিটের দিকে চলমান ৪১-বাইট পয়েন্টার। এটি তৈরি করলে ফাইল কপি হয় না, হিস্ট্রি পুনর্লিখন হয় না।',
    learningObjectives: [
      'Define a branch as a movable commit reference',
      'Explain why branch creation is instant',
      'Predict what moves a branch pointer (commit, merge, reset)',
    ],
    learningObjectivesBn: [
      'চলমান কমিট রেফারেন্স হিসেবে ব্রাঞ্চের সংজ্ঞা দেওয়া',
      'ব্যাখ্যা করা কেন ব্রাঞ্চ তৈরি তাৎক্ষণিক',
      'অনুমান করা কী ব্রাঞ্চ পয়েন্টার সরায় (কমিট, মার্জ, রিসেট)',
    ],
    keyTakeaways: [
      'A branch is a file under .git/refs/heads holding one commit hash.',
      'New commits advance only the currently checked-out branch.',
      'Two branches can point at the same commit — that is normal, not a bug.',
    ],
    sections: [
      {
        id: 'sec-pointer',
        title: 'Not a Folder, Not a Copy',
        titleBn: 'ফোল্ডার নয়, কপি নয়',
        blocks: [
          {
            type: 'paragraph',
            text: 'A branch is not a folder and not a copy of the repository. It is a reference: a tiny file named e.g. .git/refs/heads/main containing a single commit hash. Creating a branch writes 41 bytes. Deleting one removes the pointer while the commits remain until garbage collection.',
            textBn: 'ব্রাঞ্চ ফোল্ডার নয়, রিপোজিটরির কপিও নয়। এটি একটি রেফারেন্স: যেমন .git/refs/heads/main নামে ক্ষুদ্র ফাইল যাতে একটি কমিট হ্যাশ থাকে। ব্রাঞ্চ তৈরি মানে ৪১ বাইট লেখা। মুছে ফেললে পয়েন্টার যায়, কমিট গারবেজ কালেকশন পর্যন্ত থাকে।',
          },
          {
            type: 'code',
            code: 'main     → C3\nfeature  → C3   (same commit, two pointers)',
            language: 'text',
          },
        ],
      },
      {
        id: 'sec-moves',
        title: 'What Moves a Branch',
        titleBn: 'ব্রাঞ্চ কী সরায়',
        blocks: [
          {
            type: 'list',
            items: [
              'git commit advances the checked-out branch to the new commit.',
              'git merge moves it to the merge result (or fast-forwards it).',
              'git reset deliberately rewinds it — the dangerous one.',
              'Nothing else moves it: fetch, log, and diff leave pointers alone.',
            ],
            itemsBn: [
              'git commit চেক-আউট ব্রাঞ্চকে নতুন কমিটে এগিয়ে নেয়।',
              'git merge মার্জ ফলে নেয় (বা ফাস্ট-ফরোয়ার্ড করে)।',
              'git reset ইচ্ছাকৃতভাবে পেছনে নেয় — বিপজ্জনকটি।',
              'আর কিছু সরায় না: fetch, log ও diff পয়েন্টারে হাত দেয় না।',
            ],
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-branch-reference',
      subjectId: 'git',
      difficulty: 'intermediate',
      question: 'What does a branch fundamentally represent?',
      questionBn: 'ব্রাঞ্চ মৌলিকভাবে কী নির্দেশ করে?',
      options: [
        { id: 'opt-a', text: 'A folder containing that branch’s files', textBn: 'সেই ব্রাঞ্চের ফাইল ধারণকারী ফোল্ডার', isCorrect: false },
        { id: 'opt-b', text: 'A separate copy of the repository', textBn: 'রিপোজিটরির আলাদা কপি', isCorrect: false },
        { id: 'opt-c', text: 'A movable reference to a commit', textBn: 'কমিটের দিকে চলমান রেফারেন্স', isCorrect: true },
        { id: 'opt-d', text: 'A backup stored on GitHub', textBn: 'গিটহাবে সংরক্ষিত ব্যাকআপ', isCorrect: false },
      ],
      explanation: 'A branch is a 41-byte file holding a commit hash. Committing, merging, or resetting moves that pointer.',
      explanationBn: 'ব্রাঞ্চ হলো কমিট হ্যাশ ধারণকারী ৪১-বাইট ফাইল। কমিট, মার্জ বা রিসেট সেই পয়েন্টার সরায়।',
    },
    relatedCommands: ['git.branch', 'git.switch', 'git.log'],
    relatedLessons: ['git.fundamentals.branch', 'git.fundamentals.head'],
  },
  {
    id: 'git.internals.head-symbolic-references',
    moduleId: 'git-internals-mental-model',
    slug: 'head-symbolic-references',
    order: 5,
    durationMinutes: 10,
    difficulty: 'intermediate',
    title: 'HEAD and Symbolic References',
    titleBn: 'HEAD ও সিম্বলিক রেফারেন্স',
    summary: 'HEAD records where you are: normally a symbolic pointer to a branch, occasionally a direct commit pointer.',
    summaryBn: 'HEAD রেকর্ড করে আপনি কোথায় আছেন: সাধারণত ব্রাঞ্চের দিকে সিম্বলিক পয়েন্টার, মাঝে মাঝে সরাসরি কমিট পয়েন্টার।',
    learningObjectives: [
      'Read the two normal HEAD states (attached vs detached)',
      'Explain symbolic references with the main → C3 chain',
      'Explain why detached HEAD happens and why it is risky',
    ],
    learningObjectivesBn: [
      'HEAD-এর দুটি স্বাভাবিক অবস্থা পড়া (সংযুক্ত বনাম বিচ্ছিন্ন)',
      'main → C3 শৃঙ্খলে সিম্বলিক রেফারেন্স ব্যাখ্যা করা',
      'কেন ডিটাচড HEAD হয় ও কেন ঝুঁকিপূর্ণ তা ব্যাখ্যা করা',
    ],
    keyTakeaways: [
      'Attached HEAD: HEAD → branch → commit. New commits advance the branch.',
      'Detached HEAD: HEAD → commit directly. New commits belong to no branch.',
      'HEAD is not a branch — it is a pointer that usually points at one.',
    ],
    sections: [
      {
        id: 'sec-attached',
        title: 'The Normal Chain',
        titleBn: 'স্বাভাবিক শৃঙ্খল',
        blocks: [
          {
            type: 'code',
            code: 'HEAD\n ↓\nmain\n ↓\nC3',
            language: 'text',
          },
          {
            type: 'paragraph',
            text: 'HEAD is a symbolic reference: instead of a commit hash it contains the path of a branch reference, usually refs/heads/main. When you commit, Git follows HEAD to the branch and advances that branch pointer. This indirection is the entire trick behind branching.',
            textBn: 'HEAD একটি সিম্বলিক রেফারেন্স: কমিট হ্যাশের বদলে এতে ব্রাঞ্চ রেফারেন্সের পথ থাকে, সাধারণত refs/heads/main। কমিট করলে গিট HEAD অনুসরণ করে ব্রাঞ্চে পৌঁছে সেই পয়েন্টার এগিয়ে নেয়। ব্রাঞ্চিংয়ের পুরো কৌশল এই পরোক্ষ নির্দেশনায়।',
          },
        ],
      },
      {
        id: 'sec-detached',
        title: 'When HEAD Detaches',
        titleBn: 'HEAD যখন বিচ্ছিন্ন হয়',
        blocks: [
          {
            type: 'code',
            code: 'HEAD\n ↓\nC3   (no branch in between)',
            language: 'text',
          },
          {
            type: 'paragraph',
            text: 'Checking out a commit hash, tag, or remote-tracking branch points HEAD directly at a commit. You can inspect and even commit, but new commits have no branch to keep them — switch away and they become hard to find. Recovery is simple: create a branch where you stand.',
            textBn: 'কমিট হ্যাশ, ট্যাগ বা রিমোট-ট্র্যাকিং ব্রাঞ্চ চেকআউট করলে HEAD সরাসরি কমিটের দিকে যায়। পরিদর্শন এমনকি কমিটও করা যায়, কিন্তু নতুন কমিটের রাখার মতো ব্রাঞ্চ থাকে না — সরে গেলে খুঁজে পাওয়া কঠিন হয়। পুনরুদ্ধার সহজ: যেখানে দাঁড়িয়ে আছেন সেখানে ব্রাঞ্চ তৈরি করুন।',
          },
          {
            type: 'callout',
            variant: 'warning',
            title: 'Do not imply HEAD is a branch',
            titleBn: 'HEAD ব্রাঞ্চ — এমন ইঙ্গিত দেবেন না',
            text: 'HEAD tells Git what the current checkout is associated with. It usually points at a branch, but it can point at anything committish — that flexibility is exactly what detached HEAD is.',
            textBn: 'HEAD গিটকে বলে বর্তমান চেকআউট কীসের সাথে যুক্ত। সাধারণত ব্রাঞ্চের দিকে যায়, কিন্তু যেকোনো কমিট-সদৃশের দিকে যেতে পারে — এই নমনীয়তাই ডিটাচড HEAD।',
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-head-position',
      subjectId: 'git',
      difficulty: 'intermediate',
      question: 'What does HEAD normally identify?',
      questionBn: 'HEAD সাধারণত কী চিহ্নিত করে?',
      options: [
        { id: 'opt-a', text: 'The GitHub repository', textBn: 'গিটহাব রিপোজিটরি', isCorrect: false },
        { id: 'opt-b', text: 'The current checkout/reference position', textBn: 'বর্তমান চেকআউট/রেফারেন্স অবস্থান', isCorrect: true },
        { id: 'opt-c', text: 'The staging area', textBn: 'স্টেজিং এরিয়া', isCorrect: false },
        { id: 'opt-d', text: 'The default remote', textBn: 'ডিফল্ট রিমোট', isCorrect: false },
      ],
      explanation: 'HEAD records where you are — normally a branch, which leads to a commit. It is a pointer, not a branch itself.',
      explanationBn: 'HEAD রেকর্ড করে আপনি কোথায় — সাধারণত ব্রাঞ্চ, যা কমিটে নেয়। এটি পয়েন্টার, নিজে ব্রাঞ্চ নয়।',
    },
    relatedCommands: ['git.switch', 'git.checkout', 'git.log'],
    relatedLessons: ['git.fundamentals.head', 'git.fundamentals.branch'],
  },
  {
    id: 'git.internals.misconceptions',
    moduleId: 'git-internals-mental-model',
    slug: 'common-misconceptions',
    order: 6,
    durationMinutes: 8,
    difficulty: 'beginner',
    title: 'Common Git Misconceptions',
    titleBn: 'সাধারণ ভুল ধারণা',
    summary: 'Ten myths that break understanding — each corrected in one precise paragraph.',
    summaryBn: 'বোঝাপড়া নষ্ট করা দশটি ভ্রান্তি — প্রতিটি একটি নির্ভুল অনুচ্ছেদে সংশোধিত।',
    learningObjectives: [
      'Replace ten myths with the correct mental model',
      'Explain why each myth is tempting but wrong',
      'Use precise vocabulary (reference, snapshot, pointer)',
    ],
    learningObjectivesBn: [
      'দশটি ভ্রান্তি সঠিক মেন্টাল মডেলে বদলানো',
      'ব্যাখ্যা করা প্রতিটি ভ্রান্তি লোভনীয় কিন্তু ভুল কেন',
      'নির্ভুল শব্দভাণ্ডার ব্যবহার (রেফারেন্স, স্ন্যাপশট, পয়েন্টার)',
    ],
    keyTakeaways: [
      'Branches are references, commits are snapshots, HEAD is a pointer.',
      'fetch downloads; pull fetches and integrates — they are not synonyms.',
      'Reflog and GitHub are conveniences, not backups of your work.',
    ],
    sections: [
      {
        id: 'sec-myths',
        title: 'Myth vs Model',
        titleBn: 'ভ্রান্তি বনাম মডেল',
        blocks: [
          {
            type: 'paragraph',
            text: 'Each myth below is followed by the correction. Read the myth, notice if you believed it, then install the model. The explorer page repeats these as an interactive checklist.',
            textBn: 'নিচের প্রতিটি ভ্রান্তির পর সংশোধন দেওয়া আছে। ভ্রান্তি পড়ুন, বিশ্বাস করতেন কিনা লক্ষ্য করুন, তারপর মডেল স্থাপন করুন। এক্সপ্লোরার পেজে এগুলো ইন্টারেক্টিভ চেকলিস্টে পাবেন।',
          },
          {
            type: 'list',
            ordered: true,
            items: [
              'Myth: A branch is a folder. → A branch is a movable reference to a commit.',
              'Myth: A commit stores a full copy of every file. → A commit points to a tree; unchanged content is shared, not duplicated.',
              'Myth: HEAD is a branch. → HEAD is a pointer that normally points at a branch.',
              'Myth: origin/main is the remote branch itself. → It is your local memory of where the remote was at last fetch.',
              'Myth: git add uploads files. → git add stages content into the index; nothing leaves your machine.',
              'Myth: git fetch changes my current branch. → fetch only updates remote-tracking references and downloads objects.',
              'Myth: git pull is just git fetch. → pull is fetch plus an integration step (merge or rebase).',
              'Myth: Rebase moves the original commits. → Rebase creates new commits and moves the branch pointer; originals linger until collected.',
              'Myth: Reflog is a backup. → Reflog is a local, expiring journal of reference movements — not an archive.',
              'Myth: GitHub is Git. → GitHub hosts Git repositories; Git works fully without it.',
            ],
            itemsBn: [
              'ভ্রান্তি: ব্রাঞ্চ একটি ফোল্ডার। → ব্রাঞ্চ হলো কমিটের দিকে চলমান রেফারেন্স।',
              'ভ্রান্তি: কমিট প্রতিটি ফাইলের পূর্ণ কপি রাখে। → কমিট ট্রির দিকে নির্দেশ করে; অপরিবর্তিত কন্টেন্ট ভাগ হয়, ডুপ্লিকেট নয়।',
              'ভ্রান্তি: HEAD একটি ব্রাঞ্চ। → HEAD একটি পয়েন্টার যা সাধারণত ব্রাঞ্চের দিকে যায়।',
              'ভ্রান্তি: origin/main-ই রিমোট ব্রাঞ্চ। → এটি শেষ fetch-এ রিমোট কোথায় ছিল তার লোকাল স্মৃতি।',
              'ভ্রান্তি: git add ফাইল আপলোড করে। → git add ইনডেক্সে কন্টেন্ট স্টেজ করে; মেশিন থেকে কিছু যায় না।',
              'ভ্রান্তি: git fetch বর্তমান ব্রাঞ্চ বদলায়। → fetch শুধু রিমোট-ট্র্যাকিং রেফারেন্স আপডেট করে ও অবজেক্ট ডাউনলোড করে।',
              'ভ্রান্তি: git pull শুধু git fetch। → pull হলো fetch সাথে একীভূতকরণ ধাপ (মার্জ বা রিবেস)।',
              'ভ্রান্তি: রিবেস মূল কমিট সরায়। → রিবেস নতুন কমিট তৈরি করে ও ব্রাঞ্চ পয়েন্টার সরায়; মূলগুলো সংগ্রহ পর্যন্ত থাকে।',
              'ভ্রান্তি: রিফ্লগ ব্যাকআপ। → রিফ্লগ রেফারেন্স নড়াচড়ার লোকাল, মেয়াদি জার্নাল — আর্কাইভ নয়।',
              'ভ্রান্তি: গিটহাবই গিট। → গিটহাব গিট রিপোজিটরি হোস্ট করে; গিট ছাড়াই পুরোপুরি চলে।',
            ],
          },
        ],
      },
    ],
    relatedCommands: ['git.status', 'git.fetch', 'git.pull'],
    relatedLessons: ['git.fundamentals.what-is-git', 'git.fundamentals.three-areas'],
  },
];
