import { CurriculumLesson } from '@/types/content';

/**
 * Module 4 — History (git-internals-history)
 * Commit graphs, parents, reachability, DAG, cheap branches, rebase identity.
 */
export const INTERNALS_HISTORY_LESSONS: CurriculumLesson[] = [
  {
    id: 'git.internals.commit-graphs',
    moduleId: 'git-internals-history',
    slug: 'commit-graphs',
    order: 1,
    durationMinutes: 10,
    difficulty: 'intermediate',
    title: 'Commit Graphs',
    titleBn: 'কমিট গ্রাফ',
    summary: 'History is a graph you can read: nodes are commits, edges are parent links, labels are references.',
    summaryBn: 'ইতিহাস পড়া যায় এমন গ্রাফ: নোড কমিট, এজ প্যারেন্ট লিঙ্ক, লেবেল রেফারেন্স।',
    learningObjectives: [
      'Read a commit graph: nodes, edges, and labels',
      'Explain what git log --graph draws and why',
      'Distinguish linear stretches from branch-and-merge regions',
    ],
    learningObjectivesBn: [
      'কমিট গ্রাফ পড়া: নোড, এজ ও লেবেল',
      'ব্যাখ্যা করা git log --graph কী আঁকে ও কেন',
      'রৈখিক অংশ ও ব্রাঞ্চ-মার্জ অঞ্চল আলাদা করা',
    ],
    keyTakeaways: [
      'Every line in the graph is a parent pointer; every label is a reference.',
      'git log --graph --oneline --all renders the true structure, not a simplification.',
      'Reading graphs turns merge anxiety into pattern recognition.',
    ],
    sections: [
      {
        id: 'sec-read',
        title: 'How to Read the Picture',
        titleBn: 'ছবি কীভাবে পড়বেন',
        blocks: [
          {
            type: 'code',
            code: '      F1 → F2\n     /\nC1 → C2 → C3\n           ↑\n          main',
            language: 'text',
          },
          {
            type: 'paragraph',
            text: 'Circles are commits, lines are parent links pointing backwards in time, and words like main or HEAD are references pinned to tips. A straight line means sequential parents; a fork means one commit gained two children; converging lines mean a merge commit joined them. There is no hidden magic — the picture is the data structure.',
            textBn: 'বৃত্ত কমিট, রেখা সময়ে পেছনে যাওয়া প্যারেন্ট লিঙ্ক, main বা HEAD-এর মতো শব্দ টিপে পিন করা রেফারেন্স। সরলরেখা মানে ধারাবাহিক প্যারেন্ট; ফোর্ক মানে একটি কমিট দুটি সন্তান পেয়েছে; একত্রিত রেখা মানে মার্জ কমিট যুক্ত করেছে। লুকানো জাদু নেই — ছবিই ডেটা স্ট্রাকচার।',
          },
          {
            type: 'command',
            command: 'git log --graph --oneline --all',
            description: 'Draw the real graph across all references.',
            descriptionBn: 'সব রেফারেন্স জুড়ে আসল গ্রাফ আঁকুন।',
          },
        ],
      },
    ],
    relatedCommands: ['git.log', 'git.show'],
    relatedLessons: ['git.fundamentals.commit', 'git.fundamentals.branch'],
  },
  {
    id: 'git.internals.parent-relationships',
    moduleId: 'git-internals-history',
    slug: 'parent-relationships',
    order: 2,
    durationMinutes: 8,
    difficulty: 'intermediate',
    title: 'Parent Relationships',
    titleBn: 'প্যারেন্ট সম্পর্ক',
    summary: 'Zero, one, or many parents: root commits, normal commits, and merges — and the notations that address them.',
    summaryBn: 'শূন্য, এক বা অনেক প্যারেন্ট: রুট কমিট, সাধারণ কমিট ও মার্জ — এবং সেগুলোর ঠিকানা দেওয়া নোটেশন।',
    learningObjectives: [
      'Count parents to classify any commit',
      'Use ~ and ^ notation to walk ancestry',
      'Explain first-parent vs all-parents traversal',
    ],
    learningObjectivesBn: [
      'প্যারেন্ট গুনে যেকোনো কমিট শ্রেণিবদ্ধ করা',
      'পূর্বপুরুষ হাঁটতে ~ ও ^ নোটেশন ব্যবহার করা',
      'ফার্স্ট-প্যারেন্ট বনাম সব-প্যারেন্ট ট্রাভার্সাল ব্যাখ্যা করা',
    ],
    keyTakeaways: [
      '0 parents: root. 1 parent: normal. 2+: merge.',
      'HEAD~3 walks back three first-parents; ^2 selects a second parent.',
      'git log --first-parent shows mainline history, hiding merged-in side branches.',
    ],
    sections: [
      {
        id: 'sec-count',
        title: 'Count the Parents',
        titleBn: 'প্যারেন্ট গুনুন',
        blocks: [
          {
            type: 'list',
            items: [
              'No parents → the root commit; every history starts here.',
              'One parent → an ordinary commit continuing one line.',
              'Two or more parents → a merge (or octopus) joining lines.',
            ],
            itemsBn: [
              'প্যারেন্ট নেই → রুট কমিট; প্রতিটি ইতিহাস এখানে শুরু।',
              'এক প্যারেন্ট → একটি লাইন চালিয়ে যাওয়া সাধারণ কমিট।',
              'দুই বা বেশি প্যারেন্ট → লাইন যুক্ত করা মার্জ (বা অক্টোপাস)।',
            ],
          },
          {
            type: 'code',
            code: 'HEAD~1   parent of HEAD\nHEAD~3   three first-parents back\nM^2     second parent of merge M (the merged-in side)',
            language: 'text',
          },
        ],
      },
    ],
    relatedCommands: ['git.log', 'git.show'],
    relatedLessons: ['git.fundamentals.commit'],
  },
  {
    id: 'git.internals.reachability',
    moduleId: 'git-internals-history',
    slug: 'reachability',
    order: 3,
    durationMinutes: 10,
    difficulty: 'advanced',
    title: 'Reachability',
    titleBn: 'রিচেবিলিটি',
    summary: 'A commit matters while some reference can reach it. Reachability decides what you see, what you can recover, and what GC may delete.',
    summaryBn: 'কোনো রেফারেন্স পৌঁছাতে পারলে কমিট গুরুত্বপূর্ণ। রিচেবিলিটি ঠিক করে কী দেখবেন, কী উদ্ধার করবেন, GC কী মুছতে পারে।',
    learningObjectives: [
      'Define reachable vs unreachable precisely',
      'Trace reachability from main through parents',
      'Connect reachability to recovery and collection',
    ],
    learningObjectivesBn: [
      'রিচেবল বনাম আনরিচেবলের নির্ভুল সংজ্ঞা দেওয়া',
      'main থেকে প্যারেন্ট ধরে রিচেবিলিটি অনুসরণ করা',
      'রিচেবিলিটিকে উদ্ধার ও সংগ্রহের সাথে যুক্ত করা',
    ],
    keyTakeaways: [
      'Reachable = walkable from a ref by following parent links.',
      'C1, C2, C3 are reachable from main; abandoned commits are not.',
      'Unreachable is a warning state, not instant deletion — reflog and GC decide the rest.',
    ],
    sections: [
      {
        id: 'sec-reach',
        title: 'Walking Backwards From main',
        titleBn: 'main থেকে পেছনে হাঁটা',
        blocks: [
          {
            type: 'code',
            code: 'main\n ↓\nC3\n ↓\nC2\n ↓\nC1\n\nC1, C2, C3 are reachable from main.',
            language: 'text',
          },
          {
            type: 'paragraph',
            text: 'Start at every reference and walk every parent link; everything visited is reachable and therefore protected. A commit with no path from any ref — a deleted branch tip, an amended-away commit — is unreachable. Git keeps unreachable objects for a grace period precisely so mistakes remain reversible, then garbage collection may finally remove them.',
            textBn: 'প্রতিটি রেফ থেকে শুরু করে প্রতিটি প্যারেন্ট লিঙ্ক হাঁটুন; যা দেখা যায় তা রিচেবল, তাই সুরক্ষিত। কোনো ref থেকে পথ নেই এমন কমিট — মোছা ব্রাঞ্চ টিপ, amend-এ সরা কমিট — আনরিচেবল। গিট আনরিচেবল অবজেক্ট গ্রেস পিরিয়ড রাখে ঠিক যাতে ভুল ফেরানো যায়, তারপর গারবেজ কালেকশন মুছতে পারে।',
          },
          {
            type: 'keyConcept',
            title: 'Reachability is the master switch',
            titleBn: 'রিচেবিলিটি মাস্টার সুইচ',
            conceptKey: 'REACHABILITY',
            text: 'Logs show reachable commits. Recovery hunts recently-unreachable ones. Garbage collection deletes long-unreachable ones. One concept, three behaviors.',
            textBn: 'লগ রিচেবল কমিট দেখায়। উদ্ধার সম্প্রতি-আনরিচেবল খোঁজে। গারবেজ কালেকশন দীর্ঘ-আনরিচেবল মোছে। একটি ধারণা, তিন আচরণ।',
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-reachability',
      subjectId: 'git',
      difficulty: 'advanced',
      question: 'When is a commit "reachable" from main?',
      questionBn: 'কখন একটি কমিট main থেকে "রিচেবল" হয়?',
      options: [
        { id: 'opt-a', text: 'When it was pushed to GitHub', textBn: 'যখন গিটহাবে পুশ হয়েছে', isCorrect: false },
        { id: 'opt-b', text: 'When parent links lead to it starting from main’s tip', textBn: 'main-এর টিপ থেকে প্যারেন্ট লিঙ্ক সেখানে নিলে', isCorrect: true },
        { id: 'opt-c', text: 'When it is less than 90 days old', textBn: 'যখন ৯০ দিনের কম পুরনো', isCorrect: false },
        { id: 'opt-d', text: 'When its message mentions main', textBn: 'যখন বার্তায় main উল্লেখ থাকে', isCorrect: false },
      ],
      explanation: 'Reachability is purely graph-walking: start at the ref tip, follow parents. Age, remotes, and messages are irrelevant.',
      explanationBn: 'রিচেবিলিটি খাঁটি গ্রাফ-হাঁটা: ref টিপ থেকে শুরু, প্যারেন্ট অনুসরণ। বয়স, রিমোট ও বার্তা অপ্রাসঙ্গিক।',
    },
    relatedCommands: ['git.log', 'git.reset'],
    relatedLessons: ['git.fundamentals.commit'],
  },
  {
    id: 'git.internals.dag-structure',
    moduleId: 'git-internals-history',
    slug: 'dag-structure',
    order: 4,
    durationMinutes: 10,
    difficulty: 'advanced',
    title: 'DAG Structure',
    titleBn: 'DAG কাঠামো',
    summary: 'History is a directed acyclic graph: edges point to parents, and cycles are impossible by construction.',
    summaryBn: 'ইতিহাস ডিরেক্টেড অ্যাসাইক্লিক গ্রাফ: এজ প্যারেন্টের দিকে, এবং গঠনেই চক্র অসম্ভব।',
    learningObjectives: [
      'Expand DAG: directed, acyclic, graph',
      'Explain why cycles cannot exist (hashes commit to parents)',
      'Show branching and merging as natural DAG operations',
    ],
    learningObjectivesBn: [
      'DAG সম্প্রসারণ: ডিরেক্টেড, অ্যাসাইক্লিক, গ্রাফ',
      'ব্যাখ্যা করা কেন চক্র থাকতে পারে না (হ্যাশ প্যারেন্টে প্রতিশ্রুতিবদ্ধ)',
      'ব্রাঞ্চিং ও মার্জিংকে স্বাভাবিক DAG অপারেশন হিসেবে দেখানো',
    ],
    keyTakeaways: [
      'Directed: edges run child → parent, backwards in time.',
      'Acyclic: a commit’s hash covers its parents, so it can never be its own ancestor.',
      'Branch = new edge path; merge = join node with two incoming paths.',
    ],
    sections: [
      {
        id: 'sec-dag',
        title: 'Directed, Acyclic, Graph',
        titleBn: 'ডিরেক্টেড, অ্যাসাইক্লিক, গ্রাফ',
        blocks: [
          {
            type: 'code',
            code: '      F1 → F2\n     /       \\\nC1 → C2 → C3 → M',
            language: 'text',
          },
          {
            type: 'paragraph',
            text: 'Each edge points from child to parent — direction matters because every operation (log, merge-base, reachability) walks backwards. Cycles are mathematically excluded: a commit’s ID is computed over its parents’ IDs, so a commit can never contain itself as an ancestor. Branching splits paths forward in time; merging joins them. The DAG is not a metaphor — it is the data structure.',
            textBn: 'প্রতিটি এজ চাইল্ড থেকে প্যারেন্টের দিকে — দিক গুরুত্বপূর্ণ কারণ প্রতিটি অপারেশন (log, merge-base, রিচেবিলিটি) পেছনে হাঁটে। চক্র গাণিতিকভাবে বাদ: কমিট ID প্যারেন্ট ID-এর ওপর গণনা হয়, তাই কমিট নিজের পূর্বপুরুষ হতে পারে না। ব্রাঞ্চিং সময়ে সামনে পথ ভাগ করে; মার্জিং যুক্ত করে। DAG রূপক নয় — এটাই ডেটা স্ট্রাকচার।',
          },
        ],
      },
    ],
    relatedCommands: ['git.log', 'git.merge'],
    relatedLessons: ['git.fundamentals.commit', 'git.fundamentals.branch'],
  },
  {
    id: 'git.internals.cheap-branches',
    moduleId: 'git-internals-history',
    slug: 'cheap-branches',
    order: 5,
    durationMinutes: 8,
    difficulty: 'intermediate',
    title: 'Why Branches Are Cheap',
    titleBn: 'ব্রাঞ্চ কেন সস্তা',
    summary: 'Branching costs 41 bytes because history is shared, not copied. Compare with file-copy version control to feel the difference.',
    summaryBn: 'ব্রাঞ্চিংয়ে ৪১ বাইট খরচ কারণ হিস্ট্রি ভাগ হয়, কপি নয়। পার্থক্য অনুভবে ফাইল-কপি ভার্সন কন্ট্রোলের সাথে তুলনা করুন।',
    learningObjectives: [
      'Explain the 41-byte cost of a branch',
      'Contrast with copy-based branching models',
      'Predict checkout cost vs branch-creation cost',
    ],
    learningObjectivesBn: [
      'ব্রাঞ্চের ৪১-বাইট খরচ ব্যাখ্যা করা',
      'কপি-ভিত্তিক ব্রাঞ্চিং মডেলের সাথে তুলনা করা',
      'চেকআউট খরচ বনাম ব্রাঞ্চ-তৈরি খরচ অনুমান করা',
    ],
    keyTakeaways: [
      'New branch = one 41-byte ref file. No objects are created or copied.',
      'Older systems copied whole trees; Git shares everything until divergence.',
      'Checkout costs scale with changed files; branching costs nothing measurable.',
    ],
    sections: [
      {
        id: 'sec-cheap',
        title: 'Sharing Beats Copying',
        titleBn: 'ভাগ করা কপিকে হারায়',
        blocks: [
          {
            type: 'paragraph',
            text: 'In copy-based systems, branching duplicates the tree — cost grows with project size. In Git, the new branch points at the same commit, sharing its entire reachable history for free. Cost appears only as the branches diverge, and even then only as new objects for genuinely new content.',
            textBn: 'কপি-ভিত্তিক সিস্টেমে ব্রাঞ্চিং ট্রি ডুপ্লিকেট করে — খরচ প্রজেক্ট আকারে বাড়ে। গিটে নতুন ব্রাঞ্চ একই কমিটের দিকে যায়, পুরো পৌঁছানো হিস্ট্রি বিনামূল্যে ভাগ করে। খরচ আসে শুধু ব্রাঞ্চ ডাইভার্জ হলে, তাও সত্যিকারের নতুন কন্টেন্টের নতুন অবজেক্টে।',
          },
          {
            type: 'callout',
            variant: 'tip',
            title: 'Branch freely, checkout thoughtfully',
            titleBn: 'নির্ভয়ে ব্রাঞ্চ করুন, ভেবে চেকআউট করুন',
            text: 'Creating branches is free, so experiment often. Switching branches rewrites working-tree files, so commit or stash first — that asymmetry explains half of all branching advice.',
            textBn: 'ব্রাঞ্চ তৈরি বিনামূল্য, তাই প্রায়ই পরীক্ষা করুন। ব্রাঞ্চ বদলালে ওয়ার্কিং-ট্রি ফাইল পুনর্লিখিত হয়, তাই আগে কমিট বা স্ট্যাশ করুন — এই অসমতাই অর্ধেক ব্রাঞ্চিং পরামর্শ ব্যাখ্যা করে।',
          },
        ],
      },
    ],
    interviewQuestion: {
      id: 'int-cheap-branches',
      subjectId: 'git',
      category: 'Internals',
      difficulty: 'intermediate',
      question: 'Why is creating a Git branch nearly instantaneous regardless of repository size?',
      questionBn: 'রিপোজিটরি আকার নির্বিশেষে গিট ব্রাঞ্চ তৈরি প্রায় তাৎক্ষণিক কেন?',
      answer: 'A branch is a 41-byte reference file holding one commit hash. No files or objects are copied — the new branch shares all reachable history with its base until the two diverge.',
      answerBn: 'ব্রাঞ্চ হলো একটি কমিট হ্যাশ ধারণকারী ৪১-বাইট রেফারেন্স ফাইল। ফাইল বা অবজেক্ট কপি হয় না — নতুন ব্রাঞ্চ ডাইভার্জ না হওয়া পর্যন্ত বেসের পুরো পৌঁছানো হিস্ট্রি ভাগ করে।',
      keyPoints: ['41-byte ref file', 'Shared history, zero copying', 'Cost appears only on divergence'],
      keyPointsBn: ['৪১-বাইট ref ফাইল', 'ভাগ করা হিস্ট্রি, শূন্য কপি', 'খরচ শুধু ডাইভারজেন্সে'],
    },
    relatedCommands: ['git.branch', 'git.switch'],
    relatedLessons: ['git.fundamentals.branch'],
  },
  {
    id: 'git.internals.rebase-rewrites-history',
    moduleId: 'git-internals-history',
    slug: 'rebase-rewrites-history',
    order: 6,
    durationMinutes: 12,
    difficulty: 'advanced',
    title: 'Why Rebase Rewrites History',
    titleBn: 'রিবেস কেন হিস্ট্রি পুনর্লেখে',
    summary: 'Rebase never moves commits: it replays changes as new commits and slides the branch pointer. New hashes, new identities.',
    summaryBn: 'রিবেস কমিট সরায় না: পরিবর্তন নতুন কমিটে রিপ্লে করে ও ব্রাঞ্চ পয়েন্টার স্লাইড করে। নতুন হ্যাশ, নতুন পরিচয়।',
    learningObjectives: [
      'Trace the four rebase steps on the object model',
      'Explain why replayed commits get new IDs',
      'State the golden rule and its object-level reason',
    ],
    learningObjectivesBn: [
      'অবজেক্ট মডেলে রিবেসের চার ধাপ অনুসরণ করা',
      'ব্যাখ্যা করা কেন রিপ্লে কমিট নতুন ID পায়',
      'গোল্ডেন রুল ও এর অবজেক্ট-স্তরের কারণ বলা',
    ],
    keyTakeaways: [
      'Rebase = identify commits, change base, create new commits, move the branch ref.',
      'New parents and timestamps mean new hashes: F1′ is not F1.',
      'Rewriting shared history orphans teammates’ work — hence the golden rule.',
    ],
    sections: [
      {
        id: 'sec-replay',
        title: 'Replay, Not Relocation',
        titleBn: 'রিপ্লে, স্থানান্তর নয়',
        blocks: [
          {
            type: 'code',
            code: 'Before:\nC1 → C2\n       \\\n        F1 → F2\n\nAfter:\nC1 → C2 → C3\n             \\\n              F1′ → F2′   (new objects; F1, F2 linger)',
            language: 'text',
          },
          {
            type: 'paragraph',
            text: 'Conceptually Git identifies the commits to replay, changes the base beneath them, creates brand-new commits with equivalent changes on the new base, and moves the branch reference to the last replayed commit. Because parents (and usually timestamps) differ, the hashes differ: F1′ merely resembles F1. The originals stay in the object database until unreachable and collected — which is exactly why rebasing public history strands collaborators still pointing at the originals.',
            textBn: 'ধারণাগতভাবে গিট রিপ্লে করার কমিট চিহ্নিত করে, নিচে বেস বদলায়, নতুন বেসে সমতুল্য পরিবর্তনে একদম নতুন কমিট তৈরি করে, এবং ব্রাঞ্চ রেফারেন্স শেষ রিপ্লে কমিটে সরায়। প্যারেন্ট (ও সাধারণত টাইমস্ট্যাম্প) ভিন্ন বলে হ্যাশ ভিন্ন: F1′ শুধু F1-এর মতো। মূলগুলো অবজেক্ট ডাটাবেসে থাকে যতক্ষণ না অপ্রাপ্য ও সংগৃহীত হয় — ঠিক তাই পাবলিক হিস্ট্রি রিবেসে মূলের দিকে থাকা সহকর্মী আটকে যায়।',
          },
          {
            type: 'callout',
            variant: 'danger',
            title: 'The golden rule, grounded',
            titleBn: 'ভিত্তিসহ গোল্ডেন রুল',
            text: 'Never rebase commits others have based work on. You would be minting replacements while their branches still point at originals — divergent histories that only painful merges can reconcile.',
            textBn: 'অন্যরা কাজ ভিত্তি করেছে এমন কমিট কখনো রিবেস করবেন না। মূলের দিকে তাদের ব্রাঞ্চ থাকতে আপনি প্রতিস্থাপন তৈরি করবেন — ডাইভার্জড হিস্ট্রি যা শুধু কষ্টকর মার্জ মেলাতে পারে।',
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-rebase-identity',
      subjectId: 'git',
      difficulty: 'advanced',
      question: 'After git rebase, why do replayed commits have new hashes?',
      questionBn: 'git rebase-এর পর রিপ্লে কমিটের নতুন হ্যাশ কেন হয়?',
      options: [
        { id: 'opt-a', text: 'Git physically moves the original objects', textBn: 'গিট মূল অবজেক্ট শারীরিকভাবে সরায়', isCorrect: false },
        { id: 'opt-b', text: 'New parents/timestamps change the hashed bytes, so new objects are created', textBn: 'নতুন প্যারেন্ট/টাইমস্ট্যাম্প হ্যাশড বাইট বদলায়, তাই নতুন অবজেক্ট তৈরি হয়', isCorrect: true },
        { id: 'opt-c', text: 'Hashes are random and regenerated on every command', textBn: 'হ্যাশ র‍্যান্ডম ও প্রতিটি কমান্ডে পুনর্জন্মায়', isCorrect: false },
        { id: 'opt-d', text: 'Rebase compresses history into a single object', textBn: 'রিবেস হিস্ট্রি এক অবজেক্টে সংকুচিত করে', isCorrect: false },
      ],
      explanation: 'Rebase creates new commit objects on a new base. Different bytes hash differently — hence F1′ is not F1.',
      explanationBn: 'রিবেস নতুন বেসে নতুন কমিট অবজেক্ট তৈরি করে। ভিন্ন বাইট ভিন্ন হ্যাশ করে — তাই F1′ F1 নয়।',
    },
    interviewQuestion: {
      id: 'int-rebase-rewrite',
      subjectId: 'git',
      category: 'Internals',
      difficulty: 'advanced',
      question: 'Does rebase move commits? Defend the precise answer.',
      questionBn: 'রিবেস কি কমিট সরায়? নির্ভুল উত্তর সমর্থন করুন।',
      answer: 'No. Commits are immutable. Rebase replays equivalent changes as new commits on a new base and moves the branch pointer. The originals remain until unreachable and garbage-collected.',
      answerBn: 'না। কমিট অপরিবর্তনীয়। রিবেস সমতুল্য পরিবর্তন নতুন বেসে নতুন কমিটে রিপ্লে করে ও ব্রাঞ্চ পয়েন্টার সরায়। মূলগুলো অপ্রাপ্য ও গারবেজ-কালেক্টেড না হওয়া পর্যন্ত থাকে।',
      keyPoints: ['Immutability forbids moving', 'Replay + pointer slide', 'Golden rule follows directly'],
      keyPointsBn: ['অপরিবর্তনীয়তা সরণ নিষেধ করে', 'রিপ্লে + পয়েন্টার স্লাইড', 'গোল্ডেন রুল সরাসরি আসে'],
    },
    relatedCommands: ['git.rebase', 'git.log'],
    relatedLessons: ['git.fundamentals.branch'],
  },
];
