import { CurriculumLesson } from '@/types/content';

/**
 * Module 2 — Git Objects (git-internals-objects)
 * Blob, tree, commit, tag objects and content addressing.
 */
export const INTERNALS_OBJECTS_LESSONS: CurriculumLesson[] = [
  {
    id: 'git.internals.objects-overview',
    moduleId: 'git-internals-objects',
    slug: 'objects-overview',
    order: 1,
    durationMinutes: 8,
    difficulty: 'intermediate',
    title: 'Git Objects Overview',
    titleBn: 'গিট অবজেক্ট পরিচিতি',
    summary: 'Four object types hold everything Git knows. Learn what each stores and how they link together.',
    summaryBn: 'চার ধরনের অবজেক্টে গিটের জানা সবকিছু থাকে। প্রতিটি কী রাখে ও কীভাবে যুক্ত হয় শিখুন।',
    learningObjectives: [
      'Name the four object types and what each stores',
      'Sketch how commit → tree → blob links form a snapshot',
      'Explain why objects are immutable and addressed by hash',
    ],
    learningObjectivesBn: [
      'চারটি অবজেক্ট টাইপ ও প্রতিটি কী রাখে তার নাম বলা',
      'কমিট → ট্রি → ব্লব লিঙ্কে স্ন্যাপশট গঠনের খসড়া আঁকা',
      'কেন অবজেক্ট অপরিবর্তনীয় ও হ্যাশে ঠিকানাযুক্ত তা ব্যাখ্যা করা',
    ],
    keyTakeaways: [
      'Blob: file content. Tree: directory listing. Commit: snapshot + metadata. Tag: named marker.',
      'Objects never change; new content means a new object with a new ID.',
      'Everything Git shows you is rendered by walking these links.',
    ],
    sections: [
      {
        id: 'sec-four',
        title: 'Four Types, One Database',
        titleBn: 'চার টাইপ, এক ডাটাবেস',
        blocks: [
          {
            type: 'paragraph',
            text: 'Every Git repository is a database of four object types. Blobs hold file bytes. Trees hold directory listings that name blobs and subtrees. Commits hold a tree pointer plus parents, author, and message. Tags hold a pointer to another object plus a name. Immutability is the rule: editing content always creates a new object instead of modifying one.',
            textBn: 'প্রতিটি গিট রিপোজিটরি চার ধরনের অবজেক্টের ডাটাবেস। ব্লবে ফাইল বাইট। ট্রিতে ডিরেক্টরি তালিকা যা ব্লব ও সাবট্রির নাম দেয়। কমিটে ট্রি পয়েন্টার সাথে প্যারেন্ট, লেখক ও বার্তা। ট্যাগে অন্য অবজেক্টের পয়েন্টার সাথে নাম। অপরিবর্তনীয়তা নিয়ম: কন্টেন্ট এডিটে অবজেক্ট বদলায় না, নতুন অবজেক্ট তৈরি হয়।',
          },
          {
            type: 'code',
            code: 'Object Database (.git/objects)\n├── Commit\n├── Tree\n├── Blob\n└── Tag',
            language: 'text',
          },
          {
            type: 'command',
            command: 'git cat-file -p HEAD',
            description: 'Pretty-print whatever object HEAD resolves to.',
            descriptionBn: 'HEAD যে অবজেক্টে পৌঁছায় তা সুন্দরভাবে দেখুন।',
          },
        ],
      },
    ],
    relatedCommands: ['git.show', 'git.log'],
    relatedLessons: ['git.fundamentals.what-is-git'],
  },
  {
    id: 'git.internals.blob-objects',
    moduleId: 'git-internals-objects',
    slug: 'blob-objects',
    order: 2,
    durationMinutes: 8,
    difficulty: 'intermediate',
    title: 'Blob Objects',
    titleBn: 'ব্লব অবজেক্ট',
    summary: 'A blob is pure stored content — no filename, no path. Trees supply names; identical content shares one blob.',
    summaryBn: 'ব্লব হলো খাঁটি সংরক্ষিত কন্টেন্ট — ফাইলনাম নেই, পথ নেই। ট্রি নাম দেয়; একই কন্টেন্ট একটি ব্লব ভাগ করে।',
    learningObjectives: [
      'Define a blob as content without identity metadata',
      'Explain why two identical files share one blob',
      'Trace README.md → tree entry → blob',
    ],
    learningObjectivesBn: [
      'পরিচয় মেটাডেটা ছাড়া কন্টেন্ট হিসেবে ব্লবের সংজ্ঞা দেওয়া',
      'ব্যাখ্যা করা কেন দুটি একই ফাইল একটি ব্লব ভাগ করে',
      'README.md → ট্রি এন্ট্রি → ব্লব অনুসরণ করা',
    ],
    keyTakeaways: [
      'Blob = stored bytes. Filename and path live in tree entries, never in blobs.',
      'Same content anywhere in history resolves to the same blob ID.',
      'Renaming a file without changing it creates zero new blobs.',
    ],
    sections: [
      {
        id: 'sec-blob',
        title: 'Content Without a Name',
        titleBn: 'নাম ছাড়া কন্টেন্ট',
        blocks: [
          {
            type: 'paragraph',
            text: 'A blob stores bytes and nothing else — no filename, no directory, no timestamp. The tree entry that references it carries the name and permissions. This separation is why Git deduplicates effortlessly: copy the same file into ten folders and all ten entries point at one blob.',
            textBn: 'ব্লব বাইট রাখে, আর কিছু নয় — ফাইলনাম নেই, ডিরেক্টরি নেই, সময় নেই। যে ট্রি এন্ট্রি রেফারেন্স করে তাতে নাম ও অনুমতি থাকে। এই বিচ্ছেদেই গিট অনায়াসে ডুপ্লিকেট কমায়: একই ফাইল দশ ফোল্ডারে কপি করুন, দশটি এন্ট্রি একটি ব্লবের দিকে যাবে।',
          },
          {
            type: 'code',
            code: 'README.md\n   ↓\nTree entry ("README.md")\n   ↓\nBlob B1 (bytes only)',
            language: 'text',
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-blob-content',
      subjectId: 'git',
      difficulty: 'intermediate',
      question: 'What does a Git blob object store?',
      questionBn: 'গিট ব্লব অবজেক্ট কী সংরক্ষণ করে?',
      options: [
        { id: 'opt-a', text: 'File content bytes only, with no filename or path', textBn: 'শুধু ফাইল কন্টেন্ট বাইট, ফাইলনাম বা পথ ছাড়া', isCorrect: true },
        { id: 'opt-b', text: 'The filename, path, and permissions of a file', textBn: 'ফাইলের নাম, পথ ও অনুমতি', isCorrect: false },
        { id: 'opt-c', text: 'The full commit history of a file', textBn: 'ফাইলের পূর্ণ কমিট হিস্ট্রি', isCorrect: false },
        { id: 'opt-d', text: 'A compressed copy of the working directory', textBn: 'ওয়ার্কিং ডিরেক্টরির সংকুচিত কপি', isCorrect: false },
      ],
      explanation: 'Names and hierarchy live in tree entries. The blob holds raw bytes, so identical content anywhere shares one blob.',
      explanationBn: 'নাম ও শ্রেণিবিন্যাস ট্রি এন্ট্রিতে থাকে। ব্লবে কাঁচা বাইট, তাই যেকোনো জায়গার একই কন্টেন্ট একটি ব্লব ভাগ করে।',
    },
    relatedCommands: ['git.show', 'git.diff'],
    relatedLessons: ['git.fundamentals.what-is-git'],
  },
  {
    id: 'git.internals.tree-objects',
    moduleId: 'git-internals-objects',
    slug: 'tree-objects',
    order: 3,
    durationMinutes: 10,
    difficulty: 'intermediate',
    title: 'Tree Objects',
    titleBn: 'ট্রি অবজেক্ট',
    summary: 'Trees record directory structure: names pointing at blobs and subtrees. Commits point at exactly one root tree.',
    summaryBn: 'ট্রি ডিরেক্টরি কাঠামো রেকর্ড করে: ব্লব ও সাবট্রির দিকে নাম। কমিট ঠিক একটি রুট ট্রির দিকে যায়।',
    learningObjectives: [
      'Read a tree as a name → object mapping',
      'Explain nested trees for subdirectories',
      'Connect a commit to its snapshot via its tree',
    ],
    learningObjectivesBn: [
      'ট্রিকে নাম → অবজেক্ট ম্যাপিং হিসেবে পড়া',
      'সাবডিরেক্টরির নেস্টেড ট্রি ব্যাখ্যা করা',
      'ট্রির মাধ্যমে কমিটকে স্ন্যাপশটে যুক্ত করা',
    ],
    keyTakeaways: [
      'A tree lists names with the blob/tree each name points to.',
      'Subdirectories are nested tree objects, composable to any depth.',
      'git ls-tree reveals any snapshot’s structure without checking it out.',
    ],
    sections: [
      {
        id: 'sec-tree',
        title: 'Directories as Data',
        titleBn: 'ডেটা হিসেবে ডিরেক্টরি',
        blocks: [
          {
            type: 'code',
            code: 'Tree T3 (root)\n├── README.md → Blob B2\n├── package.json → Blob B3\n└── src → Tree T2\n      ├── main.js → Blob B4\n      └── utils.js → Blob B5',
            language: 'text',
          },
          {
            type: 'paragraph',
            text: 'Git needs trees because blobs deliberately know nothing about names. The tree supplies the missing half: which names exist, what type each points to, and the exact object IDs. A commit’s snapshot is simply its root tree plus everything reachable beneath it.',
            textBn: 'গিটের ট্রি দরকার কারণ ব্লব ইচ্ছাকৃতভাবে নাম জানে না। ট্রি অনুপস্থিত অর্ধেক দেয়: কোন নাম আছে, প্রতিটি কী টাইপের দিকে যায়, এবং নির্ভুল অবজেক্ট ID। কমিটের স্ন্যাপশট হলো এর রুট ট্রি সাথে নিচে পৌঁছানো সবকিছু।',
          },
          {
            type: 'command',
            command: 'git ls-tree HEAD',
            description: 'List the root tree of the current commit without touching files.',
            descriptionBn: 'ফাইলে হাত না দিয়ে বর্তমান কমিটের রুট ট্রি তালিকা করুন।',
          },
        ],
      },
    ],
    relatedCommands: ['git.show', 'git.log'],
    relatedLessons: ['git.fundamentals.what-is-git', 'git.fundamentals.commit'],
  },
  {
    id: 'git.internals.commit-objects',
    moduleId: 'git-internals-objects',
    slug: 'commit-objects',
    order: 4,
    durationMinutes: 12,
    difficulty: 'advanced',
    title: 'Commit Objects',
    titleBn: 'কমিট অবজেক্ট',
    summary: 'A commit binds one tree, zero or more parents, author, committer, and message into a single immutable record.',
    summaryBn: 'কমিট একটি ট্রি, শূন্য বা বেশি প্যারেন্ট, লেখক, কমিটার ও বার্তাকে এক অপরিবর্তনীয় রেকর্ডে বাঁধে।',
    learningObjectives: [
      'List the five fields of a commit object',
      'Explain author vs committer',
      'Explain merge commits as two-parent records',
    ],
    learningObjectivesBn: [
      'কমিট অবজেক্টের পাঁচটি ফিল্ড তালিকা করা',
      'লেখক বনাম কমিটার ব্যাখ্যা করা',
      'মার্জ কমিটকে দুই-প্যারেন্ট রেকর্ড হিসেবে ব্যাখ্যা করা',
    ],
    keyTakeaways: [
      'Commit = tree + parents + author + committer + message.',
      'Author wrote the change; committer recorded it — often the same person, not always.',
      'A merge commit is ordinary except for having two (or more) parents.',
    ],
    sections: [
      {
        id: 'sec-anatomy',
        title: 'Anatomy of a Commit',
        titleBn: 'কমিটের গঠন',
        blocks: [
          {
            type: 'code',
            code: 'Commit C3\n├── parent → C2\n├── author (who wrote it)\n├── committer (who recorded it)\n├── message\n└── tree → T3',
            language: 'text',
          },
          {
            type: 'paragraph',
            text: 'Notice what is absent: no diffs, no branch names, no notion of "current". A commit is a frozen fact — this tree, these parents, these people, this message. Branches and HEAD are separate pointers that move across these facts over time.',
            textBn: 'লক্ষ্য করুন কী নেই: ডিফ নেই, ব্রাঞ্চ নাম নেই, "বর্তমান" ধারণা নেই। কমিট হিমায়িত তথ্য — এই ট্রি, এই প্যারেন্ট, এই মানুষ, এই বার্তা। ব্রাঞ্চ ও HEAD আলাদা পয়েন্টার যা সময়ে এই তথ্যের ওপর দিয়ে সরে।',
          },
        ],
      },
      {
        id: 'sec-merge',
        title: 'Merge Commits Are Ordinary (With Two Parents)',
        titleBn: 'মার্জ কমিট সাধারণ (দুই প্যারেন্টসহ)',
        blocks: [
          {
            type: 'code',
            code: 'Merge Commit M\n├── parent → C3 (main)\n├── parent → F2 (feature)\n└── tree → TM (combined snapshot)',
            language: 'text',
          },
          {
            type: 'paragraph',
            text: 'A merge commit differs in exactly one way: it records two parents. Its tree is the combined snapshot someone (or Git, automatically) resolved. History viewers follow both parents, which is why merges draw the converging lines you see in graphs.',
            textBn: 'মার্জ কমিট ঠিক একভাবে আলাদা: দুটি প্যারেন্ট রেকর্ড করে। এর ট্রি হলো সম্মিলিত স্ন্যাপশট যা কেউ (বা গিট, স্বয়ংক্রিয়ভাবে) সমাধান করেছে। হিস্ট্রি দর্শক উভয় প্যারেন্ট অনুসরণ করে, তাই গ্রাফে একত্রিত রেখা দেখা যায়।',
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-merge-parents',
      subjectId: 'git',
      difficulty: 'advanced',
      question: 'What structurally distinguishes a merge commit from a regular commit?',
      questionBn: 'গাঠনিকভাবে মার্জ কমিটকে সাধারণ কমিট থেকে কী আলাদা করে?',
      options: [
        { id: 'opt-a', text: 'It stores two complete file copies', textBn: 'এটি দুটি পূর্ণ ফাইল কপি রাখে', isCorrect: false },
        { id: 'opt-b', text: 'It records two (or more) parent commits', textBn: 'এটি দুটি (বা বেশি) প্যারেন্ট কমিট রেকর্ড করে', isCorrect: true },
        { id: 'opt-c', text: 'It cannot have a tree snapshot', textBn: 'এতে ট্রি স্ন্যাপশট থাকতে পারে না', isCorrect: false },
        { id: 'opt-d', text: 'It is stored outside the object database', textBn: 'এটি অবজেক্ট ডাটাবেসের বাইরে থাকে', isCorrect: false },
      ],
      explanation: 'Merge commits are normal commits with an extra parent. Their tree holds the resolved combined snapshot.',
      explanationBn: 'মার্জ কমিট অতিরিক্ত প্যারেন্টসহ সাধারণ কমিট। এর ট্রিতে সমাধানকৃত সম্মিলিত স্ন্যাপশট থাকে।',
    },
    interviewQuestion: {
      id: 'int-commit-anatomy',
      subjectId: 'git',
      category: 'Internals',
      difficulty: 'advanced',
      question: 'What does a commit object contain, and what does a merge commit add?',
      questionBn: 'কমিট অবজেক্টে কী থাকে, এবং মার্জ কমিট কী যোগ করে?',
      answer: 'Tree pointer, parent list, author, committer, message. A merge commit adds a second parent; everything else follows the same rules.',
      answerBn: 'ট্রি পয়েন্টার, প্যারেন্ট তালিকা, লেখক, কমিটার, বার্তা। মার্জ কমিট দ্বিতীয় প্যারেন্ট যোগ করে; বাকি সব একই নিয়মে চলে।',
      keyPoints: ['Tree + parents + author/committer + message', 'Merge = extra parent', 'No branch info inside commits'],
      keyPointsBn: ['ট্রি + প্যারেন্ট + লেখক/কমিটার + বার্তা', 'মার্জ = অতিরিক্ত প্যারেন্ট', 'কমিটের ভেতরে ব্রাঞ্চ তথ্য নেই'],
    },
    relatedCommands: ['git.commit', 'git.show', 'git.log'],
    relatedLessons: ['git.fundamentals.commit'],
  },
  {
    id: 'git.internals.annotated-tags',
    moduleId: 'git-internals-objects',
    slug: 'annotated-tags',
    order: 5,
    durationMinutes: 8,
    difficulty: 'intermediate',
    title: 'Annotated Tag Objects',
    titleBn: 'অ্যানোটেটেড ট্যাগ অবজেক্ট',
    summary: 'An annotated tag is a real object: a name, message, tagger, and pointer — checksummed like everything else.',
    summaryBn: 'অ্যানোটেটেড ট্যাগ আসল অবজেক্ট: নাম, বার্তা, ট্যাগার ও পয়েন্টার — বাকি সবের মতো চেকসামযুক্ত।',
    learningObjectives: [
      'Describe the fields of an annotated tag object',
      'Explain why annotated tags are checksummed and verifiable',
      'Know when an annotated tag is worth the extra object',
    ],
    learningObjectivesBn: [
      'অ্যানোটেটেড ট্যাগ অবজেক্টের ফিল্ড বর্ণনা করা',
      'ব্যাখ্যা করা কেন অ্যানোটেটেড ট্যাগ চেকসামযুক্ত ও যাচাইযোগ্য',
      'জানা কখন অ্যানোটেটেড ট্যাগ অতিরিক্ত অবজেক্টের যোগ্য',
    ],
    keyTakeaways: [
      'Annotated tags store tagger, date, message, and target — as checksummed data.',
      'Use them for releases and milestones you may need to verify later.',
      'Lightweight tags (lesson: references) store nothing at all.',
    ],
    sections: [
      {
        id: 'sec-annotated',
        title: 'Tags With Substance',
        titleBn: 'বস্তুসহ ট্যাগ',
        blocks: [
          {
            type: 'paragraph',
            text: 'An annotated tag is a fourth object type in its own right: it names a target object, records who tagged it and when, and carries a message — all covered by its own content hash. That is why release tags can be verified and signed, while lightweight tags cannot.',
            textBn: 'অ্যানোটেটেড ট্যাগ নিজ অধিকারে চতুর্থ অবজেক্ট টাইপ: লক্ষ্য অবজেক্টের নাম দেয়, কে কখন ট্যাগ করেছে রেকর্ড করে, বার্তা বহন করে — সব নিজের কন্টেন্ট হ্যাশে আচ্ছাদিত। তাই রিলিজ ট্যাগ যাচাই ও স্বাক্ষর করা যায়, হালকা ট্যাগ যায় না।',
          },
          {
            type: 'code',
            code: 'Tag v1.0 (annotated object)\n├── target → C10\n├── tagger + date\n└── message ("Release 1.0")',
            language: 'text',
          },
        ],
      },
    ],
    relatedCommands: ['git.log'],
    relatedLessons: ['git.fundamentals.commit'],
  },
  {
    id: 'git.internals.object-ids',
    moduleId: 'git-internals-objects',
    slug: 'object-ids',
    order: 6,
    durationMinutes: 10,
    difficulty: 'advanced',
    title: 'Object IDs and Content Addressing',
    titleBn: 'অবজেক্ট ID ও কন্টেন্ট অ্যাড্রেসিং',
    summary: 'An object’s ID is a hash of its type, size, and bytes. SHA-1 is everywhere; SHA-256 exists for the future.',
    summaryBn: 'অবজেক্ট ID হলো এর টাইপ, আকার ও বাইটের হ্যাশ। SHA-1 সর্বত্র; ভবিষ্যতের জন্য SHA-256 আছে।',
    learningObjectives: [
      'Explain what bytes feed the object hash (type + size + content)',
      'Correct the myth that Git hashes filenames',
      'Describe SHA-1 vs SHA-256 status without cryptography deep-dives',
    ],
    learningObjectivesBn: [
      'ব্যাখ্যা করা কোন বাইট অবজেক্ট হ্যাশে যায় (টাইপ + আকার + কন্টেন্ট)',
      '"গিট ফাইলনাম হ্যাশ করে" ভ্রান্তি সংশোধন করা',
      'ক্রিপ্টোগ্রাফি গভীরে না গিয়ে SHA-1 বনাম SHA-256 অবস্থা বর্ণনা করা',
    ],
    keyTakeaways: [
      'ID = hash(type + size + NUL + content). Filenames never enter the hash.',
      'Same bytes → same ID, anywhere, forever. Different bytes → different ID.',
      'SHA-1 remains the common case; SHA-256 repositories exist for stronger guarantees.',
    ],
    sections: [
      {
        id: 'sec-hash',
        title: 'What Gets Hashed',
        titleBn: 'কী হ্যাশ হয়',
        blocks: [
          {
            type: 'paragraph',
            text: 'Git hashes a header (object type, size, null byte) plus the raw content — never the filename, which lives in tree entries outside the blob. Change one byte and you get a different object with a different ID; keep bytes identical and the ID matches across every repository on earth.',
            textBn: 'গিট হ্যাশ করে হেডার (অবজেক্ট টাইপ, আকার, নাল বাইট) সাথে কাঁচা কন্টেন্ট — ফাইলনাম কখনো নয়, তা ব্লবের বাইরে ট্রি এন্ট্রিতে থাকে। এক বাইট বদলান, ভিন্ন ID-র ভিন্ন অবজেক্ট পাবেন; বাইট এক রাখুন, পৃথিবীর প্রতিটি রিপোজিটরিতে ID মিলবে।',
          },
          {
            type: 'callout',
            variant: 'note',
            title: 'SHA-1 and SHA-256, briefly',
            titleBn: 'সংক্ষেপে SHA-1 ও SHA-256',
            text: 'Classic repositories use SHA-1 (40 hex characters); modern Git also supports SHA-256 repositories (64 hex characters) for stronger collision resistance. You will overwhelmingly encounter SHA-1 hashes — often abbreviated to 7 characters — and the mental model is identical either way.',
            textBn: 'ক্লাসিক রিপোজিটরি SHA-1 ব্যবহার করে (৪০ হেক্স অক্ষর); আধুনিক গিট শক্তিশালী সংঘর্ষ-প্রতিরোধে SHA-256 রিপোজিটরিও সমর্থন করে (৬৪ হেক্স)। বেশিরভাগ SHA-1 হ্যাশ দেখবেন — প্রায়ই ৭ অক্ষরে সংক্ষিপ্ত — এবং মেন্টাল মডেল উভয় ক্ষেত্রে এক।',
          },
        ],
      },
    ],
    quiz: {
      id: 'quiz-content-addressing',
      subjectId: 'git',
      difficulty: 'advanced',
      question: 'What determines a Git object’s ID?',
      questionBn: 'গিট অবজেক্টের ID কী নির্ধারণ করে?',
      options: [
        { id: 'opt-a', text: 'The filename and its folder path', textBn: 'ফাইলনাম ও ফোল্ডার পথ', isCorrect: false },
        { id: 'opt-b', text: 'A hash of object type, size, and content bytes', textBn: 'অবজেক্ট টাইপ, আকার ও কন্টেন্ট বাইটের হ্যাশ', isCorrect: true },
        { id: 'opt-c', text: 'The commit message and author name', textBn: 'কমিট বার্তা ও লেখকের নাম', isCorrect: false },
        { id: 'opt-d', text: 'A random UUID assigned at creation', textBn: 'তৈরির সময় দেওয়া র‍্যান্ডম UUID', isCorrect: false },
      ],
      explanation: 'Type + size + content bytes are hashed. Filenames live in trees, outside the hashed blob content.',
      explanationBn: 'টাইপ + আকার + কন্টেন্ট বাইট হ্যাশ হয়। ফাইলনাম ট্রিতে থাকে, হ্যাশড ব্লব কন্টেন্টের বাইরে।',
    },
    relatedCommands: ['git.show'],
    relatedLessons: ['git.fundamentals.what-is-git'],
  },
];
