/**
 * Git Advanced learning path — data only, no UI.
 * Connects internals lessons to the Explorer, labs, cookbook, and interview.
 */
import { LearningPath } from '@/types/learningPath';
import { buildSteps } from './buildPath';

const PATH_ID = 'git-advanced';

const STEPS = buildSteps(PATH_ID, [
  // ---------- Git Internals: objects ----------
  { slug: 'objects-overview', type: 'lesson', contentId: 'git.internals.objects-overview',
    titleEn: 'Git Objects Overview', titleBn: 'গিট অবজেক্ট পরিচিতি',
    descEn: 'Blobs, trees, commits, tags — the four building blocks.', descBn: 'ব্লব, ট্রি, কমিট, ট্যাগ — চার নির্মাণ খণ্ড।',
    whyEn: 'Every advanced answer starts at the object model.', whyBn: 'প্রতিটি advanced উত্তর অবজেক্ট মডেলে শুরু।',
    minutes: 12, tags: ['internals'] },
  { slug: 'blob-objects', type: 'lesson', contentId: 'git.internals.blob-objects',
    titleEn: 'Blob Objects', titleBn: 'ব্লব অবজেক্ট',
    descEn: 'Content without names — files stripped to bytes.', descBn: 'নামহীন কনটেন্ট — বাইটে ছাঁটা ফাইল।',
    whyEn: 'Blobs explain why renames are free and copies are cheap.', whyBn: 'ব্লব ব্যাখ্যা করে কেন রিনেম ফ্রি ও কপি সস্তা।',
    minutes: 10, prerequisites: ['objects-overview'], tags: ['internals'] },
  { slug: 'tree-objects', type: 'lesson', contentId: 'git.internals.tree-objects',
    titleEn: 'Tree Objects', titleBn: 'ট্রি অবজেক্ট',
    descEn: 'Where filenames and structure actually live.', descBn: 'ফাইলনাম ও কাঠামো আসলে কোথায় থাকে।',
    whyEn: 'Trees are the missing link between blobs and commits.', whyBn: 'ট্রি ব্লব ও কমিটের হারানো যোগসূত্র।',
    minutes: 10, prerequisites: ['blob-objects'], tags: ['internals'] },
  { slug: 'commit-objects', type: 'lesson', contentId: 'git.internals.commit-objects',
    titleEn: 'Commit Objects', titleBn: 'কমিট অবজেক্ট',
    descEn: 'Tree pointer plus metadata — the snapshot, dissected.', descBn: 'ট্রি পয়েন্টার ও মেটাডেটা — স্ন্যাপশট ব্যবচ্ছেদ।',
    whyEn: 'Reading a commit object ends hash mysticism.', whyBn: 'কমিট অবজেক্ট পড়লে হ্যাশ রহস্য শেষ।',
    minutes: 10, prerequisites: ['tree-objects'], tags: ['internals'] },
  { slug: 'object-ids', type: 'lesson', contentId: 'git.internals.object-ids',
    titleEn: 'Object IDs & Content Addressing', titleBn: 'অবজেক্ট ID ও কনটেন্ট অ্যাড্রেসিং',
    descEn: 'Why identical content can never disagree.', descBn: 'কেন অভিন্ন কনটেন্ট কখনো দ্বিমত করে না।',
    whyEn: 'Content addressing is Git’s integrity guarantee.', whyBn: 'কনটেন্ট অ্যাড্রেসিং গিটের অখণ্ডতা গ্যারান্টি।',
    minutes: 10, prerequisites: ['commit-objects'], tags: ['internals'] },
  { slug: 'object-database', type: 'lesson', contentId: 'git.internals.object-database',
    titleEn: 'The Object Database', titleBn: 'অবজেক্ট ডাটাবেজ',
    descEn: 'Loose objects today, the store they all share.', descBn: 'আজ লুজ অবজেক্ট, সবার শেয়ার্ড ভাণ্ডার।',
    whyEn: 'The store explains fetch, push, and clone costs.', whyBn: 'ভাণ্ডার fetch, push ও clone খরচ ব্যাখ্যা করে।',
    minutes: 10, prerequisites: ['object-ids'], tags: ['internals'] },
  { slug: 'packfiles', type: 'lesson', contentId: 'git.internals.packfiles',
    titleEn: 'Packfiles', titleBn: 'প্যাকফাইল',
    descEn: 'How Git stays small while remembering everything.', descBn: 'সব মনে রেখে গিট কীভাবে ছোট থাকে।',
    whyEn: 'Packfiles answer every “is Git efficient?” interview probe.', whyBn: 'প্যাকফাইল “গিট কি দক্ষ?” ইন্টারভিউ প্রশ্নের উত্তর।',
    minutes: 10, prerequisites: ['object-database'], tags: ['internals'] },
  { slug: 'garbage-collection', type: 'lesson', contentId: 'git.internals.garbage-collection',
    titleEn: 'Garbage Collection', titleBn: 'গারবেজ কালেকশন',
    descEn: 'When Git finally lets go — and why it waits.', descBn: 'গিট কখন ছাড়ে — ও কেন অপেক্ষা করে।',
    whyEn: 'GC timing is why “deleted” work stays recoverable.', whyBn: 'GC সময়ই “মোছা” কাজ উদ্ধারযোগ্য রাখে।',
    minutes: 10, prerequisites: ['packfiles'], tags: ['internals'] },
  { slug: 'unreachable-expiry', type: 'lesson', contentId: 'git.internals.unreachable-objects-expiry',
    titleEn: 'Unreachable Objects & Expiry', titleBn: 'অপ্রাপ্য অবজেক্ট ও মেয়াদ',
    descEn: 'The honest limits of every recovery story.', descBn: 'প্রতিটি উদ্ধার গল্পের সৎ সীমা।',
    whyEn: 'Expiry honesty separates seniors in recovery interviews.', whyBn: 'মেয়াদে সততা রিকভারি ইন্টারভিউতে সিনিয়র চেনায়।',
    minutes: 10, prerequisites: ['garbage-collection'], tags: ['internals'] },
  // ---------- References ----------
  { slug: 'what-is-reference', type: 'lesson', contentId: 'git.internals.what-is-a-reference',
    titleEn: 'What Is a Reference?', titleBn: 'রেফারেন্স কী?',
    descEn: 'Names that point at hashes — branches, tags, HEAD.', descBn: 'হ্যাশে দেখানো নাম — ব্রাঞ্চ, ট্যাগ, HEAD।',
    whyEn: 'References turn scary pointer talk into plain names.', whyBn: 'রেফারেন্স পয়েন্টার-ভয় সাধারণ নামে বদলায়।',
    minutes: 10, prerequisites: ['object-ids'], tags: ['internals'] },
  { slug: 'branch-references', type: 'lesson', contentId: 'git.internals.branch-references',
    titleEn: 'Branch References', titleBn: 'ব্রাঞ্চ রেফারেন্স',
    descEn: 'Branches as files that move — nothing more.', descBn: 'সরন্ত ফাইল হিসেবে ব্রাঞ্চ — এর বেশি কিছু নয়।',
    whyEn: 'This is the real answer to “what is a branch?”.', whyBn: '“ব্রাঞ্চ কী?”-এর আসল উত্তর এটাই।',
    minutes: 10, prerequisites: ['what-is-reference'], tags: ['internals'] },
  { slug: 'head-deep-dive', type: 'lesson', contentId: 'git.internals.head-deep-dive',
    titleEn: 'HEAD In Depth', titleBn: 'HEAD গভীরে',
    descEn: 'Symbolic references and exactly what checkout writes.', descBn: 'সিম্বলিক রেফারেন্স ও চেকআউট ঠিক কী লেখে।',
    whyEn: 'HEAD mechanics explain detached states completely.', whyBn: 'HEAD কৌশল ডিটাচড অবস্থা সম্পূর্ণ ব্যাখ্যা করে।',
    minutes: 10, prerequisites: ['branch-references'], tags: ['internals'] },
  { slug: 'remote-tracking', type: 'lesson', contentId: 'git.internals.remote-tracking-references',
    titleEn: 'Remote-Tracking References', titleBn: 'রিমোট-ট্র্যাকিং রেফারেন্স',
    descEn: 'origin/main as a local photograph, not a live feed.', descBn: 'লাইভ ফিড নয়, লোকাল ছবি হিসেবে origin/main।',
    whyEn: 'The photograph model ends fetch confusion forever.', whyBn: 'ছবি মডেল fetch বিভ্রান্তি চিরতরে শেষ করে।',
    minutes: 10, prerequisites: ['head-deep-dive'], tags: ['internals'] },
  { slug: 'reflog-internals', type: 'lesson', contentId: 'git.internals.reflog',
    titleEn: 'Reflog: The Safety Net', titleBn: 'রিফ্লগ: নিরাপত্তা জাল',
    descEn: 'Where every position used to be — your undo log.', descBn: 'প্রতিটি অবস্থান কোথায় ছিল — আপনার আনডু লগ।',
    whyEn: 'Reflog internals justify total recovery confidence.', whyBn: 'রিফ্লগ ইন্টারনালস পূর্ণ উদ্ধার আত্মবিশ্বাস দেয়।',
    minutes: 10, prerequisites: ['remote-tracking'], tags: ['internals'] },
  // ---------- History as a graph ----------
  { slug: 'commit-graphs', type: 'lesson', contentId: 'git.internals.commit-graphs',
    titleEn: 'Commit Graphs', titleBn: 'কমিট গ্রাফ',
    descEn: 'Reading history as a map of forks and joins.', descBn: 'ফোর্ক ও জোড়ার মানচিত্রে হিস্ট্রি পড়া।',
    whyEn: 'Graph reading is the advanced daily skill.', whyBn: 'গ্রাফ পড়া advanced দৈনন্দিন দক্ষতা।',
    minutes: 10, prerequisites: ['commit-objects'], tags: ['history'] },
  { slug: 'reachability', type: 'lesson', contentId: 'git.internals.reachability',
    titleEn: 'Reachability', titleBn: 'রিচেবিলিটি',
    descEn: 'Which commits survive — decided by parent links.', descBn: 'কোন কমিট বাঁচে — প্যারেন্ট লিঙ্কে নির্ধারিত।',
    whyEn: 'Reachability predicts GC, fetch, and clone behavior.', whyBn: 'রিচেবিলিটি GC, fetch ও clone আচরণ পূর্বাভাস দেয়।',
    minutes: 10, prerequisites: ['commit-graphs'], tags: ['history'] },
  { slug: 'dag-structure', type: 'lesson', contentId: 'git.internals.dag-structure',
    titleEn: 'DAG Structure', titleBn: 'DAG কাঠামো',
    descEn: 'Why history is a directed acyclic graph — and why it matters.', descBn: 'হিস্ট্রি কেন DAG — ও কেন গুরুত্বপূর্ণ।',
    whyEn: 'DAG vocabulary unlocks senior-level conversations.', whyBn: 'DAG শব্দভাণ্ডার সিনিয়র আলোচনা খোলে।',
    minutes: 10, prerequisites: ['reachability'], tags: ['history'] },
  { slug: 'rebase-rewrites-history', type: 'lesson', contentId: 'git.internals.rebase-rewrites-history',
    titleEn: 'Why Rebase Rewrites History', titleBn: 'রিবেস কেন হিস্ট্রি বদলায়',
    descEn: 'New parents, new hashes, new identities — proved.', descBn: 'নতুন প্যারেন্ট, নতুন হ্যাশ, নতুন পরিচয় — প্রমাণিত।',
    whyEn: 'The internals proof behind the golden rule.', whyBn: 'গোল্ডেন রুলের পেছনে ইন্টারনালস প্রমাণ।',
    minutes: 10, prerequisites: ['dag-structure'], tags: ['history', 'rebasing'] },
  // ---------- Explorer + labs ----------
  { slug: 'internals-explorer', type: 'explorer', contentId: 'git.internals.explorer',
    route: '/git/internals',
    titleEn: 'Explore: Git Internals Explorer', titleBn: 'ঘুরুন: গিট ইন্টারনালস এক্সপ্লোরার',
    descEn: 'Touch objects, references, and the DAG interactively.', descBn: 'অবজেক্ট, রেফারেন্স ও DAG হাতে ছুঁয়ে দেখুন।',
    whyEn: 'Interactive pointers beat ten diagrams.', whyBn: 'ইন্টার‌্যাক্টিভ পয়েন্টার দশ ডায়াগ্রামের চেয়ে ভালো।',
    minutes: 20, prerequisites: ['dag-structure', 'reflog-internals'], tags: ['internals', 'interactive'] },
  { slug: 'follow-head', type: 'practice', contentId: 'git.practice.command-follow-head',
    titleEn: 'Practice: Follow HEAD', titleBn: 'অনুশীলন: HEAD অনুসরণ',
    descEn: 'Trace the current position through pointers.', descBn: 'পয়েন্টারে বর্তমান অবস্থান ট্রেস করুন।',
    whyEn: 'Tracing turns theory into navigation skill.', whyBn: 'ট্রেসিং তত্ত্বকে নেভিগেশন দক্ষতায় বদলায়।',
    minutes: 12, prerequisites: ['internals-explorer'], tags: ['internals', 'hands-on'] },
  { slug: 'interpret-graph', type: 'practice', contentId: 'git.practice.command-interpret-graph',
    titleEn: 'Practice: Interpret a Commit Graph', titleBn: 'অনুশীলন: কমিট গ্রাফ পড়া',
    descEn: 'Answer ancestry questions from the graph alone.', descBn: 'শুধু গ্রাফে বংশ প্রশ্নের উত্তর দিন।',
    whyEn: 'Graph fluency is tested in every advanced interview.', whyBn: 'প্রতিটি advanced ইন্টারভিউতে গ্রাফ দক্ষতা যাচাই হয়।',
    minutes: 12, prerequisites: ['follow-head'], tags: ['internals', 'hands-on'] },
  // ---------- Advanced recovery & collaboration ----------
  { slug: 'troubleshoot-recover', type: 'troubleshooting', contentId: 'git.troubleshooting.recover-commit',
    titleEn: 'Cookbook: Recover a Lost Commit', titleBn: 'কুকবুক: হারানো কমিট উদ্ধার',
    descEn: 'The full recovery recipe with honest expiry notes.', descBn: 'সৎ মেয়াদ নোটসহ সম্পূর্ণ উদ্ধার রেসিপি।',
    whyEn: 'Recovery with expiry honesty is the senior answer.', whyBn: 'মেয়াদ-সততায় উদ্ধার সিনিয়র উত্তর।',
    minutes: 12, prerequisites: ['unreachable-expiry', 'reflog-internals'], tags: ['recovery'] },
  { slug: 'troubleshoot-secret', type: 'troubleshooting', contentId: 'git.troubleshooting.committed-secret',
    titleEn: 'Cookbook: Committed Secret Response', titleBn: 'কুকবুক: কমিটেড সিক্রেট প্রতিক্রিয়া',
    descEn: 'Revoke first, purge second, verify third.', descBn: 'আগে বাতিল, তারপর পরিষ্কার, শেষে যাচাই।',
    whyEn: 'Incident order matters more than any single command.', whyBn: 'একক কমান্ডের চেয়ে ঘটনা-ক্রম গুরুত্বপূর্ণ।',
    minutes: 12, prerequisites: ['troubleshoot-recover'], tags: ['recovery', 'security'] },
  { slug: 'troubleshoot-force', type: 'troubleshooting', contentId: 'git.troubleshooting.force-push',
    titleEn: 'Cookbook: Force Push & Safer Ways', titleBn: 'কুকবুক: ফোর্স পুশ ও নিরাপদ পথ',
    descEn: 'What force destroys and when lease saves you.', descBn: 'ফোর্স কী ধ্বংস করে ও কখন lease বাঁচায়।',
    whyEn: 'Shared-history judgment is the advanced collaboration test.', whyBn: 'শেয়ার্ড-হিস্ট্রি বিচার advanced সহযোগিতা পরীক্ষা।',
    minutes: 12, prerequisites: ['dag-structure'], tags: ['collaboration', 'recovery'] },
  { slug: 'interview-internals', type: 'interview', contentId: 'interview:internals',
    titleEn: 'Interview: Git Internals', titleBn: 'ইন্টারভিউ: গিট ইন্টারনালস',
    descEn: 'Explain objects, DAGs, and GC like a senior.', descBn: 'অবজেক্ট, DAG ও GC সিনিয়রের মতো ব্যাখ্যা করুন।',
    whyEn: 'Internals answers are the advanced interview differentiator.', whyBn: 'ইন্টারনালস উত্তর advanced ইন্টারভিউ পার্থক্যকারী।',
    minutes: 20, prerequisites: ['interpret-graph', 'unreachable-expiry'], tags: ['interview'] },
  { slug: 'interview-scenarios', type: 'interview', contentId: 'interview:scenarios',
    titleEn: 'Interview: Mixed Scenarios', titleBn: 'ইন্টারভিউ: মিশ্র দৃশ্যপট',
    descEn: 'Reason through secrets, divergence, and stale state.', descBn: 'সিক্রেট, ডাইভারজেন্স ও বাসি অবস্থায় যুক্তি দিন।',
    whyEn: 'Scenario reasoning is what senior panels actually probe.', whyBn: 'দৃশ্যপট যুক্তি সিনিয়র প্যানেল আসলে যাচাই করে।',
    minutes: 15, prerequisites: ['troubleshoot-secret', 'troubleshoot-force'], tags: ['interview'] },
  { slug: 'skill-assessment', type: 'assessment', contentId: 'git.assessment.skill',
    titleEn: 'Checkpoint: Retake the Skill Assessment', titleBn: 'যাচাই: দক্ষতা মূল্যায়ন পুনরায়',
    descEn: 'Measure how far the advanced path moved your six areas.', descBn: 'advanced পাথ ছয় ক্ষেত্রে কত এগোল মাপুন।',
    whyEn: 'A second estimate proves growth — or points at review.', whyBn: 'দ্বিতীয় অনুমান প্রবৃদ্ধি প্রমাণ করে — বা পর্যালোচনা দেখায়।',
    minutes: 20, prerequisites: ['interview-scenarios'], tags: ['assessment', 'checkpoint'] },
]);

export const GIT_ADVANCED_PATH: LearningPath = {
  id: PATH_ID,
  subjectId: 'git',
  difficulty: 'advanced',
  title: { en: 'Git Advanced', bn: 'গিট অ্যাডভান্সড' },
  description: {
    en: 'Objects, references, DAGs, and storage — plus advanced recovery and collaboration judgment. The path to explaining Git, not just using it.',
    bn: 'অবজেক্ট, রেফারেন্স, DAG ও স্টোরেজ — সাথে advanced উদ্ধার ও সহযোগিতা বিচার। গিট শুধু ব্যবহার নয়, ব্যাখ্যার পথ।',
  },
  outcomes: [
    { en: 'Explain the object model, references, DAGs, packfiles, and GC.', bn: 'অবজেক্ট মডেল, রেফারেন্স, DAG, প্যাকফাইল ও GC ব্যাখ্যা করতে পারবেন।' },
    { en: 'Recover lost work and handle secrets/force-push with judgment.', bn: 'বিচারে হারানো কাজ উদ্ধার ও সিক্রেট/ফোর্স-পুশ সামলাতে পারবেন।' },
    { en: 'Navigate the Internals Explorer and answer senior interview questions.', bn: 'ইন্টারনালস এক্সপ্লোরার চালিয়ে সিনিয়র ইন্টারভিউ প্রশ্নের উত্তর দিতে পারবেন।' },
  ],
  prerequisites: ['git-intermediate'],
  icon: 'Boxes',
  order: 3,
  tags: ['git', 'advanced', 'roadmap', 'internals', 'recovery'],
  steps: STEPS,
};
