/**
 * Git Beginner learning path — data only, no UI.
 * Every step references an existing stable content id; nothing is duplicated.
 */
import { LearningPath } from '@/types/learningPath';
import { buildSteps } from './buildPath';

const PATH_ID = 'git-beginner';

const STEPS = buildSteps(PATH_ID, [
  // ---------- Module 1 — Git Fundamentals ----------
  { slug: 'what-is-git', type: 'lesson', contentId: 'git.fundamentals.what-is-git',
    titleEn: 'What is Git?', titleBn: 'গিট কী?',
    descEn: 'Snapshots, not versions — how Git thinks about your work.', descBn: 'ভার্সন নয়, স্ন্যাপশট — গিট আপনার কাজকে কীভাবে দেখে।',
    whyEn: 'Everything else builds on the snapshot mental model.', whyBn: 'স্ন্যাপশট মানসিক মডেলের ওপর বাকি সব দাঁড়িয়ে।',
    minutes: 10, tags: ['fundamentals'] },
  { slug: 'git-vs-github', type: 'lesson', contentId: 'git.fundamentals.git-vs-github',
    titleEn: 'Git vs GitHub', titleBn: 'গিট বনাম গিটহাব',
    descEn: 'The tool on your machine versus the home for your code online.', descBn: 'আপনার মেশিনের টুল বনাম অনলাইনে কোডের ঠিকানা।',
    whyEn: 'Confusing the two causes most beginner remote mistakes.', whyBn: 'দুটো গুলিয়ে ফেলাই beginner রিমোট ভুলের মূল কারণ।',
    minutes: 8, prerequisites: ['what-is-git'], tags: ['fundamentals'] },
  { slug: 'repository', type: 'lesson', contentId: 'git.fundamentals.repository',
    titleEn: 'The Repository', titleBn: 'রিপোজিটরি',
    descEn: 'What lives inside .git and why it is safe to inspect.', descBn: '.git-এর ভেতরে কী থাকে ও কেন দেখা নিরাপদ।',
    whyEn: 'Commits and branches only make sense once the repository does.', whyBn: 'রিপোজিটরি বুঝলে কমিট ও ব্রাঞ্চ সহজ হয়।',
    minutes: 10, prerequisites: ['what-is-git'], tags: ['fundamentals'] },
  { slug: 'working-directory', type: 'lesson', contentId: 'git.fundamentals.working-directory',
    titleEn: 'Working Directory', titleBn: 'ওয়ার্কিং ডিরেক্টরি',
    descEn: 'The files on your disk — the first of Git’s three areas.', descBn: 'ডিস্কের ফাইল — গিটের তিন ক্ষেত্রের প্রথমটি।',
    whyEn: 'Every change starts here; staging and committing follow.', whyBn: 'প্রতিটি পরিবর্তন এখানে শুরু; তারপর স্টেজিং ও কমিট।',
    minutes: 8, prerequisites: ['repository'], tags: ['fundamentals'] },
  { slug: 'staging-area', type: 'lesson', contentId: 'git.fundamentals.staging-area',
    titleEn: 'Staging Area', titleBn: 'স্টেজিং এরিয়া',
    descEn: 'Curate exactly what goes into your next commit.', descBn: 'পরের কমিটে ঠিক কী যাবে তা বাছাই করুন।',
    whyEn: 'Staging is what makes commits precise instead of accidental.', whyBn: 'স্টেজিং কমিটকে নির্ভুল করে, দুর্ঘটনাজনিত নয়।',
    minutes: 10, prerequisites: ['working-directory'], tags: ['fundamentals'] },
  { slug: 'local-repository', type: 'lesson', contentId: 'git.fundamentals.local-repository',
    titleEn: 'Local Repository', titleBn: 'লোকাল রিপোজিটরি',
    descEn: 'Your permanent, private history on this machine.', descBn: 'এই মেশিনে আপনার স্থায়ী, ব্যক্তিগত হিস্ট্রি।',
    whyEn: 'Commit here with confidence before anything goes online.', whyBn: 'অনলাইনে যাওয়ার আগে এখানে আত্মবিশ্বাসে কমিট করুন।',
    minutes: 8, prerequisites: ['staging-area'], tags: ['fundamentals'] },
  { slug: 'commit', type: 'lesson', contentId: 'git.fundamentals.commit',
    titleEn: 'What is a Commit?', titleBn: 'কমিট কী?',
    descEn: 'Snapshots with identity: message, author, parents, hash.', descBn: 'পরিচয়সহ স্ন্যাপশট: বার্তা, লেখক, প্যারেন্ট, হ্যাশ।',
    whyEn: 'The commit is Git’s unit of work — interviews start here.', whyBn: 'কমিট গিটের কাজের একক — ইন্টারভিউ এখানে শুরু।',
    minutes: 12, prerequisites: ['repository', 'staging-area'], tags: ['fundamentals'] },
  { slug: 'head', type: 'lesson', contentId: 'git.fundamentals.head',
    titleEn: 'Understanding HEAD', titleBn: 'HEAD বোঝা',
    descEn: 'Where you are in the repository right now.', descBn: 'রিপোজিটরিতে আপনি এখন কোথায়।',
    whyEn: 'HEAD explains checkout, detached states, and switches.', whyBn: 'HEAD চেকআউট, ডিটাচড অবস্থা ও সুইচ ব্যাখ্যা করে।',
    minutes: 10, prerequisites: ['commit'], tags: ['fundamentals'] },
  { slug: 'branch', type: 'lesson', contentId: 'git.fundamentals.branch',
    titleEn: 'What is a Branch?', titleBn: 'ব্রাঞ্চ কী?',
    descEn: 'Lightweight movable pointers, not folders or copies.', descBn: 'ফোল্ডার বা কপি নয়, হালকা চলমান পয়েন্টার।',
    whyEn: 'Branching unlocks every workflow that follows.', whyBn: 'ব্রাঞ্চিং পরের প্রতিটি ওয়ার্কফ্লোর চাবি।',
    minutes: 12, prerequisites: ['commit', 'head'], tags: ['fundamentals', 'branching'] },
  { slug: 'three-areas', type: 'lesson', contentId: 'git.fundamentals.three-areas',
    titleEn: 'The Three Areas Together', titleBn: 'তিন ক্ষেত্র একসাথে',
    descEn: 'Working tree, index, repository — one unified flow.', descBn: 'ওয়ার্কিং ট্রি, ইনডেক্স, রিপোজিটরি — একটি ঐক্যবদ্ধ প্রবাহ।',
    whyEn: 'Seeing the whole pipeline ends beginner confusion.', whyBn: 'পুরো পাইপলাইন দেখলে beginner বিভ্রান্তি শেষ।',
    minutes: 10, prerequisites: ['staging-area', 'commit', 'head'], tags: ['fundamentals'] },
  { slug: 'init-repo', type: 'practice', contentId: 'git.practice.initialize-repository',
    titleEn: 'Practice: Initialize a Repository', titleBn: 'অনুশীলন: রিপোজিটরি তৈরি',
    descEn: 'Create a real-feeling repo in the safe simulator.', descBn: 'নিরাপদ সিমুলেটরে বাস্তবসম্মত রিপো তৈরি করুন।',
    whyEn: 'Hands beat reading for the first five commands.', whyBn: 'প্রথম পাঁচ কমান্ডে হাতে-কলমে পড়ার চেয়ে কার্যকর।',
    minutes: 10, prerequisites: ['repository'], tags: ['fundamentals', 'hands-on'] },
  { slug: 'inspect-status', type: 'practice', contentId: 'git.practice.command-inspect-status',
    titleEn: 'Practice: Inspect Repository Status', titleBn: 'অনুশীলন: রিপোজিটরি অবস্থা দেখা',
    descEn: 'Read git status like a dashboard, not a wall of text.', descBn: 'পাঠ্যের দেয়াল নয়, ড্যাশবোর্ডের মতো status পড়ুন।',
    whyEn: 'Status is the command you will run a hundred times a day.', whyBn: 'Status দিনে শতবার চালানো কমান্ড।',
    minutes: 10, prerequisites: ['three-areas'], tags: ['fundamentals', 'hands-on'] },
  { slug: 'stage-first-change', type: 'practice', contentId: 'git.practice.command-stage-first-change',
    titleEn: 'Practice: Stage Your First Change', titleBn: 'অনুশীলন: প্রথম পরিবর্তন স্টেজ',
    descEn: 'Move work from directory to index deliberately.', descBn: 'ইচ্ছাকৃতভাবে কাজ ডিরেক্টরি থেকে ইনডেক্সে নিন।',
    whyEn: 'Deliberate staging is the habit behind clean commits.', whyBn: 'ইচ্ছাকৃত স্টেজিং পরিষ্কার কমিটের অভ্যাস।',
    minutes: 10, prerequisites: ['staging-area'], tags: ['fundamentals', 'hands-on'] },
  { slug: 'first-commit', type: 'practice', contentId: 'git.practice.basic-commit',
    titleEn: 'Practice: Create Your First Commit', titleBn: 'অনুশীলন: প্রথম কমিট',
    descEn: 'Write a message and seal your first snapshot.', descBn: 'বার্তা লিখে প্রথম স্ন্যাপশট সিল করুন।',
    whyEn: 'Your first sealed snapshot makes the model concrete.', whyBn: 'প্রথম সিলড স্ন্যাপশট মডেলকে বাস্তব করে।',
    minutes: 10, prerequisites: ['commit', 'stage-first-change'], tags: ['fundamentals', 'hands-on'] },
  // ---------- Module 2 — Everyday Git Workflow ----------
  { slug: 'diff-inspection', type: 'lesson', contentId: 'git.workflow.diff-inspection',
    titleEn: 'Inspecting Changes (git diff)', titleBn: 'পরিবর্তন পর্যালোচনা (git diff)',
    descEn: 'Inspect exactly what changed before you stage anything.', descBn: 'স্টেজের আগে ঠিক কী বদলেছে দেখুন।',
    whyEn: 'Inspect-first is the habit behind every safe commit.', whyBn: 'আগে-দেখা প্রতিটি নিরাপদ কমিটের অভ্যাস।',
    minutes: 10, prerequisites: ['first-commit'], tags: ['everyday'] },
  { slug: 'history-log', type: 'lesson', contentId: 'git.workflow.history-log',
    titleEn: 'Navigating History (git log)', titleBn: 'হিস্ট্রি দেখা (git log)',
    descEn: 'Read your project’s story one commit at a time.', descBn: 'প্রজেক্টের গল্প কমিট ধরে ধরে পড়ুন।',
    whyEn: 'Log literacy turns history into a debugging tool.', whyBn: 'Log সাক্ষরতা হিস্ট্রিকে ডিবাগ টুলে বদলায়।',
    minutes: 10, prerequisites: ['commit'], tags: ['everyday'] },
  { slug: 'everyday-flow', type: 'practice', contentId: 'git.practice.command-everyday-flow',
    titleEn: 'Practice: The Everyday Git Workflow', titleBn: 'অনুশীলন: দৈনন্দিন গিট প্রবাহ',
    descEn: 'Status → diff → add → commit → log, end to end.', descBn: 'Status → diff → add → commit → log, শুরু থেকে শেষ।',
    whyEn: 'One loop you will repeat for your whole career.', whyBn: 'সারা ক্যারিয়ারে পুনরাবৃত্ত একটি চক্র।',
    minutes: 15, prerequisites: ['diff-inspection', 'history-log'], tags: ['everyday', 'hands-on'] },
  { slug: 'inspect-before-commit', type: 'practice', contentId: 'git.practice.command-inspect-before-commit',
    titleEn: 'Practice: Inspect Before Committing', titleBn: 'অনুশীলন: কমিটের আগে পরীক্ষা',
    descEn: 'Catch mistakes while they are still cheap to fix.', descBn: 'সস্তায় ঠিক করা যায় এমন সময়ে ভুল ধরুন।',
    whyEn: 'Reviewing your own diff prevents most bad commits.', whyBn: 'নিজের diff পর্যালোচনা খারাপ কমিট রোধ করে।',
    minutes: 10, prerequisites: ['diff-inspection'], tags: ['everyday', 'hands-on'] },
  { slug: 'staged-by-mistake', type: 'troubleshooting', contentId: 'git.troubleshooting.staged-file',
    titleEn: 'Cookbook: Staged a File by Mistake', titleBn: 'কুকবুক: ভুলে ফাইল স্টেজ',
    descEn: 'Unstage safely without losing a single edit.', descBn: 'একটি এডিট না হারিয়ে নিরাপদে আনস্টেজ করুন।',
    whyEn: 'Every beginner stages the wrong file — learn the calm fix now.', whyBn: 'প্রতিটি beginner ভুল ফাইল স্টেজ করে — শান্ত সমাধান এখনই শিখুন।',
    minutes: 8, prerequisites: ['stage-first-change'], tags: ['everyday', 'recovery'] },
  { slug: 'everyday-workflow-guide', type: 'workflow', contentId: 'git.workflow.everyday',
    route: '/workflows/everyday-git',
    titleEn: 'Guide: Everyday Git Workflow', titleBn: 'গাইড: দৈনন্দিন গিট প্রবাহ',
    descEn: 'The step-by-step reference for daily work.', descBn: 'দৈনন্দিন কাজের ধাপে ধাপে রেফারেন্স।',
    whyEn: 'A checklist to lean on until the loop is muscle memory.', whyBn: 'চক্র অভ্যাস না হওয়া পর্যন্ত নির্ভরযোগ্য চেকলিস্ট।',
    minutes: 10, prerequisites: ['everyday-flow'], tags: ['everyday', 'guide'] },
  // ---------- Module 3 — Branching ----------
  { slug: 'what-are-branches', type: 'lesson', contentId: 'git.branching.what-are-branches',
    titleEn: 'Understanding Branch Pointers', titleBn: 'ব্রাঞ্চ পয়েন্টার বোঝা',
    descEn: 'Why creating a branch is instant and cheap.', descBn: 'কেন ব্রাঞ্চ তৈরি মুহূর্তে ও সস্তায় হয়।',
    whyEn: 'Pointer thinking replaces folder-copy thinking.', whyBn: 'পয়েন্টার চিন্তা ফোল্ডার-কপি চিন্তা বদলায়।',
    minutes: 10, prerequisites: ['branch'], tags: ['branching'] },
  { slug: 'creating-switching', type: 'lesson', contentId: 'git.branching.creating-switching',
    titleEn: 'Creating & Switching Branches', titleBn: 'ব্রাঞ্চ তৈরি ও বদল',
    descEn: 'switch vs checkout, and moving HEAD safely.', descBn: 'switch বনাম checkout, ও নিরাপদে HEAD সরানো।',
    whyEn: 'Clean switching avoids the classic dirty-tree surprise.', whyBn: 'পরিষ্কার সুইচ ক্লাসিক ডার্টি-ট্রি চমক এড়ায়।',
    minutes: 10, prerequisites: ['what-are-branches'], tags: ['branching'] },
  { slug: 'create-feature-branch', type: 'practice', contentId: 'git.practice.create-feature-branch',
    titleEn: 'Practice: Create a Feature Branch', titleBn: 'অনুশীলন: ফিচার ব্রাঞ্চ তৈরি',
    descEn: 'Isolate new work the way teams actually do.', descBn: 'টিম যেভাবে করে নতুন কাজ আলাদা করুন।',
    whyEn: 'Branch-per-change is the doorway to collaboration.', whyBn: 'প্রতি-পরিবর্তনে ব্রাঞ্চ সহযোগিতার দরজা।',
    minutes: 10, prerequisites: ['creating-switching'], tags: ['branching', 'hands-on'] },
  { slug: 'switch-branches', type: 'practice', contentId: 'git.practice.switch-branches',
    titleEn: 'Practice: Switch Between Branches', titleBn: 'অনুশীলন: ব্রাঞ্চ বদল',
    descEn: 'Move HEAD without losing work in progress.', descBn: 'চলমান কাজ না হারিয়ে HEAD সরান।',
    whyEn: 'Safe switching is a daily survival skill.', whyBn: 'নিরাপদ সুইচ দৈনন্দিন বেঁচে থাকার দক্ষতা।',
    minutes: 10, prerequisites: ['creating-switching'], tags: ['branching', 'hands-on'] },
  { slug: 'feature-branch-workflow', type: 'practice', contentId: 'git.practice.feature-branch-workflow',
    titleEn: 'Practice: Feature Branch Workflow', titleBn: 'অনুশীলন: ফিচার ব্রাঞ্চ প্রবাহ',
    descEn: 'Branch, commit, and finish a feature end to end.', descBn: 'ব্রাঞ্চ, কমিট ও ফিচার শেষ — শুরু থেকে শেষ।',
    whyEn: 'The complete loop teams expect you to know.', whyBn: 'টিম যে সম্পূর্ণ চক্র আশা করে।',
    minutes: 15, prerequisites: ['create-feature-branch', 'switch-branches'], tags: ['branching', 'hands-on'] },
  // ---------- Module 4 — Remote Repositories ----------
  { slug: 'remote-repository', type: 'lesson', contentId: 'git.fundamentals.remote-repository',
    titleEn: 'The Remote Repository', titleBn: 'রিমোট রিপোজিটরি',
    descEn: 'The shared server and your view of it.', descBn: 'শেয়ার্ড সার্ভার ও তার প্রতি আপনার দৃষ্টি।',
    whyEn: 'Local confidence must graduate to shared history.', whyBn: 'লোকাল আত্মবিশ্বাস শেয়ার্ড হিস্ট্রিতে উন্নীত হোক।',
    minutes: 10, prerequisites: ['local-repository'], tags: ['remote'] },
  { slug: 'fetch-vs-pull', type: 'lesson', contentId: 'git.remote.fetch-vs-pull',
    titleEn: 'Fetch vs Pull, Demystified', titleBn: 'Fetch বনাম Pull',
    descEn: 'Look first, then integrate — the safe order.', descBn: 'আগে দেখুন, তারপর একীভূত — নিরাপদ ক্রম।',
    whyEn: 'This distinction prevents half of all sync disasters.', whyBn: 'এই পার্থক্য অর্ধেক সিঙ্ক বিপর্যয় রোধ করে।',
    minutes: 12, prerequisites: ['remote-repository'], tags: ['remote'] },
  { slug: 'connect-remote', type: 'practice', contentId: 'git.practice.command-connect-remote',
    titleEn: 'Practice: Connect to a Remote', titleBn: 'অনুশীলন: রিমোটে সংযোগ',
    descEn: 'Give your local history a shared home.', descBn: 'লোকাল হিস্ট্রিকে শেয়ার্ড ঠিকানা দিন।',
    whyEn: 'Origin setup is the first real collaboration act.', whyBn: 'Origin সেটআপ প্রথম বাস্তব সহযোগিতা।',
    minutes: 10, prerequisites: ['remote-repository'], tags: ['remote', 'hands-on'] },
  { slug: 'push-feature', type: 'practice', contentId: 'git.practice.push-feature',
    titleEn: 'Practice: Push a Feature Branch', titleBn: 'অনুশীলন: ফিচার ব্রাঞ্চ পুশ',
    descEn: 'Publish your branch for review and backup.', descBn: 'রিভিউ ও ব্যাকআপে ব্রাঞ্চ প্রকাশ করুন।',
    whyEn: 'Pushing makes private work visible and safe.', whyBn: 'পুশ ব্যক্তিগত কাজ দৃশ্যমান ও নিরাপদ করে।',
    minutes: 10, prerequisites: ['connect-remote', 'feature-branch-workflow'], tags: ['remote', 'hands-on'] },
  { slug: 'fetch-changes', type: 'practice', contentId: 'git.practice.fetch-changes',
    titleEn: 'Practice: Fetch Remote Changes', titleBn: 'অনুশীলন: রিমোট পরিবর্তন আনা',
    descEn: 'Update your photograph without moving your position.', descBn: 'অবস্থান না সরিয়ে ছবি হালনাগাদ করুন।',
    whyEn: 'Fetch-first is the calm way to stay in sync.', whyBn: 'আগে-fetch সিঙ্কে থাকার শান্ত উপায়।',
    minutes: 10, prerequisites: ['fetch-vs-pull'], tags: ['remote', 'hands-on'] },
  // ---------- Module 5 — GitHub ----------
  { slug: 'origin-upstream', type: 'lesson', contentId: 'github.basics.origin-and-upstream',
    titleEn: 'origin and upstream', titleBn: 'origin ও upstream',
    descEn: 'Two remotes, two jobs: yours and the source of truth.', descBn: 'দুই রিমোট, দুই কাজ: আপনারটা ও সত্যের উৎস।',
    whyEn: 'Upstream confusion breaks every first fork contribution.', whyBn: 'Upstream বিভ্রান্তি প্রথম ফোর্ক অবদান ভাঙে।',
    minutes: 10, prerequisites: ['remote-repository'], tags: ['github'] },
  { slug: 'what-is-pr', type: 'lesson', contentId: 'github.pr.what-is-a-pull-request',
    titleEn: 'What is a Pull Request?', titleBn: 'পুল রিকোয়েস্ট কী?',
    descEn: 'A proposal, a conversation, and a quality gate.', descBn: 'প্রস্তাব, আলোচনা ও মান-ফটক।',
    whyEn: 'PRs are how modern teams ship anything.', whyBn: 'PR আধুনিক টিমের পাঠানোর পথ।',
    minutes: 10, prerequisites: ['origin-upstream', 'push-feature'], tags: ['github'] },
  { slug: 'team-feature-branch', type: 'lesson', contentId: 'github.team.feature-branch-workflow',
    titleEn: 'Feature Branch Workflow', titleBn: 'ফিচার ব্রাঞ্চ প্রবাহ',
    descEn: 'The team loop: branch, push, review, merge, sync.', descBn: 'টিম চক্র: ব্রাঞ্চ, পুশ, রিভিউ, মার্জ, সিঙ্ক।',
    whyEn: 'One workflow that covers most real jobs.', whyBn: 'একটি প্রবাহে বেশিরভাগ বাস্তব কাজ।',
    minutes: 12, prerequisites: ['what-is-pr'], tags: ['github'] },
  { slug: 'fork-clone-pr', type: 'practice', contentId: 'git.practice.command-fork-clone-pr-flow',
    titleEn: 'Practice: Fork → Clone → Branch → PR', titleBn: 'অনুশীলন: ফোর্ক → ক্লোন → ব্রাঞ্চ → PR',
    descEn: 'The full open-source contribution loop, simulated.', descBn: 'সম্পূর্ণ ওপেন-সোর্স অবদান চক্র, সিমুলেটেড।',
    whyEn: 'This loop is the practical GitHub job interview.', whyBn: 'এই চক্র ব্যবহারিক গিটহাব ইন্টারভিউ।',
    minutes: 20, prerequisites: ['team-feature-branch'], tags: ['github', 'hands-on'] },
  { slug: 'origin-vs-upstream', type: 'practice', contentId: 'git.practice.command-origin-vs-upstream',
    titleEn: 'Practice: origin vs upstream', titleBn: 'অনুশীলন: origin বনাম upstream',
    descEn: 'Push to yours, propose to theirs — without mixing them.', descBn: 'নিজেরটায় পুশ, তাদেরটায় প্রস্তাব — না গুলিয়ে।',
    whyEn: 'Separating the two remotes ends fork chaos.', whyBn: 'দুই রিমোট আলাদা করলে ফোর্ক বিশৃঙ্খলা শেষ।',
    minutes: 10, prerequisites: ['origin-upstream'], tags: ['github', 'hands-on'] },
  { slug: 'interview-fundamentals', type: 'interview', contentId: 'interview:fundamentals',
    titleEn: 'Interview: Git Fundamentals', titleBn: 'ইন্টারভিউ: গিট মৌলিক বিষয়',
    descEn: 'Say what Git is, what staging does, and what HEAD means.', descBn: 'বলুন গিট কী, স্টেজিং কী করে ও HEAD মানে কী।',
    whyEn: 'First interview answers should sound like your own words.', whyBn: 'প্রথম ইন্টারভিউ উত্তর নিজের ভাষায় শোনানো উচিত।',
    minutes: 15, prerequisites: ['fork-clone-pr'], tags: ['interview'] },
  { slug: 'skill-assessment', type: 'assessment', contentId: 'git.assessment.skill',
    titleEn: 'Checkpoint: Git Skill Assessment', titleBn: 'যাচাই: গিট দক্ষতা মূল্যায়ন',
    descEn: 'Estimate your applied skill across six areas.', descBn: 'ছয় ক্ষেত্রে প্রয়োগিক দক্ষতার অনুমান করুন।',
    whyEn: 'An honest estimate shows exactly what to review next.', whyBn: 'সৎ অনুমান দেখায় পরের পর্যালোচনা কী।',
    minutes: 20, prerequisites: ['interview-fundamentals'], tags: ['assessment', 'checkpoint'] },
]);

export const GIT_BEGINNER_PATH: LearningPath = {
  id: PATH_ID,
  subjectId: 'git',
  difficulty: 'beginner',
  title: { en: 'Git Beginner', bn: 'গিট বিগিনার' },
  description: {
    en: 'From “what is Git?” to your first pull request — fundamentals, everyday workflow, branching, remotes, and GitHub teamwork.',
    bn: '“গিট কী?” থেকে প্রথম পুল রিকোয়েস্ট — মৌলিক বিষয়, দৈনন্দিন প্রবাহ, ব্রাঞ্চিং, রিমোট ও গিটহাব টিমওয়ার্ক।',
  },
  outcomes: [
    { en: 'Explain snapshots, the three areas, commits, branches, and HEAD.', bn: 'স্ন্যাপশট, তিন ক্ষেত্র, কমিট, ব্রাঞ্চ ও HEAD ব্যাখ্যা করতে পারবেন।' },
    { en: 'Work the everyday loop: status, diff, add, commit, log.', bn: 'দৈনন্দিন চক্র চালাতে পারবেন: status, diff, add, commit, log।' },
    { en: 'Branch, switch, push, fetch, and open a pull request.', bn: 'ব্রাঞ্চ, সুইচ, পুশ, fetch ও পুল রিকোয়েস্ট খুলতে পারবেন।' },
  ],
  prerequisites: [],
  icon: 'Sprout',
  order: 1,
  tags: ['git', 'beginner', 'roadmap', 'getting-started'],
  steps: STEPS,
};
