/**
 * Git Intermediate learning path — data only, no UI.
 * Deliberately interleaves Learn → Practice → Troubleshoot.
 */
import { LearningPath } from '@/types/learningPath';
import { buildSteps } from './buildPath';

const PATH_ID = 'git-intermediate';

const STEPS = buildSteps(PATH_ID, [
  // ---------- Branching & History ----------
  { slug: 'merge-types', type: 'lesson', contentId: 'git.merging.types',
    titleEn: 'Fast-Forward vs 3-Way Merge', titleBn: 'ফাস্ট-ফরোয়ার্ড বনাম 3-ওয়ে মার্জ',
    descEn: 'When history moves straight and when it needs a join.', descBn: 'হিস্ট্রি কখন সোজা এগোয়, কখন জোড়া লাগে।',
    whyEn: 'Merge literacy decides whether your history tells the truth.', whyBn: 'মার্জ সাক্ষরতা নির্ধারণ করে হিস্ট্রি সত্য বলে কিনা।',
    minutes: 12, tags: ['merging'] },
  { slug: 'merge-feature', type: 'practice', contentId: 'git.practice.merge-feature',
    titleEn: 'Practice: Merge a Feature Branch', titleBn: 'অনুশীলন: ফিচার ব্রাঞ্চ মার্জ',
    descEn: 'Join two lines of work and read the result.', descBn: 'দুই কাজের লাইন জোড়া দিয়ে ফল পড়ুন।',
    whyEn: 'Merging by hand cements what the lesson described.', whyBn: 'হাতে মার্জ পাঠের বর্ণনা পোক্ত করে।',
    minutes: 12, prerequisites: ['merge-types'], tags: ['merging', 'hands-on'] },
  { slug: 'fast-forward', type: 'practice', contentId: 'git.practice.command-fast-forward-merge',
    titleEn: 'Practice: Fast-Forward Merge', titleBn: 'অনুশীলন: ফাস্ট-ফরোয়ার্ড মার্জ',
    descEn: 'Recognize when no merge commit is needed at all.', descBn: 'চিনুন কখন মার্জ কমিট আদৌ লাগে না।',
    whyEn: 'Knowing the easy case keeps histories clean.', whyBn: 'সহজ কেস জানলে হিস্ট্রি পরিষ্কার থাকে।',
    minutes: 10, prerequisites: ['merge-types'], tags: ['merging', 'hands-on'] },
  { slug: 'resolving-conflicts', type: 'lesson', contentId: 'git.merging.conflicts',
    titleEn: 'Diagnosing & Resolving Merge Conflicts', titleBn: 'মার্জ কনফ্লিক্ট নির্ণয় ও সমাধান',
    descEn: 'What markers mean and how to compose the right result.', descBn: 'মার্কার মানে কী ও সঠিক ফল কীভাবে রচনা করবেন।',
    whyEn: 'Conflicts are inevitable; panic is optional.', whyBn: 'কনফ্লিক্ট অনিবার্য; আতঙ্ক ঐচ্ছিক।',
    minutes: 15, prerequisites: ['merge-feature'], tags: ['merging'] },
  { slug: 'conflict-flow', type: 'practice', contentId: 'git.practice.merge-conflict-flow',
    titleEn: 'Practice: Resolve a Merge Conflict', titleBn: 'অনুশীলন: মার্জ কনফ্লিক্ট সমাধান',
    descEn: 'Work a conflicted merge in the safe simulator.', descBn: 'নিরাপদ সিমুলেটরে কনফ্লিক্টেড মার্জ করুন।',
    whyEn: 'One calm rehearsal beats ten anxious real ones.', whyBn: 'এক শান্ত মহড়া দশ উদ্বিগ্ন বাস্তবের চেয়ে ভালো।',
    minutes: 15, prerequisites: ['resolving-conflicts'], tags: ['merging', 'hands-on'] },
  { slug: 'troubleshoot-conflict', type: 'troubleshooting', contentId: 'git.troubleshooting.merge-conflict',
    titleEn: 'Cookbook: Merge Conflict Recovery', titleBn: 'কুকবুক: মার্জ কনফ্লিক্ট পুনরুদ্ধার',
    descEn: 'The step-by-step recipe when a merge stops midway.', descBn: 'মার্জ মাঝপথে থামলে ধাপে ধাপে রেসিপি।',
    whyEn: 'Recipes turn mid-conflict stress into procedure.', whyBn: 'রেসিপি কনফ্লিক্ট-মাঝ চাপকে পদ্ধতিতে বদলায়।',
    minutes: 10, prerequisites: ['conflict-flow'], tags: ['merging', 'recovery'] },
  { slug: 'rebase-basics', type: 'lesson', contentId: 'git.rebasing.basics',
    titleEn: 'Rebase vs Merge', titleBn: 'রিবেস বনাম মার্জ',
    descEn: 'Replay versus join — and the golden rule of rewriting.', descBn: 'রিপ্লে বনাম জোড়া — ও পুনর্লেখনের গোল্ডেন রুল।',
    whyEn: 'Choosing well keeps shared history trustworthy.', whyBn: 'ভালো বাছাই শেয়ার্ড হিস্ট্রি বিশ্বস্ত রাখে।',
    minutes: 12, prerequisites: ['merge-types'], tags: ['rebasing'] },
  { slug: 'rebase-feature', type: 'practice', contentId: 'git.practice.rebase-feature',
    titleEn: 'Practice: Rebase a Feature Branch', titleBn: 'অনুশীলন: ফিচার ব্রাঞ্চ রিবেস',
    descEn: 'Replay private work onto a fresh base.', descBn: 'ব্যক্তিগত কাজ নতুন বেসে রিপ্লে করুন।',
    whyEn: 'Feeling replay demystifies rewriting.', whyBn: 'রিপ্লে অনুভব করলে পুনর্লেখন সহজ হয়।',
    minutes: 12, prerequisites: ['rebase-basics'], tags: ['rebasing', 'hands-on'] },
  { slug: 'rebase-rewrites', type: 'practice', contentId: 'git.practice.command-rebase-rewrites-history',
    titleEn: 'Practice: Why Rebase Rewrites History', titleBn: 'অনুশীলন: রিবেস কেন হিস্ট্রি বদলায়',
    descEn: 'Watch commit identity change across a rebase.', descBn: 'রিবেসে কমিট পরিচয় বদলাতে দেখুন।',
    whyEn: 'Seeing new hashes makes the golden rule obvious.', whyBn: 'নতুন হ্যাশ দেখলে গোল্ডেন রুল স্পষ্ট হয়।',
    minutes: 10, prerequisites: ['rebase-feature'], tags: ['rebasing', 'hands-on'] },
  { slug: 'troubleshoot-rebase', type: 'troubleshooting', contentId: 'git.troubleshooting.rebase-conflict',
    titleEn: 'Cookbook: Rebase Stopped with Conflict', titleBn: 'কুকবুক: কনফ্লিক্টে রিবেস থামা',
    descEn: 'Continue, skip, or abort — choosing calmly mid-rebase.', descBn: 'চালিয়ে, এড়িয়ে বা বাতিল — রিবেস-মাঝে শান্ত বাছাই।',
    whyEn: 'A stopped rebase is routine, not an emergency.', whyBn: 'থামা রিবেস রুটিন, জরুরি নয়।',
    minutes: 10, prerequisites: ['rebase-feature'], tags: ['rebasing', 'recovery'] },
  { slug: 'interactive-rebase', type: 'lesson', contentId: 'git.rebasing.interactive',
    titleEn: 'Interactive Rebase', titleBn: 'ইন্টার‌্যাক্টিভ রিবেস',
    descEn: 'Squash, reword, and curate a reviewable history.', descBn: 'স্কোয়াশ, পুনর্বাক্য ও পর্যালোচনাযোগ্য হিস্ট্রি সাজান।',
    whyEn: 'Curated history is a kindness to every future reader.', whyBn: 'সাজানো হিস্ট্রি ভবিষ্যৎ পাঠকের প্রতি সদয়তা।',
    minutes: 12, prerequisites: ['rebase-basics'], tags: ['rebasing'] },
  { slug: 'parent-relationships', type: 'lesson', contentId: 'git.internals.parent-relationships',
    titleEn: 'Commit Ancestry & Parents', titleBn: 'কমিট বংশ ও প্যারেন্ট',
    descEn: 'How merges, forks, and first-parents really connect.', descBn: 'মার্জ, ফোর্ক ও ফার্স্ট-প্যারেন্ট আসলে কীভাবে যুক্ত।',
    whyEn: 'Ancestry thinking explains divergence and log graphs.', whyBn: 'বংশ চিন্তা ডাইভারজেন্স ও log গ্রাফ ব্যাখ্যা করে।',
    minutes: 10, prerequisites: ['merge-types', 'rebase-basics'], tags: ['history'] },
  // ---------- Remote Collaboration ----------
  { slug: 'sync-before-work', type: 'lesson', contentId: 'github.team.sync-before-work',
    titleEn: 'Syncing Before Starting Work', titleBn: 'কাজ শুরুর আগে সিঙ্ক',
    descEn: 'Start every session from the team’s latest truth.', descBn: 'টিমের সর্বশেষ সত্য থেকে প্রতিটি সেশন শুরু।',
    whyEn: 'Stale starts cause most collaboration conflicts.', whyBn: 'বাসি শুরু বেশিরভাগ সহযোগিতা কনফ্লিক্টের কারণ।',
    minutes: 10, prerequisites: ['parent-relationships'], tags: ['collaboration'] },
  { slug: 'fetch-vs-pull-practice', type: 'practice', contentId: 'git.practice.command-fetch-vs-pull',
    titleEn: 'Practice: Fetch vs Pull', titleBn: 'অনুশীলন: Fetch বনাম Pull',
    descEn: 'Feel the difference between looking and integrating.', descBn: 'দেখা ও একীভূতের পার্থক্য অনুভব করুন।',
    whyEn: 'Muscle memory for the safe sync order.', whyBn: 'নিরাপদ সিঙ্ক ক্রমের পেশি-স্মৃতি।',
    minutes: 10, prerequisites: ['sync-before-work'], tags: ['remote', 'hands-on'] },
  { slug: 'resolve-team-conflicts', type: 'lesson', contentId: 'github.team.resolve-collaboration-conflicts',
    titleEn: 'Resolving Collaboration Conflicts', titleBn: 'সহযোগিতা কনফ্লিক্ট সমাধান',
    descEn: 'Team protocol when two histories collide.', descBn: 'দুই হিস্ট্রি ধাক্কা খেলে টিম প্রোটোকল।',
    whyEn: 'Conflicts are social before they are technical.', whyBn: 'কনফ্লিক্ট প্রযুক্তির আগে সামাজিক।',
    minutes: 12, prerequisites: ['resolving-conflicts', 'sync-before-work'], tags: ['collaboration'] },
  { slug: 'troubleshoot-diverged', type: 'troubleshooting', contentId: 'git.troubleshooting.diverged',
    titleEn: 'Cookbook: Branches Have Diverged', titleBn: 'কুকবুক: ব্রাঞ্চ ডাইভার্জড',
    descEn: 'Pick merge or rebase when both sides moved.', descBn: 'উভয় পক্ষ সরলে মার্জ বা রিবেস বাছুন।',
    whyEn: 'Divergence is the canonical intermediate problem.', whyBn: 'ডাইভারজেন্স আদর্শ intermediate সমস্যা।',
    minutes: 10, prerequisites: ['fetch-vs-pull-practice', 'rebase-basics'], tags: ['remote', 'recovery'] },
  { slug: 'troubleshoot-behind', type: 'troubleshooting', contentId: 'git.troubleshooting.behind-remote',
    titleEn: 'Cookbook: “Behind origin” Explained', titleBn: 'কুকবুক: “behind origin” ব্যাখ্যা',
    descEn: 'What the message means and the exact catch-up.', descBn: 'বার্তা মানে কী ও ঠিক ধরার উপায়।',
    whyEn: 'Reading status precisely prevents blind pulling.', whyBn: 'নির্ভুল status পড়া অন্ধ পুল রোধ করে।',
    minutes: 8, prerequisites: ['sync-before-work'], tags: ['remote'] },
  { slug: 'troubleshoot-push', type: 'troubleshooting', contentId: 'git.troubleshooting.push-rejected',
    titleEn: 'Cookbook: Push Rejected', titleBn: 'কুকবুক: পুশ প্রত্যাখ্যাত',
    descEn: 'Why the server said no and how to answer.', descBn: 'সার্ভার কেন না বলল ও কীভাবে জবাব দেবেন।',
    whyEn: 'Rejection protects the team; learn its language.', whyBn: 'প্রত্যাখ্যান টিম রক্ষা করে; ভাষা শিখুন।',
    minutes: 8, prerequisites: ['troubleshoot-diverged'], tags: ['remote', 'recovery'] },
  // ---------- Undo & Recovery ----------
  { slug: 'restore-revert', type: 'lesson', contentId: 'git.recovery.restore-and-revert',
    titleEn: 'Safe Undos: restore & revert', titleBn: 'নিরাপদ আনডু: restore ও revert',
    descEn: 'Undo without rewriting — the sharable-safe way.', descBn: 'পুনর্লেখন ছাড়া আনডু — শেয়ার-নিরাপদ পথ।',
    whyEn: 'Safe undos fix mistakes without endangering teammates.', whyBn: 'নিরাপদ আনডু সহকর্মী বিপদে না ফেলে ভুল ঠিক করে।',
    minutes: 12, prerequisites: ['merge-types'], tags: ['recovery'] },
  { slug: 'reset-matrix', type: 'lesson', contentId: 'git.recovery.reset-matrix',
    titleEn: 'The Three Trees of git reset', titleBn: 'git reset-এর তিন ট্রি',
    descEn: 'soft, mixed, hard — what each one actually moves.', descBn: 'soft, mixed, hard — প্রতিটি আসলে কী সরায়।',
    whyEn: 'Reset precision separates juniors from intermediaries.', whyBn: 'Reset নির্ভুলতা junior ও intermediate আলাদা করে।',
    minutes: 12, prerequisites: ['restore-revert'], tags: ['recovery'] },
  { slug: 'undo-change', type: 'practice', contentId: 'git.practice.command-undo-unwanted-change',
    titleEn: 'Practice: Undo an Unwanted Change', titleBn: 'অনুশীলন: অবাঞ্ছিত পরিবর্তন আনডু',
    descEn: 'Pick the right undo for the right situation.', descBn: 'সঠিক পরিস্থিতিতে সঠিক আনডু বাছুন।',
    whyEn: 'Undo judgment is pure intermediate craft.', whyBn: 'আনডু বিচার খাঁটি intermediate কারুকাজ।',
    minutes: 12, prerequisites: ['reset-matrix'], tags: ['recovery', 'hands-on'] },
  { slug: 'reflog-lesson', type: 'lesson', contentId: 'git.recovery.reflog-lifesaver',
    titleEn: 'Emergency Recovery with reflog', titleBn: 'reflog-এ জরুরি উদ্ধার',
    descEn: 'Your safety net for nearly every disaster.', descBn: 'প্রায় প্রতিটি বিপর্যয়ে নিরাপত্তা জাল।',
    whyEn: 'Knowing reflog exists changes how boldly you work.', whyBn: 'reflog আছে জানলে কাজে সাহস বাড়ে।',
    minutes: 12, prerequisites: ['undo-change'], tags: ['recovery'] },
  { slug: 'recover-branch', type: 'practice', contentId: 'git.practice.recover-deleted-branch',
    titleEn: 'Practice: Recover a Deleted Branch', titleBn: 'অনুশীলন: মোছা ব্রাঞ্চ উদ্ধার',
    descEn: 'Bring back work you thought was gone.', descBn: 'হারানো ভাবা কাজ ফিরিয়ে আনুন।',
    whyEn: 'Recovery rehearsal builds unshakeable confidence.', whyBn: 'উদ্ধার মহড়া অটল আত্মবিশ্বাস গড়ে।',
    minutes: 12, prerequisites: ['reflog-lesson'], tags: ['recovery', 'hands-on'] },
  { slug: 'recover-commit', type: 'practice', contentId: 'git.practice.command-recover-lost-commit',
    titleEn: 'Practice: Recover a Lost Commit', titleBn: 'অনুশীলন: হারানো কমিট উদ্ধার',
    descEn: 'Follow the reflog trail to a dangling commit.', descBn: 'reflog সূত্রে ঝুলন্ত কমিটে পৌঁছান।',
    whyEn: 'The flagship recovery skill, end to end.', whyBn: 'ফ্ল্যাগশিপ উদ্ধার দক্ষতা, শুরু থেকে শেষ।',
    minutes: 12, prerequisites: ['recover-branch'], tags: ['recovery', 'hands-on'] },
  { slug: 'troubleshoot-detached', type: 'troubleshooting', contentId: 'git.troubleshooting.detached-head',
    titleEn: 'Cookbook: Detached HEAD', titleBn: 'কুকবুক: ডিটাচড HEAD',
    descEn: 'Why you are floating and how to reattach safely.', descBn: 'কেন ভাসছেন ও নিরাপদে কীভাবে ফিরবেন।',
    whyEn: 'Detached HEAD alarms beginners; intermediaries navigate it.', whyBn: 'ডিটাচড HEAD beginner-কে ভয় দেখায়; intermediate চালায়।',
    minutes: 8, prerequisites: ['reflog-lesson'], tags: ['recovery'] },
  // ---------- Interview + Assessment ----------
  { slug: 'interview-branching', type: 'interview', contentId: 'interview:branching',
    titleEn: 'Interview: Branching & History', titleBn: 'ইন্টারভিউ: ব্রাঞ্চিং ও হিস্ট্রি',
    descEn: 'Explain merges, rebases, and graphs out loud.', descBn: 'মার্জ, রিবেস ও গ্রাফ মুখে ব্যাখ্যা করুন।',
    whyEn: 'Saying it proves you own it — try merge-vs-rebase first.', whyBn: 'বলা প্রমাণ করে আয়ত্ত — merge-vs-rebase দিয়ে শুরু।',
    minutes: 20, prerequisites: ['interactive-rebase', 'parent-relationships'], tags: ['interview'] },
  { slug: 'interview-remote', type: 'interview', contentId: 'interview:remote',
    titleEn: 'Interview: Remote & Collaboration', titleBn: 'ইন্টারভিউ: রিমোট ও সহযোগিতা',
    descEn: 'Field fetch-vs-pull and divergence questions calmly.', descBn: 'fetch-vs-pull ও ডাইভারজেন্স প্রশ্ন শান্তভাবে নিন।',
    whyEn: 'Sync questions are the most-asked intermediate topic.', whyBn: 'সিঙ্ক প্রশ্ন সর্বাধিক জিজ্ঞাসিত intermediate বিষয়।',
    minutes: 15, prerequisites: ['troubleshoot-diverged'], tags: ['interview'] },
  { slug: 'skill-assessment', type: 'assessment', contentId: 'git.assessment.skill',
    titleEn: 'Checkpoint: Git Skill Assessment', titleBn: 'যাচাই: গিট দক্ষতা মূল্যায়ন',
    descEn: 'Measure all six areas and find your next path.', descBn: 'ছয় ক্ষেত্র মেপে পরের পথ খুঁজুন।',
    whyEn: 'Scores point straight at Advanced or at review topics.', whyBn: 'স্কোর সরাসরি Advanced বা পর্যালোচনায় দেখায়।',
    minutes: 20, prerequisites: ['interview-branching', 'recover-commit'], tags: ['assessment', 'checkpoint'] },
]);

export const GIT_INTERMEDIATE_PATH: LearningPath = {
  id: PATH_ID,
  subjectId: 'git',
  difficulty: 'intermediate',
  title: { en: 'Git Intermediate', bn: 'গিট ইন্টারমিডিয়েট' },
  description: {
    en: 'Merge and rebase with judgment, collaborate without fear, and recover from (almost) anything — Learn → Practice → Troubleshoot.',
    bn: 'বিচারে মার্জ ও রিবেস, নির্ভয়ে সহযোগিতা ও (প্রায়) সব থেকে উদ্ধার — শিখুন → অনুশীলন → ট্রাবলশুট।',
  },
  outcomes: [
    { en: 'Resolve merges, rebases, divergence, and sync conflicts.', bn: 'মার্জ, রিবেস, ডাইভারজেন্স ও সিঙ্ক কনফ্লিক্ট সমাধান করতে পারবেন।' },
    { en: 'Choose safe undos and recover lost work with the reflog.', bn: 'নিরাপদ আনডু বেছে হারানো কাজ reflog-এ উদ্ধার করতে পারবেন।' },
    { en: 'Answer intermediate interview questions with real examples.', bn: 'বাস্তব উদাহরণে intermediate ইন্টারভিউ প্রশ্নের উত্তর দিতে পারবেন।' },
  ],
  prerequisites: ['git-beginner'],
  icon: 'GitMerge',
  order: 2,
  tags: ['git', 'intermediate', 'roadmap', 'merging', 'collaboration', 'recovery'],
  steps: STEPS,
};
